---
title: "Review of “Vagueness and Contradiction”"
abstract: |
  Review of Roy Sorensen, “Vagueness and Contradiction”. Cambridge: Cambridge University Press, 2000. 
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
doi: "10.1093/ajp/jag216"
date: 04-01-2003
toc: false
citation_url: https://doi.org/10.1111/10.1093/ajp/jag216
categories:
  - on books
  - vagueness
  - logic
citation:
  type: review-book
  container-title: "Australasian Journal of Philosophy"
  volume: 81
  page: "290-292"
format:
  html: default
  pdf: 
    output-file: "Review of Vagueness and Contradiction"
  docx: 
    output-file: "Review of Vagueness and Contradiction"
---

Like all epistemicists, Roy Sorensen holds that vagueness poses no threat to classical logic, and that appearances to the contrary are the result of mistakenly assigning semantic force to certain barriers to inquiry. We may not be able to know whether 932 seconds after noon is still noonish, but there is a fact of the matter about whether it is. Hence the sentence *932 seconds after noon is noonish* is either true or false, just as adherents of classical logic presuppose, and the threat from vagueness to classical logic dissolves.

But Sorensen is not an orthodox epistemicist. He does not hold that these barriers to inquiry rise because of our limited powers of discrimination. That would imply that a more discerning observer, say God, could know where the boundary is. Sorensen holds that vagueness is an *absolute* barrier to inquiry. No one can know whether 932 seconds after noon is noonish, even God. This is because competently using the vague predicate 'noonish' requires believing a particular analytic falsehood involving it, and having this belief prevents *knowing* the truth about a borderline case. Much of this book is dedicated to defending these surprising claims. The first half of the book argues that this is the right thing to say about vague cases, and the second half provides more general arguments that we can and should believe analytic falsehoods.

It's illuminating to compare Sorensen's epistemicism with that of Timothy Williamson. A core feature of Williamson's position is neatly summarised in this quote, which Sorensen cites: "for the epistemicist, definiteness is truth under all sharp interpretations of the language indiscriminable from the right one." ("On the Structure of Higher Order Vagueness" *Mind* 108 (1999): 127‑43.)  Sorensen disagrees with the Williamson's position in four ways. Two of these disagreements are immediate, and two are with deeper presuppositions of Williamson's.

First, Sorensen thinks that Williamson here ignores the need for 'completeness'. Williamson holds that *p* is definite iff, roughly, it is true on all interpretations we cannot know to be incorrect. Call these the admissible interpretations. Sorensen claims that is not enough for *p* to be knowable, and hence definitely true. It must also be knowable that these are all the admissible interpretations.

Secondly, indiscriminability is always indiscriminability by something, so on Williamson's account definiteness is only defined relative to a discriminator. Sorensen wants there to be absolute borderline cases, and absolute indefiniteness, so he cannot rest with this definition. Sorensen thinks that unless we accept absolute borderline cases, we do not properly respect the sense in which vagueness is an absolute barrier to inquiry. The two other innovations in Sorensen's theory guarantee that his theory has place for absolute indefiniteness.

Consider a normal Sorites conditional, say *If 932 seconds after noon is noonish, so is 933 seconds*. Sorensen holds that being a competent user of 'noonish' requires that one believe every such conditional involving 'noonish'. Someone who failed to believe it would not be competent in the language. Although Sorensen always puts this in terms of linguistic competence, he also says that one who didn't believe this couldn't have beliefs about the extension of our predicates. The most natural conclusion to draw is that from Sorensen's perspective, one who doesn't believe the Sorites conditional lacks the concept NOONISH. Sorensen talks about predicates rather than concepts, so he doesn't put it quite this way, but it succinctly summarises the picture he sketches. Moreover, beliefs in such Sorites conditionals are *a priori*, despite the fact that one of them is analytically false. These are distinctive views, and they need good arguments.

A bad argument would be, "It is always irrational to deny a Sorites conditional, so it is always rational to believe it." This ignores the possibility that agnosticism about the conditional is always possible, and sometimes desirable. Sorensen does not endorse this argument, though he does note it shows that Sorites conditionals satisfy a 'negative conception' of the *a priori*: no empirical evidence can make us believe they are *false*.

Sorensen's argument seems to be that believing every Sorites conditional gives us many true beliefs at the cost of only one false belief. He thinks that cost is worth the benefit. But this is at best a reason why *we* should believe Sorites conditionals, not why God should. And it doesn't imply much about why God needs to believe this falsehood if He is to have the concept NOONISH. If we think subjectivism about language implies that God can't know more about *our* language than we do, that may draw God into our dilemma. But it should seem very implausible, especially to an epistemicist, that God can't know more about our language than we do. So even if it is good advice to believe every Sorites conditional, it does not follow that those who spurn this advice lack any concepts, or lack linguistic competence.

In any case, there are other costs to adopting Sorensen's advice and believing a bunch of Sorites conditionals that we know includes a falsehood. For example, we can no longer safely believe the logical consequences of some things we believe. Sorensen happily accepts that consequence. He holds *p* and *q* can both be *a priori* even though their conjunction is not *a priori*. In chapter 6 Sorensen replies to several arguments against this, including a purported proof that *a priority* agglomerates across conjunction. The proof assumes that all logical truths are *a priori*. Sorensen says this is false because there are logical truths that are too complex for us to believe, *a priori* or otherwise. Since the only logical truth needed in the proof was *p* → (*q* → (*p* & *q*)), this is not obviously a sound response.

Sorensen has a more speculative reason for thinking there is absolute vagueness. (This is the final way in which Sorensen's position differs from Williamson.) Consider a card that has *The sentence on the other side of this card is false* written on each side. If the sentences have truth values, then one is true and the other false. Whichever is true is a truth without a truthmaker, for any truthmaker would do just as well at making the other true. So Sorensen concludes that here we have a truth without a truthmaker, and the truthmaker principle is false. If there are some truths without truthmakers, there could be several. Sorensen holds that *a is F* is such a truth whenever *a* is an *F* which is a borderline *F*. Assume further that only truths with truthmakers are knowable, because knowability goes via knowing truthmakers, and we conclude that no one could know of a borderline *F* whether it is *F*. This is quite an interesting line of thought, and it deserves further attention. (Sorensen is quite upfront about how speculative it is.) Two immediate issues spring to mind. First, it is not clear how this is still a version of epistemicism, for vagueness is now at base a metaphysical phenomenon. There are epistemic consequences, but vagueness is constituted by the fact that there are truths without truthmakes, not by the unknowability of these. Secondly, and relatedly, it is no longer clear how higher order vagueness will be incorporated into the model. The most obvious thought is that there will be no truthmaker for the claim that some particular truth has a truthmaker. But whether some object is a truthmaker for some truth is not contingent, and it is notoriously difficult to apply truthmaker theory to necessary truths. Since every proposition entails any necessary truth, it is plausible that any object is a truthmaker for a necessary truth.

Sorensen argues that we should believe all Sorites conditionals, including ones that are analytically false. He notes this requires an argument that we can, and should, believe some analytic falsehoods. (He calls these impossibilities 'contradictions', a term some may think should be reserved for sentences of the form *p* & ¬*p*.) His argument that we can is fairly quick. Assume, for reductio, the philosophical thesis that we cannot believe analytic falsehoods. As a philosophical thesis, this is analytically true if true at all. But Sorensen believes its negation. So it is possible for someone to believe an analytic falsehood. The weakest premise here is that if we cannot believe analytic falsehoods, then it is analytic that we cannot. If it turns out that only creatures with a language of thought can believe analytic falsehoods, and it is a contingent feature of us that we lack a language of thought, Sorensen's premise is false.

The argument that we should believe some analytic falsehoods uses a version of the preface paradox. If we can believe analytic falsehoods, we should take apparent occurrences of this (as when we make arithmetic errors) at face value. That is, reason demands we believe that we believe an analytic falsehood. But this implies it is provable that our beliefs are not collectively true. So if we follow the dictates of reason, it is provable we believe something provably false. This argument is obviously useful for removing a particular barrier to accepting Sorensen's account of vagueness, that it seems absurd that reason could require we believe an analytic falsehood. But even if we reject Sorensen's theory of vagueness, they are independently interesting contributions to the theory of belief.

Sorensen makes two distinctive contributions to the theory of vagueness here. First, he argues that linguistic competence demands that we believe Sorites conditionals. Secondly, he links the existence of vagueness to the failure of the truthmaker principle. As those familiar with Sorensen's work will suspect, he makes these contributions in a lively and entertaining way. Anyone working on vagueness, and especially anyone interested in investigating the range of theories of vagueness that preserve classical logic, should pay it close attention.
