project:
  type: website

website:
  title: "Online Articles - Brian Weatherson"
  navbar:
    right:
      - icon: mortarboard
        href: https://brian.weatherson.org
      - icon: twitter
        href: https://bsky.app/profile/bweatherson.bsky.social
format: 
    html:
      toc: true
      toc-depth: 3
      toc-location: left
      toc-title: "Sections"
      reference-location: margin
      fontsize: 1.2em
      include-in-header:
        - text: |
            <link rel="stylesheet" href="https://use.typekit.net/uzz2drx.css">
      mainfont: "ff-scala-sans-pro, sans-serif"
      html-math-method: mathjax
      self-contained: false
      output-file: "index"

