project:
  type: website

website:
  title: "Online Papers - Brian Weatherson"
  navbar:
    title: "Online Papers - Brian Weatherson" 
    right:
      - icon: mortarboard
        href: https://brian.weatherson.org
      - icon: twitter
        href: https://bsky.app/profile/bweatherson.bsky.social
format: 
    html:
      theme: 
        light: 
          - solar
          - html-fonts-light.scss
          - book-light-defaults.scss
        dark:
          - solar
          - html-fonts.scss 
          - dark-table.scss
      linestretch: 1.5
      image-height: "50"
      include-in-header:
        - text: |
            <link rel="stylesheet" href="https://use.typekit.net/uzz2drx.css">
      mainfont: "ff-scala-sans-pro, sans-serif"
      html-math-method: mathjax
      self-contained: false