project:
  type: website

website:
  title: "Brian Weatherson"
  site-url: https://brian.weatherson.org/quarto-papers
  description: "Online papers of Brian Weatherson"
  navbar:
    title: "Brian Weatherson" 
    right:
      - text: "Papers"
        menu:
          - text: "All Papers"
            file: papers.qmd
          - text: "Epistemology"
            file: epist.qmd
          - text: "Games and Decisions"
            file: gdt.qmd
          - text: "On Books"
            file: books.qmd
      - text: "Books"
        menu: 
           - text: "Normative Externalism"
             href: https://brian.weatherson.org/ne/
           - text: "A History of Philosophy Journals"
             href: https://lda.weatherson.org/
           - text: "Knowledge: A Human Interest Story"
             href: https://brian.weatherson.org/kahis/
      - text: "CV"
        file: cv.qmd
      - text: "Teaching Notes"
        file: teaching.qmd
      - text: "Blog"
        file: blog.qmd
    tools:
      - icon: google
        href: https://scholar.google.com/citations?user=rz5RF8kAAAAJ&hl=en&oi=ao
      - icon: mailbox
        href: "mailto: brian@weatherson.org"
format: 
    html:
      theme: 
        light: 
          - solar
          - html-fonts-light.scss
          - book-light-defaults.scss
        dark:
          - solar
          - html-fonts.scss 
          - dark-table.scss
      linestretch: 1.5
      image-height: "50"
      include-in-header:
        - text: |
            <link rel="stylesheet" href="https://use.typekit.net/uzz2drx.css">
      mainfont: "ff-scala-sans-pro, sans-serif"
      html-math-method: mathjax
      self-contained: false