project:
  type: website

website:
  title: "Online Articles - Brian Weatherson"
  navbar:
    right:
      - about.qmd
      - icon: mortarboard
        href: https://brian.weatherson.org
      - icon: twitter
        href: https://bsky.app/profile/bweatherson.bsky.social
format: 
    html:
      theme: 
        light: 
          - solar
          - html-fonts.scss
          - book-light-defaults.scss
        dark:
          - solar
          - html-fonts.scss
          - dark-table.scss
      linestretch: 1.5
      image-height: "100"
      toc: true
      toc-depth: 3
      toc-location: left
      toc-title: "Sections"
      reference-location: margin
      fontsize: 1.2em
      include-in-header:
        - text: |
            <link rel="stylesheet" href="https://use.typekit.net/uzz2drx.css">
      mainfont: "ff-scala-sans-pro, sans-serif"
      html-math-method: mathjax
      self-contained: false
      appendix-cite-as: bibtex
      output-file: "index"
    pdf: 
      #geometry: "left=1.5in,right=1.5in,top=1.78in,bottom=1.78in"
      mathspec: true
      mainfont: Scala Pro
      sansfont: Scala Sans Pro
      mainfontoptions: Scale = MatchLowercase
      mathfont: Scala Pro
      fontsize: 11pt
      linkcolor: black
      link-citations: true
      keep-tex: true
      reference-location: margin
      include-in-header:
        text: |
          \setlength\heavyrulewidth{0ex}
          \setlength\lightrulewidth{0ex}
          \makeatletter
          \def\@maketitle{%
          \newpage
          \null
          \vskip 2em%
          \begin{center}%
          \let \footnote \thanks
            {\LARGE \@title \par}%
            \vskip 1.5em%
            {\large
              \lineskip .5em%
              \begin{tabular}[t]{c}%
                \@author
              \end{tabular}\par}%
            %\vskip 1em%
            %{\large \@date}%
          \end{center}%
          \par
          \vskip 1.5em}
          \makeatother 

number-sections: true
number-depth: 3


