---
title: "Brian Weatherson - CV"
format: 
    pdf:
      classoption: twoside
      geometry: "left=1in,
                 right=1in,
                 top=0.8in,
                 bottom=0.8in,
                 paperheight=9.5in,
                 paperwidth=6.5in,
                 includemp=TRUE,
                 marginparwidth=0in,
                 marginparsep=0in"
      mathspec: false
      mathfont: Garamond-Math
      mainfont: EB Garamond Math
      sansfont: Europa-Bold
      mainfontoptions: 
        - ItalicFont=EB Garamond Italic
        - BoldFont=EB Garamond Bold
      fontsize: 10pt
      indent: true
      linkcolor: black
      urlcolor: black
      colorlinks: false
      linestretch: 1.1
      link-citations: true
      keep-tex: true
      pdf-engine: xelatex
      include-in-header: 
        - text: |
            \setlength{\parindent}{0em}
            \usepackage{enumitem}
            \setlist{nosep, after=\vspace{6pt}}
---

2215 Angell Hall, 435 South State Street, Ann Arbor, MI 48109 U.S.A.

{{< fa envelope title="An envelope" >}} brian@weatherson.org

{{< fa wifi title="Internet address" >}} <https://brian.weatherson.org>

AOS
:    Epistemology &nbsp;&#9643;&nbsp; Decision Theory

AOC
:    Philosophy of Language &nbsp;&#9643;&nbsp; Ethics &nbsp;&#9643;&nbsp; Logic &nbsp;&#9643;&nbsp; History of Analytic

**Last Updated**: 20 November 2024

## Education

- BA(Hons) with Honors in Philosophy, Monash University, 1994
- PhD in Philosophy, Monash University, 1998. Thesis title: _On Uncertainty_.

## Employment History

- Marshall M. Weinberg Professor of Philosophy, University of Michigan (2012-present)
- Professorial Fellow, Arché, University of St Andrews (quarter-time appointment) (2008-2018)
- Associate Professor, Rutgers, The State University of New Jersey (2008-2011)
- Associate Professor, Cornell University (2004-2007)
- Assistant Professor, Brown University (2001-2004)
- Sutton Faculty Fellow, Syracuse University (1999-2001)

## Books

2024
:    [Knowledge: A Human Interest Story](https://www.openbookpublishers.com/books/10.11647/obp.0425), Open Book Publishers.

2022
:    [A History of Philosophy Journals, Volume 1: Evidence from Topic Modeling, 1876–2013](https://www.fulcrum.org/concern/monographs/2v23vw98g). Maize Books.

2019
:    [Normative Externalism](https://global.oup.com/academic/product/normative-externalism-9780199696536). Oxford University Press.

2011
:    [Epistemic Modality](https://global.oup.com/academic/product/epistemic-modality-9780199591589) (edited, with Andy Egan). Oxford University Press.

## Journal Articles

- [Why Ain't Evidentialists Rich?](https://brian.weatherson.org/quarto/posts/war-on-war/war-on-war.html), _Analysis_. 
- [The Sporting Attitude](https://brian.weatherson.org/quarto/posts/borge/the-sporting-attitude.html), _Sport, Ethics and Philosophy_.
- [Accuracy and the Imps](https://brian.weatherson.org/quarto/posts/imps/accuracy-and-the-imps.html), (with James Joyce) _Logos \& Episteme_. 
- [Interests, Evidence and Games](https://brian.weatherson.org/quarto/posts/ieg/interests-evidence-and-games.html), _Episteme_. 
- [Notes on some ideas in Lloyd Humberstone’s philosophical applications of modal logic](https://brian.weatherson.org/quarto/posts/humberstone-modal/notes-on-some-ideas-in-lloyd-humberstones-philosophical-applications-of-modal-logic.html), (with Steven Kuhn) _Australasian Journal of Logic_. 
- [Intellectual Skill and the Rylean Regress](https://brian.weatherson.org/quarto/posts/ryle-regress/ryle-regress.html), _Philosophical Quarterly_. 
- [Games, Beliefs and Credences](https://brian.weatherson.org/quarto/posts/gbc/games-beliefs-and-credences.html), _Philosophy and Phenomenological Research_. 
- [Reply to Blackson](https://brian.weatherson.org/quarto/posts/reply-blackson/reply-to-blackson.html), _Journal of Philosophical Research_. 
- [Reply to Eaton and Pickavance](https://brian.weatherson.org/quarto/posts/reply-eaton-pickavance/reply-to-eaton-and-pickavance.html), _Philosophical Studies_. 
- [For Bayesians, Rational Modesty Requires Imprecision](https://brian.weatherson.org/quarto/posts/modesty/for-bayesians-rational-modesty-requires-imprecision.html), _Ergo_. 
- [Memory, Belief and Time](https://brian.weatherson.org/quarto/posts/mbt/memory-belief-and-time.html), _Canadian Journal of Philosophy_. 
- [Centrality and Marginalisation](https://brian.weatherson.org/quarto/posts/herman/centrality-and-marginalisation.html), _Philosophical Studies_. 
- [Running Risks Morally](https://brian.weatherson.org/quarto/posts/rrm/running-risks-morally.html), _Philosophical Studies_. 
- [In Defence of the ACA's Medicaid Expansion](https://brian.weatherson.org/quarto/posts/aca/aca-medicaid.html), (with Ishani Maitra) _Public Affairs Quarterly_. Abridged version reprinted in Fritz Alhoff and Mark Hall (eds.) _The Affordable Care Act Decision_, Routledge.
- [Margins and Errors](https://brian.weatherson.org/quarto/posts/mae/margins-and-errors.html), _Inquiry_ .
- [Ross on Sleeping Beauty](https://brian.weatherson.org/quarto/posts/ross-sleeping-beauty/ross-on-sleeping-beauty.html), _Philosophical Studies_. 
- [The Role of Naturalness in Lewis's Theory of Meaning](https://brian.weatherson.org/quarto/posts/naturalness/the-role-of-naturalness-in-lewiss-theory-of-meaning.html), _Journal for the History of Analytic Philosophy_. 
- [Explanation, Idealisation and the Goldilocks Problem](https://brian.weatherson.org/quarto/posts/eigp/goldilocks.html), _Philosophy and Phenomenological Research_. 
- [Games and the Reason-Knowledge Principle](https://brian.weatherson.org/quarto/posts/gark/games-and-the-reason-knowledge-principle.html), _The Reasoner_. 
- [In Defense of a Kripkean Dogma](https://brian.weatherson.org/quarto/posts/idakd/in-defense-of-a-kripkean-dogma.html), (with Jonathan Ichikawa and Ishani Maitra) _Philosophy and Phenomenological Research_. 
- [Induction and Supposition](https://brian.weatherson.org/quarto/posts/ias/induction-and-supposition.html), _The Reasoner_. 
- [The Temporal Generality Problem](https://brian.weatherson.org/quarto/posts/tgp/the-temporal-generality-problem.html), _Logos and Episteme_. 
- [Defending Interest-Relative Invariantism](https://brian.weatherson.org/quarto/posts/diri/defending-interest-relative-invariantism.html), _Logos and Episteme_. 
- [No Royal Road to Relativism](https://brian.weatherson.org/quarto/posts/nrrtr/no-royal-road-to-relativism.html), _Analysis_. 
- [Stalnaker on Sleeping Beauty](https://brian.weatherson.org/quarto/posts/stalnaker-sleeping-beauity/stalnaker-on-sleeping-beauty.html), _Philosophical Studies_. 
- [Assertion, Knowledge and Action](https://brian.weatherson.org/quarto/posts/aka/assertion-knowledge-and-action.html), (with Ishani Maitra) _Philosophical Studies_. 
- [Conditionals and Indexical Relativism](https://brian.weatherson.org/quarto/posts/cair/conditionals-and-indexical-relativism.html), _Synthese_. 
- [Attitudes and Relativism](https://brian.weatherson.org/quarto/posts/relative-attitude/attitudes-and-relativism.html), _Philosophical Perspectives_. 
- [Deontology and Descartes' Demon](https://brian.weatherson.org/quarto/posts/ddd/deontology-and-descartess-demon.html), _Journal of Philosophy_. 
- [Humeans Aren't Out of Their Minds](https://brian.weatherson.org/quarto/posts/haootm/humeans-arent-out-of-their-minds.html), _Noûs_. 
- [Doing Philosophy with Words](https://brian.weatherson.org/quarto/posts/dpww/doing-philosophy-with-words.html), _Philosophical Studies_. 
- [The Bayesian and the Dogmatist](https://brian.weatherson.org/quarto/posts/bayesdog/the-bayesian-and-the-dogmatist.html), _Proceedings of the Aristotelian Society_.
- [The Asymmetric Magnets Problem](https://brian.weatherson.org/quarto/posts/tamp/the-asymmetric-magnets-problem.html), _Philosophical Perspectives_. 
- [Can We Do Without Pragmatic Encroachment?](https://brian.weatherson.org/quarto/posts/cwpwpe/can-we-do-without-pragmatic-encroachment.html) _Philosophical Perspectives_. 
- [Scepticism, Rationalism and Externalism](https://brian.weatherson.org/quarto/posts/sre/scepticism-rationalism-and-externalism.html)  _Oxford Studies in Epistemology_. 
- [Should We Respond to Evil with Indifference?](https://brian.weatherson.org/quarto/posts/evil/should-we-respond-to-evil-with-indifference.html) _Philosophy and Phenomenological Research_. 
- [True, Truer, Truest](https://brian.weatherson.org/quarto/posts/ttt/true-truer-truest.html), _Philosophical Studies_.
- [Luminous Margins](https://brian.weatherson.org/quarto/posts/lummarg/luminous-margins.html), _Australasian Journal of Philosophy_. 
- [Morality, Fiction and Possibility](https://brian.weatherson.org/quarto/posts/mfp/morality-fiction-and-possibility.html), _Philosophers Imprint_. 
- [Chopping up Gunk](https://brian.weatherson.org/quarto/posts/gunk/chopping-up-gunk.html), (with John Hawthorne) _Monist_. 
- [Prankster's Ethics](https://brian.weatherson.org/quarto/posts/prank/pranksters-ethics.html), (with Andy Egan) _Philosophical Perspectives_. 
- [Are You a Sim?](https://brian.weatherson.org/quarto/posts/sims/are-you-a-sim.html), _Philosophical Quarterly_. 
- [What Good are Counterexamples?](https://brian.weatherson.org/quarto/posts/wgac/what-good-are-counterexamples.html) _Philosophical Studies_. 
- [From Classical to Intuitionistic Probability](https://brian.weatherson.org/quarto/posts/conprob/from-classical-to-intuitionistic-probability.html), _Notre Dame Journal of Formal Logic_. 
- [Nine Objections to Steiner and Wolff on Land Disputes](https://brian.weatherson.org/quarto/posts/nine-obj/nine-objections-to-steiner-and-wolff-on-land-disputes.html), _Analysis_. 
- [Many Many Problems](https://brian.weatherson.org/quarto/posts/mmp/many-many-problems.html), _Philosophical Quarterly_. 
- [Epistemicism, Parasites and Vague Names](https://brian.weatherson.org/quarto/posts/epvn/epistemicism-parasites-and-vague-names.html), _Australasian Journal of Philosophy_. 
- [Keynes, Uncertainty and Interest Rates](https://brian.weatherson.org/quarto/posts/kuir/keynes-uncertainty-and-interest-rates.html), _Cambridge Journal of Economics_. 
- [Misleading Indexicals](https://brian.weatherson.org/quarto/posts/misindex/misleading-indexicals.html), _Analysis_. 
- [Indicative and Subjunctive Conditionals](https://brian.weatherson.org/quarto/posts/indsub/indicative-and-subjunctive-conditionals.html), _Philosophical Quarterly_. 
- [Intrinsic Properties and Combinatorial Principles](https://brian.weatherson.org/quarto/posts/ipacp/intrinsic-properties-and-combinatorial-principles.html), _Philosophy and Phenomenological Research_. Reprinted in Robert M. Francescotti (ed.), _Companion to Intrinsic Properties_, De Gruyter 2014. 
- [Begging the Question and Bayesianism](https://brian.weatherson.org/quarto/posts/bqb/begging-the-question-and-bayesians.html), _Studies in History and Philosophy of Science_. 

## Chapters in Edited Volumes

- [Freedom of Research Area](https://brian.weatherson.org/quarto/posts/fora/freedom-of-research-area.html), in Jennifer Lackey (ed.), _Academic Freedom_, Oxford. 
- [Interest-Relative Invariantism](https://brian.weatherson.org/quarto/posts/iri/interest-relative-invariantism.html), in Jonathan Jenkins Ichikawa (ed.), _Routledge Handbook of Epistemic Contextualism_, Routledge. 
- [Relativism](https://brian.weatherson.org/quarto/posts/relativism/relativism.html), (with Patrick Shirreff) in Bob Hale, Alex Miller and Crispin Wright (eds.), _Blackwell Companion to the Philosophy of Language_, Blackwell. 
- [Analytic-Synthetic and A Priori-A Posteriori](https://brian.weatherson.org/quarto/posts/synthetic/analytic-synthetic-and-a-priori-a-posteriori.html), in Herman Cappelen, Tamar Szabó Gendler and John Hawthorne (eds.), _The Oxford Handbook of Philosophical Methodology_, Oxford.
- [Humean Supervenience](https://brian.weatherson.org/quarto/posts/humsup/humean-supervenience.html), in Barry Loewer and Jonathan Schaffer (eds.), _A Companion to David Lewis_, Blackwell. 
- [Probability and Scepticism](https://brian.weatherson.org/quarto/posts/pas/probability-and-scepticism.html), in Dylan Dodd and Elia Zardini (eds.), _Scepticism and Philosophical Justification_, Oxford. 
- [Disagreements, Philosophical and Otherwise](https://brian.weatherson.org/quarto/posts/dpao/disagreements-philosophical-and-otherwise.html), in David Christensen and Jennifer Lackey (eds.), _The Epistemology of Disagreement_, Oxford. 
- [Dogmatism, Probability and Logical Uncertainty](https://brian.weatherson.org/quarto/posts/dplu/dogmatism-probability-and-logical-uncertainty.html), (with David Jehle) in Greg Restall and Gillian Russell (eds.), _New Waves in Philosophical Logic_, Palgrave. 
- [Epistemic Modals and Epistemic Modality](https://brian.weatherson.org/quarto/posts/epistemic-modals/epistemic-modals-and-epistemic-modality.html), (with Andy Egan) in Andy Egan and Brian Weatherson (eds.), _Epistemic Modality_, Oxford. 
- [Vagueness as Indeterminacy](https://brian.weatherson.org/quarto/posts/vai/vagueness-as-indeterminacy.html), in Richard Dietz and Sebastiano Moruzzi, _Cuts and Clouds_, Oxford. 
- [Questioning Contextualism](https://brian.weatherson.org/quarto/posts/qc/questioning-contextualism.html), in Stephen Hetherington, _Aspects of Knowing_, Elsevier. 
- [Epistemic Modals in Context](https://brian.weatherson.org/quarto/posts/epic/epistemic-modals-in-context.html),(with Andy Egan and John Hawthorne) in Gerhard Preyer and Georg Peter (eds.), _Contextualism in Philosophy_, Oxford. 

## Encyclopedia Articles

- [Metaphysics](http://www.publishing.monash.edu/cpanz/), in Graham Oppy and N. N. Trakakis (eds.), _A Companion to Philosophy in Australia and New Zealand_,  Monash. 
- [David Lewis](http://plato.stanford.edu/entries/david-lewis/), in Ed Zalta (ed.), _Stanford Encyclopedia of Philosophy_. 
- [Problem of the Many](http://plato.stanford.edu/entries/problem-of-many/), in Ed Zalta (ed.), _Stanford Encyclopedia of Philosophy_. 
- [Intrinsic vs Extrinsic Properties (with Dan Marshall)](http://plato.stanford.edu/entries/intrinsic-extrinsic/), in Ed Zalta (ed.), _Stanford Encyclopedia of Philosophy_. 

## Book Reviews

- Penelope Maddy, What do Philosophers do? Scepticism and the Practice of Philosophy, _Mind_. 
- Daniel Nolan, David Lewis, _Mind_. 
- Frank Jackson and Graham Priest (eds.) Lewisian Themes: The Philosophy of David K. Lewis, _Notre Dame Philosophical Reviews_. 
- Christopher Peacocke, The Realm of Reason, _Times Literary Supplement_. 
- Christopher Gauker, Words without Meanings, _Notre Dame Philosophical Reviews_. 
- Rosanna Keefe, Theories of Vagueness, _Philosophy and Phenomenological Research_. 
- Roy Sorensen, Vagueness and Contradiction, _Australasian Journal of Philosophy_. 
- David Wiggins, Sameness and Substance Renewed, _Notre Dame Philosophical Reviews_. 
- Michael DePaul (ed.), Rethinking Intuition, _Ethics_. 
- Ted Lockhart, Moral Uncertainty and Its Consequences, _Mind_. 
- William Lycan, Real Conditionals, _Philosophical Review_. 

\newpage
## Talks

Knowledge: A Human Interest Story

- Frankfurt, September 2024

A Break in the Citation Patterns?

- Tilberg, August 2024

Money, States, and Liquidity

- UC Davis, April 2024

The End of Decision Theory

- Western University, March 2024

Feasible Epistemology

- Berlin, March 2023

Anxiety and Interests

- Epistemic Anxiety Workshop, UBC, December 2022

Data Driven History of Philosophy

- University of Tokyo, December 2022

The End of Decision Theory

- UBC, December 2022
- Western, March 2022

Philosophy Journals in the Early 20th Century

- Conference of Western Swiss Universities, Septmeber 2022

Indecisive Decision Theory

- ACU, October 2021

Epistemic Permissiveness and Symmetric Games

- AAP, July 2019

Pragmatic Encroachment and Close Calls

- Monash University, April 2019
- University of Sydney, May 2019
- ANU, May 2019
- Ranch Metaphysics Conference, January 2020

Moral Uncertainty and Desire as Belief

- Hebrew University of Jerusalem, June 2018
- University of Melbourne, March 2019
- University of Queensland, May 2019

Blame and Fragmented Desire

- University of Graz, December 2017

\newpage
Inferentialism and Logical Knowledge

- Conceptual Truth, Analyticity, and Conceptual Competence workshop, ConceptLab, University of Oslo, June 2017

Interests and Evidence

- Pragmatic Encroachment Conference, Sedona, AZ, February 2017
- Arché, University of St Andrews, June 2017
- Episteme Conference, Galapagos Islands, July 2017

Thick Moral Ignorance

- Blame Workshop, Arché, University of St Andrews, June 2017
- University of Vienna, December 2017  

Signalling Games

- Decisions, Games and Logic Workshop, University of Michigan, July 2016

Accuracy and the Imps

- Arché, University of St Andrews, May 2016
- University of Melbourne, March 2019

Asymmetries in Disagreement

- Complex Disagreement Workshop, University of St Andrews, May 2016

Determinacy and Borderline Cases

- University of Chicago, April 2015

Memory, Belief and Time

- Belief, Rationality and Time Conference, University of Wisconsin - Madison, September 2015

Should We Act on Higher-Order Evidence?

- Australasian Association of Philosophy Annual Conference, ANU, July 2014

Moral Ignorance is (Almost) Never Exculpatory

- University of Sydney, April 2014
- Australian National University, April 2014
- University of Melbourne, May 2014
- Arché Reading Party, June 2016

Intellectual Skills and the Rylean Regress

- Monash University, February 2014

Rayo on Possibility

- MIT, October 2014

Stopped Clocks and Generative Testimony

- University of St Andrews, October 2013

\newpage
Games, Beliefs and Credences

- Formal Epistemology Workshop/Rutgers Epistemology Conference, May 2012

Centrality and Marginalisation

- Institute of Philosophy, University of London, February 2012

Running Risks Morally

- Marshall M. Weinberg Lecture, University of Michigan, November 2012
- Bellingham Summer Philosophy Conference, Western Washington University, August 2013
- Ohio State University, September 2013
- A Night of Philosophy, New York, April 2015

Disagreements, Philosophical and Otherwise

- Summer School on Disagreement, University of Zurich, August 2012

Margins and Errors

- University of St Andrews, June 2012
- University of Edinburgh, June 2012
- Midwest Epistemology Workshop, University of Indiana, September 2012

Reflections on Lewis, Meaning and Naturalness

- CSMN, Oslo, August 2011
- Arché workshop on naturalness in semantics and metaphysics, October 2011
- Rutgers University, October 2011
- Univerity of Illinois, May 2012

Vague Events and the Problem of the Many

- LOGOS Indeterminacy Workshop, Barcelona, January 2010

Do Judgments Screen Evidence?

- Massachussets Institute of Technology, March 2010
- University of St Andrews, May 2010
- University of Konstanz, June 2010
- University of Oxford, June 2010
- University of Michigan, February 2011.

Rational Belief and Rational Action

- University of St Andrews, May 2010

In Defence of a Kripkean Dogma

- University of Leeds, May 2010

Stalnaker on Sleeping Beauty

- University of St Andrews, June 2010

Rule Following and Basicness

- University of St Andrews, May 2009

Evidence Neutrality

- University of St Andrews, June 2009

Probability and Scepticism

- Arché Scepticism Conference, University of St Andrews, June 2009

Assertion, Knowledge and Action (with Ishani Maitra)

- Bellingham Summer Philosophy Conference, Western Washington University, August 2009

Moderate Rationalism and Bayesian Scepticism

- University of Edinburgh, May 2008

Content Relativism

- Language and Law workshop, University of Oslo, June 2008

Attitudes and Relativism

- First Arché Contextualism and Relativism workshop, University of St Andrews, June 2008.

Causation and Causatives

- Univesity of Massachusetts, Amherst, April 2007.
- Arizona Ontology Conference, Tuscon, January 2008.
- Keynote address at Rutgers/Princeton graduate conference, Rutgers University, March 2008.

Moral Psychology and Epistemic Deontology

- Ryle at Ryerson conference, Ryerson University, Toronto, October 2007

Replacing Logic

- Contribution to author meets critics session on David Christensen's Putting Logic in Its Place, APA Pacific Division Conference, Portland OR, March 2006.

Natural Quantities

- University of Manitoba, March 2006 - Stanford University, May 2006

In Defence of a Dogmatist

- University of Texas, May 2006 - Stanford University, May 2006

Norms of Assertion and Expressivism

- Workshop on ethics and epistemology,  University of Missouri at Columbia, September 2006

The Bayesian and the Dogmatist

- Rutgers University, October 2006.
- University of Oklahoma, November 2006.
- University of California at Berkeley, November 2006.
- The Aristotelian Society, London, February 2007.

Tracking, Closure and Conjunctions

- Contribution to author meets critics session on Sherri Rousch's *Tracking Truth*, Philosophy of Science Association cofnerence, Vancouver, November 2006.

Vagueness as Indeterminacy

- Australian National University, January 2005
- Princeton University, February 2005
- Arché Workshop on Vagueness, University of St Andrews, February 2005

Dutch Books and Infinity

- Prague International Colloquium on Dutch Book Arguments, Prague, August 2005

Knowledge, Justification and Practical Interests

- Monash University, September 2005 - Australian National University, October 2005

Conditionals and Relativism

- LOGOS Workshop on Relativising Utterance Truth,  Barcelona, September 2005 - Workshop on Conditionals, University of Connecticut, April 2006

Morality in Fiction and Consciousness in Imagination

- APA Pacific Division Conference, Pasadena, March 2004

Uncertainty, Probability and Non-Classical Logic

- Formal Epistemology Workshop, University of California at Berkeley, May 2004

Morality, Fiction and Possibility

- American Society for Aesthetics Conference, Houston , October 2004

Intuitions and Meanings

- Fribourg Workshop on Intuitions, Fribourg Switzerland, November 2004.
- Australian National University, January 2005.
- University of Glasgow, February 2005.

Prankster's Ethics (with Andy Egan)

- International Symposium on Theoretical and Applied Ethics, Louisiana State University, February 2003 - APA Central Division Conference, Cleveland OH, April 2003

Scepticism, Rationalism and Externalism

- Cornell University, October 2003 
- Inland Northwest Philosophy Conference, Washington State University and University of Idaho, April 2004

Justification and Innateness

- Australasian Association of Philosophy conference, University of Canterbury, Christchurch, New Zealand, July 2002

\newpage
My Favourite Puzzle

- University of Melbourne, October 2002 
- University of California at Davis, January 2004

Indicatives and Subjunctives

- Brown University, February 2001
- Rutgers University, February 2001
- University of Colorado at Boulder, February 2001

Growing Individuals and Intrinsic Properties

- APA Pacific Division Conference, San Francisco, March 2001

True, Truer, Truest

- University of Michigan, October 2001
- APA Central Division Conference, Chicago, April 2002
- Bellingham Summer Philosophy Conference, Western Washington University, August 2003

Stages, Worms, Slices and Lumps

- Syracuse University, May 2000

A Puzzle About Duplication

- Monash University, June 2000

Is This Title Ambiguous?

- Australasian Association of Philosophy conference, University of Queensland, July 2000

What Good Are Counterexamples?

- Australasian Association of Philosophy conference, University of Melbourne, July 1999

Supertruth

- Australasian Association of Philosophy conference, Macquarie University,  July 1998

The Dutch Bookie Goes to Market

- International Economics and Philosophy Society Conference, University of New South Wales, July 1996, and published in conference proceedings:  Julian Lamont and Christi Dawn Favor (eds.) Edited Proceedings of the 1997 International Economics and Philosophy Society Conference, 97-100

The Possibility of Revealed Preference

- International Economics and Philosophy Society Conference, University of Queensland, Brisbane, Australia, July 1996, and published in conference proceedings: Julian Lamont (ed.) Edited Proceedings of the 1996 International Economics and Philosophy Society Conference, 121-125

\newpage
Inductive Arguments and Probability

- Australasian Association of Philosophy conference, University of Queensland, July 1996

## Invited Commentaries and Panel Presentations

- Ranch Metaphysics Workshop, January 2022
- Vancouver Summer Philosophy Conference, August 2018
- Meta-Ontology workshop at University of Tokyo, October 2018
- Arizona Ontology Conference, January 2017
- APA Central Division, San Francisco, March 2016
- APA Pacific Division, San Francisco, April 2016
- Bellingham Summer Philosophy Conference, Western Washington University, 2015 
- Rocky Mountain Ethics Congress, University of Colorado at Boulder, August 2009 
- Bellingham Summer Philosophy Conference, Western Washington University, August 2008 
- Rutgers Semantics Workshop, New Brunswick, October 2007 
- Arizona Ontology Conference, January 2006 
- Panel on Blogging in Philosophy, APA Pacific Division, March 2006 
- NYU Causation Workshop, Florence, June 2006 
- APA Central Division, Chicago, April 2005 
- Bellingham Summer Philosophy Conference, Western Washington University, August 2004 
- APA Pacific Division, San Francisco, March 2003 
- Syracuse Workshop on Metaphysics, Syracuse University, August 2003 
- BloggerCon, Harvard University, October 2003 
- Bellingham Summer Philosophy Conference, Western Washington University, August 2001 
- Metaphysical Mayhem V, Syracuse University, August 2000

## Teaching

#### Introduction to Philosophy
- Taught nine times: Spring 2005, Spring 2006, Fall 2006, Spring 2007 and Spring 2008, Winter 2013, Winter 2016, Winter 2018, Fall 2023.
- Topics included philosophy of religion, philosophy of mind, scepticism and ethics
- In early years, mainly used readings. In later years, the focus was more on great books, such as Descartes' _Meditations_ and Hume's _Dialogues Concerning Natural Religion_.
- All the courses were large introductory lecture courses, to between 80 and 150 students, except the Spring 2008 course, which was a freshman Honors seminar.

#### Introduction to Logic
- Taught four times: Spring 2003, Fall 2008, Fall 2009, Fall 2011.
- Topics included validity and soundness, the predicate calculus, models, and proofs in propositional and predicate logic.
- The courses had no pre-requisites, and focussed on continuous assessment.
- All the courses were large lecture courses, with 80 to 100 students.

#### Intermediate Logic
- Taught four times: Fall 2001, Fall 2002, Spring 2004, Fall 2004.
- The course was on predicate logic, from introduction to the proof of completeness.
- The courses had between 20 and 40 students.

#### Advanced Logic
- Taught four times: Fall 2000, Spring 2002, Fall 2003, Fall 2009.
- Topics varied, but included non-classical logic, modal logic and the incompleteness of arithmetic.
- All courses were small graduate focussed courses, with 5 to 10 students.

#### Philosophy of Language
- Taught twice: Fall 2001, Spring 2003.
- Topics included reference and description, implicature and vagueness.
- Course was a small undergraduate seminar, with some graduates sitting in, with 5 to 10 students.

#### Decision Theory
- Taught five times: Spring 2000, Fall 2004, Fall 2008, Fall 2011, Winter 2016.
- Topics included probability and utility functions, paradoxes of decision theory, game theory and collective decision making.
- Courses were targeted at juniors and seniors, with between 5 and 20 students.

#### 300-level Epistemology
- Taught twice: Fall 2013, Winter 2015.
- Topics included scepticism, analysis of knowledge and social epistemology.
- Courses were targeted at intermediate level philosophy students, with roughly 40 students.

#### 400-level Groups and Choices
- Taught seven times: Winter 2017, Winter 2018, Fall 2019, Winter 2021, Winter 2022, Winter 2023, Winter 2024.
- Topics include game theory, voting theory and group minds.
- Courses are targeted at upper level undergraduates and beginning graduate students, with courses being 25 or 50 students.

#### 300-level Formal Methods

- Taught three times:  Winter 2017, Fall 2019, Summer 2020,  Winter 2021, Winter 2022. 
- About 50 students every time.
- Introduces propositional logic, probability theory, decision theory and modal logic.

#### Undergraduate courses taught just once (all student numbers approximate)
- History of Political Philosophy, Spring 2001, 50 students
- Time Travel, Fall 2003, 20 students
- Mid 20th Century philosophy, Spring 2005, 5 students
- Applied Ethics, Summer 2005, 40 students
- Semantics, Fall 2007, 5 students
- Philosophical Babies, Fall 2012, 20 students
- 400-level Epistemology, Winter 2013, 10 students
- 400-level Ethics, Fall 2015, 10 students
- Honors Logic, Fall 2016, 18 students


#### Graduate Seminars
- Intuitions, Fall 1999
- Vagueness, Spring 2002
- Conceivability, Spring 2002
- Philosophy of Economics, Spring 2004
- David Lewis, Spring 2006, Fall 2013
- Dissertation Workshop, Spring 2008
- Probability, Spring 2009
- Scepticism, Fall 2010
- Game Theory, Summer 2011
- Scepticism, Winter 2012
- Normative Uncertainty, Fall 2014
- Responsibility, Fall 2017
- Interest-Relative Epistemology, Winter 2020
- Vices: A Users Guide, Fall 2021
- Keynes, Fall 2023

## Professional Service

- Editor-in-Chief, _Philosophy Compass_, 2006-2012.
- Co-editor, _Philosophical Review_, 2006-2007.
- Associate Editor, _Thought_, 2012-2014.
- Associate Editor, _Philosophical Review_, 2013-2018.
- Editor, _Philosophers' Imprint_, 2018-present
- External examiner for graduate degrees at Rutgers University, Australian National University, University of Oslo, University of Melbourne and Monash University.
- External reviewer for funding proposals for FWO (Belgium), AHRC (UK), ARC (Australia) and PETAF (Spain).
- Reviewed book manuscripts or proposals for Oxford University Press, Princeton University Press, MIT Press, Harvard University Press and Routledge.
- Referee for, among others, American Philosophical Quarterly, Analytic Philosophy, Australasian Journal of Philosophy, Australasian Journal of Logic, British Journal for the Philosophy of Science, Canadian Journal of Philosophy, Dialectica, Ethics, Journal of Philosophical Logic, Journal of Ethics and Social Philosophy, Linguistics and Philosophy, Mind, Mind and Language, Noûs, Philosophers' Imprint, Philosophical Quarterly, The Philosophical Review, Philosophical Studies, Philosophy and Phenomenological Research, Ratio and Synthese.

## Departmental and University Service

- Chair, Graduate Studies Committee (i.e., DGS), University of Michigan, 2014-6, 2019-present
- Member, Search Committee, PPE Search, University of Michigan, 2014-5.
- Member, Search Committee, Philosophy Department, University of Michigan, 2013, 2017.
- Chair, Search Committee, Philosophy Department, University of Michigan, 2012-3.
- Graduate Admissions Committee, Philosophy Department, University of Michigan, 2012, 2017.
- External Speakers Co-Ordinator, Philosophy Department, Rutgers University, 2009-10.
- Appointments and Promotions Committee, Dean's Office, Humanites, Rutgers University, 2008-10.
- Web co-ordinator, Philosophy Department, Rutgers University, 2008-10
- Graduate Admissions committee, Philosophy Department, Rutgers University, 2008, 2009.
- Search committee, Philosophy Department, Rutgers University, 2008-9.
- Search committee, Philosophy Department, Cornell University, 2004-5, 2006-7
- External Speakers Co-Ordinator, Philosophy Department, Cornell University, 2004-5.
- Webmaster, Philosophy Department, Cornell University, 2004-7