---
title: "Review of “Real Conditionals”"
abstract: |
  Review of William Lycan, “Real Conditionals”. Oxford: Clarendon Press, 2001. 
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
doi: "10.1215/00318108-111-4-609"
date: 10-01-2003
toc: false
citation_url: https://doi.org/10.1215/00318108-111-4-609
categories:
  - on books
  - logic
  - language
citation:
  type: review-book
  container-title: "Philosophical Review"
  volume: 111
  issue: 4
  page: "609-611"
format:
  html: default
  pdf: 
    output-file: "Review of Real Conditionals"
  docx: 
    output-file: "Review of Real Conditionals"
---

Over the last two decades, William Lycan's work on the semantics of conditionals has been distinguished by his careful attention to the connection between syntax and semantics, and more generally by his impeccible methodology. Lycan takes compositionality seriously, so in his theory the meaning of 'even if', for example, should be a combination of the meaning of 'even' and the meaning of 'if'. After reading his work, it's hard to take seriously work which does not share this methodology.

Lycan's semantics for conditionals makes central use of what he calls 'events'. An event is not a possible world, for it need not be complete or consistent. It is more like what Barwise and Perry call a 'situation'. Conditionals are quantifiers over events, as follows:

-   P if Q = P in any event in which Q
-   P only if Q = P in no event other than one in which Q
-   P even if Q = P in any event including any in which Q (17)

The quantifiers here are contextually restricted. Lycan includes in the semantic analysis a predicate of events *R*, whose role is to restrict the quantifiers over events. An event satisfies *R* only if it is 'envisaged', which is similar to saying it is a 'real' or 'relevant' possibility. The value of *R* changes frequently; sometimes it even changes mid-sentence. This fact is appealed to frequently in explaining some surprising behaviour of conditionals. For example, the invalidity of antecedent-strengthening: *if p then r*, *so if p and q then r*, is explained by saying the class of events relevant to the truth of the conclusion may be larger than the class of events relevant to the truth of the premise. In particular, at least one event in which *p* *and q* is relevant to the conclusion, but no such event need be relevant to the premise. A similar explanation is given for the failure of transitivity and contraposition.

The quantifier domain must include some non-actual events or conditionals will turn into material implications. Surprisingly, Lycan says that sometimes the quantifier includes only non-actual events. In these cases, it is possible that all (relevant) *p*-events can be *q*-events, even though *p* is true but not *q*. That is, in these cases modus ponens is invalid. Lycan argues persuasively that the case against modus ponens is at least as strong as the case against antecedent-strengthening, contraposition and modus tollens.

There is an extended discussion of 'even', which is necessary for providing a theory of 'even if'. Lycan first suggests that *Even Grannie was sober* means *Everyone, including Grannie*, *was sober*. The quantifier domain includes everyone no less likely than Grannie to be sober. After discussing some counterexamples, Lycan suggests that instead it means *Everyone plus Grannie was sober*, where the quantifer ranges over everyone whom you would expect to be sober. Lycan is committed to 'even' being a quantifier because of its syntactic similarity to 'only', and because of the "initial plausibility of ... universally quantified paraphrases" (121) of sentences involving 'even'. The discussion here is fascinating, but not conclusive. It isn't clear, for example, that 'even' and 'only' have the same syntactic role. Compare *Even supposing Jack were here, he wouldn't help* with \**Only supposing Jack were here, he wouldn't help*.

Lycan also includes a helpful discussion of how his theory handles Allan Gibbard's 'Riverboat Puzzle' and related cases. It is troubling, for those who don't analyse conditionals as material implications, that sometimes one speaker can say *If p, q*, another can say *If p, not q*, and both seem to be speaking truly. Lycan argues we should accept this troubling consequence, but explain it by making *R* sensitive to epistemic considerations.

As well as these points, Lycan raises some powerful objections to 'No Truth Value' theories of conditionals, and against the extensive use of probability theory in semantics. The book concludes with two appendicies on 'non-conditional' conditionals, such as *If you're hungry, there's biscuits on the sideboard*.

There's a lot to like about this book, not least it's witty, even charming, style. Lycan considers more examples, from more diverse sources, than most writers. The theory he presents is innovative and at least aims to be comprehensive. And of course there are some good arguments for it. Despite this there are, as always, occasional grounds for complaint.

Although Lycan is very careful to get the syntax of 'if' right, and proves that unlike 'and' and 'or' it is not a co-ordinating conjunction, it is not so clear that the syntactic evidence provides distinctive support for his semantic theory. If it's consistent with the syntax to say *p if q* means *All relevant q-events are p-events*, it's consistent with the syntax to say that it means *All nearby q-worlds are p-worlds*. So the syntactic argument for preferring Lycan's theory, to, say, Stalnaker's, is not obviously overpowering. Lycan suggests that we can naturally paraphrase conditionals as quantifications over events, but since he is using *event* 'in a slightly uncommon way' (17) it is not obvious what support this gives for his theory.

There are few reasons to favour the use of events rather than worlds in the analysis. The fact that events can be incomplete seems to only cause complications for the theory. The fact that they can be inconsistent is used to rescue some intuitions about conditionals with impossible antecedents, but many would argue those intuitions should be discarded.

But the main worry is that Lycan needs to say more about some key notions, particularly about his *R* and about validity. In the discussion of the Riverboat Puzzle, Lycan says, "I do not have a good enough intuitive handle on my own notion of 'relevance' to provide a crushing answer [to a question about why certain events are not covered by *R*]." (173)  Lycan says that for an event to be *R*, "the utterer must have it at least tacitly in mind as a live prospect." (19) All events in *R* are 'envisaged', to use the term he lands on. But "there is somethig slightly artificial or stylized about 'envisaging' ... 'Envisaging' is not a purely *de facto* cognitive or other psychological state." (30) The upshot is that the envisaged possibilities are some, but not always all, of those that are (possibly tacitly) regarded as live. Just which possibilities then? We are never given a specific account. Any account we do get is, as in the above quote, almost immediately qualified. Since *R* does so much work, the reader is probably owed a little more here. (This point is made at greater length in Ken Turner's excellent review of *Real Conditionals* in the *Journal of Pragmatics* forthcoming.)

We are also never specifically given an account of validity. We are told that several argument forms, from antecedent-strengthening to modus ponens, are invalid. This seems to mean that one could assert their premises then reject, or a least decline to assert, their conclusion. It's important that this process of assertion and rejection take place in real time, because the value of *R* needs to change for the arguments to be invalid. Lycan has some arguments that this conception of validity is the philosophically interesting one, but this deserves more treatment. The logical reforms it draws in go well beyond the logic of conditionals. On Lycan's approach, *All swans are white, so all Australian swans are white* is, presumably, invalid, since the scope of the quantifier could change from premise to conclusion. And contraposition fails for valid arguments. Contraposed modus ponens: *p, not q, so not if p, q* is valid, but modus ponens is not.

None of this is to deny that *Real Conditionals* is a great contribution to the literature, and if it causes more theorists to pay serious attention to Lycan's Event Theory, that would be an excellent consequence.

\vspace{1cm}