---
title: "Comments on *Property Versatility and Copredication*"
subtitle: "For symposium at 2026 APA Eastern Division Meeting"
---

The first thing to say is that this is a great book.^[The book, of course, is @LM2025.] I loved reading it, working through the examples, and thinking about the puzzles, and I strongly recommend it to people here. It's obviously relevant to lots of people working in, or teaching, metaphysics and philosophy of language. But there also turn out to be things relevant to philosophy of mind, to aesthetics, and, this is what I'll be talking about, philosophy of social science.

I'm not much of a critic since I'm sympathetic to the overall view. One background theme to these remarks is that Leiebesman and Magidor (hereafter, LM) aren't sufficiently radical. There will be two foreground themes. One is that they need to get more physical; they give physical objects short shrift at a couple of points. Another is that once we have abstracta like i-books, plenitude results a la @Fairchild20xx are inevitable. And then things get weird. Not that there's anything wrong with that; the social world is weirder than it looks. But cataloging the weirdness is valuable.^[These notes are too long, and there are notes along the way about what I'm planning to cut from the presented version. But it was useful to me to have them written out.]

# Example 1: Box on Knox

One guiding puzzle is explaining (@famousshelf).

(@famousshelf) There's a famous book on the shelf.

Puzzle: If 'book' means p-book (@famousshelf) is false, since that p-book isn't famous. But if 'book' means i-book (@famousshelf) is also false, since the i-book isn't on the shelf. LM argue against that second claim. They say i-books can be on shelves. But they are more sympathetic to the first. They resist the idea that p-books can always inherit properties that are grounded^[I'm being a little cheeky here since I'm not sure they'd agree with expressing things in terms of grounding. But it seems to fit the picture they have, and it's easy enough to translate this into less metaphysically loaded talk.] in facts about i-books. The evidence for this is that (@bestsellingp) is defective.

(@bestsellingp) Three wrinkled books on the shelf are bestselling.

That just seems like an awkward locution to me, and not evidence especially about p-books. (@bestsellingi) is just as defective, even though it's clearly about i-books.

(@bestsellingi) Three books featuring Inspector Rebus are bestselling.

We can give an independent argument that p-books can inherit properties freely. Imagine my wife and I are moving house. There are plenty of books that we both have in virtue of being cultured people, *The Thin Man*, *The Big Sleep*, etc, so our joint collection has some duplicates. The books go in boxes, and each box has 50 p-books and 40 i-books. Now how should we arrange the boxes? There are boring options, like sorting them by genre, chronologically, alphabetically by author, alphabetically by title, etc. But it's more fun to sort them by sales figures, or by famous, or comedic value. Depending on what sort order we choose, one of (@boxsales) to (@boxfunny) will be true of the first box.

(@boxsales) This box has 50 bestselling books.
(@boxfame) This box has 50 famous books.
(@boxfunny) This box has 50 funny books.

In those sentences, 'book' must be p-book, because there are only 40 i-books per box. But really any feature of i-book could be used in the penultimate word. So p-books inherit i-book features generally.

## Example 2:  Intermediate Classifications

Another core example of the book involves duplicate books. My teenager's Homer shelf has two copies of the _Odyssey_ and one of the _Iliad_. Intuitively both (@nyayahomer2) and (@nyayahomer3) have true readings.

(@nyayahomer2) Their shelf has exactly two books on it.
(@nyayahomer3) Their shelf has exactly three books on it.

My Homer shelf is a more complicated case. It only has the _Odyssey_, but it has two copies of the Fagles translation and one of the Wilson. It seems to me that all of (@brianhomer1) to (@brianhomer3) have true readings, and I think from what LM say in ยง9.3 they agree.

(@brianhomer1) My shelf has exactly one book on it, the _Odyssey_.
(@brianhomer2) My shelf has exactly two books on it, the Fagles translation and the Wilson translation
(@brianhomer3) My shelf has exactly three books on it, which I can throw at those beer bottles.

The solution is to say that the _Odyssey_ is an i-book, and so are the translations of it. That seems like a good step to me, but there are two questions. 

One concerns my wife's Homer shelf, which has one p-book on it, the Wilson translation of the _Odyssey_. Now (@ishanihomer1) is true, but (@ishanihomer2) is false, even though there are two i-books, the _Odyssey_ and the Wilson translation of the _Odyssey_ on her shelf.

(@ishanihomer1) Her shelf has exactly one book on it.
(@ishanihomer2) Her shelf has exactly two books on it.

Here's a challenge. It's not immediately an objection, but if it can't be answered it would be. Given LM's theory of i-books, why don't we get a true reading of (@ishanihomer2)? This is related to an argument @Sider199x gives against Lewis's theory of continuants.

The other question concerns how many variants we can get that are like (@brianhomer1) to (@brianhomer3). (In talk I'll end section here, but the following examples are possibly interesting.)

Does it apply to editions? My Jeffrey shelf has two copies of the first edition of _Logic of Decision_ and one copy of the second edition. Can we get a reading of (@brianjeffrey2) on which it's true?

(@brianjeffrey2) My Jeffrey shelf has exactly two books on it.

Here's a slightly harder case. My Keynes shelf at the office has four p-books on it. It has both volumes of _Treatise on Money_ and two copies of the _General Theory_. It's easy to get readings where we get two and four books, but can we get a reading where (@briankeynes3) is true?

(@briankeynes3) My Keynes shelf at the office has exactly three books on it.

I think we can. It has volumes 5 to 7 of the Collected Works, i.e., three books. Compare my Beatles shelf. It has seven pieces of vinyl on it; _Revolver_ and three copies of the White Album. Do we get true readings of each of (@brianbeatles2) through (@brianbeatles7)?

(@brianbeatles2) My Beatles shelf has two records on it.
(@brianbeatles3) My Beatles shelf has three records on it.
(@brianbeatles4) My Beatles shelf has four records on it.
(@brianbeatles7) My Beatles shelf has seven records on it.

I think so^[For (@brianbeatles2) _Revolver_ and the White Album; for (@brianbeatles3), _Revolver_ and both discs of the White Album; for (@brianbeatles4), the four spines; for (@brianbeatles7), the seven discs.], but I'm getting less certain. I'll end this with two cases where I think we really don't get the readings, though again I'm not certain.

My home Keynes shelf is cleaner. It has the 30 volume collected works, and nothing else. I think (@briankeynes1) is false, the collected works is not a book.

(@briankeynes1) My Keynes shelf at home has exactly one book on it.

I feel in theory we should be able to get (@briankeynes29), counting the two volumes of the _Treatise on Money_ as one book, or even (@briankeynes28), doing that and also not counting the index, volume 30, as a book. But personally I can't hear them as true.

(@briankeynes29) My Keynes shelf at home has exactly 29 books on it.
(@briankeynes28) My Keynes shelf at home has exactly 28 books on it.

Or from a different direction. My bible shelf has a modern King James bible, and nothing else. (So it doesn't have the apocrypha.) So here are some books on that shelf: Genesis, Exodus, Leviticus, etc. Still, I can't hear (@brianbible66) as true.

(@brianbible66) My bible shelf has 66 books on it.

But maybe I'm just not sufficiently holy. None of these are objections; unlike the Sider-style point about overlapping books. I just think it's worth trying to get clearer on what the data is, and what the theory would have to be to track it.

## Example 3: Schools of schools

LM say that 'school' is not semantically variable. I think that can't be right, because of what they say about the variable granularity of i-books.

The context is that they argue against people who say that sometimes 'school' means 'school building'. I agree that can't be right. For one thing, schools typically, at least in my schooling, have multiple buildings. For another, the hypothesis that schools are buildings doesn't capture the data it was meant to capture, that schools can be vandalized. If one sets fire to the school football field, as I definitely did not do on April 17th 1986, one has vandalized the school but not any building.

But the problem is that schools can come in different granularities, or have different persistence conditions, and that makes 'school' semantically variable. Just in Ann Arbor there are a bunch of cases of this. Was the school I work out founded in 1817, when something like it's closest continuant was founded in Detroit, on in 1837, when a university was first founded in Ann Arbor? Did my current President, President Grasso, change schools when he 'moved' from UM Dearborn to UM Ann Arbor to become President? I think in both cases both answers are ok, which is evidence of semantic variability. But there are stronger cases at the elementary level.

Back in the bad old days of segregation, there were two elementary schools in southeast Ann Arbor: Bryant and Pattengill. One of these was predominantly Black, the other predominantly white. (I never learned which was which.) As a desegregation move, the school district was reorganised. Bryant became a K-2 school, and Pattengill a 3-5 school; unlike the typical K-5 organisations. The catchment area was the same for 'each'. This was a kind of bussing, and it basically worked; a Worthwhile Ann Arbor initiative. There is a level of common organisation to Bryant and Pattengill, but also some independence. The messiness is nicely reflected in their websites, where they have their own name, but also the logo for Bryant-Pattengill.

So question, are these the same school? I think it's vague in a way that reveals semantic indeterminacy. Imagine two parents whose children just moved from grade 2 at Bryant to grade 3 at Pattengill are asked if their child has changed school. One says, "Yes, they moved from Bryant to Pattengill". The other says, "No, though they did change campus." I think in local dialects both answers are acceptable, though they can't be conjoined. That's good evidence of semantic variability.

In the talk I'll finish there, but I'll note here that there is a case I'm more familiar with that makes a similar point. Ann Arbor has had for several decades something it calls an Open school. This doesn't have a catchment area, and it has an idiosyncratic curriculum. It's basically a hippie school. From 1986 to 1999 the Open school was at a campus called Bach. Since then the Open school has been at a campus called Mack. These are only about half a mile apart, closer than Bryant and Pattengill, but they are administratively separate. When Open wasn't at those campuses, they were normal K-5 schools.

Now we have three characters, Betty, Mary and Gauri. Betty and Mary were elementary school students in the 1990s. Betty went to Bach, i.e., to Open. Mary went to Mack Elementary. They each, separately, talk to Gauri, who is a current student at the Open School at Mack. I'm pretty confident that it's fine in local dialect for each of them to say to Gauri, "I went to the same school you're going to." But it's not fine (again in local dialect) for them to say to each other, "We went to the same school". I think the only way to square those responses is to say that 'school' is semantically variable.

That said, there is one other way to make everything fit together in this example. We might insist that 'school' is univocal, and deny the transitivity of identity. LM say in places that they have a particularist approach to metaphysics, staying away from big generalisations. Is transitivity of identity one of those big generalisations that they will be happy to give up to get the simplest explanation of the data? I hope not, but it is a possible way out here.

# Example Four: Breakfast at Sweethearts


