---
title: "Books, Schools, and Restaurants"
draft: true
author:
  - name: Brian Weatherson
    orcid: 0000-0002-0830-141X
    email: brian@weatherson.org
    affiliation:
      - name: University of Michigan
        department: Department of Philosophy
        city: Ann Arbor
        region: MI
        country: USA
format:
  pdf:
    documentclass: article
    geometry: margin=1in
    linestretch: 1.5
    output-file: "pv-titlepage"
    include-in-header:
      text: |
        \usepackage{titling}
        \pretitle{\begin{center}\LARGE}
        \posttitle{\end{center}\vskip 1em}
  docx:
    output-file: "pv-titlepage"
number-sections: false
---

## Abstract {.unnumbered}

This is a contribution to a symposium on David Liebesman and Ofra Magidor's book *Property Versatility and Copredication*. It was originally presented, in compressed version, at the 2026 Eastern APA. I agree with their big picture metaphysical view, but quibble at four points about its application to social metaphysics. First, Liebesman and Magidor argue that abstract objects can have paradigmatically physical properties like being on shelves. I agree, and suggest they should accept the converse claim, that physical objects can have properties usually associated with abstracta. Second, I argue that there are several puzzles about how their view applied to books of variable granularity, like multi-volume works, or volumes containing several books. Third, I argue (against their preferred view of schools), that schools can come in different levels of granularity. Finally, I argue that 'restaurant' and 'coffee shop' can sometimes pick out physical objects. Liebesman and Magidor argue that these terms don't pick out buildings, and I agree. But, I claim, they do sometimes pick out physical locations.

## Keywords {.unnumbered}

copredication; property versatility; social ontology; semantic ambiguity; abstract objects; mereology

## Statements and Declarations {.unnumbered}

**Competing Interests:** The author has no competing interests to declare that are relevant to the content of this article. This paper has no associated data.
