---
title: "Review of “Words Without Meaning”"
description: |
  Review of Christopher Gauker, “Words Without Meaning”. Cambridge: MIT Press, 2002. 
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
date: 09-08-2003
self-contained: false
preview: gauker.jpg
citation: false
citation_url: https://ndpr.nd.edu/news/words-without-meaning/
categories:
  - book review
  - on books
  - language
output:
  distill::distill_article:
    toc: false
    toc_depth: 2
    number_sections: TRUE
---

In philosophy it's hard to find a view that hasn't had an *ism*
associated with it, but there are some. Some theories are too obscure or
too fantastic to be named. And occasionally a theory is too deeply
entrenched to even be conceptualised as a theory. For example, many of
us hold without thinking about it the theory that "the central function
of language is to enable a speaker to reveal his or her thoughts to a
hearer," (3) that in the case of declarative utterances the thoughts in
question are beliefs whose content is some proposition or other, and
that hearers figure out what the content of that belief is by virtue of
an inference that turns on their beliefs about the meanings of the words
we use. These claims might seem too trivial to even be called a theory.
They have seemed too trivial to draw an *ism*. Christopher Gauker calls
them 'the received view', and the purpose of his book *Words Without
Meanings* (all page references to this book) is to argue against this
received view and propose an alternative theory in its place. In
Gauker's theory the primary function of language is social coordination.
If language ever functions as a conduit to the mind, this is a secondary
effect.

<aside>
Published in [Notre Dame Philosophical Reviews](https://ndpr.nd.edu/news/words-without-meaning/).
</aside>

It is useful to have an *ism* for everything, so let's call 'the
received view' *Lockism*, since Locke believed something similar. Of
course, Locke probably didn't have any detailed opinions about where the
semantics/pragmatics distinction lies or what the role and importance
Horn scales might be or how to build a compositional semantics for
quantification, or indeed about many of the issues on which various
contemporary Lockists have their most distinctive views, but there's an
intellectual legacy worth noting. Still, if Locke was a Lockist without
having views on these matters, this starts to suggest how broad, and how
divided, the Lockist church may be. Lockists need not agree on the
semantic analyses of indicative conditionals or attitude reports. They
need not even agree on whether there are such things as conventional
implicatures or deep structures. An argument against Lockism will have
to either focus on the few rather platitudinous points where Lockists
agree, or try to respond to all the ways Lockists might develop their
position. Gauker takes both options throughout his book. The central
theses of the Lockist position that are attacked concern the nature and
contents of beliefs, the nature of logical implication and the status of
truth. Gauker's attacks on Lockist theories of quantifier domain
restriction and of presupposition rely more heavily on attacking all the
variants of Lockism.

But the arguments against Lockism are not necessarily the most important
parts of the book. Alongside the criticisms of Lockism, Gauker develops
in great detail his own positive theory about the nature and role of
linguistic communication. Gauker suggests "the primary function of
assertions \... is to shape the manner in which interlocutors attempt to
achieve their goals." (52) Conversations do not take place in a vacuum.
Conversants frequently talk because they want something. The world does
not always make it easy for us to get what we want, but sometimes at
least other people can tell us which ways work best.

It becomes crucial to Gauker's theory here that certain actions are or
are not in accord with certain sets of sentences. Given this idea the
primary norm of conversation becomes: *Say things such that others who
act in accord with what you say, and with what else has been said, will
achieve their goals*. The concept of actions according with (sets of)
sentences seems intuitive at first. If my goal is to download the new
Matrix movie, then going to stealthatmovie.com is in accord with {'The
new Matrix movie is available at stealthatmovie.com'} while going to
moviebootlegger.com, or anywhere else, is not. (These are, by the way,
fake site names.) Given this idea of actions according with sets of
sentences, we can then define the *context*, or set of relevant
sentences, as the smallest set such that "all courses of action in
accordance with it relative to the goal of the conversation are good
ways of achieving the goal". (56) We can then restate the primary norm
as: *Say things that are in the context*. Those sentences will be useful
to say, and their negations will be useful to deny. This idea of useful
assertability becomes crucial to Gauker's theory, often playing much the
role that a Lockist has truth play. For example, validity gets defined
in terms of assertability preservation in all contexts.

Clearly the concept of actions according with contexts given goals is
quite crucial, but there's less explication of it than we might hope. I
have some idea what it might mean to say that my going to
stealthatmovie.com accords with the *proposition* that the new Matrix
movie is available at stealthatmovie.com, and I have some idea which
facts in the world may make this true. But I don't have as clear an idea
about what it means to say this action accords with any *sentence*.
Sentences are just marks on paper, or sound waves. We can be pretty sure
that this accord between actions and marks on paper is not a *primitive*
fact about the world. Lockists think that actions accord with sentences
because sentences express propositions and some actions accord with
propositions. But this isn't Gauker's account, and it isn't clear what
is. At one stage Gauker notes that the distinction between actions that
accord with a context and those that do not will be primitive relative
to the 'fundamental norms of discourse', which are the primary focus of
*Words Without Meanings*. That sounds right, and I hope it's a sign that
we'll see more details about the concept of accord in future work.

This issue though is important because there are a few reasons to worry
about how the concept of accord will be explicated. First, whatever
problems face Lockist theories of meaning, including some of the
problems Gauker raises, may recur here. Second, some theories of accord
will introduce entities that are functionally just like meanings, so if
meaning is a functional concept, as seems plausible, those theories will
not end up being theories of words without meaning. Third, as Gauker
notes, there are serious epistemological questions about how we could
ever learn which actions accord with which contexts relative to which
goals. Those who are impressed by Fodor's arguments for the
systematicity of human linguistic competence will probably think these
questions raise insuperable difficulty for anything like Gauker's
program. On the other hand, those that are impressed by Gauker's program
will probably find these Fodorian claims overstated.

*Words Without Meaning* concludes with three chapters setting out a
rather distinctive view of belief. Gauker argues that a complete account
of the role of belief ascriptions should be sufficient for a theory of
belief. This is not because of a general policy that explaining the talk
about something is sufficient to explain the thing in general. Such a
policy is not entirely antithetical to Gauker's overall picture, but it
would be hard to defend in all cases. Rather, Gauker argues, in practice
we have little use for beliefs and desires other than in our ascriptions
of them, so an account of their ascription is all the account we need.
Many philosophers will baulk here, because they think folk psychology
provides a crucial role for beliefs and desires. Since folk psychology
is a crucial part of how we predict the actions of other people, and of
how we explain their actions, there is an important aspect of the
*nature* of beliefs and desires that a mere account of their ascriptions
will not capture. These philosophers will not agree with Gauker that an
"account of the attribution of beliefs and desires is already an account
of [their] nature." (271‑2)

Gauker's response to these philosophers is to question the explanatory
and predictive capacity of folk psychology. He argues first that the
explanatory, and especially the predictive, power of folk psychology is
much over-rather. And more importantly, he argues that when there do
appear to be good folk psychological explanations or predictions, there
are equally good explanations that do not appeal to beliefs and desires.
The argument for this involves running through several cases with some
care, but very roughly the common theme is that beliefs and desires (if
they exist) are themselves capable of explanation, so at least most of
the time we can replace an explanation in terms of beliefs and desires
with one that appeals to the explanations of those very beliefs and
desires. This gives us a fairly general strategy for dispensing with
folk psychological concepts in explanation and prediction.

This does not mean that we adopt an error theory of belief or desire
ascriptions. Gauker thinks these have a use, so they are properly
assertable. Their role, in general, is to let us speak on behalf of
other people. "The primary function of attributions of belief and desire
is to extend the range of participation in conversation." (226) When I
say that Harry believes that tech stocks are good investments, I say *on
Harry's behalf* that tech stocks are good investments. Unfortunately, we
never get a complete positive characterisation of when it is permissible
to say something on Harry's behalf. We are told that such assertions,
like all assertions, must be relevant to the conversation, but beyond
that not a lot. We are told that it can't just be permissible to say
this just in case Harry would be disposed to say it, were he here. Harry
might have a habit of keeping his investment ideas to himself, but still
believe that tech stocks are good investments. And we're told that this
can be permissible to say even if Harry has never made an 'inner
assertion' that tech stocks are good investments. But this doesn't
amount to a positive characterisation. Further, it's not clear how to
extend this account to all attitude reports, especially reports of
desire-like attitudes. One could truly say *Brian wants to play for the
Red Sox*, but in doing so one is not making a command, or even a
request, on my behalf.

As well as these intriguing positive proposals, there are several
arguments against Lockism. Chapter 2, on mental representation, is an
attack on the Lockist position that there are beliefs with propositional
content. Gauker first notes that any attempt to provide an atomistic
theory of mental content seems to run into insuperable counterexamples.
The main focus is Fodor's asymmetric dependence theory, but a few other
atomist theories are raised and dismissed. Gauker suggests that holistic
theories are a little more promising, but when we look at the details we
see that these all fall to a version of Putnam's model-theoretic
argument. Gauker's argument here differs from Putnam's in two key
respects. First, it concerns primarily mental content, rather than
linguistic content. Second, it has fewer theoretical overheads. Gauker
shows that the argument never really needed any complicated mathematics;
the formalism in the standard semantics for first-order logic is quite
sufficient. Despite those two differences, the argument is fairly
familiar, and the moves that could be made in response are also, by now,
fairly familiar. Gauker quickly surveys these moves, and notes why he
thinks none of them work, but the survey will probably be too brief to
convince many who are happy with their preferred reply to Putnam. Those
who are not happy with any of the replies to Putnam, or who would be
more impressed by a version of Putnam's argument that did not drift into
needless technicality, should enjoy Gauker's argument.

The middle half of *Words Without Meanings* consists of six case studies
designed to show that Gauker's approach can solve problems that are
intractable for Lockism. Three of these are described as being in
pragmatics, the other three in semantics. Here Gauker more often has to
revert to arguing against each of the different versions of Lockism in
the literature, for there are few points of agreement among Lockists
once we get to the details on how language works. This is particularly
clear when we look at pragmatics. I guess most Lockists agree that there
is a pragmatics/semantics distinction, and most of those who do agree
think that there is such a thing as scalar implicature. Beyond that
there are disagreements everywhere. So Gauker is more often required to
argue against all the versions of Lockism in existence. Even if he
succeeds against all of them, Lockism is a growing doctrine, and a smart
Lockist could often take Gauker's positive ideas and incorporate them
into Lockism. So it's not clear we'll see any *knock-down* argument
against Lockism here. But maybe there will be an interesting abductive
argument develop, and in any case it is always worthwhile to see
Gauker's positive account. Space prevents a full discussion of many of
the issues raised here, but I'll provide a quick summary of the salient
issues, and why Gauker thinks he has an advantage over his Lockist
rivals.

The first case study concerns domains of discourse, which mostly means
domains of quantification. To use Gauker's example, imagine Tommy runs
into Suzy's room, where Suzy is playing with her marbles, and says "All
the red ones are mine." What determines the domain of Tommy's
quantifier? If it is what Tommy intends, then we might end up saying
that his sentence is, surprisingly, true. For Tommy, it turns out,
intends only to speak of the marbles in his room, which are as it turns
out all his. But if we don't take it to be what Tommy intends, and
instead let the domain be set by what Suzy thinks the domain is, or what
a reasonable hearer would think the domain is, then we undermine the
Lockist picture that the role of language is for the *speaker's*
thoughts to be communicated. In these cases it is the thoughts of the
hearer, or of a reasonable hearer, seem to determine the meaning of what
is said. Gauker suggests it is better to say that the domain is the
class of things that are relevant to the goal of the conversation that
Tommy and Suzy are having.

The second case concerns presupposition. Allegedly, some sentences are
such that they cannot be properly asserted or denied unless some
condition, the presupposition, is met. Sentences containing factive
attitude verbs are sometimes held to fall into this category. So I
cannot affirm or deny *I regret that you failed the test* unless you
failed the test. There are several Lockist theories of presupposition,
but Gauker argues that none of them can satisfactorily explain how
asserting such sentences can inform the hearer of the truth of the
presupposition, in this case that the test was in fact failed. Gauker's
theory, which does not have a special category of truth conditions apart
from assertability conditions, does not have this difficulty. For a
similar reason, however, the Lockist theory that rejects the concept of
presupposition also avoids any problem of informative presupposition.

The third case concerns Gricean implicature. Gauker notes, correctly,
that we can well explain the effects of Gricean implicature without
presuming that the hearer even contemplates what the speaker had in mind
in speaking. But this kind of contemplation is essential to Grice's
official story. Gauker's alternative suggestion is that we can explain
non-literal communication by assuming the hearer draws inferences about
the context from the assertability of what is actually said.

The next three case studies are classified as 'Semantics', so we might
hope that here Lockists will present a more unified target. But two of
the studies seem, from a Lockist perspective, to concern the
semantics/pragmatics boundary, so again there will be several varieties
of Lockism that need to be addressed.

The first semantics study concerns quantifiers. Gauker argues that in
practice (1) is a bad argument form, (1a) for instance is invalid, while
(2) is a good argument form.

1. Everything is F. Therefore, a is F.
1a. Everything is made of wood. Therefore, Socrates is made of wood.
2. a is F. Therefore, something is F.

Gauker argues in some detail that various Lockist theories of quantifier
domain restriction cannot explain the asymmetry here. On his theory, the
asymmetry falls out quite naturally, since quantification is always over
named objects, and once named an object is relevant. So (1) need not be
valid, since a need not have been named, but (2) must be valid.

The last two case studies are the most interesting, and the most
intricate. I can't do justice in a small space to the details of
Gauker's theory, but I'll say a little about the issues raised. Chapter
8 concerns conditionals. Gauker thinks he has a telling argument against
a central Lockist claim. The primary intuition is that (3) and (4) are
logically equivalent, i.e. each entails the other, (at least when p and
q are not themselves conditionals), but they are not equivalent when
embedded in longer sentences. In particular, (5) and (6) need not be
equivalent.

3. Either not p or q
4. If p then q
5. Either not p or q, or r
6. If p then q, or r

If this is right, then what Gauker calls 'the Equivalence Principle',
that substitution of logical equivalent constituents preserves
truth-conditional content, is false. Gauker suggests this is a serious
problem for Lockism. There are, however, a few Lockist theories in which
Equivalence fails. For example, in classical supervaluationism, p or not
p is a logical truth, and p is equivalent to p is true, but p is true or
not p is not a logical truth. So some Lockists have learned to live
without Equivalence. More importantly, the data that suggests that (3)
and (4) are logically equivalent isn't unequivocal. Some Lockists have
provided arguments as to why (3) and (4) will usually have the same
assertion conditions even though they have different truth conditions.
(Gauker notes Robert Stalnaker's 1975 paper 'Indicative Conditionals'
that argues for this line.) If those arguments can be made to succeed,
then we can keep Equivalence by denying that (3) really *entails* (4).

More interesting than the possible Lockist replies is Gauker's own
theory. He manages, quite impressively I think, to provide a recursive
definition of truth conditions for the connectives without keeping
Equivalence. The rough idea is that *If p then q* is true iff p strictly
implies q relative to the context. Strict implication theories usually
block the inference from (5) to (6), as Gauker's does, but they also
normally block the inference from (3) to (4). In Gauker's theory,
however, because entailment is defined in terms of
assertability-preservation, and disjunctions can only be asserted if one
or other disjunct is assertable in every possibility left open by the
context, the inference from (3) to (4) is valid. Roughly, any
contextually salient possibility either contains not p or q, so all the
possibilities that contain p contain q, in which case *If p then q* is
assertable. This theory still has some counter-intuitive features, since
the paradoxes of material implication are still with us, but it's a
fascinating addition to the literature on conditionals.

The final case study concerns truth, and in particular the semantic
paradoxes. Gauker argues that extant Lockist responses to the paradoxes
are not capable of handling metalinguistic versions of the paradox. In
particular, Lockist theories struggle with sentences like (7).

7. (7) does not express a true sentence in this context.

Gauker's argument that his theory does better than the Lockist here has
two parts. First, he has a detailed demonstration that it is impossible
to infer a contradiction directly from (7) in his theory. Second, he
argues that a Lockist explanation of what's going on with (7) has to
posit that uttering, or writing, 'this context' changes the context.
This might be true, indeed Gauker endorses a similar claim in his
response to the paradoxes. But on most Lockist accounts of what contexts
are, we could replace the demonstrative with some other phrase that more
directly picks out the context. For example if a context is just an
ordered n-tuple, we could just replace 'this context' with a description
of the n-tuple that is, actually, the context. Here it does look as if
Gauker's theory has more resources than the traditional Lockism. It
remains to be seen whether Gauker's theory is completely free from the
paradoxes - it's quite a bit harder to come up with a consistent theory
of truth than it is to block the liar paradox - but again Gauker
provides an interesting alternative to existing approaches, and one that
experts in the area should pay close attention.

Overall, what should we make of *Words Without Meanings*? I think the
book has three major aims, and it succeeds in two of them. The first aim
is to extend Gauker's preferred theory of linguistic communication to
show how it handles presupposition, quantification, conditionals,
attitude reports and truth ascriptions. In this it succeeds quite well,
especially in showing how the project holds together technically. The
second aim is to raise a host of problems for the Lockist theory,
problems that are deserving of serious consideration and response. And
again, there is no doubt it succeeds. Even if one thinks that all the
problems Gauker raises can be solved, having them set forth so sharply
certainly advances the debate. The third aim, the big one, is to
convince Lockists that their research program is moribund, and Gauker's
contextualist alternative is the way of the future. That aim, in short,
is for a revolution in semantics. (And in any fields that presuppose
Lockist semantics. Many of our best syntactic theories have to be
revised if Gauker is correct.) Here I think the book is less successful,
if only because the aim is so high. It's not clear how any short book,
and the MIT series *Words Without Meaning* is in is clearly a series for
short books, could trigger such a revolution. Lockism may have its
weaknesses, and Gauker shines a spotlight on a few, but it's been a
relatively productive program the last fifty years, so overthrowing it
will not be easy. Such a revolution would need a longer book, or books,
answering among other questions the metaphysical and epistemological
questions about Gauker's concept of actions according with sentences we
noted above. Gauker's work always leaves the impression that he has
worked through the relevant material in much more detail than is
apparent from a superficial reading of the text, so such books and
papers may well be in the pipeline. If one is already on Gauker's side
in these disputes, one should heartily welcome the wealth of detail
*Words Without Meaning* adds to his program. If one is more
conservative, more orthodox, one should perhaps be worried about the
anomalies rising, but not panicked. At least, not panicked *yet*.
