---
title: "Four Problems in Decision Theory"
abstract: |
  TBC
date: today
draft: true
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
categories:
  - games and decisions
  - unpublished
format:
    html:
       css: ../trad_defn.css
    pdf:
      fig-format: pdf
      output-file: "Four Problems in Decision Theory"
      include-in-header:
        - file: ../quarto2024.tex
        - text: |
            \setkomafont{descriptionlabel}{\normalfont\scshape\bfseries}
      include-after-body: 
        text: |
          \noindent Published online in September 2024.
format-links: [html]
---

Decision theory has become too disjointed. Problems that should be discussed together have spawned separate literatures. This paper aims to put the parts back together.

One principle, what I'll call the Single Choice Principle, tightly constrains the solutions to four separate kinds of problems in decision theory. These are: how to model rational risk aversion; how to incorporate evidential connections between options and states; whether probabilities, values, or options can be non-linear; and, how to relate synchronic and dynamic choice. In each case, once we accept the Single Choice Principle, only a narrow range of views are left as viable. By seeing the connections between these four questions, we also see how to answer them.

Ultimately, I'll argue for these conclusions, all of them using little more than the principle I call Single Choice.

- Risk-sensitive alternatives to orthodox expected utility theory, as defended by e.g., @BuchakRisk, are mistaken.
- The right decision theory for problems involving Demons (e.g., Newcomb's Problem) is a form of causal ratificationism.^[It's a version of what @EellsHarper1991 call _basic ratificationism_.]
- Even if probabilities are completely ordered (contra @Keynes1921), and values of outcomes are completely ordered (contra @Chang2002), preferences over options are not completely ordered. This undermines many of the arguments that have been made against Keynes and Chang.
- The two main views about dynamic choice, the _sophisticated_ [@Hammond1976] and _resolute_ [@McClennen1990], are both half right. In cases where the agent's preferences do not change over the course of a decision problem^[Cases where they do change are set aside for purposes of this paper; see @Pettigrew2019 for a good discussion of the issues that they bring up.], a choice is rational only if both dynamic and resolute approaches would endorse it.

In the next two sections I'll set out the Single Choice Principle. The following six sections will make good on the promises in these bullet points. (There are two sections each on the middle two bullet points.) I conclude by noting how the arguments here support a conclusion defended by William Harper [-@Harper1984; -@Harper1986; -@Harper1989]: decision theory should be more like game theory.

```{r tikz-fonts}
#| echo: FALSE
#| output: FALSE

if(knitr::is_latex_output()) {
font_opts <- list(extra.preamble=c("\\usepackage{fontspec}", 
                                   "\\setmainfont{EB Garamond}",
                                   "\\usetikzlibrary{calc}",
                                   "\\usetikzlibrary{backgrounds}",
                                   "\\definecolor{backgroundcolor}{RGB}{255,255,255}"),
                                   fig.ext = "pdf")
} else {
  font_opts <- list(extra.preamble=c("\\usepackage{fontspec}", 
                                   "\\setmainfont{Scala Sans Pro}",
                                   "\\usetikzlibrary{calc}",
                                   "\\usetikzlibrary{backgrounds}",
                                   "\\definecolor{backgroundcolor}{RGB}{249,255,255}"),
                                   fig.ext = "svg")
}
options(tinytex.engine = "xelatex")
```

{{< include chess.txt >}}

{{< include info-set.txt >}}

{{< include buchak.txt >}}

{{< include edt.txt >}}

{{< include ratify-again.txt >}}

{{< include non-linear.txt >}}

{{< include more-non-linear.txt >}}

{{< include dynamics.txt >}}

::: {.content-visible unless-format="html"}
## References {-}
:::