---
title: "Review of “Lewisian Themes”"
description: |
  A review of Frank Jackson and Graham Priest (eds), “Lewisian Themes: The Philosophy of David K. Lewis”, Oxford University Press, 2004.
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
date: 08-02-2005
citation_url: https://ndpr.nd.edu/reviews/lewisian-themes-the-philosophy-of-david-k-lewis/
citation:
  type: review-book
  container-title: "Notre Dame Philosophical Reviews"
categories:
  - on books
  - David Lewis
  - history of analytic
format:
  html: default
  pdf: 
    output-file: "Review of Lewisian Themes"
    include-after-body: 
        text: |
           Published in \emph{Notre Dame Philosophical Reviews}, 2005 \\
           \url{https://ndpr.nd.edu/reviews/lewisian-themes-the-philosophy-of-david-k-lewis/}
  docx: 
    output-file: "Review of Lewisian Themes"
---

David Lewis didn't seem particularly fond of festschrifts. He didn't participate in the one volume of papers on his work published in his lifetime (*Reality and Humean Supervenience*, Rowman and Littlefield 2001). He rarely contributed to festschrifts for others, in recent decades only contributing papers to volumes in honour of his very closest friends (David Armstrong and Hugh Mellor). I haven't done a systematic study of this, but my casual reading suggests he didn't often refer to papers published in festschrifts either. More generally, he strongly favoured publishing in journals with blind review to publishing in edited volumes of solicited papers.

So if there was to be a festschrift for David Lewis, as there surely should be, it should be one put together just the way *Lewisian Themes* was. Most of the papers for it were selected by blind refereeing, not by inviting the usual suspects. (And the result was that several young philosophers, even graduate students, are represented in the collection.) The festschrift did not start life as this volume, but as an edition of a journal. And not just any journal, but the journal that Lewis's work most often graced: the *Australasian Journal of Philosophy*. This volume reprints the papers from that issue, and adds four more papers that were left out for space considerations.

The result is a marvellous collection that reflects Lewis's work in both its quality and its breadth. Given the amount of material herein, I can do little more than summarise the papers and present a few reflections on what some of them tell us about the future directions for Lewisian philosophy. Here is the list of topics covered, each of which is followed in parentheses by the names of the authors who address that topic.

-   Quantum Mechanics (David Lewis; David Papineau)
-   Properties (Andy Egan; Josh Parsons)
-   Truth in Fiction (Richard Hanley; Jim Mackenzie)
-   Ramseyan Humility (Rae Langton; Jonathan Schaffer)
-   Chance (Adam Elga; Ned Hall)
-   Mental Content (Robert Stalnaker; Barry Taylor; Alan Hájek and Philip Pettit)
-   Modal Realism (Kris McDaniel; Barry Taylor; Max Cresswell)
-   Counterpart Theory and Essentialism (Max Cresswell; L. A. Paul)
-   Similarity (Barry Taylor; David Vander Laan)
-   Holes (Roberto Casati and Achille Varzi)
-   Truth (Marian David)
-   Vagueness (Gideon Rosen and Nicholas J. J. Smith)

The breadth of the papers here is astounding. Three of the papers (Papineau, Langton and Schaffer) respond to material of Lewis's that was only published posthumously. Summaries of David Lewis's work normally start by mentioning his modal realism, but this presents a somewhat distorted picture of his interests and importance. The list here is a better guide to the range of Lewis's work. (Though as the editors note, it is quite incomplete because it leaves out Lewis's work on materialism and on set theory and mereology, not to mention his work on conditionals and on value theory and many other topics.)

The only paper directly about modal realism is McDaniel's interesting paper on how we might formulate and defend a version of modal realism that allows worlds to overlap. Barry Taylor's paper develops some considerations about simplicity that suggest a worry for Lewis's argument against linguistic ersatzism: in particular he argues against the existence of alien universals. And Max Cresswell formulates his discussion of counterpart theory using modal realist language. And that's it for the discussion of modal realism, which seems about right given its relative importance in Lewis's overall picture.

Many of the papers accept the broad outlines of Lewis's views, but suggest alternative ways of developing the details. For instance, Andy Egan's paper "Second Order Predication and the Metaphysics of Properties" discusses Lewis's view that properties are sets of individuals. Egan argues that Lewis should instead have said that properties are functions from worlds to sets of individuals in that world. You might think that these two views are equivalent. Let *f* be a function that Egan calls a property, and consider the set \{*x*: for some world *w*, *x* ∈ *f*(*w*)\}. Why wouldn't that set be a Lewis-style property? Well, it would be if no object is in more than one world. Isn't that true on Lewis's metaphysics? Not quite. Most ordinary individuals are in one world only, but *properties* are in multiple worlds. If the property *being red* has some property, say *being instantiated*, in some worlds but not others, should it be a member of the property *being instantiated* or not? Egan argues, persuasively, that Lewis can give no good answer to this question. But on the view that properties are functions, we can say that the function that we identify with the property *being instantiated* maps worlds onto a set that includes *being red* in worlds where there are red things, and a set that does not include it in worlds where there are no red things. So this looks like a nice fix to a technical problem for Lewis. Egan goes on to argue that the change undermines some of Lewis's arguments against endurantism and modal overlap.

Ned Hall discusses Lewis's widely influential theory of objective chance. There are two disputes running through Hall's paper: the dispute between reductionists and anti-reductionists about chance, and the dispute between the old and new versions of the Principal Principle, presented here as (O) and (N).

\(O\) 
:    C~0~(A \| E & ch~t~(A) = x) = x

\(N\) 
:    C~0~(A \| HL) = ch~t~(A \| L)

Here C~0~ is an initial credence function of a rational agent, ch~t~ is the chance function at t, H is the history of the world to t, L is the conjunction of the laws, and E is any evidence that is 'admissible' with respect to A at t. (Evidence is admissible, roughly, if it doesn't provide any more information about A than we get from knowing its chance.) Lewis thought it was a cost of his reductionist position that he was forced to give up (O) and retreat to (N). Hall suggests that it isn't a cost, it is really something we could have derived all along. Hall's reasoning is a little hard to follow here. He shows elegantly that if the reductionist agrees to treat the chance function as an expert function, then she should accept (N) rather than (O). (Roughly speaking, to treat a function as an expert function is, as Hall says on page 101, to consider its opinion so epistemically superior to yours that you are disposed to defer to it. Before we can give a formal statement of this we need to make it precise, which may not be trivial. One of the important innovations of Hall's paper is to clarify some importantly distinct ways of making it precise, in particular distinguishing the cases where the expert is better informed than you from the case where the expert is a better judge of evidence than you.) But it is not clear how showing that the reductionist is forced to accept (N) rather than (O), shows that it isn't a *cost* of reductionism that it is incompatible with (O).

Hall makes two nice points about how (N) stands with respect to the reductionist/anti‑reductionist debate. First, he notes that it isn't clear in general how reductionists can derive (N), i.e. derive the claim that the chance function *is* an expert function, from their general principles. Lewis often touted it as a virtue of reductionism that such a derivation seems possible, but Hall suggests that there will be problems with the details here. Lewis's optimism rested on cases where there was a close connection between chance and limiting relative frequency, but this is not the only kind of case. Hall argues, persuasively, that this part of the reductionist program will have difficulties with cases where the chance of an F being a G varies continuously with some magnitude *m* of the F (say its mass), and the proposition A concerns whether a particular object *a*, which is an *F* such that *m*(*a*) is unique, is also a G. (The general project of trying to incorporate continuously variable quantities, like masses, into Lewis's metaphysics appears to be very difficult, and there could be some very interesting philosophical discoveries to be made in this field.) Second, Hall notes that it is not as hard for the anti‑reductionist to explain (N) as Lewis suggests. To be sure, the anti-reductionist can't derive (N) from, say, metaphysical necessities and logic. But we know that reasonable principles of inductive rationality won't follow merely from metaphysical necessities and logic; in addition, we need a number of substantive synthetic principles. There is no reason why (N), or something that entails (N), cannot be among these.

The difficulty Lewis imagines for the anti-reductionist here arises largely from an insufficient attention to epistemology. Lewis never took epistemology (at least informal epistemology) as seriously as he took metaphysics, philosophy of mind, or philosophy of language, and occasionally this shows up in the papers here. Jonathan Schaffer's paper "Quiddistic Knowledge" argues that there is no plausible epistemological theory that grounds Lewis's claim in "Ramseyan Humility" that "we are irredemiably ignorant about the identities of the fundamental properties." And Robert Stalnaker in "Lewis on Intentionality" argues that Lewis's content internalism derives from an implausible commitment to epistemological internalism.

There are of course many more good ideas throughout this volume. For example, Marian David has a thorough, and thoroughly convincing, response to Lewis's argument that the correspondence theory of truth is not a competitor to the redundancy theory of truth. Max Cresswell provides a few reasons for thinking that the counterpart relation has to be an equivalence relation, in which case we may as well do without counterpart theory. (Cresswell's paper and the recent paper on a similar topic by Michael Fara and Timothy Williamson, "Counterparts and Actuality", *Mind* 114: 1-30, complement each other nicely, and should be required reading for anyone interested in debates about counterpart theory.) Alan Hájek and Philip Pettit argue that Lewis's argument against the view that desires are beliefs about what is good assumes that goodness is not an 'indexical' property, and that this might fail if what is good is partially a function of, say, our evidence, as on the view that what is good is what maximises *expected* utility. And there are many more gems like these.

It is a great compliment to Lewis's style as a philosopher that, as we see in this collection, Lewis amassed a great number of admirers who thought the best way to honour his work was to criticise it in every way imaginable. It is sad to stop and think how much we would have learned from hearing Lewis's responses.