---
title: "Morality, Fiction and Possibility"
abstract: |
  Authors have a lot of leeway with regard to what they can make true in their story. In general, if the author says that p is true in the fiction we're reading, we believe that p is true in that fiction. And if we're playing along with the fictional game, we imagine that, along with everything else in the story, p is true. But there are exceptions to these general principles. Many authors, most notably Kendall Walton and Tamar Szabó Gendler, have discussed apparent counterexamples when p is "morally deviant". Many other statements that are conceptually impossible also seem to be counterexamples. In this paper I do four things. I survey the range of counterexamples, or at least putative counterexamples, to the principles. Then I look to explanations of the counterexamples. I argue, following Gendler, that the explanation cannot simply be that morally deviant claims are impossible. I argue that the distinctive attitudes we have towards moral propositions cannot explain the counterexamples, since some of the examples don't involve moral concepts. And I put forward a proposed explanation that turns on the role of 'higher-level concepts', concepts that if they are satisfied are satisfied in virtue of more fundamental facts about the world, in fiction, and in imagination.
date: November 1 2004
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
citation:
  type: article-journal
  container-title: "Philosophers' Imprint"
  publisher: Michigan
  volume: 4
  page: "1-27"
categories:
  - ethics
  - metaphysics
format:
  html: default
  pdf:
    output-file: "Morality, Fiction and Possibility"
    thanks: "I've spoken to practically everyone I know about the issues here, and a full list of thanks for useful advice, suggestions, recommendations, criticisms, counterexamples and encouragement would double the size of the paper. If I thank philosophy departments rather than all the individuals in them it might cut the size a little, so thanks to the departments at Brown, UC Davis, Melbourne, MIT and Monash. Thanks also to Kendall Walton, Tamar Gendler and two referees for *Philosophers' Imprint*. The most useful assistance came from Wolfgang Schwarz and especially Tyler Doggett, without whose advice this could never have been written, and to George Wilson, who prevented me from (keeping on) making a serious error of over-generalisation."
---

# Four Puzzles

::: {.content-visible when-format="html"}
<aside>
I've spoken to practically everyone I know about the issues here, and a full list of thanks for useful advice, suggestions, recommendations, criticisms, counterexamples and encouragement would double the size of the paper. If I thank philosophy departments rather than all the individuals in them it might cut the size a little, so thanks to the departments at Brown, UC Davis, Melbourne, MIT and Monash. Thanks also to Kendall Walton, Tamar Gendler and two referees for *Philosophers' Imprint*. The most useful assistance came from Wolfgang Schwarz and especially Tyler Doggett, without whose advice this could never have been written, and to George Wilson, who prevented me from (keeping on) making a serious error of over-generalisation.
</aside>
:::

Several things go wrong in the following story.

> *Death on a Freeway*  
> Jack and Jill were arguing again. This was not in itself unusual, but this time they were standing in the fast lane of I-95 having their argument. This was causing traffic to bank up a bit. It wasn't significantly worse than normally happened around Providence, not that you could have told that from the reactions of passing motorists. They were convinced that Jack and Jill, and not the volume of traffic, were the primary causes of the slowdown. They all forgot how bad traffic normally is along there. When Craig saw that the cause of the bankup had been Jack and Jill, he took his gun out of the glovebox and shot them. People then started driving over their bodies, and while the new speed hump caused some people to slow down a bit, mostly traffic returned to its normal speed. So Craig did the right thing, because Jack and Jill should have taken their argument somewhere else where they wouldn't get in anyone's way.

The last sentence raises a few related puzzles. Intuitively, it is not true, even in the story, that Craig's murder was morally justified. What the narrator tells us here is just false. That should be a little surprising. We're being told a story, after all, so the storyteller should be an authority on what's true in it. Here we hearers get to rule on which moral claims are true and false, not the author. But usually the author gets to say what's what. The action takes place in Providence, on Highway 95, just because the author says so. And we don't reject those claims in the story just because no such murder has ever taken place on Highway 95. False claims can generally be true in stories. Normally, the author's say so is enough to make it so, at least in the story, even if what is said is really false. The first puzzle, the **alethic** puzzle, is why authorial authority breaks down in cases like *Death on the Freeway*. Why can't the author just make sentences like the last sentence in *Death* true in the story by saying they are true? At this stage I won't try and give a more precise characterisation of which features of *Death* lead to the break down of authorial authority, for that will be at issue below.

The second puzzle concerns the relation between fiction and imagination. Following Kendall @Walton1990, it is common to construe fictional works as invitations to imagine. The author requests, or suggests, that we imagine a certain world. In *Death* we can follow along with the author for most of the story. We can imagine an argument taking place in peak hour on Highway 95. We can imagine this frustrating the other drivers. And we can imagine one of those drivers retaliating with a loaded gun. What we cannot, or at least do not, imagine is that this retaliation is morally justified. There is a limit to our imaginative ability here. We refuse, fairly systematically, to play along with the author here. Call this the **imaginative** puzzle. Why don't we play along in cases like *Death*? Again, I won't say *for now* which cases are like *Death*.

The third puzzle concerns the phenomenology of *Death* and stories like it. The final sentence is striking, jarring in a way that the earlier sentences are not. Presumably this is closely related to the earlier puzzles, though I'll argue below that the cases that generate this peculiar reaction are not identical with cases that generate alethic or imaginative puzzles. So call this the **phenomenological** puzzle.

Finally, there is a puzzle that David @Hume1757 first noticed. Hume suggested that artistic works that include morally deviant claims, moral claims that wouldn't be true were the descriptive aspects of the story true, are thereby aesthetically compromised. Why is this so? Call that the **aesthetic** puzzle. I will have nothing to say about that puzzle here, though hopefully what I have to say about the other puzzles will assist in solving it.

I'm going to call sentences that raise the first three puzzles **puzzling** sentences. Eventually I'll look at the small differences between those three puzzles, but for now we'll focus on what they have in common. The puzzles, especially the imaginative puzzle, have become quite a focus of debate in recent years. The aesthetic puzzle is raised by David @Hume1757, and is discussed by Kendall @Walton1994 and Richard @Moran1995. Walton and Moran also discuss the imaginative and alethic puzzles, and they are the focus of attention in recent work by Tamar Szabó @Gendler2000, Gregory @Currie2002 and Stephen @Yablo2002. My solution to the puzzles is best thought of as a development of some of Walton's 'sketchy story' (to use his description). Gendler suggests one way to develop Walton's views, and shows it leads to an unacceptable solution, because it leads to mistaken predictions. I will argue that there are more modest developments of Walton's views that don't lead to so many predictions, and in particular don't lead to *mistaken* predictions, but which still say enough to solve the puzzles.

# The Range of the Puzzles

As Walton and Yablo note, the puzzle does not only arise in connection with thin moral concepts. But it has not been appreciated how widespread the puzzle is, and getting a sense of this helps us narrow the range of possible solutions.

Sentences in stories attributing **thick moral concepts** can be puzzling. If my prose retelling of *Macbeth* included the line "Then the cowardly Macduff called on the brave Macbeth to fight him face to face," the reader would not accept that in the story Macduff was a coward. If my retelling of *Hamlet* frequently described the young prince as decisive, the reader would struggle to go along with me imaginatively. Try imagining Hamlet doing exactly what he does, and saying exactly what he says, and thinking what he thinks, but always decisively. For an actual example, it's easy to find the first line in Bob Dylan's *Ballad of Frankie Lee and Judas Priest*, that the titular characters 'were the best of friends' puzzling in the context of how Frankie Lee treats Judas Priest later in the song. It isn't too surprising that the puzzle extends to the thick moral concepts, and Walton at least doesn't even regard these as a separate category.

More interestingly, any kind of **evaluative** sentence can be puzzling. Walton and Yablo both discuss sentences attributing aesthetic properties. [@Yablo2002 485] suggests that a story in which the author talks about the sublime beauty of a monster truck rally, while complaining about the lack of aesthetic value in sunsets, is in most respects like our morally deviant story. The salient aesthetic claims will be puzzling. Note that we *are* able to imagine a community that prefers the sight of a 'blood bath death match of doom' (to use Yablo's evocative description) to sunsets over Sydney Harbour and it could certainly be true in a fiction that such attitudes were commonplace. But that does not imply that those people could be *right* in thinking the trucks are more beautiful. [@Walton1994 43-44] notes that sentences describing jokes that are actually unfunny as being funny will be puzzling. We get to decide what is funny, not the author.

Walton and Yablo's point here can be extended to **epistemic evaluations**. Again it isn't too hard to find puzzling examples when we look at attributions of rationality or irrationality.

> *Alien Robbery*  
> Sam saw his friend Lee Remnick rushing out of a bank carrying in one hand a large bag with money falling out of the top and in the other hand a sawn-off shotgun. Lee Remnick recognised Sam across the street and waved with her gun hand, which frightened Sam a little. Sam was a little shocked to see Lee do this, because despite a few childish pranks involving stolen cars, she'd been fairly law abiding. So Sam decided that it wasn't Lee, but really a shape-shifting alien that looked like Lee, that robbed the bank. Although shape-shifting aliens didn't exist, and until that moment Sam had no evidence that they did, this was a rational belief. False, but rational.

The last two sentences of *Alien Robbery* are fairly clearly puzzling.

So far all of our examples have involved normative concepts, so one might think the solution to the puzzle will have something to do with the distinctive nature of normative concepts, or with their distinctive role in fiction. Indeed, Gendler's and Currie's solutions have just this feature. But sentences that seem somewhat removed from the realm of the normative can still be puzzling. (It is of course contentious just where the normative/non-normative barrier lies. Most of the following cases will be regarded as involving normative concepts by at least some philosophers. But I think few people will hold that *all* of the following cases involve normative concepts.)

Attributions of **mental states** can, in principle, be puzzling. If I retell *Romeo and Juliet*, and in this say 'Although he believed he loved Juliet, and acted as if he did, Romeo did not really love Juliet, and actually wanted to humiliate her by getting her to betray her family', that would I think be puzzling. This example is odd, because it is not obviously *impossible* that Romeo could fail to love Juliet even though he thought he loved her (people are mistaken about this kind of thing all the time) and acted as if he did (especially if he was trying to trick her). But given the full detail of the story, it is impossible to imagine that Romeo thought he had the attitudes towards Juliet he is traditionally thought to have, and he is mistaken about this.

Attributions of **content**, either mental content or linguistic content, can be just as puzzling. The second and third sentences in this story are impossible to imagine, and false even in the story.

> *Cats and Dogs*  
> Rhodisland is much like a part of the actual world, but with a surprising difference. Although they use the word 'cat' in all the circumstances when we would (i.e. when they want to say something about cats), and the word 'dog' in all the circumstances we would, in their language 'cat' means dog and 'dog' means cat. None of the Rhodislanders are aware of this, so they frequently say false things when asked about cats and dogs. Indeed, no one has ever known that their words had this meaning, and they would probably investigate just how this came to be in some detail, if they knew it were true.

A similar story can be told to demonstrate how claims about mental content can be puzzling. Perhaps these cases still involve the normative. Loving might be thought to entail special obligations and @Kripke1982 has argued that content is normative. But we are clearly moving away from the moral, narrowly construed.

Stephen Yablo recently suggested that certain **shape** predicates generate imaginative resistance. These predicates are meant to be special categories of a broader category that we'll discuss further below. Here's Yablo's example.

> *Game Over*  
> They flopped down beneath the giant maple. One more item to find, and yet the game seemed lost. Hang on, Sally said. It's staring us in the face. This is a *maple* tree we're under. She grabbed a five-fingered leaf. Here was the oval they needed! They ran off to claim their prize. [@Yablo2002 485, title added]

There's a potential complication in this story in that one might think that it's metaphysically impossible that *maple* trees have ovular leaves. That's not what is meant to be resisted, and I don't think is resisted. What is resisted is that maple leaves have their distinctive five-fingered look, that the shape of the leaf Sally collects is like *that* (imagine I demonstrate a maple leaf here) and that its shape be an *oval*.

Fewer people may care about the next class of cases, or have clear intuitions about them, but if one has firm **ontological** beliefs, then deviant ontological claims can be puzzling. I'm a universalist about mereology, at least with respect to ordinary concrete things, so I find many of the claims in this story puzzling.

> *Wiggins' World*  
> The Hogwarts Express was a very special train. It had no parts at all. Although you'd be tempted to say that it had carriages, an engine, seats, wheels, windows and so on, it really was a mereological atom. And it certainly had no temporal parts - it wholly was wherever and whenever it was. Even more surprisingly, it did not enter into fusions, so when the Hogwarts Local was linked to it for the first few miles out of Kings Cross, there was no one object that carried all the students through north London.

I think that even in fictions any two concrete objects have a fusion. So the Hogwarts Express and the Hogwarts Local have a fusion, and when it is a connected object it is commonly called a train. I know how to describe a situation where they have no fusion (I did so just above) but I have no idea how to *imagine* it, or make it true in a story.

More generally, there are all sorts of puzzling sentences involving claims about **constitution**. These I think are the best guide to a solution to the puzzle.

> *A Quixotic Victory*  
> --What think you of my redecorating Sancho?  
> --It's rather sparse, said Sancho.  
> --Sparse. Indeed it is sparse. Just a television and an armchair.  
> --Where are they, Señor Quixote? asked Sancho. All I see are a knife and fork on the floor, about six feet from each other. A sparse apartment for a sparse mind. He said the last sentence under his breath so Quixote would not hear him.  
> --They might look like a knife and fork, but they are a television and an armchair, replied Quixote.  
> --They look just like the knife and fork I have in my pocket, said Sancho, and he moved as to put his knife and fork besides the objects on Quixote's floor.  
> --Please don't do that, said Quixote, for I may be unable to tell your knife and fork from my television and armchair.  
> --But if you can't tell them apart from a knife and fork, how could they be a television and an armchair?  
> --Do you really think *being a television* is an observational property? asked Quixote with a grin.  
> --Maybe not. OK then, how do you change the channels? asked Sancho.  
> --There's a remote.  
> --Where? Is it that floorboard?  
> --No, it's at the repair shop, admitted Quixote.  
> --I give up, said Sancho.
>
> Sancho was right to give up. Despite their odd appearance, Quixote's items of furniture really were a television and an armchair. This was the first time in months Quixote had won an argument with Sancho.

Quixote is quite right that whether something is a television is not determined entirely by how it looks. A television could be indistinguishable from a non-television. Nonetheless, something indistinguishable from a knife is not a television. Not in this world, and not in the world of *Victory* either, whatever the author says. For whether something is a television is determined at least *in part* by how it looks, and while it is impossible to provide a non-circular constraint on how a television may look, it may not look like a common knife.

In general, if whether or not something is an *F* is determined in part by 'lower-level' features, such as the shape and organisation of its parts, and the story specifies that the lower-level features are incompatible with the object being an *F*, it is not an *F* in the fiction. Suitably generalised and qualified, I think this is the explanation of all of the above categories. To understand better what the generalisations and qualifications must be, we need to look at some cases that aren't like *Death*, and some alternative explanations of what is going on in *Death*.

Sentences that are **intentional errors** on the part of storytellers are not puzzling in our sense. We will use real examples for the next few pages, starting with the opening line of Joyce's most famous short story.

> *The Dead*  
> Lily, the caretaker's daughter, was literally run off her feet.  
> [@Joyce1914 138]

It isn't true that Lily is *literally* run off her feet. She is run off her feet by the incoming guests, and if you asked her she may well say she was literally run off her feet, but this would reveal as much about her lack of linguistic care as about her demanding routine. Is this a case where the author loses authority over what's true in the story? No, we are not meant to read the sentence as being true in the story, but being a faithful report of what Lily (in the story) might say to herself. In practice it's incredibly difficult to tell just when the author intends a sentence to be true in the story, as opposed to being a report of some character's view of what is true. (See @Holton1997 for an illustration of the complications this can cause.) But since we are operating in theory here, we will assume *that* problem solved. The alethic puzzle only arises when it is clear that the author intends that *p* is true in her story, but we think *p* is not true. The imaginative puzzle only arises when the author invites us to imagine *p*, but we can not, or at least do not. Since Joyce does not intend this sentence to be true in *The Dead*, nor invites us to imagine it being true, neither puzzle arises. What happens to the phenomenological puzzle in cases like these is a little more interesting, and I'll return to that in .

Just as intentional errors are not puzzling, **careless errors** are not puzzling. Writing a full length novel is a perilous business. Things can go wrong. Words can be miswritten, mistyped or misprinted at several different stages. Sometimes the errors are easily detectable, sometimes they are not, especially when they concern names. In one of the drafts of *Ulysses*, Joyce managed to write "Connolly Norman" in place of "Conolly Norman". Had that draft being used for the canonical printing of the work, it would be tempting to say that we had another alethic puzzle. For the character named here is clearly the Superintendent of the Richmond District Lunatic Asylum, and his name had no double-'n', so in the story there is no double-'n' either.[^1]

[^1]: For details on the spelling of Dr Norman's name, and the story behind it, see @Kidd1988. The good doctor appears on page 6 of @Joyce1922.

Here we do have an instance where what is true in the story differs from the what is written in the text. But this is not a particularly *interesting* deviation. To avoid arcane discussions of typographical errors, we will that in every case we possess an ideal version of the text, and are comparing it with the author's intentions. Slip-ups that would be detected by a careful proof-reader, whether they reveal an unintended divergence between word and world, as here, or between various parts of the text, as would happen if Dr Norman were not named after a real person but had his name spelled differently in parts of the text, will be ignored.[^2]

[^2]: At least, they will be ignored if it is clear they are *errors*. If there seems to be a method behind the misspellings, as in *Ulysses* there frequently is, the matter is somewhat different, and somewhat more difficult.

    Tyler Doggett has argued that these cases are more similar to paradigm cases of imaginative resistance than I take them to be. Indeed, I would not have noticed the problems they raise without reading his paper. It may be a shortcoming of my theory here that I have to set questions about whether these sentences are puzzling to one side and assume an ideal proof-reader.

Note two ways in which the puzzles as I have stated them are narrower than they first appear. First, I am only considering puzzles that arise from a particular sentence in the story, intentionally presented in the voice of an authoritative narrator. We could try and generalise, asking why it is that we sometimes (but not always) question the moral claims that are intended to be tacit in a work of fiction. For instance, we might hold that for some Shakespearean plays there are moral propositions that Shakespeare intended to be true in the play, but which are not in fact true. Such cases are interesting, but to keep the problem of manageable proportions I won't explicitly discuss them here. (I believe the solution I offer here generalises to those cases, but I won't defend that claim here.) Second, all the stories I have discussed are either paragraph-long examples, or relatively detachable parts of longer stories. For all I've said so far, the puzzle *may* be restricted to such cases. In particular, it might be the case that a suitably talented author could make it true in a story that killing people for holding up traffic is morally praiseworthy, or that a television is phenomenally and functionally indistinguishable from a knife. What we've seen so far is just that an author cannot make these things true in a story simply by saying they are true.[^3] I leave open the question of whether a more subtle approach could make those things true in a fiction. Similarly, I leave it open whether a more detailed invitation to imagine that these things are true would be accepted. All we have seen so far is that simple direct invitations to imagine these things are rejected, and it feels like we could not accept them.

[^3]: Thanks here to George Wilson for reminding me that we haven't shown anything stronger than that.

# An Impossible Solution

Here's a natural solution to the puzzles, one that you may have been waiting for me to discuss. The alethic puzzle arises because only propositions that are possibly true can be true in a story, or can be imagined. The latter claim rests on the hypothesis that we can imagine only what is possible, and that we resist imagining what is impossible.

This solution assumes that it is *impossible* that killing people for holding up freeway traffic is the right thing to do. Given enough background assumptions, that *is* plausible. It is plausible, that is, that the moral facts supervene on the non-moral facts. And the supervenience principle here is quite a strong one - in *every* possible world where the descriptive facts are thus and so, the moral facts are the same way.[^4] If we assume the relevant concept of impossibility is truth in no possible worlds, we get the nice result that the moral claims at the core of the problem could not possibly be true.

[^4]: Arguably the relevant supervenience principle is even stronger than that. To use some terminology of Stephen Yablo's, there's no difference in moral facts without a difference in non-moral facts between any two *counteractual* worlds, as well as between any two *counterfactual* worlds. This might be connected to some claims I will make below about the relationship between the normative and the descriptive.

Several authors have discussed solutions around this area. Kendall @Walton1994 can easily be read as endorsing this solution, though Walton's discussion is rather tentative. Tamar Szabó Gendler rejects the theory, but thinks it is the most natural idea, and spends much of her paper arguing against this solution. As those authors, and Gregory @Currie2002, note, the solution needs to be tidied up a little before it will work for the phenomenological and imaginative puzzles. (It is less clear whether the tidying matters to the alethic puzzle.) For one thing, there is no felt asymmetry between a story containing, "Alex proved the twin primes theorem," and one containing, "Alex found the largest pair of twin primes," even though *one of them* is impossible. Since we don't know which it is, the impossibility of the false one cannot help us here. So the theory must be that it is believed impossibilities that matter, for determining what we can imagine, not just any old impossibilities. Presumably impossibilities that are not salient will also not prevent imagination.

Even thus qualified, the solution still overgenerates, as Gendler noted. There are stories that are not puzzling in any way that contain known salient impossibilities. Gendler suggests three kinds of cases of this kind, of which I think only the third *clearly* works. The first kind of case is where we have direct contradictions true in the story. Gendler suggests that her *Tower of Goldbach* story, where seven plus five both does and does not equal twelve, is not puzzling. Graham @Priest1999 makes a similar point with a story, *Sylvan's Box*, involving an empty box with a small statue in one corner. These are clear cases of known, salient impossibility, but arguably are not puzzling in any respect. (There is a distinction between the puzzles though. It is very plausible to say that it's true in Priest's story that there's an empty box with a small statue in one corner. It is less plausible to say we really can imagine such a situation.) Opinion about such cases tends to be fairly sharply divided, and it is not good I suspect to rest too much weight on them one way or the other.

The second kind of case Gendler suggests is where we have a distinctively metaphysical impossibility, such as a singing snowman or a talking playing card. Similar cases as discussed by Alex @Byrne1993 who takes them to raise problems for David Lewis's [-@Lewis1978b] subjunctive conditionals account of truth in fiction. If we believe a strong enough kind of essentialism, then these will be impossible, but they clearly do not generate puzzling stories. For a quick proof of this, note that *Alice in Wonderland* is not puzzling, but several essentialist theses are violated there. It is true in *Alice in Wonderland*, for example, that playing cards plant rose trees.

But these examples don't strike me as particularly convincing either. For one thing, the essentialism assumed here may be wrong. For another, the essentialism might not be both salient and believed to be right, which is what is needed. And most importantly, we can easily reinterpret what the authors are saying in order to be make the story possibly true. We can assume, for example, that the rosebush planting playing cards are not *playing cards* as we know them, but roughly human-shaped beings with playing cards for torsos. Gendler and Byrne each say that this is to misinterpret the author, but I'm not sure this is true. As some evidence, note that the authorised illustrations in *Alice* tend to support the reinterpretations.[^5]

[^5]: Determining whether this is true in *all* such stories would be an enormous task, I fear, and somewhat pointless given the next objection. If anyone wants to say all clearly impossible statements in fiction are puzzling, I suspect the best strategy is to divide and conquer. The most blatantly impossible claims are most naturally fit for reinterpretation, and the other claims rest on an essentialism that is arguably not proven. I won't try such a massive defence of a false theory *here*.

Gendler's third case is better. There are science fiction stories, especially time travel stories, that are clearly impossible but which do not generate resistance. Here's two such stories, the first lightly modified from a surprisingly popular movie, and the second lifted straight from a very popular source.

> *Back to the Future*′\  
> Marty McFly unintentionally travelled back in time to escape some marauding Libyan terrorists. In doing so he prevented the chance meeting which had, in the timeline that had been, caused his father and mother to start dating. Without that event, his mother saw no reason to date the unattractive, boring nerdy kid who had been, in a history that no longer is, Marty's father. So Marty never came into existence. This was really a neat trick on Marty's part, though he was of course no longer around to appreciate it. Some people manage to remove themselves from the future of the world by foolish actions involving cars. Marty managed to remove himself from the past as well.
>
> *The Restaurant at the End of the Universe*\  
> The Restaurant at the End of the Universe is one of the most extraordinary ventures in the entire history of catering.
>
> It is built on the fragmented remains of an eventually ruined planet which is enclosed in a vast time bubble and projected forward in time to the precise moment of the End of the Universe.
>
> This is, many would say, impossible.
>
> ...
>
> You can visit it as many times as you like ... and be sure of never meeting yourself, because of the embarrassment this usually causes.
>
> This, even if the rest were true, which it isn't, is patently impossible, say the doubters.
>
> All you have to do is deposit one penny in a savings account in your own era, and when you arrive at the End of Time the operation of compound interest means that the fabulous cost of your meal has been paid for.
>
> This, many claim, is not merely impossible but clearly insane. [@Adams1980 213-214]

Neither of these are puzzling. Perhaps it's hard to imagine the last couple of sentences of the McFly story, but everything the respective authors say is true in their stories. So the impossibility theory cannot be right, because it overgenerates, just as Gendler said.

Recently Kathleen @Stock2003 has argued that one of the assumptions that Gendler makes, specifically that it isn't true that "a judgement of conceptual impossibility renders a scenario unimaginable" [@Gendler2000 66] is false. Even if Stock is right, this doesn't threaten the kind of response that I have (following Gendler) offered to the puzzles. But actually there are a few reasons to doubt Stock's reply. I'll discuss these points in order.

It isn't entirely clear from Stock's discussion what she is taking a conceptual impossibility to be. I *think* it is a proposition of the form *Some F is a G* (or *That F is a G*, or something of this sort) where it is constitutive of being an *F* that the *F* is not a *G*. There is no positive characterisation of conceptual impossibility in Stock's paper, but it is clearly meant to be something stronger than mere impossibility, or a priori falsehood. In any case, most of the core arguments turn on worries about allegedly deploying a concept while refusing to draw inferences that are constitutive of that concept, so the kind of definition I've offered above seems to be on the right track.

Now if this is the case then Stock has no objection to the imaginability of the two stories I offered that involve known and salient impossibilities. For neither of these stories includes a conceptual impossibility in this sense. So even if conceptual impossibilities cannot be imagined, some impossibilities can be imagined. (And at this point what holds for imagination also holds for truth in fiction.)

While this suffices as a response to the particular claims Stock makes, it might be thought it undercuts the objection I have made to the impossible solution. For it might be thought that what is wrong with the puzzling sentences just is that they represent *conceptual* impossibilities in this sense, and we have no argument that these can be imagined, or true in fiction. This is not too far removed from the actual solution I will offer, so it is a serious worry. The problem with this line is that not all of our puzzles are conceptual impossibilities. It isn't constitutive of being a television that a thing is phenomenally or functionally distinguishable from a knife, but the claim in *Victory* that some television is not phenomenally or functionally distinguishable from a knife is puzzling. Even in our core cases, of morally deviant claims in fiction, there need not be any conceptual impossibilities. As R. M. @Hare1951 pointed out long ago, people with very different moral beliefs could have in common the concept GOOD. Arguably, someone who thinks that what Craig does in *Death* is good is morally confused, not conceptually confused. So whether Gendler or Stock is right about the imaginability of conceptual impossibility is neither here nor there with respect to these puzzles.

Having said that, there are some reasons to doubt Stock's argument. One of her moves is to argue that we couldn't imagine conceptual impossibilities because we can't believe conceptual impossibilities. But as @Sorensen2001 persuasively argues, we *can* believe conceptual impossibilities. One of Sorensen's arguments, lightly modified, helps us respond to another of Stock's arguments. Stock notes, rightly, that we shouldn't take the fact that it *seems* we can imagine impossibilities to be conclusive evidence we can do so. After all, we are wrong about whether things are as they seem all the time. But this might be a special case. I think that if it seems to be the case that *p* then we can imagine that *p*. And Stock agrees it *seems* to be the case that we can imagine conceptual impossibilities. So we can imagine that we can imagine conceptual impossibilities. Hence it can't be a conceptual impossibility that we can imagine at least one conceptual impossibility. This doesn't tell against the claim that it is some other kind of impossibility, though as we'll see Stock's main argument rests on considerations about the conceptual structure of imagination, so it isn't clear how she could argue for this.

The main argument Stock offers is that no account of how concepts work are compatible with our imagining conceptual impossibilities. Her argument that atomist theories of concepts (as in @Fodor1998) are incompatible with imagining conceptual impossibilities isn't that persuasive. She writes that "clearly it is not the case that imagining "the cow jumped over the moon" stands in a lawful relation to the property of being a cow (let alone the property of \[being\] a cow jumping over the moon). Imagining by its very nature is resistant to any attempt to incorporate it into an externalist theory of content" [-@Stock2003 114]. But this isn't clear at all. When I imagine going out drinking with Bill Clinton there is, indeed there must be, some kind of causal chain running back from my imagining to Bill Clinton himself. If there was not, I'd at most be imagining going out drinking with a guy who looks a lot like Bill Clinton. Perhaps it isn't as clear, but when I imagine that a cow (and not just a zebra disguised to look like a cow) is jumping over the moon it's nomologically necessary that there's a causal chain of the right kind stretching back to actual cows. And it's arguable that the concept I deploy in imagining that a cow (a real *cow*) is jumping over the moon just is the concept whose content is fixed by the lawful connections between various cows and my (initial) deployment of it. So I don't see why a conceptual atomist should find this kind of argument convincing.

Stock's response to Gendler was presented at a conference on Imagination and the Arts at Leeds in 2001, and at the same conference Derek @Matravers2003 offered an alternative solution to the alethic puzzle. Although it does not rest on claims about impossibility, it also suffers from an overgeneration problem. Matravers suggests that in at least some fictions, we treat the text as a report by a (fictional) narrator concerning what is going on in a faraway land. Now in reality when we hear reports from generally trustworthy foreign correspondents, we are likely to believe their descriptive claims about the facts on the ground. Since they have travelled to the lands in question, and we have not, the correspondent is epistemologically privileged with respect to those facts on the ground. But when the correspondent makes moral evaluations of those facts, she is not in a privileged position, so we don't just take her claims as the final word. Matravers suggests there are analogous limits to how far we trust a fictional narrator.

The problem with this approach is that there are several salient disanalogies between the position of the correspondent and the fictional narrator. The following case, which I heard about from Mark Liberman, illustrates this nicely. On March 5, 2004, the BBC reported that children in a nursery in England had found a frog with three heads and six legs. Many people, including Professor Liberman, were sceptical, notwithstanding the fact that the BBC was actually in England and Professor Liberman was not. The epistemological privilege generated by proximity doesn't extend to implausible claims about three-headed frogs. The obvious disanalogy is that if a fictional narrator said that there was a three-headed six-legged frog in the children's nursery then other things being equal we would infer it is true in the fiction that there was indeed a three-headed six-legged frog in the children's nursery.[^6] So there isn't an easy analogy between when we trust foreign correspondents and fictional narrators. Now we need an explanation of why the analogy does hold when either party makes morally deviant claims, even though it doesn't when they both make biologically deviant claims. But it doesn't seem any easier to say why the analogy holds then than it is to solve the original puzzle.

[^6]: There is a complication here in that such a sentence *might* be evidence that the fictional work is not to be understood as this kind of report, and instead understood as something like a recording of the children's thoughts. I'll assume we're in a story where it is clear that the sentences are not to be so interpreted.

Two other quick points about Matravers's solution. It's going to be a little delicate to extend this solution to all the cases I have discussed above, for normally we do think fictional narrators are privileged with respect to where the televisions and windows are. What matters here is that how far narratorial privilege extends depends on what other claims the narrator makes. Perhaps the same is true of foreign correspondents, though we'd need to see an argument for that. Second, it isn't clear how this solution could possibly generalise to cover cases, such as frequently occurs in plays, where the deviant moral claim is clearly intended by the author to be true in the fiction but the reader (or watcher) does not agree even though the author's intention is recognised. As I mentioned at the start, these cases aren't our concern here, though it would be nice to see how a generalisation to these cases is possible. But the primary problem with Matravers's solution is that as it stands it (improperly) rules out three-headed frogs in fiction, and it is hard to see how to remedy this problem without solving the original puzzle.

# Some Ethical Solutions

If one focuses on cases like *Death*, it is natural to think the puzzle probably has something to do with the special nature of ethical predicates, or perhaps of ethical concepts, or perhaps of the role of either of these in fiction. I don't think any such solution can work because it can't explain what goes wrong in *Victory*, and this will recur as an objection in what follows.

The most detailed solution to the puzzles has been put forward by Tamar Szabó Gendler. She focuses on the imaginative puzzle, but she also makes valuable points about the other puzzles. My solution to the phenomenological puzzle is basically hers plus a little epicycle.

She says that we do not imagine morally deviant fictional worlds because of our "general desire to not be manipulated into taking on points of view that we would not reflectively endorse as our own." How could we take on a point of view by accepting something in a fiction? Because of the phenomena noted above that some things become true in a story *because* they are true in the world. If this is right, its converse must be true as well. If what is true in the story must match what is true in the world, then to accept that something is true in the story just is to accept that it is true in the world. Arguably, the same kind of 'import/export' principles hold for imagination as for truth in fiction. Some propositions become part of the content of an imagining because they are true. So, in the right circumstances, they will only be part of an imagining if they are true. Hence to imagine them (in the right circumstances) is to commit oneself to their truth. Gendler holds that we are sensitive to this phenomena, and that we refuse to accept stories that are morally deviant because that would involve accepting that morally deviant claims are true in the world.

That's a relatively rough description of Gendler's theory, but it says enough to illustrate what she has in mind, and to show where two objections may slip in. First, it is not clear that it generalises to all the cases. Gendler is aware of some of these cases and just bites the relevant bullets. She holds, for instance, that we can imagine that actually lame jokes are funny, and it could be true in a story that such a joke is funny. It would be a serious cost to her theory if she had to say the same thing about *all* the examples discussed above.

The second problem is more serious. The solution is only as good as the claim that moral claims are more easily exported than descriptive claims, and more generally that the types of claims we won't imagine are more easily exported than those we don't resist. Gendler has two arguments for why the first of these should be true, but neither of them sounds persuasive. First, she says that the moral claims are true in all possible worlds if true at all. But this won't do on its own, because *as she proved*, we don't resist some necessarily false claims. (This objection is also made by [@Matravers2003 94].)

Secondly, she claims that in other cases where there are necessary falsehoods true in a story, as in *Alice in Wonderland*, or the science fiction cases, the author makes it clear that unusual export restrictions are being imposed. But this is wrong for two reasons. First, I don't think that any particularly clear signal to this effect occurs in my version of *Back to the Future*. Secondly, even if I had explicitly signalled that I had intended to make some of the facts in the story available for export, and you didn't believe that, that isn't enough reason to resist imagining the story. For my intent as to what can and cannot be exported is not part of the story.

To see this, consider one relatively famous example. At one stage B. F. Skinner tried to promote behaviourism by weaving his theories into a novel (of sorts): *Walden Two*. Now I'm sure @Skinner1948 intended us to export some psychological and political claims from the story to the real world. But it is entirely possible to read the story with full export restrictions in force without rejecting that what Skinner says is true in that world. (It is dreadfully boring, since there's nothing but propagandising going on, but *possible*.) If exporting was the only barrier here, we should be able to impose our own tariff walls and read the story along, whatever the intent of the author, as we can with *Walden Two*. One can accept it is true in *Walden Two* that behaviourism is the basis of a successful social policy, even though Skinner wants us to accept this as true in the story iff it is true in the world, and it isn't true in the world. We cannot read *Death* or *Victory* with the same ironic detachment, and Gendler's theory lacks the resources to explain this.

Currie's theory attacks the problem from a quite different direction. He relies on the motivational consequences of accepting moral claims. Assume internalism about moral motivation, so to accept that ${\phi}$-ing is right is to be motivated to ${\phi}$, at least ceteris paribus. So accepting that ${\phi}$-ing is right involves acquiring a desire to ${\phi}$, as well, perhaps, as beliefs about ${\phi}$-ing. Currie suggests that there is a mental state that stands to desire the way that ordinary imagination stands to belief. It is, roughly, a state of having an off-line desire, in the way that imagining that *p* is like having an off-line belief that *p*, a state like a belief that *p* but without the motivational consequences. Currie suggests that imagining that ${\phi}$-ing is right involves off-line acceptance that ${\phi}$-ing is right, and that in part involves having an off-line desire (a desire-like imagination) to ${\phi}$. Finally, Currie says, it is harder to alter our off-line desires at will than it is to alter our off-line beliefs, and this explains the asymmetry. The argument for this last claim seems very hasty, but we'll let that pass. For even if it is true, Currie's theory does little to explain the later cases of imaginative resistance, from *Alien* *Robbery* to *Victory*. It cannot explain, why we have resistance to claims about what is rational to believe, or what is beautiful, or what attitudes other people have. The idea that there is a state that stands to desire as imagination stands to belief is I suspect a very fruitful one, but I don't think its fruits include a solution to these puzzles.

# Grok

Stephen Yablo has suggested that the puzzles, or at least the imaginative puzzle, is closely linked to what he calls *response-enabled* concepts, or *grokking* concepts. (I'll also use response-enabled (grokking) as a property of the predicates that pick out these concepts.) These are introduced by examples, particularly by the example 'oval'.

Here are meant to be some platitudes about OVAL. It is a shape concept - any two objects in any two worlds, counterfactual or counteractual, that have the same shape are alike in whether they are ovals. But which shape concept it is is picked out by our reactions. They are the shapes that strike us as being egg-like, or perhaps more formally, like the shape of all ellipses whose length/width ratio is the golden ratio. In this way the concept OVAL meant to be distinguished on the one hand from, say, PRIME NUMBER, which is entirely independent of us, and from WATER, which would have picked out a different chemical substance had our reactions to various chemicals been different. Note that what 'prime number' picks out is determined by us, like all semantic facts are. So the move space into which OVAL is meant to fit is quite tiny. We matter to its extension, but not the way we matter to 'prime number' (or that we don't matter to PRIME NUMBER), and not the way we matter to 'water'. I'm not sure there's any space here at all. To my ear, Yablo's grokking predicates strike me as words that have associated egocentric descriptions that fix their reference without having egocentric reference fixing descriptions, and such words presumably don't exist. But for present purposes I'll bracket those general concerns and see how this idea can help solve the puzzles. For despite my disagreement about what these puzzles show about the theory of concepts, Yablo's solution is not too dissimilar to mine.

The important point for fiction about grokking concepts is that we matter, in a non-constitutive way, for their extension. Not we as we might have been, or we as we are in a story, but us. So an author can't say that in the story squares looked egg-shaped to the people, so in the story squares are ovals, because *we* get to say what's an oval, not some fictional character. Here's how Yablo puts it:

> Why should resistance [meaning, roughly, unimaginability] and grokkingness be connected in this way? It's a feature of grokking concepts that their extension in a situation depends on how the situation does or would strike us. 'Does or would strike us' *as we are*: how we are represented as reacting, or invited to react, has nothing to do with it. Resistance is the natural consequence. If we insist on judging the extension ourselves, it stands to reason that any seeming intelligence coming from elsewhere is automatically suspect. This applies in particular to being 'told' about the extension by an as-if knowledgeable narrator. [-@Yablo2002 485]

It might look at first as if *Victory* will be a counterexample to Yablo's solution, just as it is to the Ethical solutions. After all, the concept that seems to generate the puzzles there is TELEVISION, and that isn't at all like his examples of grokking concepts. (The examples, apart from evaluative concepts, are all shape concepts.) On the other hand, if there are any grokking concepts, perhaps it is plausible that TELEVISION should be one of them. Indeed, the platitudes about TELEVISION provide some support for this. (The following two paragraphs rely heavily on @Fodor1998.)

Three platitudes about TELEVISION stand out. One is that it's very hard to define just what a television is. A second is that there's a striking correlation between people who have the concept TELEVISION and people who have been acquainted with a television. Not a perfect correlation - some infants have acquaintance with televisions but not as such, and some people acquire TELEVISION by description - but still strikingly high. And a third is that conversations about televisions are rarely at cross purposes, even when they consist of people literally talking different languages. TELEVISION is a shared concept.

Can we put these into a theory of the concept TELEVISION? Fodor suggests we can, as long as we are not looking for an analysis of TELEVISION. Televisions are those things that strike us, people in general, as being sufficiently like the televisions we've seen, in a televisual kind of way. This isn't an account of the meaning of the word 'television' - there's no reference to us in that word's dictionary entry, and rightly so. Nor is it an analysis of what constitutes the concept television. There's no reference to us there either. But it does latch on to the right concept, or at least the right extension, in perhaps the only way we could. And this proposal certainly explains the platitudes well. The epistemic necessity of having a paradigm television to use as a basis for similarity judgments explains the striking correlation between televisual acquaintance and concept possession. The fact that the only way of picking out the extension uses something that is not constitutive of the concept, namely our reactions to televisions, explains why we can't reductively analyse the concept. And the use of people's reactions in general rather than idiosyncratic reactions explains why its a common concept. These look like good reasons to think something like Fodor's theory of the concept TELEVISION is right, and if it is then TELEVISION seems to be response-enabled in Yablo's sense. So unlike the Ethical solutions, Yablo's solution might yet predict that *Victory* will be puzzling.

Still, I have three quibbles about his solution, and that's enough to make me think a better solution may still to be found.

First, there's a missing antecedent in a key sentence in his account, and it's hard to see how to fill it in. What does he mean when he says 'how the situation does or would strike us'? Does or would strike us if *what*? If we were there? But we don't know where there is. There, in *Victory*, is allegedly a place where televisions look like knifes and forks. What if the antecedent is *If all the non-grokking descriptions were accurate*? The problem now is that this will be too light. If TELEVISION is grokking, then there is a worry that many concepts, including perhaps all artefact concepts, will be grokking. Fodor didn't illustrate his theory with TELEVISION, he always used DOORKNOB. But the theory was meant to be rather general. If we take out all the claims involving grokking concepts, there may not be much left.

Second, despite the generality of Fodor's account, it isn't clear that mental concepts, and content concepts, are grokking. We would need another argument that LOVE is grokking, and that so is BELIEVING THAT THERE ARE SPACE ALIENS. Perhaps such an argument can be given, but it will not be a trivial exercise.

Finally, I think this Yablo's solution, at least as most naturally interpreted, overgeneralises. Here's a counterexample to it. The following story is not, I take it, puzzling.

> *Fixing a Hole*  
> DQ and his buddy SP leave DQ's apartment at midday Tuesday, leaving a well-arranged lounge suite and home theatre unit, featuring DQ's prized oval television. They travel back in time to Monday, where DQ has some rather strange and unexpected adventures. He intended to correct something that happened yesterday, that had gone all wrong the first time around, and by the time the buddies reunite and leave for Tuesday (by sleeping and waking up in the future) he's sure it's all been sorted. When DQ and his buddy SP get back to his apartment midday Tuesday, it looks for all the world like there's nothing there except an ordinary knife and fork.

Now this situation would not strike us, were we to see it, as one where there is a lounge suite and home theatre unit in DQ's apartment midday Tuesday, for it looks as if there's an ordinary knife and fork there. But still, the author gets to say that what's in DQ's apartment as the story opens includes an oval television. And this despite the fact that the two concepts, TELEVISION and OVAL, are grokking. Perhaps some epicycles could be added to Yablo's theory to solve this problem, but for now the solution is incomplete.

# Virtue

The content cases may remind us of one of Fodor's most famous lines about meaning.

> I suppose that sooner or later the physicists will complete the catalogue they've been compiling of the ultimate and irreducible properties of things. When they do, the likes of *spin*, *charm*, and *charge* will perhaps appear on the list. But *aboutness* surely won't; intentionality doesn't go that deep ... If the semantic and the intentional are real properties of things, it must be in virtue of their identity with (or maybe their supervenience on?) properties that are themselves neither intentional nor semantic. If aboutness is real, it must really be something else. [@Fodor1987 97]

If meaning doesn't go that deep, but there are meaning facts, then those facts must hold in virtue of more fundamental facts. "Molino de viento" means windmill in Spanish in virtue of a pattern of usage of those words by Spanish speakers, for instance.

It seems that many of the stories above involve facts that hold, if they hold at all, in virtue of other facts. Had Fodor other interests than intentionality, he may have written instead that beauty doesn't go that deep, and neither does television. If an event is to be beautiful, this is a fact that must obtain in virtue of other facts about it, perhaps its integrity, wholeness, symmetry and radiance as Aquinas says [@Joyce1944 212], and that event being a monster truck death match of doom *probably* precludes those facts from obtaining.[^7] If Quixote's favourite item of furniture is to be a television, this must be in virtue of it filling certain functional roles, and being indistinguishable from a common knife probably precludes that.

[^7]: Although it isn't obvious just which of the Thomistic properties the death match lacks.

What is it for a fact to obtain in virtue of other facts obtaining? A good question, but not one we will answer here. Still, the concept seems clear enough that we can still use it, as Fodor does. What we have in mind by 'virtue' is understandable from the examples. One thing to note from the top is that it is not just supervenience: whether *x* is good supervenes on whether it is good, but it is not good *in virtue of* being good. How much our concept differs from supervenience is a little delicate, but it certainly differs.

Returning to our original example, moral properties are also less than perfectly fundamental. It is not a primitive fact that the butcher or the baker is generous, but a fact that obtains in virtue of the way they treat their neighbours. It is not a primitive fact that what Craig does is wrong, but a fact that obtains in virtue of the physical features of his actions.

How are these virtuous relations relevant to the puzzles? To a first approximation, these relations are always imported into stories and into imagination. The puzzles arise when we try to tell stories or imagine scenes where they are violated. The rest of the paper will be concerned with making this claim more precise, motivating it, and arguing that it solves the puzzles. In making the claim precise, we will largely be qualifying it.

The first qualification follows from something we noted at the end of section 2. We don't know whether puzzles like the ones with which we started arise whenever there is a clash between real-world morality (or epistemology or mereology) and the morality (or epistemology or mereology) the author tries to put in the story. We do know they arise for simple stories and direct invitations to imagine. So if we aren't to make claims that go beyond our evidence, we should say there is a default assumption that these relations are imported into stories or imaginations, and it is not easy to overcome this assumption. (I will say for short there is a strong default assumption, meaning just that an author cannot cancel the assumption by saying so, and that we cannot easily follow invitations to imagine that violate the relations.)

The second qualification is that sometimes we simply ignore, either in fiction or imagination, what goes on at some levels of detail. This means that sometimes, in a sense, the relations are not imported into the story. For instance, for it to really be true that in a language that "glory" means *a nice knockdown argument*, this must be true in virtue of facts about how the speakers of that language use, or are disposed to use, "glory". But we can simply say in a story that "glory" in a character's language means *a nice knockdown argument* without thereby making any more general facts about usage or disposition to use true in the story.[^8] More generally, we can simply pick a level of conceptual complexity at which to write our story or conduct our imaginings. Even if those concepts apply, when they do, in virtue of more basic facts, no more basic facts need be imported into the story. For a more vivid, if more controversial, example, one might think that cows are cows in virtue of their DNA having certain chemical characteristics. But when we imagine a cow jumping over the moon, we need not imagine anything about chemistry. Those facts are simply below the radar of our imagining. What do we mean then when we say that these relations are imported into the story? Just that if the story regards both the higher-level facts and the lower-level facts as being within its purview, then they must match up. This does not rule out the possibility of simply leaving out all lower-level facts from the story. In general the same thing is true for imagining, though we will look at some cases below where we it seems there is a stronger constraint on imagining.

[^8]: Do we make facts about the actual speaker's usage true in the story? No. The character might have idiosyncratic reasons for not using the word "glory", and for ignoring all others who use it. That's consistent with the word meaning a nice knockdown argument.

The third qualification is needed to handle an example pressed on me by a referee. Recall our example *Fixing a Hole*.

> *Fixing a Hole*  
> DQ and his buddy SP leave DQ's apartment at midday Tuesday, leaving a well-arranged lounge suite and home theatre unit, featuring DQ's prized oval television. They travel back in time to Monday, where DQ has some rather strange and unexpected adventures. He intended to correct something that happened yesterday, that had gone all wrong the first time around, and by the time the buddies reunite and leave for Tuesday (by sleeping and waking up in the future) he's sure it's all been sorted. When DQ and his buddy SP get back to his apartment midday Tuesday, it looks for all the world like there's nothing there except an ordinary knife and fork.

In this story it seems that on Tuesday there is a television that looks exactly like a knife. If we interpret the claim about the relations between higher-level facts and the lower-level facts as a kind of impossibility claim, e.g. as the claim that a conjunction *p* ${\wedge}$ *q* is never true in a story if the conditional *If q, then* *p* *is false in virtue of q being true* is true, then we have a problem. Let *p* be the claim that there is a television, and let *q* be the claim that the only things in the apartment looked life a knife and fork. If that's how the more basic phenomenal and functional facts are, then there isn't a television in virtue of those facts. (That is, this relation between phenomenal and functional facts and facts about where the televisions are really holds.) So this rule would say *p* ${\wedge}$ *q* could not be true in the story. But in fact *p* ${\wedge}$ *q* is true in the story.

The difficulty here is that *Fixing a Hole* is a contradictory story, and contradictory stories need care. First, here's how we should interpret the rule

> *Virtue*  
> If *p* is the kind of claim that if true must be true in virtue of lower-level facts, and if the story is about those lower-level facts, then it must be true in the story that there is some true proposition *r* which is about those lower-level facts such that *p* is true in virtue of *r*.

In *Fixing a Hole* there are some true lower-level claims that are inconsistent with there being a television. But there is also in the story a true proposition about how DQ's television looked before his time-travel misadventure. And it is true (both in reality and in the story) that something is a television in virtue of looking that way. (Note that we don't say there must be some proposition *r* that is true in the story in virtue of which *p* is true. For there is no fact of the matter in *Fixing a Hole* about how DQ's television looked before he left. So in reality we could not find such a proposition. But it is true in the story that his television looks some way or other, so as long as we talk about what in the story is true, and don't quantify over propositions that are (in reality) true in the story, we avoid this pitfall.)

So my solution to the alethic puzzle is that *Virtue* is a strong default principle of fictional interpretation. I haven't done much yet to motivate it, apart from noting that it seems to cover a lot of the cases that have been raised without overgenerating in the manner of the impossible solution. A more positive motivation must wait until I have presented my solutions to the phenomenological and imaginative puzzles. I'll do that in the next section, then in tell a story about why we should believe *Virtue*.

# More Solutions

## The Phenomenological Puzzle

My solution here is essentially the same as Gendler's. She think that when we strike a sentence that generated imaginative resistance we respond with something like, "That's what you think!" What makes this notable is that it's constitutive of playing the fiction game that we not normally respond that we way, that we give the author some flexibility in setting up a world. I think that's basically right, but a little more is needed to put the puzzle to bed.

Sometimes the "That's what you think!" response does not constitute abandoning the fiction game. At times it is the only correct way to play the game. It's the right thing to say *to Lily* when reading the first line of *The Dead*. (Maybe it would be rude to say it *aloud* to poor Lily, the poor girl is run off her feet after all, but it's appropriate to think it.) This pattern recurs throughout *Dubliners*. When in *Eveline* the narrator says that Frank has sailed around the world, the right reaction is to say to Eveline (or whoever is narrating then), "That's what you think!" There's a cost to playing the game this way. We end up knowing next to nothing about Frank. But it is not as if making the move stops us playing, or even stops us playing correctly. It's part of the point of *Eveline* that we know next to nothing about Frank.

What makes cases like *Death* and *Victory* odd is that our reaction is directed at someone who isn't in the story. One of Alex Byrne's [-@Byrne1993] criticisms of Lewis was that on Lewis's theory it is true in every story that the story is being told. Byrne argued that in many fictions it is not true that in the fictional world there is someone sufficiently knowledgeable to tell the story. In these fictions, we have a story without a storyteller. If there are such stories, then presumably *Death* and *Victory* are amongst them. It is not a character in the story who ends by saying that Craig's action was right or that Quixote's apartment contains a television. The *author* says that, and hence deserves our reproach, but the author isn't in the story. Saying "That's what you think!" directly to him or her breaks the fictional spell for suddenly we have to recognise a character not in the fictional world.

This proposal for the phenomenological puzzle yields a number of predictions which seem to be true and interesting. First, a story that has a narrator should not generate a phenomenological puzzle, even when outlandish moral claims are made. The more prominent the narrator, the less striking the moral claim. Imagine, for example, a version of *Death* where the text purports to be Craig's diary, and it includes naturally enough his own positive evaluation of what he did. We wouldn't believe him, of course, but we wouldn't be struck by the claim the same way we are in the actual version of *Death*.

One might have thought that what is shocking is what we discover about the author. But this isn't right, as can be seen if we reflect on stories that contain Craig's diary. It is possible, difficult but possible, to embed the diary entry corresponding to *Death* in a longer story where it is clear that the author endorses Craig's opinions. (Naturally I won't do this. Examples have to come to an end somewhere.) Such a story would, in a way, be incredibly shocking. But it wouldn't make the final line shocking in just the way that the final line of *Death* is shocking. Our reactions to these cases suggest that the strikingness of the last line of *Death* is not a function of what it reveals about the author, but of how it reveals it.

The final prediction my theory makes is somewhat more contentious. Some novels announce themselves as works of fiction. They go out of their way to prevent you ignoring the novel's role as mediation to a fictional world. (For an early example of this, consider the sudden appearance of newspaper headlines in the 'Aeolus' episode of *Ulysses*.) In such novels we already have to recognise the author as a player in the fictional game, if not a character in the story. I predict that sentences where we do not take what is written to really be true in the story, even though this is what the author intended, should be less striking in these cases because we are already used to reacting to the author *as such* rather than just to the characters. Such books go out of their way to break the fictional spell, so spell breaking should matter less in these cases. I think this prediction is correct, although the works in question tend to be so complicated that it is hard to generate clear intuitions about them.

## The Imaginative Puzzle

Imagine, if you will, a chair. Have you done so? Good. Let me make some guesses about what you imagined. First, it was a specific kind of chair. There is a fact of the matter about whether the chair you imagined is, for example, an armchair or a dining chair or a classroom chair or an airport lounge chair or an outdoor chair or an electric chair or a throne. We can verbally represent something as being a chair without representing it as being a specific kind of chair, but imagination cannot be quite so coarse.[^9]

[^9]: This relates to another area in which my solution owes a debt to Gendler's solution. Supposing can be coarse in a way that imagining cannot. We can suppose that Jack sold a chair without supposing that he sold an armchair or a dining chair or any particular kind of chair at all. Gendler concludes that what we do in fiction, where we try and imagine the fictional world, is very different to what we do, say, in philosophical argumentation, where we often suppose that things are different to the way they actually are. We can suppose, for the sake of argument as it's put, that Kantian or Aristotelian ethical theories are entirely correct, even if we have no idea how to imagine either being correct. Thanks to Tyler Doggett for pointing out the connection to Gendler here.

Secondly, what you imagined was incomplete in some respects. You possibly imagined a chair that if realised would contain some stitching somewhere, but you did not imagine any details about the stitching. There is no fact of the matter about how the chair you imagined holds together, if indeed it does. If you imagined a chair by imagining bumping into something chair-like in the dead of night, you need not have imagined a chair of any colour, although in reality the chair would have some colour or other.[^10]

[^10]: Thanks to Kendall Walton for pointing out this possibility.

Were my guesses correct? Good. The little I needed to know about imagination to get those guesses right goes a long way towards solving the puzzle.

Chairs are not very distinctive. Whenever we try to imagine that a non-fundamental property is instantiated the content of our imagining will be to some extent more specific than just that the object imagined has the property, but not so much more specific as to amount to a complete description of a possibilia. It's the latter fact that does the work in explaining how can imagine impossible situations. If we were, foolishly, to try to fill in all the details of the impossible science fiction cases it would be clear they contained not just impossibilities, but violations of *Virtue*, and then we would no longer be able to imagine them. But we can imagine the restaurant at the end of the universe without imagining it in all its glorious gory detail. And when we do so our imagining appears to contain no such violations.

But why can't we imagine these violations in fictions? It is primarily because we can only imagine the higher-level claim some way or another, just as we only imagine a chair as some chair or other, and the instructions that go along with the fiction forbid us from imagining *any* relevant lower-level facts that would constitute the truth of the higher-level claim. We have not stressed it much above, but it is relevant that fictions understood as invitations to imagine have a "That's all" clause.[^11] We are not imagining *Death* if we imagine that Jack and Jill had just stopped arguing with each other and were about to shoot everyone in sight when Craig shot them in self-defence. The story does not explicitly say that wasn't about to happen. It doesn't include a "That's all" clause. But such clauses have to be understood. So not only are we instructed to imagine something that seems incompatible with Craig's action being morally acceptable, we are also instructed (tacitly) to *not* imagine anything that would make it the case that his action is morally acceptable. But we can't simply imagine moral goodness in the abstract, to imagine it we have to imagine a particular kind of goodness.

[^11]: "That's all" clauses play a distinct, but related, role in Jackson [-@Jackson1998 Ch. 1]. It's also crucial to my solution to the alethic puzzle that there be a "That's all" clause in the story. What's problematic about these cases is that the story (implicitly) rules out there being the lower-level facts that would make the expressed higher-level claims true.

## Two Thoughts Too Many?

I have presented three solutions to the three different puzzles with which we started. Might it not be better to have a uniform solution? No, because although the puzzles are related, they are not identical. Three puzzles demand three solutions.

We saw already that the phenomenological puzzle is different to the other two. If we rewrite *Death* as Craig's diary there would be nothing particularly striking about the last sentence, certainly in the context of the story as so told. But the last sentence generates alethic and imaginative puzzles. Or at least it could generate these puzzles if the author has made it clear elsewhere in the story that Craig's voice is authoritative. So we shouldn't expect the same solution to that puzzle as the other two.

The alethic puzzle is different to the other two because ultimately it depends on what the moral and conceptual truths are not on what we take them to be. Consider the following story.

> *The Benefactor*  
> Smith was a very generous, just and in every respect moral man. Every month he held a giant feast for the village where they were able to escape their usual diet of gains, fruits and vegetables to eat the many and varied meats that Smith provided for them.

Consider in particular, what should be easy to some, how *Benefactor* reads to someone who believes that we are morally required to be vegetarian if this is feasible. In *Benefactor* it is clear in the story that most villagers can survive on a vegetarian diet. So it is morally wrong to serve them the many and varied meats that Smith does. Hence such a reader should disagree with the author's assessment that Smith is moral 'in every respect'. Such a reader will think that in fact in the story Smith is quite immoral in one important respect.

Now for our final assumption. Assume it is really true that we morally shouldn't eat meat if it is avoidable. Since the ethical vegetarians have true ethical beliefs about the salient facts here, it seems plausible that their views on what is true in the story should carry more weight than ours. (I'm just relying on a general epistemological principle here: other things being equal trust the people who have true beliefs about the relevant background facts.) So it seems that it really is false in the story that Smith is in every respect moral. *Benefactor* raises an alethic puzzle even though for non-vegetarians it does not raise a phenomenological or imaginative puzzle.

This point generalises, so we need not assume for the general point that vegetarianism is true or that our typical reader is not vegetarian. We can be very confident that *some* of our ethical views will be wrong, though for obvious reasons it is hard to say which ones. Let *p* be a false moral belief that we have. And let *S* be a story in which *p* is asserted by the (would-be omniscient) narrator. For reasons similar to what we said about *Benefactor*, *p* is not true in *S*. But *S* need not raise any imaginative or phenomenological puzzles. Hence the alethic puzzle is different to the other two puzzles.

# Why Virtue Matters

I owe you an argument for why authors should be unable to easily generate violations of *Virtue*, though there is no general bar on making impossibilities true in a story. My general claims here are not too dissimilar to Yablo's solution to the puzzles, but there are a couple of distinctive new points. Before we get to the argument, it's time for another story.

Three design students walk into an furniture showroom. The new season's fashions are all on display. The students are all struck by the *piece de resistance*, though they are all differently struck by it. Over drinks later, it is revealed that while B and C thought it was a chair, A did not. But the differences did not end there. When asked to sketch this contentious object, A and B produced identical sketches, while C's recollections were drawn somewhat differently. B clearly disagrees with both A and C, but her differences with each are quite different. With C she disagrees on some simple empirical facts, what the object in question looked like. With A she disagrees on a conceptual fact, or perhaps a semantic fact, whether the concept CHAIR, or perhaps just the term 'chair', applies to the object in question. As it turns out, A and B agree that 'chair' means CHAIR, and agree that CHAIR is a public concept so one of them is right and the other wrong about whether this object falls under the concept. In this case, their disagreement will have a quite different feel to B's disagreement with C. It may well be that there is no analytic/synthetic distinction, and that questions about whether an object satisfies a concept are always empirical questions, but this is not how it feels to A and B. They feel that they agree on what the world is like, or at least what this significant portion of it is like, and disagree just on which concepts apply to it.

The difference between these two kinds of disagreement is at the basis of our attitudes towards the alethic puzzle. It may look like we are severely cramping authorial freedom by not permitting violations of *Virtue*.[^12] From A and B's perspective, however, this is no restriction at all. Authors, they think, are free to stipulate which world will be the site of their fiction. But as their disagreement about whether the *piece de resistance* was a chair showed, we can agree about which world we are discussing and disagree about which concepts apply to it. The important point is that the metaphysics and epistemology of concepts comes apart here.

[^12]: Again, it is worth noting that I am not ruling out any violation of *Virtue*, just easy violations of it. The point being made in the text is that even a blanket ban on violations would not be a serious restriction on authorial freedom.

There can be no difference in whether the concept CHAIR applies without a difference in the underlying facts. But there can be a difference of opinion about whether a thing is a chair without a difference of opinion about the underlying facts. The fact that it's the author's story, not the reader's, means that the author gets to say what the underlying facts are. But that still leaves the possibility for differences of opinion about whether there are chairs, and on that question the author's opinion is just another opinion.

Authorial authority extends as far as saying which world is fictional in their story, it does not extend as far as saying which concepts are instantiated there. Since the main way that we specify which world is fictional is by specifying which concepts are instantiated at it, authorial authority will usually let authors get away with any kind of conceptual claim. But once we have locked onto the world being discussed, the author has no special authority to say which concepts, especially which higher-level concepts like RIGHT or FUNNY or CHAIR are instantiated there.

(Does it matter much that the distinction between empirical disagreements and conceptual disagreements with which I started might turn out not to rest on very much? Not really. I am trying to explain why we have the attitudes towards fiction that we do, which in turn determines what is true in fiction generally. All that matters is that people generally think that there is something like a conceptual truth/empirical truth distinction, and I think enough people would agree that A and B's disagreement is different in kind from B and C's disagreement to show that is true. If folks are generally wrong about this, if there is no difference in kind between conceptual truths and empirical truths, then our communal theory of truth in fiction will rest on some fairly untenable supports. But it will still be our theory, although any coherent telling of it will have to be in terms of things that are taken to be conceptual truths and things that are taken to be empirical truths.)

This explanation of why authorial authority collapses just when it does yields one fairly startling, and I think true, prediction. I argued above that authors could not easily generate violations of *Virtue*. That this is impossible is compatible with any number of hypotheses about how readers will resolve those impossibilities that authors attempt to slip in. The story here, that authors get to say which world is at issue but not which concepts apply to it, yields the prediction that readers will resolve the tension in favour of the lower-level claims. When given a physical description of a world and an incompatible moral description, we will take the physical description to fix which world is at issue and reduce the moral description to a series of questionable claims about the world. Compare what happens with A, B and C. We take A and B to agree about the world and disagree about concepts, rather than say taking B and C to agree about what the world is like (there's a chair at the heart of the furniture show) and say that A and B disagree about the application of some recognitional concepts. This prediction is borne out in every case discussed in . We do not conclude that Craig did not really shoot Jack and Jill, because after all the world at issue is stipulated to be one where he did the right thing. Even more surprisingly, we do not conclude that Quixote's furniture does not look like kitchen utensils, because it consists of a television and an armchair. This is surprising because in *Victory* I never said that the furniture looked like kitchen utensils. The *tacit* low-level claim about appearances is given precedence over the *explicit* high-level claims about which objects populate Quixote's apartment. The theory sketched here predicts that, and supports the solution to the alethic puzzle sketched in , which is good news for both the theory and the solution.

It's been a running theme here that the puzzles do not have anything particularly to do with normativity. But some normative concepts raise the kind of issues about authority mentioned here in a particularly striking way. There is always some division of cognitive labour in fiction. The author's role is, among other things, to say which world is being made fictional. The audience's role is, among other things, to determine the artistic merit of the fictional work. On other points there may be some sharing of roles, but this division is fairly absolute. The division threatens to collapse when authors start commenting on the aesthetic quality of words produced by their characters. At the end of *Ivy Day in the Committee Room* Joyce has one character describe a poem just recited by another character as "A fine piece of writing" [@Joyce1914 105]. Most critics seem to be happy to *accept* the line, because Joyce's poem here really is, apparently, a fine piece of writing. But to me it seems rather jarring, even if it happens to be true. It's easy to feel a similar reaction when characters in a drama praise the words of another character.[^13] This is a special, and especially vivid, illustration of the point I've been pushing towards here. The author gets to describe the world at whichever level of detail she chooses. But once it has been described, the reader has just as much say in which higher-level concepts apply to parts of that world. When the concepts are evaluative concepts that directly reflect on the author, the reader's role rises from being an equal to having more say than the author, just as we normally have less say than others about which evaluative concepts apply to us.

[^13]: For a while this would happen frequently on the TV series *The West Wing*. President Bartlett would deliver a speech, and afterwards his staffers would congratulate themselves on what a good speech it was. The style of the congratulations was clearly intended to convey the author's belief that the speech they themselves had written was a good speech, not just the characters' beliefs to this effect. When in fact it was a very bad speech, this became very jarring. In later series they would often not show the speeches in question and hence avoid this problem.

This idea is obviously similar to Yablo's point that we get to decide when grokking concepts apply, not the author. But it isn't quite the same. I think that if any concepts are grokking, most concepts are, so it can't be the case that authors never get to say when grokking concepts apply in their stories. Most of the time authors will get to say which grokking concepts apply, because they have to use them to tell us about the world. What's special about the kind of concepts that cause puzzles is that we get to decide when they apply full stop, but that we get to decide how they apply *given how more fundamental concepts apply*. So the conciliatory version of the relation between my picture here and Yablo's is that I've been filling in, in rather laborious detail, his missing antecedent.

# Two Hard Cases

The first hard case is suggested by Kendall @Walton1994. Try to imagine a world where the over-riding moral duty is to maximise the amount of nutmeg in the world. If you are like me, you will find this something of a challenge. Now consider a story *Nutmeg* that reads (in its entirety!): "Nobody ever discovered this, but it turned out all along their over-riding moral duty was to maximise the amount of nutmeg in the world." What is true in *Nutmeg*? It seems that there are no violations of *Virtue* here, but it is hard to imagine what is being described.

The second hard case is suggested by Tamar Szabó @Gendler2000. (I'm simplifying this case a little, but it's still hard.) In her *Tower of Goldbach*, God decrees that 12 shall no longer be the sum of two primes, and from this it follows (even in the story) that it is not the sum of 7 and 5. (It is not clear why He didn't just make 5 no longer prime - say the product of 68 and 57. That may have been simpler.) Interestingly, this has practical consequences. When a group of seven mathematicians from one city attempts to join a group of five from another city, they no longer form a group of twelve. Again, two questions. Can we imagine a Goldbachian situation, where 7 and 5 equal not 12? Is it true in Gendler's story that 7 and 5 equal not 12? If we cannot imagine Goldbach's tower, where is the violation of *Virtue*?

First a quick statement of my responses to the two cases then I'll end with my detailed responses. To respond properly we need to tease apart the alethic and imaginative puzzles. I claim that the alethic puzzle only arises when there's a violation of *Virtue*. There's no violation in either story, so there is no alethic puzzle. I think there are independent arguments for this conclusion in both cases. We can't imagine either (if we can't) because any way of filling in the more basic facts leads to violations.

It follows from my solution to the alethic puzzle that Nutmegism (Tyler Doggett's name for the principle that we must maximise quantities of nutmeg) could be true in a story. There is no violation in *Nutmeg*, since there are no lower level claims made. Still, the story is very hard to imagine. The reason for this is quite simple. As noted, we cannot just imagine a chair, we have to imagine something more detailed that is a chair in virtue of its more basic properties. (There is no particular more basic property we need imagine, as is shown by the fact that we can imagine a chair just by imagining something with a certain look, or we can imagine a chair in the dark with no visual characteristics. But there is always *something* more basic.) Similarly to imagine a duty, we have to imagine something more detailed, in this case presumably a society or an ecology, in virtue of which the duty exists. But no such possible, or even impossible, society readily springs to mind. So we cannot imagine Nutmegism is true.

But it is hard to see how, or why, this inability should be raised into a restriction on what can be true in a story. One might think that what is wrong with *Nutmeg* is that the fictional world is picked out using high-level predicates. If we extend the story *any way at all*, the thought might go, we will generate a violation of *Virtue*. And that is enough to say that Nutmegism is not true in the story. But actually this isn't quite right. If we extend the story by adding more *moral* claims, there is no duty to minimise suffering, there is no duty to help the poor etc, there are still no violations in the story. The restriction we would have to impose is that there is no way of extending the story to fill out the facts in virtue of which the described facts obtain, without generating a violation. But that looks like too strong a constraint, mostly because if we applied it here, to rule out Nutmegism being true in *Nutmeg*, we would have to apply it to every story written in a higher level language than that of microphysics. It doesn't *seem* true that we have to be able to continue a story all the way to the microphysical before we can be confident that what the author says about, for instance, where the furniture in the room is. So there's no reason to not take the author's word in *Nutmeg*, and since the default is always that what the author says is true, Nutmegism is true in the story.

The mathematical case is more difficult. The argument that 7 and 5 could fail to equal 12 in the story turns on an example by Gregory @Currie1990. (The main conclusions of this example are also endorsed by @Byrne1993.) Currie imagines a story in which the hero refutes Gödel's Incompleteness Theorem. Currie argues that the story could be written in such a way that it is true in the story not merely that everyone believes our hero refuted Gödel, but that she really did. But if it could be true in a story that Gödel's Incompleteness Theorem could be false, then it's hard to see just why it could not be true in a story that a simpler arithmetic claim, say that 7 and 5 make 12, could also be false. Anything that can't be true in a story can't be true in virtue of some feature it has. The only difference between Gödel's Incompleteness Theorem and a simple arithmetic statement appears to be the simplicity of the simple statement. And it doesn't seem possible, or advisable, to work that kind of feature into a theory of truth in fiction.

The core problem here is that how simple a mathematical impossibility is very much a function of the reader's mathematical knowledge and acumen. Some readers probably find the unique prime factorisation theorem so simple and evident that for them a story in which it is false is as crashingly bad as a story in which 7 and 5 do not make 12. For other readers, it is so complex that a story in which it has a counterexample is no more implausible than a story in which Gödel is refuted. I think it cannot be true for the second reader that the unique prime factorisation theorem fails in the story and false for the first reader. That amounts to a kind of relativism about truth in fiction that seems preposterous. But I agree with Currie that some mathematical impossibilities can be true in a fiction. So I conclude that, whether it is imaginable or not, it could be true in a story that 7 and 5 not equal 12.

I think, however, that it is impossible to imagine that 7 plus 5 doesn't equal 12. Can we explain that unimaginability in the same way we explained why *Nutmeg* couldn't be imagined? I think we can. It seems that the sum of 7 and 5 is what it is in virtue of the relations between 7, 5 and other numbers. It is not primitive that various sums take the values they take. That would be inconsistent with, for example, it being constitutive of addition that it's associative, and associativity does seem to be constitutive of addition. We cannot think about 7, 5, 12 and addition without thinking about those more primitive relations. So we cannot imagine 7 and 5 equally anything else. Or so I think. There's some rather sophisticated, or at least complicated, philosophy of mathematics in the story here, and not everyone will accept all of it. So we should predict that not everyone will think that these arithmetic claims are unimaginable. And, pleasingly, not everyone does. Gendler, for instance, takes it as a data point that *Tower of Goldbach* is imaginable. So far so good. Unfortunately, if the story is true we should also expect that whether people find the story imaginable links up with the various philosophies of mathematics they believe. And the evidence for that is thin. So there may be more work to do here. But there is clearly *a* story that we can tell that handles the case.

::: {.content-visible when-format="pdf"}
## References {-}
:::