---
title: "Nested Frames and the Value of Information"
abstract: |
  Recently several philosophers have discussed a result due to John Geanakoplos concerning the value of information. Very roughly, it says that if a frame is reflexive, transitive, and nested, then getting information is guaranteed to have non-negative expected value. This result has been taken by some philosophers to be reason to think that evidence should satisfy these three constraints, while other philosophers have put forward intuitive models that violate the constraint. This paper makes a small technical contribution to the debate. Two natural generalisations of Geanakoplos's result do not hold, and in each case there is an argument that the philosophical applications of the result really need this stronger claim. In particular, the result does not hold on infinite frames, and the three constraints (reflexivity, nestedness, and transitivity) do not suffice to show that more information is (in expectation) more valuable than less information. 
date: May 2 2004
draft: true
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
citation: false
bibliography: ../../brian-quarto.bib
categories:
  - games and decisions
  - unpublished
bibliography: ../../../brian-quarto.bib
csl: ../../../chicago-with-note.csl
format:
  html: default
  docx:
      reference-doc: ../../../quarto-articles-template.docx
  pdf:
    output-file: "Nested Frames and the Value of Information"
    include-after-body: 
      text: |
         \noindent Unpublished. 
---

Let an experimental frame ⟨W, E~1~, E~2~, P, O⟩ be defined as follows. 

- W is a finite set of worlds.
- E~1~ and E~2~ are binary relations on W. Intuitively, *x*E~*i*~*y* means that if world *x* is actual, and experiment *i* is performed, then after the experiment, world *y* is possible.
- P is a prior probability function defined over some algebra including all singletons of members of W.
- O is a finite set of functions from members of W to real numbers. Intuitive, they are bets, and if *x* is a world and *b* a bet, *b*(*x*) is the return from taking bet *b* in world *x*.

David Blackwell [-@Blackwell1951, -@Blackwell1953] proved a number of important results about these frames. He showed that if E~1~ and E~2~ were equivalence relations, and E~1~ was a refinement of E~2~ in the sense that ∀*x*,*y*(*x*E~1~*y* → *x*E~2~*y*), then in expectation, performing experiment 1 was at least as valuable as performing experiment 2. More precisely, assume that the experimenter starts with credence function P, performs experiment *i*, updates (by conditionalisation) on the proposition {*y*: *xE~i~y*}, where *x* is the world they are in, and then chooses the member of B that has, post-update, the highest expected value. Blackwell shows that before performing the experiment, the experimenter expects performing experiment 1 to have at least as high an expected value as performing experiment 2. Blackwell shows a lot more than this; most importantly he proves a converse of this result as well. But that result will be the 