### Checking and Inquiring {#sec-mcgrath-checking}

In KAHIS I agreed that typically one cannot inquire into what one knows, but argued that there are some atypical cases where you can. In particular, when the purpose of inquiry is getting sensitive beliefs, it is find to inquire into things one knows. Since saying to oneself "*p*, therefore *p*" would not increase the sensitivity of one's belief in *p*, this isn't a good inquiry, even though it starts with what one knows and uses clearly valid steps. (Is this a counterexample to the principle that you can always start with what you know? No, because what's wrong with this inquiry is not where it starts, but the result that running through it fails at the aim of increasing sensitivity.)

McGrath suggests that these cases are better described as _checking_ than as inquiring. As he points out, ordinary language agrees here. When he looks into the office at the insistence of a sceptical colleague, it is natural to say he is _checking_ where the chair is there, and unnatural to say one is inquiring into whether she is there.

I'm happy to accept his amendment, but I don't think this is the end of the story, for a couple of reasons. First, this leaves open what exactly it is to check something. It isn't just inquiring into what we know. Grabbing an old flashlight to take to the basement while a storm approaches, my spouse might sensibly say "You should check that's still working." This isn't because we already know it is working; quite the contrary. So checking is compatible with ignorance. On the other hand, not all inquiry is checking. If I go into a philosopher's archives and start reading with no fixed goal, I might be trying to find out something about them, but I'm not checking anything. Exactly what checking is feels like a bigger question.

Or, perhaps I should say, it feels like _two_ bigger questions. One question is how the ordinary term 'check' gets used. The other question is whether there is a theoretically interesting class of activities picked out by this word, or in the vicinity of what this word gets picked out. I suspect the answer to the latter question is _yes_, but that's for another day.

This leads to my other worry about McGrath's argument. I said above that it isn't natural to describe McGrath's checkers as inquiring into something. But it's rarely natural to say someone is 'inquiring into' something. That's a theorist's construction, not ordinary language. There's a response to this, and it's right there in what McGrath said. Some inquirers are _trying to find something out_. The person who checks because of a sceptical colleague is not doing that. They know where the chair is, they aren't trying to find it out. 

This all suggests a nice synthesis. There are two related activities: _checking_ and _finding out_. We can do both at once; I find out whether the flashlight is working by checking it. But they can come apart in both directions. Open-ended archival research is finding out without checking; satisfying a sceptical colleague is checking without finding out. Which of these is 'inquiry'? I'd rather say they both are kinds of inquiry, but if someone insists that only finding out is inquiry, I'm not going to argue.^[Well, I'm not going to argue much. I would note that Friedman's Morse, who is pretending to inquire, is neither checking nor finding out, so the intuition that he's not inquiring doesn't settle this dispute.]

What's more important is that with this distinction in hand, we can say something more systematic into the relationship between knowledge and inquiry. When you are simply trying to find things out, it's permissible to start with any (relevant) fact you know. That's enough to get the argument for pragmatic encroachment off the ground.

