### Questions About Probability {#sec-mcgrath-probability}

The view in KAHIS has a striking consequence concerning probability. It says that when one is trying to find out how likely it is that *p*, either the answer is 1, or one doesn't know *p*. McGrath says that this is implausible when *p* is _At least one player will hit a free throw in tonight's NBA games_. (Assume it's mid-season, and there are ten games on.) If I stick to this verdict, I have to say, implausibly according to McGrath, that either the answer to the likelihood question is 1, or the inquirer doesn't know *p*. I'm not going to try wriggling out of this; I think the second option is right: the inquirer doesn't know *p*. That is not exactly what intuition says, so I better argue for it.

Start with how you'd try to figure out this likelihood. You'd look at the frequency of made free throws over the last few hundred games, the number of free throw attempts awarded per game, perhaps something about how those attempts are distributed. What you would not do, under any circumstances, is start with "Well, at least one will be made tonight, so let's take that as given." That premise is simply unavailable in _this_ inquiry, because of which question is being asked.

In the previous subsection I distinguished checking whether *p* from trying to find out whether *p*, and I endorsed a strong principle about the latter: when you are trying to find something out, you can use whatever relevant fact you know. I'd like to keep that principle exceptionless, and the view that you lose knowledge that *p* when working out the likelihood of *p* is the only way to keep it. On McGrath's picture, the inquirer knows that some player will make a free throw, that's obviously relevant to the likelihood they are trying to deduce, but they can't use it. The connection between knowledge and sensible methods for finding stuff out has been broken, and once it is broken, for me the interest of inquiring into the nature of knowledge goes with it.

McGrath suggests the naturalness of the following speech raises a problem for my view here. One could concede a minuscule probability that no free throw is made, then add "But that's not going to happen; someone will make one"? That's fine I think, but look what it does. It *sets a possibility aside*. Contra @Lewis1996, I don't think the fact that we are attending to a possibility means we have to take it seriously. We can propose that we're not going to consider some possibility,^[Here I'm basically agree with the criticisms that @MBT2009a makes of the Rule of Attention that @Lewis1996 proposes] and provided that everyone else goes along with this, we can act as if we know it. If this ignoring makes sense given our interests, we may in fact know it, so it's not just acting as if. All I insist on is that in doing that we are tacitly agreeing that we're no longer working out how many 9's there are at the start of the probability that at least one free throw will be hit tonight. 
