---
title: "Comments for Ranch Metaphysics 2024"
subtitle: "Commentary on Casey O'Callaghan, What's To Fear in Losing a Sense"
description: |
  What is fear after all?
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
date: 01-17-2024
citation: false
categories:
  - unpublished
format:
    html: default
    docx:
        output-file: "Weatherson Comments for Ranch"
    pdf:
        output-file: "Weatherson Comments for Ranch"
        include-after-body: 
            text: |
                
---

Thanks to Casey for a really thoughtful, and thought-provoking, paper. I'm going to mostly talk about his first question, then say a little about the second question at the end.

A very small point first. You need a *strong* version of the mere-difference view to get the first question puzzle off the ground. Here's a simple reason to fear becoming disabled: disabled people are treated awfully in this society. Barnes's mere-difference view says that being disabled wouldn't be an all-things-considered bad if society weren't so awful. To really get the puzzle going, you need that it isn't an all-things-considered bad right now. Maybe some of the testimony from disabled people can support that claim, but it's a *really* strong claim. Still, let's see what happens if we take it on board.

As a somewhat old-fashioned philosopher, my first thought when I saw the title was to ask "What is fear?". There are two somewhat different types of things we call fears. The first are what I'll call (apologies if this is new terminology for old concepts), acute fear. It's what happens in animals like us when they are confronted with certain kinds of danger, and it typically involves bunch of characteristic physiological reactions.^[Recent work on this includes Bronwyn Finnegan's "Fear is Anticipatory: A Buddhist Analysis", Davide Bordini & Giuliano Torrengo's "Frightening Times", and Anthony Hatzimoysis's "Passive Fear".] The other I'll call chronic fear, and it's how we describe someone who has an elevated disvalue on a kind of harm. Fear of death is the really paradigmatic case here.^[Tom Cochrane's "Fear of Death and the Will to Live" is a useful paper on recent work on this.] There are cases that mix the two - fear of flying and fear of needles for example.^[Fear that a harm has befallen a loved one, as Jesse Prinz discusses in _Gut Reactions_, is an interesting in-between case too.] 

But it's striking how different the extremes are. Acute fear has distinctive reactions, and has been widely studies in psychology. Many of these reactions are not actions, they are involuntary movements. Fear of death is not like that at all. Most people who fear death don't stop acting, if anything they over-act, and they don't lose means-end coherence in their actions. They just have a very large disvalue on a particular end. The philosophical literature on the fear of death has almost no overlap with the philosophical, or more extensive psychological, literature on acute fears. Apart from the word 'fear', they have almost nothing in common.

Fearing a loss of a sense is chronic, not acute. It's a lot like fear of death, but perhaps with less intensity. One initial challenge here for the normative version of Casey's first question is that some people seem to take chronic fears as to involve irrationality. Fear of death is meant to be more than a desire for longer life. What's the 'more'? Sometimes it seems like it's irrationality. This might be terminological, and I'll assume that chronic fears can be more-or-less rational.

Chronic fears are aspectual. To fear something doesn't require regarding it as all-things-considered bad. It merely requires one of two things.

First, it is sufficient that there's a non-trivial probability of a bad outcome. That's what happens in fear of flying.

Second, it is sufficient that there's a harm that's part of the outcome, even if it's outweighed by other goods. That's what happens when a person with a fear of needles gets an important vaccination.

Either of these points suffices to explain how fear of losing a sense is compatible with the mere difference view, and even how that fear can be recalcitrant. Losing a sense is psychologically devastating for some people. Maybe not that many, but a higher proportion than the proportion of passengers who die in plane crashes. 

And there are definitely bads that go with losing a sense. Maybe for many people there are offsetting goods, and maybe the bads aren't as bad as feared, but this isn't like losing \$100 somewhere and gaining \$100 somewhere else. The goods and bads involved don't offset that easily.

And I think Casey's paper does a great job setting out what some of those bads are. There are things that one simply can't do without a sense. If I lost my sight, I wouldn't be able to *watch* football. I would be able to listen to descriptions, and that's fun too, but it's not the *same*.

Chronic fears frequently involve fearing the unknown. As Casey points out, that's particularly relevant here. As he says, losing a sense is *transformative*. And one thing about transformative experiences is that it makes sense to fear what will happen, even if you expect that all-things-considered things will not be worse. Indeed, it makes sense to fear what will happen, even if you expect that all-things-considered things will be better. Fear with a positive expected gain can be mundane: think about a scary but fun amusement park ride. But the transformative cases are more striking.

Consider two paradigm cases of transformative experience: migrating, and having a child. Both of them are frequently tinged with fear, even for the willing migrant and excited parent. You don't know what it's like on the other side, and that's a bit scary. 

I think all these reflections help explain not just the fear, but what Casey rightly points out is the big thing to explain here: the recalcitrance of the fear. Tell me all the statistics you like about the distribution of hedonic outcomes; fill me in on the goods that go along with the bads, or losses, I can more easily comprehend. It won't make migrating, or having a first child, or losing a sense, not be scary. There's still a greater than plane crash probability of things going badly wrong, and there still will be losses - even if they are offset. And that's enough for fear.

I'll end on an autobiographical note relevant to the second question. One sense I wouldn't fear losing is smell. There are some smells I'd miss - kitchens full of curry or coffee. But I'm basically a city person at heart, and cities ... don't smell great. The car fumes, the dog poop, the cigarettes, that distinctive tang of underpasses; I could do without it all. There is information in there that I'd somewhat miss, though even there I wouldn't mind not being reminded of some parts. I suspect there's a generalisation here; if the aesthetic value of a sense isn't that great, it's easy to imagine doing without it. It's much harder being able to imagine doing without the things I enjoy *watching* or *listening to*.

Thanks again to Casey for a great paper, and I'm looking forward to the discussion!




