---
params:
  seed: 14884
  cats: 5
title: "Summary of an LDA"
abstract: |
  Input: Papers from _Philosophical Studies_ 1980-2019. Seed: 14884 Categories: 5. Iterations: 1000.
date: October 13, 2024
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
categories:
  - lda summary
format:
  html: default
format-links: [html]
csl: ../../chicago-with-note.csl
bibliography: 
  - /Users/weath/Documents/citations-2024/autobib.bib
  - /Users/weath/Documents/citations-2024/supplement.bib
---

```{r packages}
#| echo: false
#| warning: false

for (ipkg in c("tidyverse", "tidytext", "tm", "topicmodels", "lsa")) {
  if (!require(ipkg, character.only = TRUE)) {
    install.packages(ipkg)
    library(ipkg, character.only = TRUE)
  }
}
```

```{r loader}
#| echo: false
#| warning: false

load("ps_cites.RData")
load("ps_meta.RData")
load("ps_join.RData")
load("ps_to_ps.RData")
load("common_ps_words.RData")

load(
  paste0(
    "ps_lda_",
    params$seed,
    "_",
    params$cats,
    ".RData"
  )
)
```

```{r process}
#| echo: false
#| warning: false

  all_gamma <- tidy(my_lda, matrix = "gamma") 
  
  all_classifications <- all_gamma |>
    group_by(document) |>
    top_n(1, gamma) |>
    ungroup()
  
  all_titles_and_topics <- left_join(all_classifications,
                                              ps_meta,
                                              by = c("document" = "jstor_id"))
  
  phil_topics <- tidy(my_lda, matrix = "beta")
  
  word_score <- phil_topics |>
    group_by(term) |>
    dplyr::summarise(avgbeta = mean(beta), sdbeta = sd(beta))
  
  busy_topics <- phil_topics |>
    left_join(word_score, by = "term") |>
    right_join(common_ps_words, by = c("term" = "ngram")) |>
    mutate(score = (beta - avgbeta) * log(tn) / sdbeta)
```

```{r categorylists}
#| echo: false

all_classifications <- all_gamma |>
  group_by(document) |>
  top_n(1, gamma) |>
  ungroup()

meta_with_gamma <- ps_meta |>
  left_join(all_classifications,
            by = c("jstor_id" = "document"))

gamma_sd <- all_gamma |>
  group_by(document) |>
  summarise(sd = sd(gamma))

wide_gamma <- all_gamma |>
  mutate(gamma = round(gamma, 3)) |>
  pivot_wider(
    id_cols = document,
    names_from = topic,
    names_prefix = "t",
    values_from = gamma
  )

wos_cites <- ps_meta |>
  select(wos_id, cites)

wos_gamma <- wide_gamma |>
  left_join(ps_join, by = c("document" = "jstor_id")) |>
  left_join(gamma_sd, by = "document") |>
  left_join(select(meta_with_gamma, jstor_id, topic), by = c("document" = "jstor_id")) |>
  select(wos_id, t1:t5, sd, topic) |>
  mutate(Article = paste0(
    "@",
    str_replace(wos_id, ":", "")
  )) |>
  left_join(wos_cites, by = "wos_id") |>
  arrange(-cites)
```

```{r}
#| label: tbl-confusing
#| echo: false
#| tbl-cap: "Articles the model is confused about."

knitr::kable(wos_gamma |>
  arrange(sd) |>
  slice_min(order_by = sd, n = 20) |>
  select(Article, t1:t5))
```


```{r}
#| echo: false
#| output: asis

  distinctive_articles <- all_titles_and_topics |>
    ungroup() |>
    group_by(topic) |>
    slice_max(order_by = gamma, n = 15)
  
  for (tt in 1:params$cats) {
  active_topics <- busy_topics |>
    filter(topic == tt) |>
    ungroup() |>
    slice_max(n = 20, score)
  
  active_articles <- meta_with_gamma |>
    filter(topic == tt) |>
    mutate(citation = paste0(
      author,
      " [-@",
      str_replace(wos_id, ":", ""),
      "] ",
      "\"",
      title,
      "\""
    )) |>
    ungroup() |>
    slice_max(n = 10, gamma)
    
  active_gamma <- all_gamma |>
      filter(document %in% active_articles$jstor_id) |>
      group_by(topic) |>
      summarise(gamma = mean(gamma))
    
  cites_gamma <- ps_to_ps |>
      filter(new %in% active_articles$jstor_id) |>
      left_join(all_gamma,
                by = c("old" = "document"),
                relationship = "many-to-many"
      ) |>
      ungroup() |>
      group_by(topic) |>
      summarise(gamma = mean(gamma))
    
    sim_score <- as.numeric(
      cosine(
        active_gamma$gamma,
        cites_gamma$gamma
      )
    )
  
  cat("# Topic ", 
      tt,
      "\n\n")
  cat("**Terms**: ")
  cat(active_topics$term,
      sep = ", ")
  cat("\n\n")
  cat("**Score**: ", sim_score, "\n\n")
  cat("**Characteristic Articles**: \n\n - ")
  cat(active_articles$citation, sep = "\n- ")
  cat("\n\n")
  cat("**Highly Cited Articles**: \n\n")
  cat(sep = "\n", knitr::knit_child(quiet = TRUE, text = c(
    "```{r}",
    "#| echo: false",
    sprintf("#| label: tbl-%s", tt),
    "knitr::kable(wos_gamma |> filter(topic == tt) |> select(Article, t1:t5) |> slice(1:20)) ",
    "```"
  )))
}
```