---
title: "Review of “Theories of Vagueness”"
description: |
  Review of Rosanna Keefe, “Theories of Vagueness”. Cambridge: Cambridge University Press, 2000. 
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
doi: "10.1111/j.1933-1592.2003.tb00305.x"
date: 09-01-2003
self-contained: false
preview: keefe.jpg
toc: false
citation_url: https://doi.org/10.1111/j.1933-1592.2003.tb00305.x
citation:
  type: review-book
  container-title: "Philosophy and Phenomenological Research"
  volume: 67
  page: "491-494"
categories:
  - on books
  - vagueness
  - logic
format:
  html: default
  pdf: 
    output-file: "Review of Theories of Vagueness"
  docx: 
    output-file: "Review of Theories of Vagueness"
---

Many philosophers, I suspect, are partial to supervaluational theories of vagueness. And with good reason. Its rivals all seem to promise metaphysical mysteries concerning hitherto unnoticed, and perhaps unnoticeable, sharp boundaries around our concepts, or radical revision in our logical practices. And not only have philosophers been so tempted. The texts are a little unclear, but it seems several economists can be read as adopting supervaluational solutions to the difficulties raised by vagueness in economic concepts. Given its popularity, and plausibility, supervaluationism deserves a book-length defence. Yet this is the first such book in the philosophical canon.

And it is a fine defence of supervaluationism, though I doubt it is entirely successful. I ended up, a little contrariwise, feeling less convinced in the hegemony of supervaluational approaches than I was when I started. In part this was because Keefe was so clear in setting out where some rival approaches, especially degree-based approaches, failed that I felt she had inadvertently pointed out where her opponents should move next. Keefe's positive theory is fairly familiar, though she often marshalls new arguments for it, so this review will not dwell on exposition but concentrate on Keefe's arguments.

The book effectively divides into three parts. The first two chapters involve some scene-setting, and a discussion of the various methodological principles adopted. The next four chapters are attacks on non-supervaluational theories. And the final two chapters defend Keefe's preferred version of supervaluationism. Starting with methodology seemed to be a good idea, but the discussion didn't break much new ground. It turns out, surprisingly enough, that reflective equilibrium is useful in theorising about vagueness too.

The first rival theory to be examined is epistemicism, and Keefe presents two main arguments. One of these is fairly familiar, epistemicists have no theory about how predicates get the particular precise extensions that they do. This is true, but then supervaluationists aren't exactly flush with theories about how predicates get the particular imprecise extensions that they do either. The other criticism is more interesting. Epistemicism posits a sharp boundary between the tall and not-tall, but we don't know where this boundary is. It is a mystery why we do not have this knowledge, one that epistemicists try to solve by showing we could not know where the boundary is. But there are other mysteries too. For some reason, we don't try to find out where the boundary is, and we don't have beliefs about where it is. That we couldn't get this kind of knowledge doesn't explain these omissions. Like Hobbes trying to square the circle, we all try impossible things sometimes. So epistemicism has more explaining to do than it has hitherto done.

Keefe spends two chapters attacking theories based on degrees of truth. There are several related objections raised to these theories, but fundamentally they all boil down to the problem of false precision. If there is no fact of the matter as to whether Kylie is happy is true or not, then there is no fact of the matter as to whether it is true to degree 0.314. The most natural formulation of degree theories assumes there are facts of this latter form. More complicated formulations are either incoherent or incomplete. Keefe is good at working through the various moves that have been attempted to avoid this problem, and showing that none of them work. But at times she seemed too content to refute theories that had appeared in the literature, rather than anticipating future challengers. One particular challenge seemed particularly worthy of consideration. At one point Keefe introduces a new connective ≥~T~ to mean true to the same or a greater degree. She notes that most extant degree theorists are committed to a connectedness principle for ≥~T~: either *p* ≥~T~ *q* or *q* ≥~T~ *p*. But this principle is implausible given their other commitments. At this point it seemed relevant to wonder how well a theory that dropped all talk of degrees of truth and just took this connective ≥~T~ as primitive could avoid Keefe's objections. Indeed, at the equivalent point in his discussion in *Vagueness*, Timothy Williamson considers some arguments against just this position, but his discussion is rather brief. One can't reply to every *possible* response, but this one seemed so apposite, I would have liked to see Keefe's response to it.

Keefe holds that a sentence is true iff it is true on all admissible precisifications, i.e. that truth is supertruth. She says little about what makes a precisification acceptable, except that it must respect penumbral connections, and that admissibility is a vague matter. One consequence of this is that schema (T): S is true iff S is not always true. Keefe suggests that the standard arguments for (T) are circular, because they assume that there are no truth-value gaps. And, following van Fraassen, she notes something similar to (T) is true, and this is good enough.

She holds that an argument is valid iff it preserves truth, i.e. supertruth. Hence we have S $\dashv \vdash$ S is true.This interderivability might explain why we, mistakenly, think (T) is true. There is a familiar problem with this move, one stressed by Williamson. On all precisifications, all theorems of classical logic are true, so these all end up being true. So to that extent supervaluationism preserves classical logic. But not all admissible inference rules of classical logic preserve supertruth. In particular, the deduction theorem is no longer admissible. We can't infer (2) from (1):

1.  S $\vdash$ S is true.
2.  $\vdash$ S ⊃ S is true.

Keefe responds by noting that something similar to the deduction theorem is true, and this might explain our mistaken attachment to it. Keefe assumes the language contains an operator D, read 'definitely', such that DA means A is supertrue. Then the following rule is admissible:

⊃I\*

:   From A,B $\vdash$ C, infer B $\vdash$ DA ⊃ C

We think the standard ⊃ introduction rule, the deduction theorem, is acceptable because we mistake it for this one. Keefe notes we can set out similar kinds of rules for argument by cases (∨-elimination) and reductio ad absurdum (¬-introduction). These are intended to be small deviations from classical logic, but they strip the proof theory of much of its power. Keefe's rules are insufficient to prove p ⊃ r $\vdash$ (p ∧ q) ⊃ r, or p ⊃ p. One might question the value of inference rules with such little power.

There is little on the specific problems associated with the problem of the many for supervaluationism. Stephen Schiffer[^1] recently proposed a variant on the problem, suggesting that the standard supervaluational solution misclassifies some speech reports. Keefe replies that Schiffer's argument doesn't seem to go through if we adopt Davidson's paratactic theory of speech reports. Well, maybe it doesn't, but if supervaluationism requires the paratactic theory of speech reports, that seems highly relevant to its ultimate success, but Keefe merely assigns it a footnote.

[^1]: "Two Issues of Vagueness" Monist 81: 193-214.

There is a little more on the most obvious difficulty for supervaluationism, that it verifies some strange existentials. Consider a Sorites series of objects arranged with respect to F-ness, each a little more F than its predecessor, with the extremes being clearly F and not-F respectively. Then the sentence *There is a pair of adjacent objects such that one is F and the other is not* is supertrue. Keefe notes that we can distinguish here between the truth of the existential and the truth of an instance. And she notes that pragmatic theories due to Fine and Tappenden might explain our unwillingness to assert the existential, even if it is true. Still, it is would have been nice to see some discussion on whether this is a particular problem when F is a phenomenal predicate, or when it is 'ineradicably vague', as Dummett and other think predicates like 'sort of nearby' are.

The major innovation in the book is its treatment of higher-order vagueness. Keefe notes the following argument raises a serious difficulty for supervaluationism here

> According to the theory, a sentence is true simpliciter iff it is true on all complete and admissible specifications [i.e. on all precisifications]. But for any sentence, either it is true on all complete and admissible specifications (hence true simpliciter) or not (hence borderline or false). So there is no scope for avoiding sharp boundaries to the borderline cases or for accommodating borderline borderline cases. (202)

Keefe's response is to claim that the argument assumes, falsely, that there is "a precise and unique set of complete and admissible specifications." (202) Keefe denies this and instead develops a theory of higher-order vagueness based on supervaluating the concept of admissibility. But it is not clear where the argument does assume this. After all, the argument makes no mention of sets. And it is a little unclear just why this assumption should be false. Keefe argues that there is no such set because complete and admissible specification is vague, just as there is no precise and unique set of tall things because tall is vague. But even though complete and admissible specification is vague, on every precisification there is still a unique set of complete and admissible specifications, so it is true that there is such a set, so there is one. (Keefe accepts the S is true therefore S direction of (T).)

It is also unclear how the vagueness of the term complete and admissible specification is relevant. The supervaluational idea was that a sentence is true iff it is true on all specifications (precisifications) that are complete and admissible, not iff it is true on all specifications satisfying the term complete and admissible. It is a use/mention confusion to hold the latter view. But if the former is correct, the vagueness of any term, even 'admissible', is irrelevant to the above argument. So there still seems to be work to do on higher-order vagueness.

I've focussed on the negatives here, but this shouldn't overshadow how many good parts this book has. The coverage of the literature is peerless, the writing is always crisp and clear, and in many places Keefe's arguments move the debate in interesting new directions. It would be a great book to teach from, and indeed I would already be doing so, if only it were available in paperback. I do hope the publishers correct this problem shortly.
