---
title: "Infinity and Intransitivity"
abstract: |
    Jacob Nebel has an example that he uses to argue that a kind of impartiality is impossible when the world population is infinite. I think it shows something else, namely that infinite worlds give us another reason to reject the transitivity of indifference.
date: today
draft: false
execute:
  echo: false
  warning: false
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
number-sections: true
categories:
  - ethics
  - games and decisions
citation: false
format:
    html:
        css:
           - ..\trad_defn.css
           - color.css
    pdf:
        output-file: "Infinity and Intransitivity"
        keep-tex: true
        include-in-header:
          - text: |
              \usepackage{xcolor}
              \newcommand{\textred}[1]{\textcolor{red}{#1}}
              \newcommand{\textblue}[1]{\textcolor{blue}{#1}}
bibliography: 
  - /Users/weath/Documents/quarto-articles/brian-quarto.bib
---

The most famous result in social choice theory, the impossibility theorem due to Kenneth @Arrow1951, shows that if some structural conditions are met, any function for aggregating social preferences must treat people asymmetrically. In Arrow's case, the asymmetry is very strong; one person must be a dictator. In a forthcoming paper in *Noûs*, Jacob @Nebel2025 makes an argument with the same kind of structure. He shows that if certain structural conditions are met, anyone trying to act benevolently in the interest of people in general must treat people asymmetrically. In Nebel's case the result is not that there must be anything like a dictator, just that there must be asymmetric treatment.

The usual way to prove Arrow's theorem is to start with the plausible structural assumptions, and show that they entail the existence of a dictator. Nevertheless, it is not a particularly common inference from Arrow's theorem that, since the structural conditions are clearly true, we should have a dictator. Still, it is interesting to ask just which of the structural conditions should fail.

Nebel does argue that the structural conditions are true, and hence we should embrace asymmetry. I'm going to argue that would be a mistake, the same kind of mistake someone would be making if they accepted the structural conditions in Arrow's proof. As with Arrow's theorem, we should take the proof as a *reductio* of the assumptions.

The assumption I think fails in Nebel's case is that indifference is transitive. Amartya @Sen1970sec noted that this is also a load-bearing assumption in Arrow's theorem, and explored what would a theory that rejected it would look like. It turns out in that case rejecting the transitivity of indifference alone is not enough to get out of an intolerable result [@Gibbard2014]. Something similar will be true here; once transitivity of indifference goes some other principles will have to go too. But the idea that Sen had in response to Arrow's result is, I'll argue, the right response to Nebel's result.

The point is not just to defend the possibility of impartiality from Nebel's argument, important though that is. The central point is that cases like this provide a new kind of reason to reject the transitivity of indifference.

# Nebel's Paradox {#sec-nebel}

This section describes the argument that Nebel gives against the possibility of impartial beneficence.^[The main example in this argument draws on @Goodsell2021.] We have a world that includes a countable infinity of people, *a*~1~, *a*~2~, …, *b*~1~, *b*~2~, ….^[Actually all that matters is that these people are in the world. There could be other people who are not affected by any actions in what follows. I'll come back to this point. Each of these people has one of two possible welfare states, which we'll denote as 0 and 1.^[So while we will be interested in paradoxes involving unbounded good, none of these paradoxes are relevant to the maximisation of expected welfare for any individual.] We'll say an outcome is any assignment of a probability distribution of welfare payouts to each individual.^[This means that we're not going to consider what happens if the world population changes; that raises a whole host of different concerns.]

One of four lotteries will take place. The lotteries are shown in @tbl-nebel. In each lottery, there are two random devices that contribute to the determination of the state“. The first is a fair [red]{.text-red} coin which will be flipped once. The second is a fair coin that will be flipped indefinitely until it lands heads. We'll write [H]{.text-red} and [T]{.text-red} for the [red]{.text-red} coin landing heads and tails respectively, and H~*i*~ for the proposition that the other coin will be flipped *i* times. (For completeness, say that H~1~ also includes the possibility that it lands tails every time.) So we have the states shown in the top row of @tbl-nebel, with their probability below them. In each cell, we show the people who get payout 1 in that state from that lottery; everyone else gets payout 0.

::: {.column-screen-inset}
| Lottery | [H]{.text-red}H~1~ | [T]{.text-red}H~1~ | [H]{.text-red}H~2~ | [T]{.text-red}H~2~ | … | [H]{.text-red}H~*k*~ | [T]{.text-red}H~*k*~ | … |
|----:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| **Probability** | 1/4 | 1/4 | 1/8 | 1/8 | … | 1/2^*k*+1^ |  1/2^*k*+1^ | … |
| *P*  | *a*~1~, *a*~2~ | *a*~1~, *a*~2~ | *a*~1~ … *a*~4~ | *a*~1~ … *a*~4~ | … | *a*~1~ … *a*~2^*k*^~ | *a*~1~ … *a*~2^*k*^~ | … |
| *Q*  | *a*~1~, *a*~2~ | *b*~1~, *b*~2~ | *a*~1~ … *a*~4~ | *b*~1~ … *b*~4~ | … | *a*~1~ … *a*~2^*k*^~ | *b*~1~ … *b*~2^*k*^~ | … |
| *P*ʹ | *a*~1~, *a*~2~ | *a*~1~ … *a*~4~ | *a*~1~, *a*~2~ | *a*~1~ … *a*~8~ | … | *a*~1~, *a*~2~ | *a*~1~ … *a*~2^*k*+1^~ | … |
| *Q*ʹ | *a*~1~, *b*~1~ | *a*~1~, *a*~2~, *b*~1~, *b*~2~ | *a*~2~, *b*~2~ | *a*~1~ … *a*~4~, *b*~1~ … *b*~4~ | … | *a*~*k*-1~, *b*~*k*-1~ | *a*~1~ … *a*~2^*k*^~, *b*~1~ … *b*~2^*k*^~  | … |

: Nebel's example {#tbl-nebel}
:::

Now assume that that for each person *x* we have relations of strict welfare preference ≻~*x*~ and welfare indifference &#126;~*x*~. We also have a social welfare ordering, i.e., a pair of relations of strict preference ≻~∀~ and indifference \~~∀~. In Nebel's discussion, these are the preference orderings of a benevolent person. I think it's more intuitive to think of them as the preference orderings of a good state, but not much turns on this. Either way, they are a social ordering, in just the sense that Arrow was interested in, and they should relate to the individual orderings in some principled way.

We'll make the following assumptions:

- No matter the subscript, \~ is symmetric and ≻ is asymmetric;
- No matter the subscript, ≻ is transitive;
- For any individual *x*, &#126;~*x*~ is transitive;
- No matter the subscript, for any options *A* and *B*, *A* ≻ *B*, *A* \~ *B* and *B* ≻ *A* are exclusive and exhaustive.^[The last assumption I'll denote below as **I-completeness**.]
- Every individual prefers a higher probability of getting 1 to a lower probability, and is indifferent between any two states with the same probability of getting 1.

Nebel then derives a contradiction from the following principles.

Transitivity of Social Indifference
:    If *A* &#126;~∀~ *B* and *B* &#126;~∀~ *C* then *A* \~~∀~ *C*.

Pareto Indifference
:    If *A* &#126;~*x*~ *B* for all *x*, then *A* \~~∀~ *B*.

Pareto Strict Preference
:    If *A* ≻~*x*~ *B* for all *x*, then *A* ≻~∀~ *B*.

Pairwise Anonymity
:    For outcome *O* and individual *x*, write *O~x~* for the outcome individual *x* gets in *O*. For any outcomes *A* and *B* if there are two individuals *i* and *j* such that *A~i~* &#126;~*i*~ *B*~j~ and *A~j~* &#126;~*j*~ *B*~i~, and for all other individuals *h*, *A~h~* &#126;~*h*~ *B*~h~, then *A* &#126;~∀~ *B*.

Lottery Indifference
:    For any two lotteries *A* and *B* defined over the same partition of the possibilities in states, if in each state *A* &#126;~∀~ *B*, then prior to the lottery taking place, *A* &#126;~∀~ *B*.

The derivation involves proving *Q*ʹ ≻~∀~ *Q*, *Q* &#126;~∀~ *P*, *P* &#126;~∀~ *P*ʹ and *P*ʹ &#126;~∀~ *Q*ʹ.

First, to prove *Q*ʹ ≻~∀~ *Q*. Note that each individual has a higher probability of getting 1 in *Q*ʹ than *Q*. So *Q*ʹ ≻~*x*~ *Q* for all *x*, so by Pareto Strict Preference, *Q*ʹ ≻~∀~ *Q*.

Second, to prove *Q* &#126;~∀~ *P*. In each result of the lottery, the same number of people get 1. So in each state, a finite number of applications of Pairwise Anonymity plus one use of Pareto Indifference we have *Q* &#126;~∀~ *P* conditional on each state of the lottery. So by Lottery Indifference, *Q* &#126;~∀~ *P*.

Third, to prove *P* &#126;~∀~ *P*ʹ. Each individual has the same probability of getting 1 in each lottery, so each individual is indifferent between the lotteries, so by Pareto Indifference, *P* &#126;~∀~ *P*ʹ.

Fourth, to prove *P*ʹ &#126;~∀~ *Q*ʹ. Here it is the same reasoning as in step 2. No matter what lottery outcome we're in, the same number of people get payout 1 in *P*ʹ as *Q*ʹ, so by many (but in each state a finite number of) applications of Pairwise Anonymity plus one use of Pareto Indifference we have *Q* &#126;~∀~ *P* conditional on each state of the lottery. So by Lottery Indifference, *Q* &#126;~∀~ *P*.

Finally, by two applications of Transitivity of Indifference we get from *Q* &#126;~∀~ *P*, *P* &#126;~∀~ *P*ʹ, and *P*ʹ &#126;~∀~ *Q*ʹ to *Q* &#126;~∀~ *Q*ʹ, contradicting *Q*ʹ ≻~∀~ *Q*.

Nebel argues that the culprit here is Pairwise Anonymity. He argues that his means that a certain kind of impartial benevolence is impossible. I'm going to argue that it's really the transitivity assumption we should give up. The short version of my argument is going to be that (a) there are situations where the first four steps of this proof seem just like good reasoning, and (b) if we accept the transitivity of indifference, then not only can we prove the social welfare ordering does not treat everyone alike, we can prove that it has arbitrarily large differences in how it treats people. The latter seems unacceptable, particularly when we are thinking about how the state should allocate resources and risks across a population.

# Background Ideology {#sec-ideology}

There are two ways of presenting welfare orderings that get used in the literature, and they end up being helpful for different purposes.

One is to start with notions of *better than* and *exactly as good as*, where the latter is assumed to be an equivalence relation. This is I think the standard way to do things in contemporary philosophy. But there is an older notation that I will use here, because I think it turns out to be more useful.

Following @Sen1970sec, I'll write *xRy* for the claim that *x* is at least as good as *y*. More precisely, I'll understand it as the claim that *x* is choiceworthy when it and *y* are the available options. Using *R* we can define relations of strict indifference, *P*, and indifference, *I*, as the asymmetric and symmetric parts of *R*. We could also, if we like, define a relation of equality *E*, where *xEy* means that *x* and *y* stand in the same *R*-relations with respect to some space of options.^[Formally, *xEy* is true iff *xRx* and for all *z*, *xRz* \leftrightarrow *yRz*, and *zRx* \leftrightarrow *zRy*.] So defined, *E* is clearly an equivalence relation. But while *I* is by definition symmetric, it isn't obvious it is transitive.^[It also isn't obvious it is reflexive. I'll come back to this presently. Rejecting the transitivity of *I* does not give us a reason to reject the transitivity of *P*, as advocated by, e.g., @Temkin1987.]

The different notations naturally suggest slightly different understandings of what it is for a preference relation to be *complete*. If we start with a strict better than ≻, and a relation of exactly as good as that's assumed to be an equivalent relation, it's natural to write a relation of being preferred or equal as ⪰. And then it's natural to understand completeness as what I'll call **E-completeness**.

E-completeness
:    *x* ⪰ *y* ∨ *y* ⪰ *x*

In Nebel's paper he talks about how dropping completeness might be a way out of the problem, and by this he means, as I think most philosophers would these days, E-completeness. If we start with *R* as our basic notion, it's more natural to define completeness as what I'll call **I-completeness**.

I-completeness
:    *xRy* ∨ *yRx*

Both E-completeness and I-completeness can be stated as trichotomy theses.^[The language of trichotomy is taken from @Chang2002.] E-completeness is equivalent to *xPy* ∨ *xEy* ∨ *yPx*, while I-completeness is equivalent to *xPy* ∨ *xIy* ∨ *yPx*.

Assuming *P* is transitive, E-completeness is entailed by I-completeness and the transitivity of *I*. A reason to prefer starting with notions like *R* and *I* is that the last line suggests there are two quite distinct ways for E-completeness to fail. One is that I-completeness fails, and the other is that *I* is intransitive. And it might be useful to readily distinguish these two failure cases.

It is very common to assume *I* is complete, at least as an idealising assumption. There are really two prominent ways for *I* to fail to be complete. One is that the thinker simply has no attitude about (at least one of) *x* and *y*, perhaps because they don't have the capacity to think about them. Think about a subject who has never heard of Porepunkah or Tidbinbilla, and ask what preferences they have over a holiday in one or the other.^[I don't mean ask them; that might cause them to form attitudes. I mean ask whether they prefer one or the other before hearing about either. The reason I included *xRx* in the formal definition of *E* is so we wouldn't say *E* holds in cases where the agent has no attitude towards either relata.] It's natural to say that any positive claim about what preferences they have is false, so I-completeness fails. I-completeness might also fail if there are prudential dilemmas, where neither choice is acceptable.

The cases where I-completeness fails are very different from the cases where *I* appears to be intransitive. In the next section we'll look at some cases from the literature that have been argued to be counterexamples to transitivity.



One kind of case involves non-numerical probability. There is a long line of arguments from @Keynes1921 to @HajekHawthorneEtc arguing that some propositions do not have numerical probabilities. Let *p* be such a proposition, *x* a bet that pays 1 if *p* and 0 otherwise, and *y* a constant return of some value that the probability of *p* is neither strictly greater than nor strictly less than. The natural decision rules for non-numerical probability, as in e.g., @Williams201x, imply that 

The older case, first discussed by Wallace @Armstrong1939, starts with the assumption that perceptual discriminability is intransitive. There may be a Sorites series of cups of coffee with sugar where the subject cannot tell any two adjacent cups apart, and so is indifferent between any pair, but the last one is too sweet for the chooser, so they strictly prefer the first cup to the last cup. This looks like a good argument against the transitivity of indifference iff perceptual indiscriminability really is intransitive. If it is transitive, as Delia Graff @Fara2001 argues, then it is less compelling.

The other argument traces back to an example by Gerard @Debreu1960. Let *x* and *y* be very different options that the chooser is indifferent between, in the sense that they could happily choose either. Now let *x*^+^ be something that strictly improves *x*, e.g., it is *x* plus a dollar.^[Debreu describes an example like this but not this argument. I haven't been able to find anything I'd happily say is the first instance of this argument. I don't think the arguments in @Keynes1921 for non-numerical probability are quite of this form, though perhaps that's uncharitable.] Plausibly we have *xIy* and *yIx*^+^, but we definitely do not have *xIx*^+^. This is the kind of example that motivated @Sen1970sec to look for what happens to Arrow's impossibility theorem when we drop the assumption that indifference in the social ordering is transitive. Like Sen, I'll 
