---
title: "Desire as Belief and Moral Newcomb Problems"
description: |
  David Lewis [-@Lewis1988; -@Lewis1996] offered a formal argument against the view desiring something was equivalent to believing it to be good. There have been many objections to this argument. I'm going to offer a new objection that unifies some existing replies to Lewis. Lewis's formalism is ambiguous, and there is no way to disambiguate it without making one or other premise implausible. On one disambiguation, the objection that @Price1989 makes is unanswerable; on the other, the objection @Collins2015 makes is unanswerable. My first contribution is to show that Lewis can't avoid one or other of these objections. My second is to show that once we make the disambiguation, a new kind of philosophical puzzle arises. I call the puzzle a Moral Newcomb Problem, and suggest that it may be trickier to solve than familiar Newcomb Problems.
date: March 30 2024
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
citation: false
bibliography: ../../brian-quarto.bib
categories:
  - games and decisions
  - unpublished
format:
  html:
    css: ../trad_defn.css
    theme: dab-variant.scss
  docx: default
  pdf:
    output-file: "Four Problems in Decision Theory"
    include-after-body: 
      text: |
         Unpublished. Posted online in 2024.
---

The agent in standard versions of decision theory is characterised by two functions: a credence function and a value function. The credence function is meant to represent something like beliefs.^[Whether it represents partial beliefs about factual propositions, or full beliefs in propositions about probability is a tricky question we won't address here, though it parallels the questions we will address. See @Holton2013 for more on this point.] But what does the value function represent? One idea is that it represents something like desire. Indeed, on a broadly Ludovician view about the nature of propositional attitudes, to be a desire just is to be the (closest thing to being the) realiser of the cleaned up platitudes about desire [@Lewis1994bn]. And when those platitudes are cleaned up, they say that desires are what determine the value function in decision theory. So that's one picture: credences represent beliefs, or more generally belief-like states, and values represent desires, or more generally desire-like states.

In ordinary talk, we don't make a sharp distinction between valuing something and believing it is in some way good. When we say that our decider believes that A is good, it is natural to say they value A, and to assign a high value to V(A). One way to implement this idea is to deny that the value function represents desires. But a more common way, and the one I'll work with here, is to say that the desires just are beliefs about the good. This is the Desire as Belief thesis that Lewis [-@Lewis1988, -@Lewis1996] argues against.

Lewis gives a couple of versions of the argument against Desire as Belief, and the secondary literature gives many more. The argument in the first paper is agreed on all sides (including by Lewis in the second paper) to be needlessly complicated, but the argument in the second paper is incredibly condensed. But there's nothing like agreement on how to uncompress it. I'll start with a version of the argument that relies on relatively weak premises, and which helps make clear where the argument ultimately fails.^[It's going to fail because the V function is ambiguous, and there's no viable disambiguation of it.]

Assume our Hero, called Hero, has a credence function C and a value function V defined over a (finite) set of worlds.^[The restriction to finitely many worlds is potentially substantive, but it makes setting out the problem so much easier, and as far as I can tell, the complications that are added in the infinite case aren't relevant to this problem.] I'll use *w* as a variable for an arbitrary world. Since we want there to be distinct worlds for any way Hero thinks things might be, we need worlds to be more finely individuated than Ludovician concreta [@Chalmers2011m, @Mahtani2024]. For current purposes I'll take worlds to be pairs of concreta and what I'll call *assessments*.^[This way of setting things up owes a lot to @Collins2015.] An assessment is a function from concrete propositions to numerical values. (I'll say what a concrete proposition is in a second) Intuitively, it means how good things would be were that proposition actualised. So a world is a pair ⟨*c*, *f*⟩, where *c* is a concretum, and *f* is a function from concrete propositions to reals. The value of that world is *f*(\{*c*\}). A proposition is a set of worlds. A proposition A is concrete iff for any concretum *c*, and any two functions *f* and *g*, ⟨*c*, *f*⟩ ∈ A iff ⟨*c*, *g*⟩ ∈ A. That is, concrete propositions are only about how the concrete worlds are, in the sense of aboutness from @Lewis1982c.

We'll now show that four somewhat natural principles are incompatible. In what follows, P is Hero's credence function, V is Hero's value function, w is an arbitrary world, and A and B refer to arbitrary concrete propositions. P~A~ and V~A~ are the credence and value functions after updating on A. Finally, A~*x*~ is {⟨*c*, *f*⟩: *f*(A) = *x*}. That is, A~*x*~ is the proposition that the value of A is *x*.

Ludovician Desire as Belief
:    If A is concrete, then V(A) = Σ~*x*~ *x*P(A~*x*~).

Worldly Value
:    V(\{⟨*c*, *f*⟩\}) = *f*(\{⟨*c*, *f*⟩\})

Value Additivity
:    V(A) = Σ~*w*~ V(\{w\})C(\{w\} | A)

Restricted Conditionalisation
:    P~A~(B) = P(B | A)

We assume all of these hold after updating. The 'restricted' in **Restricted Conditionalisation** is because we're only assuming tha conditionalisation is the way to update on concrete propositions. As Lewis himself notes, it isn't obvious that it's the right way to update for centered-world propositions, and for similar reasons, we should be hesitant to assume that it's the right way to update for propositions that take a stance on value. 

**Worldly Value** says that to find the value of the proposition true at just that world, you just look at what the value assignment that partially constitutes the world says about the proposition that's true just there. If that wasn't true, it wouldn't really make sense to call it a *value* assignment. And note that **Worldly Value** entails a principle I'll call **Restricted Invariance**. This is going to be the only point I'll use **Worldly Value**.

Restricted Invariance
:    V~A~(\{w\}) = V(\{w\})

The proof is that since the right-hand-side of **Worldly Value** doesn't contain anything that varies at all, it just contains things that are fixed by the nature of w itself. Invariance has been often cited as the bug in Lewis's argument, but I think that's a mistake. The argument for the version of **Restricted Invariance** (which is all Lewis uses) that he gives on the final page of the 1988 paper looks pretty good. And it's the argument I've formalised here with **Worldly Value** as the starting point.

::: {.column-page}
|     |     |      |
|----:|:----|:-----|
| Σ~*x*~ *x*P(A~*x*~) | = V(A) | (Ludovician Desire as Belief) |
|     | = Σ~*w*~ V(\{w\})C(\{w\} \| A) | (Value Additivity) |
|     | = Σ~*w*~ V~A~(\{w\})C(\{w\} \| A) | (Restricted Invariance) |
|     | = Σ~*w*~ V~A~(\{w\})C~A~(\{w\}) | (Restricted Conditionalisation) |
|     | = V~A~(A) | (Value Additivity), after updating on A |
|     | = Σ~*x*~ *x*P~A~(A~*x*~) | (Ludovician Desire as Belief), after updating on A |
|     | = Σ~*x*~ *x*P(A~*x*~ \| A) | (Restricted Conditionalisation), after updating on A |
:::

If we make the extra simplifying assumption that *f* is always a binary function that maps bad outcomes to 0 and good outcomes to 1, we can identify for each concrete proposition A, an evaluative proposition Å which is \{⟨*c*, *f*⟩: *f*(A) = 1\}. And then the result of the proof is that Å and A are probabilistically independent. It's a bit absurd to think that there are only two possible values, so it's better to think through the general version which says that the expected goodness of A is independent of A.

Lewis's own version of the argument continues from here to derive odd results from this independence claim. But we shouldn't follow him down that route for several reasons. One is that the extra derivations require assumptions that seem much more dubious than he's already used. In particular, he needs an unconditional version of conditionalisation. For another, as far as I can tell, everyone of his actual opponents either rejects Ludovician Desire as Belief as the way to state their view, or rejects independence. And most importantly of all, the independence view seems on the face of it quite implausible.

