---
title: "Intrinsic Properties and Combinatorial Principles"
description: |
  Three objections have recently been levelled at the analysis of intrinsicness offered by Rae Langton and David Lewis. While these objections do seem telling against the particular theory Langton and Lewis offer, they do not threaten the broader strategy Langton and Lewis adopt: defining intrinsicness in terms of combinatorial features of properties. I show how to amend their theory to overcome the objections without abandoning the strategy.
date: September 1 2001
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
doi: "10.1111/j.1933-1592.2001.tb00110.x"
citation:
  type: article-journal 
  container-title: "Philosophy and Phenomenological Research"
  volume: 63
  issue: 2
  page: "365-380"
format:
  html: default
  pdf:
    output-file: "Intrinsic Properties and Combinatorial Principles"
    reference-location: document
---

Three objections have recently been levelled at the analysis of intrinsicness in Rae Langton and David Lewis's "Defining 'Intrinsic'". @Yablo1993 has objected that the theory rests on "controversial and (apparently) irrelevant" judgements about the relative naturalness of various properties. Dan Marshall and Josh Parsons @Marshall2001 have argued that quantification properties, such as *being accompanied by an cube*, are counterexamples to Langton and Lewis's theory. And Theodore Sider @Sider2001 has argued that maximal properties, like *being a rock*, provide counterexamples to the theory. In this paper I suggest a number of amendments to Langton and Lewis's theory to overcome these counterexamples. The suggestions are meant to be friendly in that the basic theory with which we are left shares a structure with the theory proposed by Langton and Lewis. However, the suggestions are not meant to be *ad hoc* stipulations designed solely to avoid theoretical punctures, but developments of principles that follow naturally from the considerations adduced by Langton and Lewis.

<aside>
Thanks to David Lewis, Europa Malynicz, Dan Marshall, Daniel Nolan, Josh Parsons and Ted Sider for helpful discussions.
</aside>

# Langton and Lewis's Theory

Langton and Lewis base their theory on a combinatorial principle about intrinsicness. If a property *F* is intrinsic, then whether a particular object is *F* is independent whether there are other things in the world. This is just a specific instance of the general principle that if *F* is intrinsic then whether some particular is *F* is independent of the way the rest of the world is. So if *F* is intrinsic, then the following four conditions are met:

1.  Some lonely object is *F*;
2.  Some lonely object is not-*F*;
3.  Some accompanied object is *F*; and
4.  Some accompanied object is not-*F*.

The quantifiers in the conditions range across objects in all possible worlds, and indeed this will be the quantifier domain in everything that follows (except where indicated). An object is 'lonely' if there are no wholly distinct contingent things in its world. The effect of including 'distinct' in this definition is that an object can be lonely even if it has proper parts; an object is not identical with its parts, but nor is it distinct from them. Following Langton and Lewis, I will say that any property that meets the four conditions is 'independent of accompaniment'.

All intrinsic properties are independent of accompaniment, but so are some extrinsic properties. For example, the property *being the only round thing* is extrinsic, but independent of accompaniment. So Langton and Lewis do not say that independence of accompaniment is sufficient for intrinsicness. However, within a certain class of properties, what we might call the *basic* properties, they do say that any property independent of accompaniment is intrinsic. A property is *basic* if it is neither *disjunctive* nor the negation of a disjunctive property. Langton and Lewis define the disjunctive properties as follows:

> \[L\]et us define the *disjunctive* properties as those properties that can be expressed by a disjunction of (conjunctions of) natural properties; but that are not themselves natural properties. (Or, if naturalness admits of degrees, they are much less natural than the disjuncts in terms of which they can be expressed.) @Lewis2001Langton

Langton and Lewis assume here that there is some theory of naturalness that can be plugged in here, but they are explicitly ecumenical about what the theory may be. They mention three possibilities: naturalness might be primitive; it might be defined in terms of which universals and tropes exist, if you admit such into your ontology; or it might be defined in terms of which properties play a special role in our theory. Call the first the primitivist conception, the second the ontological conception, and the third the pragmatic conception. (One can generate different versions of the pragmatic theory by altering what one takes to be 'our theory'. In @Taylor1993, which Langton and Lewis credit as the canonical statement of the pragmatic conception, naturalness is relativised to a theory, and the theories he focuses on are 'regimented common sense' and 'unified science'.) Langton and Lewis's intention is to be neutral as to the correct interpretation of naturalness whenever they appeal to it, and I will follow their policy.

With these concepts, we can now define intriniscness. A property is *basic intrinsic* iff it is basic and independent of accompaniment. Two objects are *duplicates* iff they have the same basic intrinsic properties. And a property is *intrinsic* iff there are no two duplicates that differ with respect to it.

Langton and Lewis make one qualification to this definition: it is only meant to apply to *pure*, or qualitative, properties, as opposed to *impure*, or haeccceitistic, properties. One reason for this restriction is that if there are any impure intrinsic properties, such as *being John Malkovich*, they will not have the combinatorial features distinctive of pure intrinsic properties. If *F* is a pure intrinsic property then there can be two wholly distinct things in a world that are *F*. This fact will be crucial to the revised definition of intrinsicness offered below. However, it is impossible to have wholly distinct things in the same world such that each is John Malkovich. So for now I will follow Langton and Lewis and just say what it takes for a pure property to be intrinsic. As Langton and Lewis note, it would be nice to complete the definition by giving conditions under which impure properties are intrinsic, but the little task of working out the conditions under which pure properties are intrinsic will be hard enough for now.

# Three Objections

Stephen Yablo [@Yablo1993] criticises the judgements of naturalness on which this theory rests. Consider again the property *being the only round thing*, which is extrinsic despite being independent of accompaniment. If Langton and Lewis are right, this must not be a basic property. Indeed, Langton and Lewis explicitly say that it is the negation of a disjunctive property, since its negation can be expressed as: *being round and accompanied by a round thing or being not-round*. Yablo's criticism is that it is far from obvious that the existence of this expansion shows that *being the only round thing* is disjunctive. For simplicity, let us name all the salient properties: 

> *R* =~df~ being the only round thing  
> *S* =~df~ being not the only round thing  
> *T* =~df~ being round and accompanied by a round thing  
> *U* =~df~ being not-round  

(Something is accompanied by an *F* iff one of its distinct worldmates is *F*.) Langton and Lewis claim that since *S* = *T* ${\vee}$ *U*, and *S* is much less natural than *T* and than *U*, *S* is disjunctive, so *R* is not basic. Yablo notes that we can also express *S* as *being round if accompanied by a round thing*, so it differs from *T* only in that it has an *if* where *T* has an *and*. Given this expansion, we should be dubious of the claim that *S* is much less natural than *T*. But without that claim, *R* already provides a counterexample to Langton and Lewis's theory, unless there is some other expression of *R* or *S* that shows they are disjunctive.[^1]

[^1]: It would be no good to say that Langton and Lewis should be more liberal with their definition of disjunctiveness, and say instead that a property is disjunctive iff it can be expressed as a disjunction. Any property *F* can be expressed as the disjunction *F* *and G* *or F and not G*, or for that matter, *F or F*, so this would make every property disjunctive.

    I do not want to dismiss out of hand the possibility that there is another expression of *S* that shows it is disjunctive. Josh Parsons suggested that if we define *T*$^\prime$ to be *being accompanied by a round thing*, then *S* is *T*$^\prime$ ${\vee}$ *U*, and there is some chance that *T*$^\prime$ is more natural than *S* on *some* conceptions of naturalness. So we cannot derive a decisive counterexample from Yablo's discussion. Still, Langton and Lewis need it to be the case that on any account of naturalness, there is an expression that shows *S* or *R* to be disjunctive, and unless *T*$^\prime$ is much more natural than *S* on *all* conceptions of naturalness, this task is still far from complete.

Dan Marshall and Josh Parsons @Marshall2001 argue that the same kind of difficulties arise when we consider certain kinds of quantificational properties. For example, let *E* be the property *being such that a cube* *exists*. This is independent of accompaniment, since a lonely cube is *E*, a lonely sphere is not *E*, each of us is accompanied and *E*, and each of Max Black's two spheres is accompanied and not *E*. So it is a counterexample to Langton and Lewis if it is basic. Marshall and Parsons note that, like all properties, it does have disjunctive expressions. For example *x* is *E* iff *x* is a cube or *x* is accompanied by a cube. And *E* is a less natural property than *being a cube*. But it is not at all intuitive that *E* is much less natural than the property *being accompanied by a cube*. This does not just show that Langton and Lewis have to cease being ecumenical about naturalness, because on some conceptions of naturalness it is not clear that *E* is much less natural than *being accompanied by a cube*. Rather, this example shows that there is no conception of naturalness that could play the role that Langton and Lewis want. The properties *E* and *being accompanied by a cube* seem just as natural as each other on the ontological conception of naturalness, on the pragmatic conception of naturalness, and, as far as anyone can tell, on the primitivist conception. This is not because *E* is particularly natural on any of these conceptions. It certainly does not, for example, correspond to a universal, and it does not play a special role in our thinking or in ideal science. But since there is no universal for *being accompanied by a cube*, and that property does not play a special role in our thinking or in ideal science, it seems likely that each property is as natural as the other.

Theodore @Sider2001 notes that similar problems arise for *maximal* properties, like *being a rock*. A property *F* is maximal iff large parts of *F*s are typically not *F*s. For example, *being a house* is maximal; a very large part of a house, say a house minus one window ledge, is not a house, it is just a large part of a house. Purported proof: call the house minus one window ledge house-. If Katie buys the house she undoubtedly buys house-, but she does not thereby buy two houses, so house- is not a house. As Sider notes, this is not an entirely conclusive proof, but it surely has some persuasive force. Maximal properties could easily raise a problem for Langton and Lewis's definition. All maximal properties are extrinsic; whether *a* is a house depends not just on how *a* is, but on what surrounds *a*. Compare: House- would be a house if the extra window ledge did not exist; in that case it would be *the* house that Katie buys. But some maximal properties are independent of accompaniment. *Being a rock* is presumably maximal: large parts of rocks are not rocks. If they were then presumably tossing one rock up into the air and catching it would constitute juggling seventeen rocks, making an apparently tricky feat somewhat trivial. But there can be lonely rocks. A rock from our planet would still be a rock if it were lonely. Indeed, some large rock parts that are not rocks would be rocks if they were lonely. And it is clear there are be lonely non-rocks (like our universe), accompanied rocks (like Uluru) and accompanied non-rocks (like me).

Since *being a rock* is independent of accompaniment and extrinsic, it is a counterexample if it is basic. Still, one might think it is not basic. Perhaps *being a rock* is not natural on the primitivist conception. (Who is to say it is?) And perhaps it does not correspond to a genuine universal, or to a collection of tropes, so it is a disjunctive property on the ontological conception of naturalness. Sider notes, however, that on at least one pragmatic conception, where natural properties are those that play a special role in regimented common sense, it does seem particularly natural. Certainly it is hard to find properties such that *being a rock* can be expressed as a disjunction of properties that are more central to our thinking than *being a rock*. So this really does seem to be a counterexample to Langton and Lewis's theory.

# The Set of Intrinsic Properties

It is a platitude that a property *F* is intrinsic iff whether an object is *F* does not depend on the way the rest of the world is. Ideally this platitude could be morphed into a definition. One obstacle is that it is hard to define *the way the rest of the world is* without appeal to intrinsic properties. For example, even if *F* is intrinsic, whether *a* is *F* is not independent of whether other objects have the property *not being accompanied by an F*, which I will call *G*. To the extent that having *G* is a feature of the way the rest of the world is, properties like *G* constitute counterexamples to the platitude. Since platitudes are meant to be interpreted to be immune from counterexamples, it is wrong to interpret the platitude so that *G* is a feature of the way the rest of the world is. The correct interpretation is that *F* is intrinsic iff whether an object is *F* does not depend on which *intrinsic* properties are instantiated elsewhere in the world.

If what I call the independence platitude is to be platitudinous, we must not treat independence in exactly the same way as Langton and Lewis do. On one definition, whether *a* is *F* is independent of whether the rest of the world is *H* iff it is possible that *a* is *F* and the rest of the world *H*, possible that *a* is not-*F* and the rest of the world *H*, possible that *a* is *F* and the rest of the world not-*H*, and possible that *a* is not-*F* and the rest of the world not-*H*. On another, whether *a* if *F* is independent of whether the rest of the world is *H* iff whether *a* is *F* is entirely determined by the way *a* itself, and nothing else, is, and whether the rest of the world is *H* is determined by how it, and not *a*, is. This latter definition is very informal; hence the need for the formal theory that follows. But it does clearly differ from the earlier definition in a couple of cases. The two definitions may come apart if *F* and *H* are excessively disjunctive. More importantly, for present purposes, they come apart if *F* is the necessary property (that everything has), or the impossible property (that nothing has). In these cases, whether *a* is *F* is entirely settled by the way *a*, and nothing else is, so in the latter sense it is independent of whether the rest of the world is *H*. But it is not the case that all four possibilities in the former definition are possible, so it is not independent of whether the rest of the world is *H* in that sense. Since there is some possibility of confusion here, it is worthwhile being clear about terminology. When I talk about independence here, I will always mean the latter, informal, definition, and I will refer to principles about which combinations of intrinsic properties are possible, principles such as Langton and Lewis's principle that basic intrinsic properties are independent of accompaniment, as combinatorial principles. So, in the terminology I am using, the combinatorial principles are attempts to formally capture the true, but elusive, independence platitude with which I opened this section.

Since the platitude is a biconditional with *intrinsic* on either side, it will be a little tricky to morph it into a definition. But we can make progress by noting that the platitude tells us about relations that hold between some intrinsic properties, and hence about what the set of intrinsic properties, which I will call *SI*, must look like.

For example, from the platitude it follows that *SI* is closed under Boolean operations. Say that *F* and *G* are intrinsic. This means that whether some individual *a* is *F* is independent of how the world outside *a* happens to be. And it means that whether *a* is *G* is independent of the way the world outside *a* happens to be. This implies that whether *a* is *F and G* is independent of the way the world outside *a* happens to be, because whether *a* is *F and G* is a function of whether *a* is *F* and whether *a* is *G*. And that means that *F and G* is intrinsic. Similar reasoning shows that *F or G*, and *not F* are also intrinsic. Call this condition *Boolean closure*.

Another implication of the independence platitude is that *SI* must be closed under various mereological operations. If *F* is intrinsic then whether *a* is *F* is independent of the outside world. If some part of *a* is *F*, that means, however the world outside that part happens to be, that part will be *F*. So that means that however the world outside *a* is, *a* will have a part that is *F*. Conversely, if *a* does not have a part that is *F*, that means all of *a*'s parts are *not F*. As we saw above, if *F* is intrinsic, so is *not F*. Hence it is independent of the world outside *a* that all of its parts are *not F*. That is, it is independent of the world outside *a* that *a* does not have a part that is *F*. In sum, whether *a* has a part that is *F* is independent of how the world outside *a* turns out to be. And that means *having a part that is F* is intrinsic. By similar reasoning, the property *Having n parts that are F* will be intrinsic if *F* is for any value of *n*. Finally, the same reasoning shows that the property, *being entirely composed of n things that are each F* is intrinsic if *F* is intrinsic. The only assumption used here is that it is independent of everything outside *b* that *b* is entirely composed of the particular things that it is composed of, but again this seems to be a reasonable assumption. So, formally, if *F* ${\in}$ *SI*, then *Having n parts that are F* ${\in}$ *SI*, and *Being entirely composed of n things that are F* ${\in}$ *SI*. Call this condition *mereological closure*.

Finally, and most importantly, various combinatorial principles follow from the independence platitude. One of these, that all intrinsic properties are independent of accompaniment, forms the centrepiece of Langton and Lewis's theory. The counterexamples provided by Marshall and Parsons, and by Sider, suggest that we need to draw two more combinatorial principles from the platitude. The first is that if *F* and *G* are intrinsic properties, then whether some particular object *a* is *F* should be independent of how many other things in the world are *G*. More carefully, if *F* and *G* are intrinsic properties that are somewhere instantiated then, for any *n* such that there is a world with *n*+1 things, there is a world constituted by exactly *n*+1 pairwise distinct things, one of which is *F*, and the other *n* of which are all *G*. When I say the world is constituted by exactly *n*+1 things, I do not mean that there are only *n*+1 things in the world; some of the *n*+1 things that constitute the world might have proper parts. What I mean more precisely is that every contingent thing in the world is a fusion of parts of some of these *n*+1 things. Informally, every intrinsic property is not only independent of accompaniment, it is independent of accompaniment by every intrinsic property. As we will see, this combinatorial principle, combined with the Boolean closure principle, suffices to show that Marshall and Parsons's example, *being such that a cube exists*, is extrinsic.

Sometimes the fact that a property *F* is extrinsic is revealed by the fact that nothing that is *F* can be worldmates with things of a certain type. So the property *being lonely* is extrinsic because nothing that is lonely can be worldmates with anything at all. But some extrinsic properties are perfectly liberal about which other properties can be instantiated in their world; they are extrinsic because their satisfaction excludes (or entails) the satisfaction of other properties in their immediate neighbourhood. Sider's maximal properties are like this. That *a* is a rock tells us nothing at all about what other properties are instantiated in *a*'s world. However, that *a* is a rock does tell us something about what happens around *a*. In particular, it tells us that there is no rock enveloping *a*. If there were a rock enveloping *a*, then *a* would not be a rock, but rather a part of a rock. If *being a rock* were intrinsic, then we would expect there could be two rocks such that the first envelops the second.[^2] The reason that *being a rock* is extrinsic is that it violates this combinatorial principle. (As a corollary to this, a theory which ruled out *being a rock* from the class of the intrinsic just because it is somehow unnatural would be getting the right result for the wrong reason. *Being a rock* is not a property like *being a lonely electron or an accompanied non-electron* that satisfies the independence platitude in the wrong way; rather, it fails to satisfy the independence platitude, and our theory should reflect this.)

[^2]: I assume here that there are rocks with rock-shaped holes in their interior. This seems like a reasonable assumption, though without much knowledge of geology I do not want to be too bold here.

So we need a second combinatorial principle that rules out properties like *being a rock*. The following principle does the job, although at some cost in complexity. Assume there is some world *w*~1~, which has some kind of spacetimelike structure.[^3] Let *d*~1~ and *d*~2~ be shapes of two disjoint spacetimelike regions in *w*~1~ that stand in relation *A*. Further, suppose *F* and *G* are intrinsic properties such that in some world there is an *F* that wholly occupies a region with shape *d*~1~, and in some world, perhaps not the same one, there is a *G* that wholly occupies a region with shape *d*~2~. By 'wholly occupies' I mean that the *F* takes up all the 'space' in *d*~1~, and does not take up any other 'space'. (There is an assumption here that we can identify shapes of spacetimelike regions across possible worlds, and while this assumption seems a little contentious, I hope it is acceptable in this context.) If *F*, *G*, *d*~1~, *d*~2~ and *A* are set up in this way, then there is a world where *d*~1~ and *d*~2~ stand in *A*, and an *F* wholly occupies a region of shape *d*~1~ in that world, and a *G* wholly occupies a region of shape *d*~2~ in that world. In short, if you could have an *F* in *d*~1~, and you could have a *G* in *d*~2~, and *d*~1~ and *d*~2~ could stand in *A*, then all three of those things could happen in one world. This kind of combinatorial principle has been endorsed by many writers on modality (for example Lewis 1986 and Armstrong 1989), and it seems something we should endorse in a theory on intrinsic properties.

[^3]: Perhaps all worlds have some kind of spacetimelike structure, in which case this qualification is unnecessary, but at this stage it is best not to take a stand on such a contentious issue.

In sum, the set of intrinsic properties, *SI*, has the following four properties:

\(B\)
:   If *F* ${\in}$ *SI* and *G* ${\in}$ *SI* then *F and G* ${\in}$ *SI* and *F or G* ${\in}$ *SI* and *not F* ${\in}$ *SI*.

\(M\)
:   If *F* ${\in}$ *SI* then *Having n parts that are F* ${\in}$ *SI* and *Being entirely composed of exactly n things that are F* ${\in}$ *SI*.

\(T\)
:   If *F* ${\in}$ *SI* and *G* ${\in}$ *SI* and there is a possible world with *n*+1 pairwise distinct things, and something in some world is *F* and something in some world is *G*, then there is a world with exactly *n*+1 pairwise distinct things such that one is *F* and the other *n* are *G*.

\(S\)
:   If *F* ${\in}$ *SI* and *G* ${\in}$ *SI* and it is possible that regions with shapes *d*~1~ and *d*~2~ stand in relation *A*, and it is possible that an *F* wholly occupy a region with shape *d*~1~ and a *G* wholly occupy a region with shape *d*~2~, then there is a world where regions with shapes *d*~1~ and *d*~2~ stand in *A*, and an *F* wholly occupies the region with shape *d*~1~ and a *G* wholly occupies the region with shape *d*~2~.

Many other sets than *SI* satisfy (B), (M), (T) and (S). That is, there are many sets *I~k~* such that each condition would still be true if we were to substitute *I~k~* for *SI* wherever it appears. Say that any such set is an *I*-set. Then *F* is intrinsic only if *F* is an element of some *I*-set. Is every element of every *I*-set intrinsic? As we will see, sadly the answer is *no*. However, most of the counterexamples proposed to Langton and Lewis's theory are not elements of any *I*-set, so we already have the resources to show they are extrinsic.

# Responding to Counterexamples

Marshall and Parsons noted that *E*, the property *being such that a cube exists*, is independent of accompaniment. However, it is not part of any *I*-set. To see this, assume it is in *I~k~*, which is an *I*-set. By (B), *not E* is also in *I~k~*. So by (T), there is a world where something is *E*, and there are two things, one of which is *E* and the other of which is *not* *E*. But clearly this cannot be the case: if something in a world is *E*, so is everything else in the world. Hence *I~k~* cannot be an *I*-set, contrary to our assumption. Intuitively, *E* is extrinsic because whether it is satisfied by an individual is not independent of whether other individuals satisfy it.

Some other quantificational properties, such as *being one of at most seventeen cubes*, require a different argument to show that they are not in any *I*-set. Call that property *E17*. (Note, by the way, that *E17* is independent of accompaniment, and not obviously disjunctive.) If *E17* is in an *I*-set, then by (T) there is a world containing exactly 18 things, each of which is *E17*. But this is clearly impossible, since everything that is *E17* is a cube, and everything that is *E17* is in a world containing at most seventeen cubes. So *E17* is not in any *I*-set, and hence is extrinsic. Similarly, *being the only round thing* cannot be in an *I*-set, because if it were by (T) there would be a world in which two things are the only round thing, which is impossible. So a definition of intrinsicness in terms of *I*-sets need not make the odd postulations about naturalness that Yablo found objectionable.

Assume, for *reductio*, that *being a rock* is in an *I*-set. There is a rock that is roughly spherical, and there is a rock that has a roughly spherical hollow in its interior. (Actually, there are many rocks of each type, but we only need one of each.) Let *d*~1~ be the region the first rock takes up, and assume that the shape of the hollow in the second is also *d*~1~. If it is not, we could always find another rock with a hollow this shape, so the assumption is harmless. Let *d*~2~ be the region the second rock, the one with this nicely shaped hollow, takes up. If *being a rock* is an *I*-set, then by (S) there is a world where *d*~2~ exactly surrounds *d*~1~, there is a rock wholly occupying *d*~1~ and a rock wholly occupying *d*~2~. But this is impossible; if there were rock-like things in both *d*~1~ and *d*~2~, they would both be parts of a single large rock, that extends outside both *d*~1~ and *d*~2~ and if there were not a rock-like thing in one or the other region, then there would not be a rock in that region. So no set satisfying (S) contains *being a rock*, so that property is not in any *I*-set, and hence is extrinsic.

The first extrinsic property independent of accompaniment that Langton and Lewis consider is *CS*: *being spherical and lonely or cubical and accompanied*. This too is not in any *I*-set. Again, assume for reductio that it is. In the actual world, there are (accompanied) cubes that are entirely composed of eight smaller cubes. Both the large cube and the eight smaller cubes are accompanied, so they are both *CS*. Hence there is a *CS* that is entirely composed of eight things that are *CS*. By (M), *being entirely composed of exactly eight things that are CS* is in the *I*-set. By (B), *being CS and entirely composed of exactly eight things that are CS* is in the *I*-set. So by (T), there is a world in which something has that property, and there is nothing else. (To see that (T) entails this, let *G* be any element of the *I*-set, and let *n* be zero.) That is, there is a lonely *CS* that is composed of eight things that are *CS*. But this is impossible. A lonely *CS* is a sphere, but its eight parts are not lonely, and are *CS*, so they must be cubes. And no sphere is entirely composed of exactly eight cubes. So *CS* cannot be in an *I*-set, and hence is extrinsic.

# Problem Cases and Disjunctive Properties {#sec-problem}

Those five successes might make us think that only intrinsic properties are ever in *I*-sets. However there are still some extrinsic properties that can slip into *I*-sets. For an example, consider the property *LCS*, defined as follows:

> *x* is *LCS* ${\leftrightarrow}$ (*x* is cubical and not both lonely and simple) or (*x* is lonely, simple and spherical)

The smallest set containing *LCS* and satisfying (B) and (M) is an *I*-set. There is an important reason for this. Define a *simple world* as a world containing just one mereological simple, and a compound world as a world that is not a simple world. Whether a property satisfies (T) and (S) (or, more precisely, whether a set containing that property can satisfy (T) and (S)) depends on just how the property interacts with other properties in compound worlds and whether it is ever instantiated in simple worlds. Since the same things are *LCS* as are cubical in compound worlds, these two properties, *LCS* and *being cubical*, interact with other properties in compound worlds in the same way. And each property is instantiated in simple worlds, although they are instantiated in different simple worlds. In sum, the properties are similar enough to be indistinguishable by (T) and (S), and that means we will not be able to show that *LCS* is extrinsic using just those considerations.

Any property that agrees with an intrinsic property, like *being cubical*, in the compound worlds, and is somehow extended so it is instantiated in simple worlds, will be in an *I*-set. This is not just because we have not put enough restrictions on what makes an *I*-set. There are just no combinatorial principles we could deduce from the independence platitude that *LCS* violates. This is because any such principle would, like (T) and (S), be satisfied or not depending just on how the property interacts with other properties in worlds where there are things to interact with, i.e. the compound worlds, and whether it is instantiated in the simple worlds. It is to the good that our deductions from the independence platitude did not show that *LCS* is extrinsic, because in an important sense *LCS*, like all properties that agree with some intrinsic property in all compound worlds, satisfies the platitude.

So at this point appeal to disjunctive and non-disjunctive properties is needed. Intuitively, intrinsic properties are not only capable of being instantiated in all possible combinations with other intrinsic properties, they are capable of being so instantiated in *the same way* in all these possible combinations. We need to distinguish between the disjunctive and the non-disjunctive properties in order to say which properties are instantiated the same way in all these different combinations.

It might be thought at this stage that we could just adopt Langton and Lewis's definition of the disjunctive properties. If that definition worked, we could say the basic intrinsic properties are the non-disjunctive properties that are in *I*-sets, then define duplication and intrinsicness as they do in terms of basic intrinsics. The definition does not, it seems, work as it stands because it does not show that *LCS* is disjunctive. This will be easier to follow if we name all the components of *LCS*, as follows: 

> *C* =~df~ being cubical  
> *L* =~df~ being lonely  
> *M* =~df~ being simple  
> *H* =~df~ being spherical  
> *LCS* =~df~ (*C* $\wedge \neg$(*L* $\wedge$ *M*)) $\vee$ (*L* $\wedge$ *C* $\wedge$ *H*)

Let us agree that *LCS* is not a natural property, if naturalness is an on/off state, or is very unnatural, if naturalness comes in degrees. On Langton and Lewis's first definition, it is disjunctive if it is a disjunction of conjunctions of natural properties. This seems unlikely: ${\neg}$(*L* $\wedge$ *M*) is not a natural property. This is the property of *being in a compound world*, hardly a natural property. Similarly, *C* $\wedge \neg$(*L* $\wedge$ *M*), *being a cube in a compound world*, is hardly natural either. We could insist that these properties are natural, but at this point Yablo's complaint, that clear facts like the extrinsicness of *LCS* are being made to rest on rather obscure facts, like the putative naturalness of *being in a compound world*, returns to haunt us. (I assume, for the sake of the argument, that *L* $\wedge$ *M* $\wedge$ *H* is a natural property, though this assumption could be easily questioned.) On the second definition, *LCS* is disjunctive if it is much less natural than ${\neg}$(*L* & *M*), or than *C* $\wedge \neg$(*L* $\wedge$ *M*). Again, it seems unlikely that this is the case. These properties seem rather unnatural. I have defined enough terms that we can state in the lexicon of this paper just what ${\neg}$(*L* $\wedge$ *M*) amounts to, i.e. *being in a compound world*, but the apparent simplicity of this definition should not make us think that the properties are natural. It is true in natural languages that predicates that are easy to express are often natural, but this fact does not extend across to the technical language that is employed here.

The way out is to change the definition of disjunctive properties. A property is disjunctive, intuitively, if it can be instantiated in two quite different ways. Most properties of the form: (*N*~1~ $\wedge$ *U*~1~) ${\vee}$ (*N*~2~ $\wedge$ *U*~2~), where *N*~1~ and *N*~2~ pick out distinct (relatively) natural properties, and *U*~1~ and *U*~2~ pick out distinct (relatively) unnatural properties that are independent of *N*~1~ and *N*~2~, will be like this. If we name this predicate *F*, there will be two quite different types of *F*s: those that are *N*~1~ and those that are *N*~2~. Note that this will be true no matter how unnatural *U*~1~ and *U*~2~ are; provided some *F*s are *N*~1~, and some are *N*~2~, there will be these two ways to be *F*. So I suggest we amend Langton and Lewis's definition of disjunctiveness as follows:

> A property *F* is disjunctive iff it can be expressed as a disjunction of conjunctions, i.e.: (*A*~11~ $\wedge$ ... $\wedge$ *A*~1*n*~) ${\vee}$ ... ${\vee}$ (*A~k~*~1~ $\wedge$ ... $\wedge$ *A~km~*) and in each disjunct, at least one of the conjuncts is much more natural than *F*.

On this definition it is clear that *LCS* is disjunctive, since it is much less natural than *being cubical* and than *being spherical*, and in its expression above, *being cubical* is one of the conjuncts in the first disjunct, and *being spherical* is one of the conjuncts in the second disjunct. These kinds of comparisons of naturalness do not seem contentious, or any less obvious than the conclusions about extrinsicness we use them to generate. Further, the new definition of disjunctiveness is not meant to be an *ad hoc* fix. Rather this requirement that only one conjunct in each disjunct need be much more natural than *F* seems to follow directly from the reason we introduced the concept of disjunctiveness to begin with. For each *F* that satisfies the combinatorial principle (either independence of accompaniment in Langton and Lewis's theory, or being in an *I*-set in my theory), we wanted to know whether it only does this because there are two or more ways to be an *F*. If *F* satisfies the definition of disjunctiveness I offer here, it seems there are two or more ways to be an *F*, so the fact that it can be in an *I*-set should not lead us to believe it is intrinsic.

Using this definition of disjunctiveness, we can say that the basic intrinsic properties are those that are neither disjunctive nor the negation of a disjunctive property, and are in at least one *I*-set, then say duplicates are things that share all basic intrinsic properties, and finally that intrinsic properties are properties shared by all duplicates. There are two reasons for thinking that this definition might well work. First, as we have seen it handles a wide range of hard cases. More importantly, the way that the hard cases were falling gave us reason to suspect that the only extrinsic properties that will be in *I*-sets are properties like *LCS*: properties that agree with some intrinsic property in all compound worlds. It is reasonably clear that these properties will be disjunctive according to the above definition. To see this, let *F* be the extrinsic property in an *I*-set, and let *G* be the intrinsic property it agrees with in all compound worlds. Then for some *J*, *F* can be expressed as (*G* $\wedge$ ${\lnot}$(*L* $\wedge$ *M*)) ${\vee}$ (*L* $\wedge$ *M* $\wedge$ *J*), and it will presumably be much less natural than *G*, probably much less natural than *J*, and almost certainly much less natural than *being simple*, our *L*. So if these are the only kind of extrinsic properties in *I*-sets, our definition is correct.

Indeed, if these are the only kinds of extrinsic properties in *I*-sets, we may not even need to worry about which properties should count as disjunctive. Say that a property *F* *blocks* another property *G* iff both *F* and *G* are in *I*-sets, but there is no *I*-set containing both *F* and *G*. If *F* and *G* were both intrinsic, then there would be an *I*-set they are both in, such as say *SI*, so the fact that there is no such *I*-set shows that one of them is extrinsic. Note that *LCS* blocks *being cubical*. To prove this, assume *LCS* and *being cubical* are in an *I*-set, say *I~k~*. By two applications of (B), *LCS and not cubical* is in *I~k~*. This property is instantiated in some possible worlds: it is instantiated by all lonely spheres. So by (T) there should be a world containing two things that satisfy *LCS and not cubical*. But only lonely, simple spheres satisfy this property, so there is no world where two things satisfy it, contradicting our assumption that *LCS* and *being cubical* can be in the same *I*-set. The proof here seems perfectly general: if *G* is intrinsic and *F* differs from *G* only in which things in simple worlds satisfy it, and *G* is in an *I*-set, then *F* will block *G*. Blocking, as defined, is symmetric, so the fact that *F* blocks *G* is no evidence that *F* is extrinsic, as opposed to *G*. Still, if *G* is much more natural than *F*, then in all probability the reason *F* blocks *G* is that they agree about all cases in compound worlds, and disagree just about the simple worlds. In that case, it seems that *F* is extrinsic, and *G* is intrinsic. So I think the following conjecture has merit: *F* is intrinsic iff it is in an *I*-set and does not block any property much more natural than itself. If the conjecture works, the only kind of naturalness comparisons we need to make will be between properties like *LCS* and properties like *being cubical*. Again, I think these kinds of comparisons should be fairly uncontentious.

# Back to Basics?

Most of the work in my theory is done by the concept of *I*-sets. It might be wondered whether we can do without them. In particular, it might be thought that the new definition of disjunctivenes I offer in @sec-problem will be enough to rescue Langton and Lewis's theory from the objections I have been fretting about. Indeed, the new definition of disjunctiveness *does* suffice for responding to Yablo's objection. However, it will not do on its own, and I think it will end up being essential to define intrinsicness in terms of *I*-sets.

Yablo notes that a property like *being the only red thing* is independent of accompaniment, and that the way Langton and Lewis suggest showing it is disjunctive is by expressing its negation as *being red and accompanied by a red thing, or not being red*. Yablo criticises the claim that the first of these disjuncts really is a natural property. Above I agreed that this was a good objection. However, on the new definition of disjunctiveness, it is beside the point.

To show that *not being the only red thing* is disjunctive, we need only express it as a disjunction of conjunctions such that at least one conjunct in each disjunct is much more natural than it is. We have the disjunctive expansion of *not being the only red thing*, and the first disjunct is *being red and accompanied by a red thing*. Now this disjunct as a whole may not be particularly natural, but the first conjunct, *being red*, is much more natural than *not being the only red thing*. So all we need to show is that one of the conjuncts in the second disjunct is much more natural than the whole disjunction. Since the second disjunct has only one conjunct, this means we have to show *not being red* is much more natural than *not being the only red thing*. However, there seems to be no simple way to show this. It is just entirely unclear how natural properties like *not being red* should seem to be. My guess (for what it is worth) is that like most properties that can be expressed by negations of English predicates, it is very unnatural. Certainly it is very unnatural if we suppose, as seems fair in *this* context, that *F* is only a natural property if all the things that are *F* resemble each other in some important way. The class of things that are not red is as heterogeneous a class as you can hope to find; blue berries, green leaves, silver Beetles, colourless gases and immaterial souls all find their way in. It is true that in *New Work for a Theory of Universals*, David Lewis provides two importantly distinct criteria for naturalness. One is the resemblance criterion just mentioned. The other is that *F* is only perfectly natural if it is fundamental. It might be thought that when we look at this criterion, it does turn out that *not being red* is much more fundamental than *being the only red thing*. Even if this is the case, it is not clear that it does help, or more importantly, that it *should* help. The problem Langton and Lewis were trying to handle is that *not being the only red thing* satisfies a particular combinatorial principle (independence of accompaniment), but only, they say, because there are two different ways of instantiating that property: *not being red* and *being accompanied by a red thing*. The problem is that *not being red* is not a way to instantiate a property, because it is not a way that something could be. It seems very intuitive that 'ways things could be', in this sense, are resemblance properties: they are properties that make for resemblance amongst their instantiators. And even if we can defend the claim that *not being red* is a fundamental property, the fact that it is not a resemblance property seems to undercut Langton and Lewis's case here.

The new definition of disjunctiveness does not provide a defender of Langton and Lewis's theory with a response to Yablo's criticism. On the new definition of disjunctiveness, we do not have to show that *being red and accompanied by a red thing* is more natural than *not being the only red thing* in order to show that the latter is disjunctive. However, in order to show that *not being the only red thing* is disjunctive, we still need to show that *not being red* is a moderately natural property, and this does not seem to be true.

# Conclusion

There are four major differences between the analysis of intrinsic properties provided here and the one provided by Langton and Lewis. Three of these are reflected in the difference between the combinatorial principle they use, independence of accompaniment, and the combinatorial principle I use, membership in an *I*-set. All properties that are in *I*-sets are independent of accompaniment, but they also have a few other nice features. First, membership in an *I*-set guarantees not just independence of whether there are other things, but independence of what other types of things there are. This is the independence principle encoded in condition (T) on *I*-sets. Secondly, membership in an *I*-set guarantees independence of where the other things are. This is the principle encoded in condition (S). Third, the mereological principle (M) has no parallel in Langton and Lewis's theory.

The effect of these extra three restrictions is that I have to make many fewer appeals to naturalness than do Langton and Lewis. The fourth difference between their theory and mine is in the role naturalness considerations play in determining which properties are intrinsic. In @sec-problem I offer two ways of finishing the analysis using naturalness. The first is in the new definition of disjunctiveness; with this definition in hand we can finish the story just as Langton and Lewis suggest. The second is in terms of blocking: *F* is intrinsic iff it is in an *I*-set and does not block any property that it is much less natural than. Both ways are designed to deal with a quite specific problem: properties that differ only in which things instantiate them in simple worlds have the same combinatorial features, so a definition of intrinsicness in terms of combinatorial features (as is Langton and Lewis's, and as is mine) will not be able to distinguish them. Still, both solutions seem likely to provide the same answer in all the hard cases: the right answer.

:::{.content-visible when-format="pdf"}
## References {-}
:::