# Flagging Assumptions {#sec-flagging}

I'm going to make three assumptions in what follows, and it helps to have them on the table.

One is that we can sensibly talk about demons who are arbitrarily accurate at predicting Chooser's strategy. One reason for making this assumption is that all the problems we discuss could be rephrased if we just assumed Demon was at least epsilon better than chance at predicting Chooser's strategy, and this is a realistic assumption. It would complicate the algebra considerably in what follows to do this, without making the examples clearer. A second reason for making the assumption is that standard approaches to game theory assume each player is a demon who can predict the other players' strategies with arbitrary precision, so we're just deferring to orthodox opinion in a notable research topic by making this assumption.

A second is that decision problems are fully specified by setting out the states (assumed to be causally independent of actions), the available actions, the payoffs for each state-action pair, and the conditional probability of each state given each action. Here I'm following @Gallownd, whose formalism for decision problems only includes places for these variables. The primary motivation for this assumption is that it is common in the literature to describe a decision problem in a way that only specifies these factors - the state-action payoffs and the state probabilities conditional on actions - and presupposes without comment that enough has been said to specify which actions ae rational. So I think this assumption is rather widespread, if often implicit. Still, it is a substantial assumption. Some decision theorists think that which choices are rational turns on other factors, such as Chooser's prior unconditional probabilities for various states, or Chooser's attitude to risk. I'll note below where this assumption matters, but in general I'll be following Gallow in making this assumption.

And a third is that in any dynamic choice, a choice at a point is permissible only if it would be permissible were that starting point of a decision problem. This rules out so-called _sophisticated_ approaches to dynamic choice. And I'll come back in @sec-dual-mandate to what happens if this assumption is relaxed.
