---
format: html
---

We are going to be comparing two credence functions, $A$ and $B$. They are both defined over the set $\{w_1, \dots, w_n, \dots\}$. We're just going to be interested in the $\{w_1, \dots, w_n\}$ part. The actual world, call it $w$, is in this set. Both functions are at least finitely additive, so what they say over things in $\{w_1, \dots, w_n\}$ is determined entirely by what they say on the atoms.

There is a constant $r > 1$ such that for $1 \leq i \leq n$, $B(\{w_i\}) = rA(\{w_i\})$. So $r \leq 1/B(\{w_1, \dots, w_n\})$.

Let $S_1, S_2$ be an exclusive pair of subsets of $\{w_1, \dots, w_n\}$ such that neither contain $w$, and the union of $S_1$, $S_2$ and $\{w\}$ is $\{w_1, \dots, w_n\}$. We'll measure the inaccuracy of $A$ and $B$, using the Brier score, over these four sets:

- $S_1$
- $S_1 \cup \{w\}$
- $S_2$
- $S_2 \cup \{w\}$

If $A(S_1) = a_1$, $A(S_2) = a_2$, and $A(\{w\}) = a_3$, can you write out the formulae for the accuracy of $A$ and $B$ over these four propositions, and simplify it as much as possible.