---
title: "Trends in *Philosophical Studies*"
abstract: |
  *Philosophical Studies* has become one of the most important journals for work in several large topics in philosophy. This paper uses data from the word distributions in those papers, and the citations of the papers, to look at how it has changed over time, and how it became so central.
date: today
draft: false
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
categories:
  - history of analytic
  - unpublished
  - in progress
format:
    html:
       css: ../trad_defn.css
    pdf:
      fig-format: pdf
      output-file: "Trends in Philosophical Studies"
      include-in-header:
        - file: ../quarto2024.tex
        - text: |
            \setkomafont{descriptionlabel}{\normalfont\scshape\bfseries}
      include-after-body: 
        text: |
          \noindent Published online in October 2024.
format-links: [html, pdf]
---

# Intro

TKTK

# Articles

Notes - including things that JSTOR counts as book reviews
Not including things that WOS counts as discussions
This is, to put it mildly, a bit random; some precis are included, some aren't; some replies are included, some aren't. In general if the word 'comment' appears in the title excluded, but it's a bit random. But going with them seems best.
Alternative is to work through 100 other journals if we wanted an apples-to-apples comparison.
Missing the supplement in 2013, which I don't understand, and was coded differently in the two databases

# Studies

Number of articles
Length of articles
Number of articles over 10K, 15K, 20K
Average citations over the 100 journals - boring because can't compare
Average citations compared to top 25 - more interesting
Maybe redo that graph as a ratio

# Comparisons

Articles with highest ratio of PS cites/general cites
Articles with lowest ratio of PS cites/general cites
Previously I just did that with articles published in PS; that seems wrong

Hmm, this could be complicated. 
Study: For each decade find 20 most cited, and look at how often they are cited in PS.

For 1980s, the low is 0 for Rawls (1980) and Dennett (1971). But Rawls is cited in Post (1984), under a variant name, and Dennett is cited in Lormond (1985), but to the reprint. Maybe just live with the messiness
High five in 1980s are all language, or language-adjacent: Lewis (1979) (both de se and time's arrow), two Perry papers, and Donnellan

For 1990s, the low is 0 for McDowell's Virtue and Reason. Is in Brighouse (1990), but the citation is incomplete and uses the wrong year. Oddly the third lowest is for Discrimination and Perceptual Knowledge, only 2/38. And this looks right.
The highs in 1990s are still language based, though with metaphysics seeping in (Kim on supervenience, Lewis on Universals)

For 2000s, lows include Cummins (1975) (which is hard to track, such a common name), Anderson (1999), and Mechanisms paper (2000).
The highs are very epistemology based - Goldman is among them, and the two big contextualism papers by DeRose and Lewis. Obviously the editor at the time was also a prominent contextualist, but his papers are not cited in the journal at a particularly out of the ordinary rate. (There are many cases in history where editors are cited a lot, but this isn't one of them.)
Just outside top 20, but Jackson and Chalmers has nearly 1/3 its cites in PS. Tracing back to Davies and Humberstone's original paper.
Remarkably, Elusive Knowledge is most cited in the decade; normally this kind of calculation pushes towards less cited, high variance cases.

For 2010s, still mechanisms, Anderson (1999), also Kripke (1975) are the low ones
Top 5 is more varied, both in topic and time: Kolodny (2005), Pryor (2000), Lewis (1986), Frankfurt (1969), Jackson (1982). Could be result of publishing more papers, but striking that it's pulling these older papers in.

# The LDA

Build the model
Note the five categories
Graph the trends
Flag the methodology

# Language

Find the 40 most cited in each topic over the 40 years (i.e., most cited per year)
Look how often they are cited in PS
Look how often they are cited across the 100
See if the trends in PS track wider trends
Find other journals that have similar trends (Analysis, PQ, AJP)

# Metaphysics

Note the two Schaffer papers, and differences in citing
Is that because little grounding
There is some - see graph of words
Maybe just count how 'modal' vs 'postmodal' the 2019 papers are
Maybe do a small LDA of the metaphysics papers

# Ethics

Is there anything to say here?
Does it go more political? Still not citing Anderson, but something?
