% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  11pt,
  letterpaper,
  DIV=11,
  numbers=noendperiod,
  twoside]{scrartcl}
\usepackage{xcolor}
\usepackage[left=1in, right=1in, top=1in, bottom=1in, paperheight=11in,
paperwidth=8.5in, includemp=TRUE, marginparwidth=0in,
marginparsep=0in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{3}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
  \setmathfont[]{Garamond-Math}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{setspace}
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{booktabs}
\usepackage{caption}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{array}
\usepackage{anyfontsize}
\usepackage{multirow}
\setlength\heavyrulewidth{0ex}
\setlength\lightrulewidth{0ex}
\usepackage[automark]{scrlayer-scrpage}
\clearpairofpagestyles
\cehead{
  Brian Weatherson
  }
\cohead{
  Trends in Philosophical Studies, 1980-2019
  }
\ohead{\bfseries \pagemark}
\cfoot{}
\makeatletter
\newcommand*\NoIndentAfterEnv[1]{%
  \AfterEndEnvironment{#1}{\par\@afterindentfalse\@afterheading}}
\makeatother
\NoIndentAfterEnv{itemize}
\NoIndentAfterEnv{enumerate}
\NoIndentAfterEnv{description}
\NoIndentAfterEnv{quote}
\NoIndentAfterEnv{equation}
\NoIndentAfterEnv{longtable}
\NoIndentAfterEnv{abstract}
\renewenvironment{abstract}
 {\vspace{-1.25cm}
 \quotation\small\noindent\emph{Abstract}:}
 {\endquotation}
\newfontfamily\tfont{EB Garamond}
\addtokomafont{disposition}{\rmfamily}
\addtokomafont{title}{\normalfont\itshape}
\let\footnoterule\relax

\makeatletter
\renewcommand{\@maketitle}{%
  \newpage
  \null
  \vskip 2em%
  \begin{center}%
  \let \footnote \thanks
    {\itshape\huge\@title \par}%
    \vskip 0.5em%  % Reduced from default
    {\large
      \lineskip 0.3em%  % Reduced from default 0.5em
      \begin{tabular}[t]{c}%
        \@author
      \end{tabular}\par}%
    \vskip 0.5em%  % Reduced from default
    {\large \@date}%
  \end{center}%
  \par
  }
\makeatother
\RequirePackage{lettrine}

\renewenvironment{abstract}
 {\quotation\small\noindent\emph{Abstract}:}
 {\endquotation\vspace{-0.02cm}}

\setmainfont{EB Garamond Math}[
  BoldFont = {EB Garamond SemiBold},
  ItalicFont = {EB Garamond Italic},
  RawFeature = {+smcp},
]

\newfontfamily\scfont{EB Garamond Regular}[RawFeature=+smcp]
\renewcommand{\textsc}[1]{{\scfont #1}}

\renewcommand{\LettrineTextFont}{\scfont}
\setkomafont{descriptionlabel}{\normalfont\scshape\bfseries}
\cehead{
  Trends in Philosophical Studies, 1980-2019
  }
\cohead{
  Trends in Philosophical Studies, 1980-2019
  }
\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{sidenotes}{}{\usepackage{sidenotes}}
\@ifpackageloaded{marginnote}{}{\usepackage{marginnote}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Trends in Philosophical Studies, 1980-2019},
  pdfauthor={Anon},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}


\title{Trends in \emph{Philosophical Studies}, 1980-2019}
\author{Anon}
\date{2025}
\begin{document}
\maketitle
\begin{abstract}
\emph{Philosophical Studies} is the most cited journal in
English-language philosophy. This essay looks at how it became so
central, and how the changes in its subject matter over time reflect
changes in English language philosophy. Special attention is paid to the
role of special issues of the journal, notably the publication of
conference proceedings, and to the rise in papers in social philosophy
in the second half of the 2010s.
\end{abstract}


\setstretch{1.1}
\section{Introduction}\label{sec-introduction}

\emph{Philosophical Studies} is the most cited journal in
English-language philosophy, making it worthy of study both in its own
right and as a mirror of broader trends in the discipline. This paper
uses a variety of tools from data analysis to examine the nature of
\emph{Philosophical Studies} and how it has changed over time, from 1980
to 2019.

In the first half of the paper, I examine the growth of
\emph{Philosophical Studies}' citation rate (i.e., the number of
citations per article). Compared with the twenty philosophy journals
that had the highest citation rates over the last forty years,
\emph{Philosophical Studies} has gone from a citation rate 10-20 percent
below average to one 10-20 percent above average. The journal has
achieved this growth despite increasing its publication volume---a
change that typically decreases citation rates. This growth stems partly
from the journal's increased publication of special issues, with those
from the Bellingham Summer Philosophy Conference being particularly
important. It also reflects changes in \emph{Philosophical Studies}'
topic mix that paralleled broader shifts in the philosophical community.

This leads to the second half of the paper, which examines how the
journal's topic mix changed over the years. Figure~\ref{fig-five-topics}
illustrates these changes in topical focus.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/fig-five-topics-1.pdf}}

}

\caption{\label{fig-five-topics}Proportion of \emph{Philosophical
Studies} articles that are in different topics, 1980-2019.}

\end{figure}%

In the late twentieth century, \emph{Philosophical Studies} focused on
philosophy of language, particularly core analytic questions about
reference and description. These questions became central to philosophy
in the 1970s following the publication of \emph{Naming and Necessity}
and remained central to graduate education at top schools well into the
twenty-first century. Other leading journals, however, shifted away from
these questions earlier than \emph{Philosophical Studies} did.

After the turn of the century, the journal moved into two topics that
enhanced its impact. First, it participated actively in the 2000s'
extensive discussions of epistemology, particularly contextualism.
Second, in the 2010s, it joined much of the rest of the discipline in
moving more strongly into social philosophy.

\section{Overview}\label{sec-overview}

\subsection{Editorial History}\label{editorial-history}

\emph{Philosophical Studies} was founded by Herbert Feigl and Wilfrid
Sellars, both then at the University of Minnesota, in 1950, as the
``first American journal expressly devoted to analytic philosophy''
(\citeproc{ref-DeVries2005}{DeVries 2005, 1--2}). They stayed as editors
until Feigl's retirement in 1971, though after 1954 Sellars was listed
as the first editor. At Feigl's retirement the journal moved from the
University of Minnesota Press to Reidel, where it has stayed ever
since.\footnote{Springer is the current continuant of Reidel after
  several mergers and takeovers.} Sellars edited the journal alone until
Keith Lehrer was brought on as associate editor in 1974, starting an
association with the journal that would last nearly half a century.

In 1975 Lehrer, who had just moved from Rochester to Arizona, became
editor. He stayed in that role until 1982, having been joined by John
Pollock (also at Arizona) in 1979. From 1982, Pollock was
Editor-in-Chief, and Lehrer went back to being Associate Editor.

In 1992 the journal moved 100 miles up I-10, as Stewart Cohen, then at
Arizona State, took over as Editor.\footnote{While the journal was at
  Arizona, each year a grad student assistant was recognized on the
  title page as an editorial assistant. Many prominent philosophers had
  this role over the years, including, in 1983, Stewart Cohen.} Cohen
stayed as editor through the rest of the time covered in this study,
eventually being an editor of the journal for longer than even Wilfrid
Sellars.

Thomas Blackson joined as book symposium editor in 2003. In 2010, Cohen
moved to the University of Arizona, and so the journal was edited out of
Tucson for a second time. Jennifer Lackey and Wayne Davis, who would
eventually take over from Cohen, joined as Associate Editors in 2014. In
2016 Cohen was made Editor-in-Chief, while Davis and Lackey became
Editors, and that was the arrangement that persisted through 2019, the
end of the focus of this paper.

Three aspects of this editorial history merit attention. First, the
names here include several of the most important epistemologists of the
last half century. Second, the journal has had remarkably stable
editorial leadership; a comparable summary for most other leading
journals would take twice as long to write. Third, the biggest single
change---the transition from John Pollock to Stewart Cohen as Editor in
1992---does not appear to have had an immediate impact on the journal.
You see dramatic changes straight away at \emph{Mind} when G.~E.~Moore
takes over in 1921, and again when Gilbert Ryle takes over in
1947.\footnote{See Lewy (\citeproc{ref-Lewy1976}{1976}) on Moore, and
  Warnock (\citeproc{ref-Warnock1976}{1976}) on Ryle.} The effects of
the switch from Pollock to Cohen are much more delayed.

\subsection{Articles}\label{articles}

\emph{Philosophical Studies} increased its output considerably when it
moved to Reidel, and then increased it again between 1980 and 2019. Four
figures illustrate these publication trends.
Figure~\ref{fig-article-count-by-year} shows how many articles
\emph{Philosophical Studies} has published each year.
Figure~\ref{fig-word-count-by-year} shows the total word count for the
journal each year. Figure~\ref{fig-word-max-by-year} shows the length of
the longest article each year. Figure~\ref{fig-word-quartiles} shows the
25th, 50th, and 75th percentile article lengths for each year.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/fig-article-count-by-year-1.pdf}}

}

\caption{\label{fig-article-count-by-year}Number of articles published
each year}

\end{figure}%

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/fig-word-count-by-year-1.pdf}}

}

\caption{\label{fig-word-count-by-year}Number of words published each
year}

\end{figure}%

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/fig-word-max-by-year-1.pdf}}

}

\caption{\label{fig-word-max-by-year}Longest article published each
year}

\end{figure}%

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/fig-word-quartiles-1.pdf}}

}

\caption{\label{fig-word-quartiles}25th, 50th, and 75th percentile word
lengths each year.}

\end{figure}%

Some of these changes reflect wider disciplinary changes, but others do
not. Most journals have a much more stable publication rate. Journals
that are commercially published, like \emph{Philosophical Studies}, have
tended to increase their production in recent years, but this growth is
still unusual.

Articles have been getting longer all across philosophy. What's striking
in Figure~\ref{fig-word-quartiles} is the 25th percentile rising to over
8000 words by the end of the 2010s. It used to be common for philosophy
colloquia to include papers that were read aloud by the author. This
(bad) practice has largely disappeared in recent years. By the
mid-2010s, however, reading papers aloud had become impractical. Authors
were no longer writing papers that could be presented orally within a
typical colloquium time slot.

The preceding discussion concerns \emph{articles} in \emph{Philosophical
Studies}. As Section~\ref{sec-what-is-an-article} explains, this is a
less straightforward category than it might appear, partly because of
the variety of issue types \emph{Philosophical Studies} publishes.

\subsection{Special Issues}\label{sec-special-issues}

\emph{Philosophical Studies} has had many special issues, especially
since the mid-1990s. These fall into four main categories. The first
three are papers from three long-running conferences that
\emph{Philosophical Studies} published selected papers from:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The APA Pacific Division
\item
  The Oberlin Colloquium
\item
  The Bellingham Summer Philosophy Conference (BSPC)
\end{enumerate}

The fourth category consists of one-off issues, either on a special
topic, or, in two cases, conferences that \emph{Philosophical Studies}
published once but did not continue with. I'll call all of these
\textbf{One-off} issues.

Often these were double, or occasionally triple, issues. I'm counting
these as 2, or 3, issues, because this provides a better sense of what
proportion of the papers in a year are from special issues. As
Table~\ref{tbl-issues-by-decade} shows, special issues became a
substantial part of \emph{Philosophical Studies}' output in the 1990s.

\begin{longtable}[]{@{}lrrrr@{}}

\caption{\label{tbl-issues-by-decade}Special issues by type and decade.}

\tabularnewline

\toprule\noalign{}
Type & 1980s & 1990s & 2000s & 2010s \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Normal & 62 & 79 & 111 & 107 \\
One-off & 4 & 14 & 13 & 10 \\
APA Pacific & 0 & 18 & 12 & 10 \\
Oberlin & 0 & 6 & 5 & 4 \\
BSPC & 0 & 0 & 8 & 5 \\

\end{longtable}

Special issues exhibit distinct citation patterns and topical emphases,
as subsequent sections will demonstrate.

\section{Methods}\label{sec-methods}

\subsection{Sources}\label{sec-sources}

The studies here are primarily based on two sources: citation data from
Web of Science, and word lists from JSTOR.

I downloaded the Web of Science (hereafter, WoS) Core Collection in XML
format. Within it, I selected 100 prominent philosophy journals that WoS
indexes. The journals I selected are, like \emph{Philosophical Studies},
primarily English-language, analytic philosophy journals. I filtered the
citations for just citations from and to those 100 journals. The XML
file only ran through mid-2022, so I supplemented it by downloading from
the WoS website citation data for those 100 journals through 2024.

WoS has a special way of recording citations in indexed articles to
other articles that it has indexed. These records are easy to extract,
and are considerably more reliable than citation records in general.
That's not to say they are perfect. They certainly have false negatives,
especially when there are any errors in the original citation. Eugenio
Petrovich (\citeproc{ref-Petrovich2024}{2024, 77n10}) notes, they are
more reliable when the citations are in a bibliography than when they
are in footnotes. They also do badly with supplements. So for this study
I've excluded all the supplements to \emph{Noûs}, i.e., those issues of
\emph{Philosophical Perspectives} and \emph{Philosophical Issues} which
were listed as supplements to \emph{Noûs}. I did include the
supplemental issue \emph{Philosophical Studies} issued in 2013, because
the data there looked reliable enough. What follows uses just those
citations. So it is citations from indexed journals to indexed journals,
where WoS recognized that both the cited and citing journal were in its
database.

This is obviously a small subset of all citations. It excludes citations
in academic journals in other fields, in books and edited volumes, and
in many other places that Google Scholar indexes, such as dissertations,
lecture notes, slides, and draft manuscripts. Losing that information is
a cost, but there are three large upsides. First, these citations are
much more accurate. Second, we can be more confident that our data set
is relatively complete; finding a full list of philosophy journals is
easier than finding a full list of edited volumes, or manuscripts on
websites, in philosophy. Third, by looking at citations internal to
philosophy, we can get a sense of philosophy's self-image, and how it
changes over time.

The other source I used is JSTOR, and in particular the Data for
Research (DfR) program that they provide through their Constellate
project. This lets you download lists of the words used in various
journal articles, along with a count of how often each word is
used.\footnote{It also provides bigrams and trigrams, which I've looked
  at in preparing this paper, but didn't end up using.} It also provides
word counts for the articles, which I have used in
Section~\ref{sec-overview}. The words an author uses are a pretty good
guide to what they are talking about; if the word `denotation' is used
frequently, it's probably a philosophy of language article.

\subsection{Articles?}\label{sec-what-is-an-article}

I said I'm talking about articles here, but what exactly is an
\emph{article}? A more helpful question is, which things that philosophy
journals publish are not articles?

Some things are easy. The table of contents is not an article. Nor is a
correction, or a report on editorial change. Book reviews are not
articles. If they were, \emph{Philosophical Review} would have the
lowest rate of citations per article, not the highest.\footnote{I'll
  report on citations per article in Table~\ref{tbl-citation-rate}.}
Both WoS and JSTOR also distinguish articles from discussion notes,
especially if the journal has a designated discussions section. Without
this distinction, \emph{Mind} would have a much lower rate of citations
per article.

Both of these last two categories are relevant to \emph{Philosophical
Studies}, even though it does not run book reviews or have designated
discussion sections. Although it has neither of those things, it does
have many book symposia. The classifiers, WoS and JSTOR, struggle with
how to classify articles in these symposia. They disagree with each
other, and occasionally with their own past practice.

I have some sympathy for the classifiers; these are really borderline
cases. Mostly what they settled on was that the précis and replies by
the book author are not articles, and that the contributions by
commentators are. But they did not stick precisely to this.

For the most part, I've gone with WoS's classifications. It would be
practical, just barely, to go through \emph{Philosophical Studies} issue
by issue and reclassify the book symposium entries so all and only the
commentaries are articles. But it would not be practical to do this for
all one hundred journals. And for this paper, we're mostly interested in
comparing articles in \emph{Philosophical Studies} with articles in
other journals, so it's best to not modify only one journal.

There is one place where I've overridden WoS's classifications. It has
categories of Discussion, Note, and Review, each of which make up about
0.75\% of the articles across the 100 journals. The three categories
include similar enough pieces that I'll treat them as a unified
category. Mostly these are discussion notes, or longer book reviews,
that we want to exclude. But, especially in \emph{Philosophical Review},
they occasionally put ordinary articles here. So important articles by
Stanley Cavell (\citeproc{ref-WOSA1962CGX0500005}{1962}), Jonathan
Schaffer (\citeproc{ref-WOS000272855000002}{2010}), and Harvey Lederman
(\citeproc{ref-Lederman2022PR}{2022}) were all classified as
non-articles.\footnote{The Cavell article was in the discussion section
  of the January 1962 issue of the Review, so this classification is
  understandable. The other two are not.} I've counted any piece in
these three categories twenty pages or longer as an article.

There is one last tricky category to flag. The special issues on the
Oberlin Colloquium sometimes include commentaries on the main articles.
These are mostly not counted as articles, and I think rightly so.
Occasionally, as when Andy Egan (\citeproc{ref-Egan2011}{2011}) was the
commentator on an important paper by Tamar Szabò Gendler
(\citeproc{ref-WOS000295087100003}{2011}), the commentary gets a
reasonable number of citations. But mostly these commentaries are rarely
if ever cited, and I think they aren't really what most people think of
as journal articles. So I've been happy to exclude them.\footnote{If
  these aren't articles, what are they? WoS classifies Egan's paper as
  `Editorial-Matter'. That's wrong, but I'm not sure what I would say in
  their position.}

With this understanding of what an article is in place, I'll now turn to
how \emph{Philosophical Studies} articles have been cited over time.

\section{Outbound Citations}\label{sec-outbound}

\subsection{Overview of Citations}\label{sec-citations-overview}

Articles in \emph{Philosophical Studies} get cited a lot.
Table~\ref{tbl-all-cites} shows the five journals with the most
citations of articles published between 1980 and 2019 within the study's
set of 100 journals.

\begin{longtable}[]{@{}lr@{}}

\caption{\label{tbl-all-cites}Leading journals by total citations for
articles published 1980-2019.}

\tabularnewline

\toprule\noalign{}
Journal & Citations \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Philosophical Studies & 36644 \\
Synthese & 28083 \\
Journal of Philosophy & 23251 \\
Philosophy of Science & 21904 \\
Philosophy and Phenomenological Research & 21295 \\

\end{longtable}

\emph{Philosophical Studies} is in first place on that list in part, but
only in part, because it publishes so much. Table~\ref{tbl-all-articles}
lists the top five journals by the number of articles they have
published.

\begin{longtable}[]{@{}lr@{}}

\caption{\label{tbl-all-articles}Leading journals by article count for
articles published 1980-2019.}

\tabularnewline

\toprule\noalign{}
Journal & Articles \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Synthese & 4524 \\
Philosophical Studies & 3776 \\
Journal of Medical Ethics & 3517 \\
Journal of Symbolic Logic & 3283 \\
Analysis & 2236 \\

\end{longtable}

\emph{Synthese} has 20\% more articles, but 25\% fewer citations. The
other three journals on Table~\ref{tbl-all-articles} are somewhat
special cases. Two of them get a lot of citations outside of philosophy,
and this is only a study of citations in philosophy journals.
\emph{Analysis} only publishes short papers, and so while they get a lot
of citations per page, they don't get as many citations per article as
other journals.

Still, we'd expect on general principles that raw volume of publication
wouldn't make a big difference. Citations tend to follow something like
a log-normal distribution (\citeproc{ref-Brzezinski2015}{Brzezinski
2015}). The bulk of the citations come from a handful of highly cited
articles. Publishing more articles helps, but is no guarantee.

If we look not at total citations, but at citations per article as in
Table~\ref{tbl-citation-rate}, we get a list that looks a bit more like
a familiar ranking of philosophy journals by prestige.

\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.0685}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.4795}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1233}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1370}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1918}}@{}}

\caption{\label{tbl-citation-rate}Leading journals by citation rate for
articles published 1980-2019.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
Rank
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Journal
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Articles
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Citations
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Citation Rate
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
1 & Philosophical Review & 511 & 17016 & 33.30 \\
2 & Philosophy \& Public Affairs & 521 & 9996 & 19.19 \\
3 & Journal of Philosophy & 1221 & 23251 & 19.04 \\
4 & Noûs & 1152 & 18967 & 16.46 \\
5 & Mind & 1072 & 16750 & 15.62 \\
& \ldots{} & & & \\
13 & Australasian Journal of Philosophy & 1362 & 13328 & 9.79 \\
14 & Philosophical Studies & 3776 & 36644 & 9.70 \\

\end{longtable}

I've included \emph{Philosophy and Phenomenological Research} there
because, like \emph{Philosophical Studies}, it publishes many book
symposia. And, like \emph{Philosophical Studies}, the articles in these
symposia are typically not cited very much.

\subsection{Large Trend}\label{sec-large-trend}

There is a striking step-change in citations to \emph{Philosophical
Studies} that occurred in the mid-2000s. To bring this out, I'll compare
\emph{Philosophical Studies} to nineteen other prominent philosophy
journals. From the 100 journals in this study, I selected the 20
(including \emph{Philosophical Studies}) with the highest rates of
citations per published article that Web of Science has indexed
continuously since 1980.\footnote{The last constraint notably rules out
  \emph{Philosophers' Imprint} and \emph{Mind and Language}.}

Figure~\ref{fig-compare-cites-dots} shows, for each year from 1980 to
2019, the average number of citations for articles published in
\emph{Philosophical Studies} (in green), and in the other nineteen (in
red). The figure is fairly noisy, but some trends are clear. Before
2000, the red dots, for the other journals, are mostly above the green
dots, for \emph{Philosophical Studies}. After 2000, and especially from
2003 onwards, that is mostly reversed.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/fig-compare-cites-dots-1.pdf}}

}

\caption{\label{fig-compare-cites-dots}Average citation rates for
\emph{Philosophical Studies} and peer journals.}

\end{figure}%

Figure~\ref{fig-compare-cites-rolling} smooths out some of the noise in
Figure~\ref{fig-compare-cites-dots} in two ways. First, instead of
measuring average citations per year, I measure average citations over a
five-year rolling window. Second, instead of showing the red and green
dots separately, I've just displayed the ratio between them.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/fig-compare-cites-rolling-1.pdf}}

}

\caption{\label{fig-compare-cites-rolling}Ratio of citations to
\emph{Philosophical Studies} versus other journals, five-year rolling
windows.}

\end{figure}%

The difference in Figure~\ref{fig-compare-cites-rolling} between the
earlier and later years is striking. By this one measure, citations per
article, \emph{Philosophical Studies} was doing ok before 2003, but was
below the average of the top 20 journals. After 2003, it consistently
exceeds the average journal in the top 20.

My very anecdotal impression is that \emph{Philosophical Studies} is
viewed as being more prestigious by younger philosophers than by older
philosophers. A toy model of prestige, where it is heavily anchored to
how often a journal was cited when one was in graduate school, would
explain that difference. That said, I have not done (and am not going to
do) a careful study of comparative prestige judgments to know if there
is even an effect here to find, or whether my informal sample was not
reflective of the wider population.

Using median or 75th percentile citations instead of means produces a
similar graph shape. On any of these measures, \emph{Philosophical
Studies} was below the middle of this group of twenty before 2000, and
above it afterwards.

\subsection{Citations of Special
Issues}\label{sec-citations-of-special-issues}

Part of the explanation of the pattern in
Figure~\ref{fig-compare-cites-rolling} is that the special issues that
\emph{Philosophical Studies} published in the 2000s were very heavily
cited. Table~\ref{tbl-citation-by-type} shows three summary statistics,
mean, median, and 75th percentile (Q3), for the normal
\emph{Philosophical Studies} issues, and for the four classes of special
issues. Table~\ref{tbl-citation-by-type} shows three summary
statistics---mean, median, and 75th percentile (Q3)---for normal
\emph{Philosophical Studies} issues and for the four classes of special
issues. Table~\ref{tbl-citation-by-type-decade} shows the means for the
five classes over each of the four decades from 1980-2019. (Blank cells
indicate that no special issues of that type appeared in that decade.)

\begin{longtable}[]{@{}lrrr@{}}

\caption{\label{tbl-citation-by-type}Summary citation statistics for the
five types of \emph{Philosophical Studies} issues.}

\tabularnewline

\toprule\noalign{}
Type & Mean & Median & Q3 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
BSPC & 26.6 & 14.0 & 46.0 \\
Oberlin & 19.0 & 5.5 & 14.0 \\
One-off & 13.3 & 5.0 & 14.5 \\
APA Pacific & 9.1 & 3.0 & 8.0 \\
Normal & 8.6 & 4.0 & 10.0 \\

\end{longtable}

\begin{longtable}[]{@{}lrrrr@{}}

\caption{\label{tbl-citation-by-type-decade}Mean citations by decade for
the five types of \emph{Philosophical Studies} issues.}

\tabularnewline

\toprule\noalign{}
Type & 1980s & 1990s & 2000s & 2010s \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Normal & 6.8 & 7.7 & 10.6 & 8.6 \\
One-off & 9.1 & 14.4 & 16.6 & 11.6 \\
APA Pacific & & 5.1 & 16.6 & 7.8 \\
Oberlin & & 18.5 & 21.5 & 18.1 \\
BSPC & & & 32.6 & 21.0 \\

\end{longtable}

The numbers for BSPC are particularly striking. In the full set of
articles I'm working from, i.e., all the indexed articles from 100
journals, only 1.1\% of articles have 39 or more citations. But one
quarter of the articles that \emph{Philosophical Studies} published from
BSPC are in that 1.2\%. Surprisingly, only one of the 25 most cited
articles in \emph{Philosophical Studies} was from a BSPC special
issue.\footnote{``Epistemic Modals, Relativism and Assertion''
  (\citeproc{ref-WOS000245280800001}{Egan 2007}) is the equal 12th most
  cited paper in \emph{Philosophical Studies}.} The high average is not
caused by outliers but by many BSPC articles being cited very
frequently. By contrast, four of the ten most cited articles were from
the Oberlin colloquium. This is why the Q3 numbers for BSPC and Oberlin
are so different, even though the means aren't that far apart.

The fact that the normal issues have such lower citation statistics than
the special issues might make us think that the explanation of
Figure~\ref{fig-compare-cites-rolling} can be found entirely in the
special issues. Indeed, if we just compare the normal issues of
\emph{Philosophical Studies} to the other 19 journals, the effect we
were seeing basically vanishes. This can be seen in
Figure~\ref{fig-means-normal-only}.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/fig-means-normal-only-1.pdf}}

}

\caption{\label{fig-means-normal-only}Ratio of citations to normal
issues of \emph{Philosophical Studies} versus other leading journals,
five-year rolling window.}

\end{figure}%

When we just focus on the normal issues, there are on average more
citations to the other 19 journals than to \emph{Philosophical Studies}
until the mid-2010s. So part of the story behind
Figure~\ref{fig-compare-cites-rolling} is that the special issues of
\emph{Philosophical Studies} in the 2000s were well cited. But it's
potentially misleading to compare normal issues of one journal to all
issues of other journals. I looked at the most cited article since 2005
in each of the 20 journals that go into
Figure~\ref{fig-means-normal-only}, and in 6 of them (including
\emph{Philosophical Studies}), the most cited article was in a special
issue. (Or, in one case, a special unit in a regular issue.) Special
issues, including refereed special issues, have been very widely cited
in recent times.

Rather than pursuing this line of inquiry further, I now examine what
\emph{Philosophical Studies} published over the years, beginning with
its inbound citations.

\section{Inbound Citations}\label{sec-inbound-citations}

This section looks at the eighty journal articles that are most cited
across the hundred journals between 1980 and 2019, and looks at what
proportion of their citations are in \emph{Philosophical Studies}. On
average, those articles have about 10\% of their citations in
\emph{Philosophical Studies}, but the proportion varies greatly by
articles. Table~\ref{tbl-mainly-in-ps} lists the ten articles whose
citations are most concentrated in \emph{Philosophical
Studies}.\footnote{The ranking here is not by proportion of cites in
  \emph{Philosophical Studies}, but instead by the probability that an
  article would have this many cites in \emph{Philosophical Studies},
  given how many overall citations it has and that highly cited articles
  have about 10\% of their citations in \emph{Philosophical Studies}. I
  think this is a slightly better way to separate the signal from the
  noise.}


\begin{longtable}[]{@{}lrr@{}}

\caption{\label{tbl-mainly-in-ps}Articles with a high concentration of
ciations in \emph{Philosophical Studies}.}

\tabularnewline

\toprule\noalign{}
Article & PS Citations & All Citations \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Pryor (\citeproc{ref-WOS000165361800002}{2000})
& 54 & 270 \\
Kolodny (\citeproc{ref-WOS000231037900002}{2005})
& 37 & 173 \\
Schaffer (\citeproc{ref-WOS000272855000002}{2010})
& 38 & 181 \\
Lewis (\citeproc{ref-WOSA1996VY21200001}{1996})
& 65 & 391 \\
Johnston (\citeproc{ref-WOSA1992KC39800002}{1992})
& 40 & 216 \\
Lewis (\citeproc{ref-WOSA1979JB14500003}{1979})
& 50 & 298 \\
Lewis (\citeproc{ref-WOSA1984TQ70900001}{1984})
& 32 & 171 \\
Lewis (\citeproc{ref-WOSA1997WP33800001}{1997})
& 31 & 171 \\
Frankfurt (\citeproc{ref-WOSA1969Y444700002}{1969})
& 60 & 412 \\
Broome (\citeproc{ref-WOS000084073700005}{1999})
& 24 & 142 \\
Lewis (\citeproc{ref-WOSA1983RR51600001}{1983})
& 70 & 518 \\
Dretske (\citeproc{ref-WOSA1970ZE33800001}{1970})
& 41 & 278 \\

\end{longtable}

There are articles here in the five main topics \emph{Philosophical
Studies} covers: language, ethics, metaphysics, mind, and epistemology
(hereafter, LEMME). The other end of the scale looks quite different, as
shown in Table~\ref{tbl-mainly-out-ps}. There we mainly see articles in
political philosophy, philosophy of science, and logic, with Clark and
Chalmers (\citeproc{ref-WOS000073222300002}{1998}) being a notable (and
surprising) exception.


\begin{longtable}[]{@{}lrr@{}}

\caption{\label{tbl-mainly-out-ps}Articles with a low concentration of
ciations in \emph{Philosophical Studies}.}

\tabularnewline

\toprule\noalign{}
Article & PS Citations & All Citations \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Machamer, Darden, and Craver (\citeproc{ref-WOS000087305900001}{2000})
& 11 & 372 \\
Alchourrón, Gärdenfors, and Makinson(\citeproc{ref-WOSA1985AKA2200025}{1985})
& 3 & 219 \\
Laudan (\citeproc{ref-WOSA1981LY92900002}{1981})
& 4 & 223 \\
Anderson (\citeproc{ref-WOS000078432400003}{1999})
& 7 & 264 \\
Cummins (\citeproc{ref-WOSA1975BF60100001}{1975})
& 9 & 275 \\
Clark and Chalmers (\citeproc{ref-WOS000073222300002}{1998})
& 11 & 306 \\
Singer (\citeproc{ref-WOSA1972Z066400001}{1972})
& 10 & 287 \\
Rawls (\citeproc{ref-WOSA1980KH88100001}{1980})
& 4 & 181 \\
G. A. Cohen (\citeproc{ref-WOSA1989AE70300010}{1989})
& 7 & 231 \\
Kitcher (\citeproc{ref-WOSA1981NA08400001}{1981})
& 6 & 197 \\

\end{longtable}

These tables tell us that the LEMME topics are at the heart of what
\emph{Philosophical Studies} has published over these four decades. I'll
use that fact in the next analysis.

\section{\texorpdfstring{A Topic Model for \emph{Philosophical
Studies}}{A Topic Model for Philosophical Studies}}\label{sec-topic-model}

\subsection{The Model}\label{the-model}

Following the groundbreaking work of Christophe Malaterre and
colleagues, I analyzed the content of \emph{Philosophical Studies}
articles by building a five-topic topic model.\footnote{This technique
  is used to analyze \emph{Philosophy of Science} by Malaterre,
  Chartier, and Pulizzotto (\citeproc{ref-Malaterre2019}{2019}), to
  analyze \emph{Biology and Philosophy} by Malaterre, Pulizzotto, and
  Lareau (\citeproc{ref-Malaterre2019b}{2019}), and to analyze a family
  of eight philosophy of science journals by Malaterre et al.
  (\citeproc{ref-Malaterre2020}{2020}). In Malaterre and Lareau
  (\citeproc{ref-Malaterre2022}{2022}) the technique is extended to
  journals that don't publish exclusively in one language, but that's
  not relevant to \emph{Philosophical Studies}.} Without going too deep
into the details of what topic modeling is, I'll note four features of
it that are relevant.

First, a topic model divides some texts into \emph{k} topics, where
\emph{k} is given by the model builder. On the one hand, the model
itself doesn't tell you how many topics to use. On the other hand, the
model builder doesn't tell the model what those topics should be. I
chose five topics because \emph{Philosophical Studies} concentrates on
the LEMME topics. After asking the model to divide the articles into
five topics, it more or less found those five groups. (Though with some
caveats that will become clearer in what follows.) The model doesn't
give names to those topics; that's something I did. But it does create
the five groupings.

Second, the model takes as input the words in an article, but not the
order those words appear in. For this reason, it is poorly suited to
determining which side of a debate an article is on. Articles on
utilitarianism use different words from articles on mental content;
articles for and against utilitarianism tend to use similar words. So
the model isn't much help at telling us whether articles in
\emph{Philosophical Studies} are for or against the topic being
discussed; for that we have to read the articles.

Third, the model doesn't simply say that an article is in one or other
topic. For each of the five topics, it gives a probability to the
article being in that topic. This is helpful for classifying articles
that don't slot cleanly into one or other group. \emph{Philosophical
Studies} has published a lot of papers on physicalism. For many such
papers, it would be arbitrary to classify them as mind articles or
metaphysics articles. The model doesn't require that we choose. It gives
a probability to the article being in metaphysics, and a probability to
it being in mind. In some cases, such as ``Chalmers on the Addition of
Consciousness To the Physical World''
(\citeproc{ref-WOS000086712500005}{Latham 2000}), the model gives almost
equal probability to the two topics.

Often when topic models are used, articles are classified by their
maximal probability. I prefer to use the actual probabilities. So the
graph in Figure~\ref{fig-five-topics} shows the average probability that
an article is in each topic by year. I think it shouldn't matter much
whether Latham's article is counted as 51\% mind and 49\% metaphysics or
vice versa, and using the probabilities allows for that.

Finally, the models are rather random. Somewhat metaphorically, they
work by picking a random starting point, and scanning for a local
maximum. The scanning procedure is deterministic, but the starting point
is not. This can make a difference to individual articles. Every model I
built was unsure how to classify ``What Do Philosophers Believe?''
(\citeproc{ref-WOS000340619100006}{Bourget and Chalmers 2014}). The one
I'm using said it was 50\% metaphysics, and 50\% spread between the
other four topics, but other models said it was 60\% mind, or largely
ethics. All this makes sense; the article cuts across all the fields.

But this randomness raises a problem: how do we choose which random
starting point to use? We could just use the first one we run, but that
might be a very idiosyncratic output. We could hand code the starting
point, but that would introduce our own biases. We could build many
models and choose the one that looks most like familiar topics, but that
would introduce different biases.

Here I got around this problem by using citation data. I had the
computer build (or at least start building) several thousand models. I
told it to focus on the ones where articles were classified in a similar
way to articles that they cited. In general, the greater the similarity
between the classification of articles and classification of citations
of those articles, the more the model resembled familiar topics. So
rather than using my own judgment about the best model\footnote{If I had
  used my own judgment, I would have picked a model similar to, but not
  quite identical to, this one. But I'd rather trust citation data than
  my idiosyncratic judgments.}, I used the one that best conformed to
the citation data.\footnote{There was one real oddity in this model. It
  put articles on phenomenal properties in metaphysics, and articles on
  dispositions in mind. Most other models did not do this, and I would
  have preferred this one didn't either. But overall, this model did
  best at co-classifying articles and articles they cite, and every
  model is odd in some respect, so I stuck with this model.}

\subsection{The Five Topics}\label{sec-five-topics}

I picked five topics for the model hoping, correctly, that it would land
on something like the LEMME topics. And that's more or less what
happened.

I labeled the topics, and mostly the labels are straightforward. The
only one of those labels that might be misleading is `ethics'. In the
model, that topic includes all papers on norms broadly construed. So it
includes papers on decision theory\footnote{I think this is the right
  way to classify decision theory; it could sensibly be called `formal
  ethics'. But I'm not relying on my views here, just noting that the
  model was remarkably confident that decision theory papers go in
  ethics.}, on political philosophy (though there aren't a lot of
those), and even some papers on epistemic norms. So Kelly's ``The
Rationality of Belief and Some Other Propositional Attitudes''
(\citeproc{ref-WOS000178572700004}{Kelly 2002}) is classified as 50\%
ethics and 50\% epistemology.\footnote{The model I'm using actually had
  it at 51\% ethics. Most models I looked at had it around 51/49 the
  other direction, but we shouldn't treat this difference as meaningful.}
Other articles which seem similar to me are classified as 99\% or more
epistemology. This model (and all the others I looked at) put any
article with explicit discussion of norms at least partially in ethics.

What happens to articles that are not from the LEMME topics? The simple
answer is that they are mostly not published in \emph{Philosophical
Studies}. That's part of what we learn from
Table~\ref{tbl-mainly-out-ps}. If there were more political philosophy
papers, for example, we would see more citations to Rawls or Anderson.

Philosophy of science raises a complication though. \emph{Philosophical
Studies} publishes a fair amount of philosophy of science; many of its
papers could easily appear in \emph{Philosophy of Science}. Despite
this, the five-way classification used here makes sense. Despite that,
the five way classification used here makes sense. The important thing
is that the philosophy of science articles that \emph{Philosophical
Studies} publishes also fall into one of those five topics. So there are
a lot of articles on Bayesian epistemology, e.g., ``Belief and the
Problem of Ulysses and the Sirens''
(\citeproc{ref-WOSA1995QE80400001}{van Fraassen 1995}), but it makes
sense to count them in epistemology. There are also a lot of articles on
the metaphysics of science, e.g., ``Realism, Anti-foundationalism and
the Enthusiasm for Natural Kinds''
(\citeproc{ref-WOSA1991FC38500010}{Boyd 1991}), but we don't lose much
if we count these as metaphysics. What \emph{Philosophical Studies}
doesn't have (or, more precisely, doesn't have much of) are articles
like ``Thinking about Mechanisms''
(\citeproc{ref-WOS000087305900001}{Machamer, Darden, and Craver 2000}),
that are clearly philosophy of science articles but not in one of these
five topics. So we aren't losing much by not having a separate topic for
those articles. And we can see that by looking at the fact that
``Thinking about Mechanisms'', and several other papers like it, are
cited rather rarely in \emph{Philosophical Studies}.\footnote{Figure~\ref{fig-quantum}
  and Figure~\ref{fig-genetic}, below, provide more evidence that
  \emph{Philosophical Studies} does not publish a lot of philosophy of
  physics or philosophy of biology; again, the pattern is that the
  philosophy of science articles it publishes fall into one of these
  five categories.}

The main use I'll put this model to is looking for changes in
publication rates, and Section~\ref{sec-words-and-trends} will go over
those changes in more detail. I'll end this section by looking at how
these five topics relate to the special issues, and the citation rates
of articles in those five topics.

\subsection{Topics and Special Issues}\label{topics-and-special-issues}

Table~\ref{tbl-topics-special} shows the distribution of the five topics
over the types of issues that \emph{Philosophical Studies} publishes.

\begin{longtable}[]{@{}llllll@{}}

\caption{\label{tbl-topics-special}Distribution of philosophical topics
over types of issue.}

\tabularnewline

\toprule\noalign{}
Type & Epistemology & Mind & Ethics & Language & Metaphysics \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
APA Pacific & 17.6\% & 21.5\% & 32.6\% & 11.2\% & 17.1\% \\
BSPC & 20.7\% & 6.1\% & 30.5\% & 12.4\% & 30.3\% \\
Normal & 17.5\% & 15.2\% & 23.3\% & 22.3\% & 21.6\% \\
Oberlin & 20.5\% & 35.5\% & 8.5\% & 12\% & 23.5\% \\
One-off & 28.6\% & 22.1\% & 13\% & 19.6\% & 16.8\% \\

\end{longtable}

The differences between Oberlin and BSPC are striking, even if not
surprising. BSPC was primarily an ethics and metaphysics conference,
while Oberlin has focused more on philosophy of mind. The higher numbers
for language in normal issues partly reflect the greater number of
normal issues before the mid-1990s, when language was more central to
the journal and perhaps the discipline.

As noted previously, the journal publishes fewer epistemology articles
than one might expect given the prominence of the editors in
epistemology. Here we do see an effect. The one-off issues, where the
editors have more say over the topic, lean more towards epistemology
than the rest of the journal.

\subsection{Topics and Citations}\label{topics-and-citations}

Table~\ref{tbl-topics-cites} shows how often, on average, articles in
the different topics were cited.

\begin{longtable}[]{@{}lrrr@{}}

\caption{\label{tbl-topics-cites}Average citation rates for the five
main topics.}

\tabularnewline

\toprule\noalign{}
Topic & Articles & Citations & Rate \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Epistemology & 722.8 & 8389.9 & 11.61 \\
Ethics & 899.0 & 7726.5 & 8.59 \\
Language & 746.0 & 5766.4 & 7.73 \\
Metaphysics & 775.5 & 8556.6 & 11.03 \\
Mind & 628.6 & 6177.6 & 9.83 \\

\end{longtable}

The differences are not as stark as in Table~\ref{tbl-citation-by-type},
but they are still notable. Epistemology articles are cited, on average,
about 50\% more often than language articles. Now a simple explanation
for that might be that epistemology articles appear on average later,
and articles that appear later get cited more often. As
Table~\ref{tbl-topics-cites-decades} shows, that is partially right. But
breaking up the citations by decades reveals something surprising.

\begin{longtable}[]{@{}lrrrr@{}}

\caption{\label{tbl-topics-cites-decades}Average citation rates for the
five main topics by decade.}

\tabularnewline

\toprule\noalign{}
Topic & 1980s & 1990s & 2000s & 2010s \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Epistemology & 8.80 & 9.66 & 15.80 & 10.74 \\
Ethics & 6.67 & 7.38 & 12.12 & 8.00 \\
Language & 5.80 & 6.03 & 11.91 & 7.15 \\
Metaphysics & 7.54 & 10.18 & 14.21 & 11.14 \\
Mind & 6.38 & 10.38 & 11.47 & 9.60 \\

\end{longtable}

The difference between the 2000s and every other decade in
Table~\ref{tbl-topics-cites-decades} is stark. But the really striking
thing is the lack of citations to language articles before the 2000s.
I'll come back to this point in Section~\ref{sec-1980s-articles}, as
part of a broader look at how the topic distribution in
\emph{Philosophical Studies} changed over time.

\section{Words and Trends}\label{sec-words-and-trends}

\subsection{The Decline of Philosophy of
Language}\label{the-decline-of-philosophy-of-language}

Four of the five topics retain a stable share of papers in
\emph{Philosophical Studies} over time, while philosophy of language
falls away dramatically. Figure~\ref{fig-language} isolates the language
panel from Figure~\ref{fig-five-topics}, and adds a trendline, to make
this more visible.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/fig-language-1.pdf}}

}

\caption{\label{fig-language}Proportion of \emph{Philosophical Studies}
articles in philosophy of language.}

\end{figure}%

If you don't trust black box methods like topic modeling, you can see a
similar trend just in the word usage. From here on we'll see a lot of
graphs of word usage in \emph{Philosophical Studies}, and they will all
have the format on display in Figure~\ref{fig-description} and
Figure~\ref{fig-reference}.

The first graph shows how often the target word is used each year per
thousand words in the journal. The large red circles show the rate in
\emph{Philosophical Studies}. The small grey squares show the rate in
twenty leading journals that I'm using as a comparison class.\footnote{The
  journals are \emph{American Philosophical Quarterly}, \emph{Analysis},
  \emph{Australasian Journal of Philosophy}, \emph{British Journal for
  the Philosophy of Science}, \emph{Canadian Journal of Philosophy},
  \emph{Ethics}, \emph{Journal of Philosophical Logic}, \emph{Journal of
  Philosophy}, \emph{Linguistics and Philosophy}, \emph{Mind},
  \emph{Monist}, \emph{Noûs}, \emph{Pacific Philosophical Quarterly},
  \emph{Philosophical Quarterly}, \emph{Philosophical Review},
  \emph{Philosophical Studies}, \emph{Philosophy \& Public Affairs},
  \emph{Philosophy and Phenomenological Research}, \emph{Philosophy of
  Science}, and \emph{Synthese}.} The dashed line shows the average for
\emph{Philosophical Studies}.

The second graph shows the proportion of articles that the target word
appears in. It's useful to isolate this, because sometimes a word
appears frequently simply because it gets used hundreds of times by a
single author. Again, it includes an average, the dashed line, and
values for the peer journals.

The third graph shows the proportion of articles that the target word
appears ten or more times in. This is useful for teasing apart passing
references from sustained engagement, while also not allowing the
measure to be swamped by someone using the words hundreds of times.

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-1-1.pdf}}

}

\subcaption{\label{fig-description-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-1-2.pdf}}

}

\subcaption{\label{fig-description-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-1-3.pdf}}

}

\subcaption{\label{fig-description-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-description}``description''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-1-4.pdf}}

}

\subcaption{\label{fig-reference-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-1-5.pdf}}

}

\subcaption{\label{fig-reference-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-1-6.pdf}}

}

\subcaption{\label{fig-reference-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-reference}``reference''}

\end{figure*}%

In Figure~\ref{fig-description} and Figure~\ref{fig-reference}, the word
counts go down sharply over time. The other graphs don't decline quite
as steeply; after all, there are plenty of reasons to use the words
other than talking about the relationship between reference and
description. But it is still noteworthy that the dots in the 2010s are
consistently below the trendline in all of the graphs.

\subsection{Word Trends as a Guide}\label{sec-word-guide}

These trends in word usage are a more fine-grained guide to what is
happening in \emph{Philosophical Studies} than the five topic model. I
did use topic modeling to build many more fine-grained models for the
journal, but there was too much variation between the models to use any
one model as the basis for this section. Instead I'll look at word
frequency, and how it relates to citation patterns.

For each decade, I'll look at words whose usage in \emph{Philosophical
Studies}, as measured by these three kinds of graphs, stands out. That
typically means it is used more often in \emph{Philosophical Studies}
than in other decades, so the red dots in that decade are higher than
elsewhere, and it is used more often in \emph{Philosophical Studies} at
that time than elsewhere, so the red dots are higher in that time than
the grey dots.

The two tests I just measured are somewhat independent. Sometimes they
point in the same direction. For instance, Figure~\ref{fig-sentences},
Figure~\ref{fig-worlds}, and Figure~\ref{fig-grounding} show examples
where a word's usage in the highlighted decade is above both the line
showing the long term average, and above the grey dots showing usage at
the time in other journals. In the other direction,
Figure~\ref{fig-knowledge}, Figure~\ref{fig-logic}, and
Figure~\ref{fig-context}, show words that, in the highlighted decades,
were used less often than in other decades or other journals.

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-2-1.pdf}}

}

\subcaption{\label{fig-sentences-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-2-2.pdf}}

}

\subcaption{\label{fig-sentences-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-2-3.pdf}}

}

\subcaption{\label{fig-sentences-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-sentences}``sentences''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-2-4.pdf}}

}

\subcaption{\label{fig-worlds-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-2-5.pdf}}

}

\subcaption{\label{fig-worlds-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-2-6.pdf}}

}

\subcaption{\label{fig-worlds-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-worlds}``worlds''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-2-7.pdf}}

}

\subcaption{\label{fig-grounding-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-2-8.pdf}}

}

\subcaption{\label{fig-grounding-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-2-9.pdf}}

}

\subcaption{\label{fig-grounding-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-grounding}``grounding''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-3-1.pdf}}

}

\subcaption{\label{fig-knowledge-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-3-2.pdf}}

}

\subcaption{\label{fig-knowledge-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-3-3.pdf}}

}

\subcaption{\label{fig-knowledge-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-knowledge}``knowledge''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-3-4.pdf}}

}

\subcaption{\label{fig-logic-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-3-5.pdf}}

}

\subcaption{\label{fig-logic-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-3-6.pdf}}

}

\subcaption{\label{fig-logic-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-logic}``logic''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-3-7.pdf}}

}

\subcaption{\label{fig-context-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-3-8.pdf}}

}

\subcaption{\label{fig-context-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-3-9.pdf}}

}

\subcaption{\label{fig-context-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-context}``context''}

\end{figure*}%

The other directions are possibly more interesting. Words associated
with topics that are not as common in \emph{Philosophical Studies},
especially in philosophy of science, can get used above their long term
average, but below the average across journals. We see this in
Figure~\ref{fig-quantum}, Figure~\ref{fig-genetic}, and
Figure~\ref{fig-model}.

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-4-1.pdf}}

}

\subcaption{\label{fig-quantum-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-4-2.pdf}}

}

\subcaption{\label{fig-quantum-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-4-3.pdf}}

}

\subcaption{\label{fig-quantum-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-quantum}``quantum''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-4-4.pdf}}

}

\subcaption{\label{fig-genetic-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-4-5.pdf}}

}

\subcaption{\label{fig-genetic-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-4-6.pdf}}

}

\subcaption{\label{fig-genetic-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-genetic}``genetic''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-4-7.pdf}}

}

\subcaption{\label{fig-model-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-4-8.pdf}}

}

\subcaption{\label{fig-model-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-4-9.pdf}}

}

\subcaption{\label{fig-model-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-model}``model''}

\end{figure*}%

In the other direction, sometimes a word appears less frequently than at
other times, but more frequently than in peer journals. When this
happens, it can be a sign that \emph{Philosophical Studies} is
publishing articles in topics that other journals have not yet picked
up. One notable example of this is in Figure~\ref{fig-intuitions}, and
I'll come back to that case in Section~\ref{sec-1990s-articles}.

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-5-1.pdf}}

}

\subcaption{\label{fig-intuitions-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-5-2.pdf}}

}

\subcaption{\label{fig-intuitions-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-5-3.pdf}}

}

\subcaption{\label{fig-intuitions-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-intuitions}``intuitions''}

\end{figure*}%

\subsection{Three Observations}\label{three-observations}

Before getting into words that tell us about changes in the subject
matter, I want to briefly note three other things we can see in the word
count.

The JSTOR set includes all the words in the article, including headers,
footnotes, and bibliography. \emph{Philosophical Studies} gradually
moved from footnote citations to author-text plus bibliography. So `op'
and `cit' appear primarily in the 1980s dataset. More strikingly,
Figure~\ref{fig-oxford} shows how much more common the word ``Oxford''
has become. This is in part a result of longer bibliographies in the
2010s, in part a consequence of the proliferation of Oxford Handbooks
and Oxford Studies publications, but largely a sign of the dominance of
philosophy book publishing in the 2010s by Oxford University Press.

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-6-1.pdf}}

}

\subcaption{\label{fig-oxford-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-6-2.pdf}}

}

\subcaption{\label{fig-oxford-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-6-3.pdf}}

}

\subcaption{\label{fig-oxford-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-oxford}``oxford''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-6-4.pdf}}

}

\subcaption{\label{fig-thanks-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-6-5.pdf}}

}

\subcaption{\label{fig-thanks-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-6-6.pdf}}

}

\subcaption{\label{fig-thanks-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-thanks}``thanks''}

\end{figure*}%

Another word that appears a lot in the 2010s is ``thanks'', as
Figure~\ref{fig-thanks} shows. As Eugenio Petrovich
(\citeproc{ref-Petrovich2024}{2024}) notes, one pattern in the 2010s is
that acknowledgements footnotes became more frequent, and more informal.
So papers will cite ``Theodore Sider'' and thank ``Ted Sider''. And they
will not start with ``I am grateful to\ldots{}'' but simply ``Thanks
to\ldots{}''.

Finally, the trend in gender terms is remarkable. I could pick just
about any gendered terms to display this, but it's easiest to just
compare Figure~\ref{fig-his} and Figure~\ref{fig-her}.

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-7-1.pdf}}

}

\subcaption{\label{fig-his-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-7-2.pdf}}

}

\subcaption{\label{fig-his-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-7-3.pdf}}

}

\subcaption{\label{fig-his-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-his}``his''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-7-4.pdf}}

}

\subcaption{\label{fig-her-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-7-5.pdf}}

}

\subcaption{\label{fig-her-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-7-6.pdf}}

}

\subcaption{\label{fig-her-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-her}``her''}

\end{figure*}%

\section{1980s}\label{sec-1980s-articles}

From the 1990s to at least the mid 2010s, the bulk of ethics papers in
\emph{Philosophical Studies} were on fairly theoretical questions, with
special focus on questions about moral realism, moral motivation, and (a
topic I'll return to) moral responsibility. But in the 1980s the ethics
papers in the journal had a different focus.

There were several papers on utilitarianism. So there was a lot of
discussion of ``utility'', ``utilitarianism'' and ``utilitarian''. The
graphs of these words are fairly similar, so I've just highlighted
``utilitarian'' in Figure~\ref{fig-utilitarian}.

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-8-1.pdf}}

}

\subcaption{\label{fig-utilitarian-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-8-2.pdf}}

}

\subcaption{\label{fig-utilitarian-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-8-3.pdf}}

}

\subcaption{\label{fig-utilitarian-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-utilitarian}``utilitarian''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-8-4.pdf}}

}

\subcaption{\label{fig-trolley-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-8-5.pdf}}

}

\subcaption{\label{fig-trolley-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-8-6.pdf}}

}

\subcaption{\label{fig-trolley-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-trolley}``trolley''}

\end{figure*}%

One can use almost any philosophical term in a paper attacking the
theory it names; indeed the 1980s paper with the most uses of
``Kantian'' (\citeproc{ref-WOSA1989CE37600004}{Terzis 1989}) is an
anti-Kantian paper. But most of these papers were supporting
utilitarianism. Relatedly, there were several discussions of the trolley
problem, as shown in Figure~\ref{fig-trolley}. The word count graph in
that figure is rather uneven because there were some papers that used
the word `trolley' hundreds of time, with Kamm
(\citeproc{ref-WOSA1989CE37600001}{1989}) being the most notable.

There was also a lot of discussion of abortion, with a particular focus
on the defense of abortion in Thomson
(\citeproc{ref-Thomson1971}{1971}).\footnote{One of the papers on
  abortion (\citeproc{ref-WOSA1985ANT6600005}{Gensler 1985},
  \citeproc{ref-WOSA1986AZA8100007}{1986}) got printed twice because the
  pages were out of order the first time.} Figure~\ref{fig-abortion} and
Figure~\ref{fig-Thomson} show how prevalent this was at the time, and
how much it dropped off afterwards.\footnote{The proportion of articles
  mentioning `Thomson' went up, not least because so many of her
  students were publishing in \emph{Philosophical Studies} and thanking
  her.}

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-9-1.pdf}}

}

\subcaption{\label{fig-abortion-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-9-2.pdf}}

}

\subcaption{\label{fig-abortion-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-9-3.pdf}}

}

\subcaption{\label{fig-abortion-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-abortion}``abortion''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-9-4.pdf}}

}

\subcaption{\label{fig-Thomson-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-9-5.pdf}}

}

\subcaption{\label{fig-Thomson-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-9-6.pdf}}

}

\subcaption{\label{fig-Thomson-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-Thomson}``Thomson''}

\end{figure*}%

The papers in \emph{Philosophical Studies} on abortion were largely
\emph{anti}-abortion arguments. They did not get much uptake in
philosophy journals. The nine\footnote{Or ten, if you count both
  printings of the Gensler piece.} papers from the 1980s that use
``abortion'' five times or more average less than one citation per
article in philosophy journals. Google Scholar shows that some of them
have more uptake elsewhere, especially in specialist bioethics journals.
After the 1980s, \emph{Philosophical Studies} largely lost interest in
this topic.

The big story of the 1980s is the centrality of philosophy of language
to the journal, and how different this is to what the journal became
after 2000. But as I detail more fully in
Section~\ref{sec-1990s-articles}, the kind of philosophy of language it
was publishing was very different to the work that would become central
to the field in later decades. In the 1980s, the central focus in
\emph{Philosophical Studies} was Donnellan's distinction between
referential and attributive uses of definite descriptions, and the words
`Donnellan', `referential' and `attributive' all appear frequently. But
there isn't much engagement with linguistics, or more broadly with work
on compositional semantics.

\section{1990s}\label{sec-1990s-articles}

While the discussions of ethics drop off in the 1990s, the fascination
with debates about content continue. There is more discussion now of
mental content, as well as linguistic content. But the focus is still
very much on the debates between internalists and externalists about
content. Some of that is visible in words associated with prominent
examples from these debates, such as Figure~\ref{fig-Hesperus},
Figure~\ref{fig-Phosphorus}, and Figure~\ref{fig-arthritis}.\footnote{The
  discussion of `arthritis' is of course mostly a response to Burge
  (\citeproc{ref-WOSA1986AYX3200001}{1986}).}

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-10-1.pdf}}

}

\subcaption{\label{fig-Hesperus-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-10-2.pdf}}

}

\subcaption{\label{fig-Hesperus-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-10-3.pdf}}

}

\subcaption{\label{fig-Hesperus-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-Hesperus}``Hesperus''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-10-4.pdf}}

}

\subcaption{\label{fig-Phosphorus-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-10-5.pdf}}

}

\subcaption{\label{fig-Phosphorus-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-10-6.pdf}}

}

\subcaption{\label{fig-Phosphorus-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-Phosphorus}``Phosphorus''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-10-7.pdf}}

}

\subcaption{\label{fig-arthritis-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-10-8.pdf}}

}

\subcaption{\label{fig-arthritis-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-10-9.pdf}}

}

\subcaption{\label{fig-arthritis-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-arthritis}``arthritis''}

\end{figure*}%

We also see some discussion of philosophers associated with this debate,
though as with most of the major figures in these debates, we have to be
careful because they didn't only write about internalism and
externalism. Still, the trends in Figure~\ref{fig-Burge},
Figure~\ref{fig-Fodor}, and Figure~\ref{fig-Putnam} are striking.

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-11-1.pdf}}

}

\subcaption{\label{fig-Burge-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-11-2.pdf}}

}

\subcaption{\label{fig-Burge-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-11-3.pdf}}

}

\subcaption{\label{fig-Burge-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-Burge}``Burge''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-11-4.pdf}}

}

\subcaption{\label{fig-Fodor-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-11-5.pdf}}

}

\subcaption{\label{fig-Fodor-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-11-6.pdf}}

}

\subcaption{\label{fig-Fodor-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-Fodor}``Fodor''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-11-7.pdf}}

}

\subcaption{\label{fig-Putnam-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-11-8.pdf}}

}

\subcaption{\label{fig-Putnam-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-11-9.pdf}}

}

\subcaption{\label{fig-Putnam-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-Putnam}``Putnam''}

\end{figure*}%

Looking back, a lot of this discussion of content feels stale by the
mid-1990s. There is a sense that the important things to say have been
said. This shows up in the citation data. The \emph{Philosophical
Studies} papers using these terms are not cited particularly often, and
a high proportion of these citations are in \emph{Philosophical Studies}
itself. The rest of the field was moving on, but \emph{Philosophical
Studies} was a step behind.

Even the giants of the field weren't immune to this change in
philosophical fashion. Fodor published \emph{The Elm and the Expert} in
1995. It has around 500 citations on Google Scholar. Most of us would be
happy with that kind of recognition, but by Fodor's lofty standards it
was a flop. \emph{Holism} (\citeproc{ref-FodorLepore1992}{Fodor and
Lepore 1992}) has over 1500 Google Scholar citations; \emph{Concepts}
(\citeproc{ref-Fodor1998}{Fodor 1998}) has nearly 3000. Content
externalism was not as central to philosophy in the 1990s as it had been
in earlier decades.

Despite the amount of work on language, and content more generally, in
\emph{Philosophical Studies}, what is more notable is perhaps what isn't
there. Despite the prominence of philosophy of language, there isn't
much discussion of conditionals. There are no \emph{Philosophical
Studies} articles cited in Dorothy Edgington's influential and
comprehensive ``On Conditionals''
(\citeproc{ref-WOSA1995QX94800001}{Edgington 1995}). Similarly, there
was very little on speech acts, or on context sensitivity. The words
``assertion'' and ``Austin'' appear at lower than average frequency
before 2000, as do all the cognates of ``context''.

Perhaps most significantly, despite the centrality of philosophy of
language, there was very little interaction with linguistics, and
especially not with linguists working on formal semantics. Here it helps
to look at the 1980s and 1990s together, because this trend continues
through the turn of the century. Before 2000, only one paper mentioned
Irene Heim, only two mentioned Angelika Kratzer, and only three
mentioned James McCawley.\footnote{See respectively: King
  (\citeproc{ref-WOSA1988P180000006}{1988}); Cross
  (\citeproc{ref-WOSA1986D182100003}{1986}); Tichý
  (\citeproc{ref-WOSA1984SK63200001}{1984}); Asher and Bonevac
  (\citeproc{ref-WOSA1985ABV7900005}{1985}); Blackburn
  (\citeproc{ref-WOSA1988M482100005}{1988}); Ostertag
  (\citeproc{ref-WOS000083809100001}{1999}).} Five of those six papers
were published between 1984 and 1988; outside of that window these
linguists were mentioned just once. There were more mentions of Chomsky,
though they were mostly in passing, and as often in philosophy of mind
papers as philosophy of language. Similarly, there were a few mentions
of George Lakoff, but again not always in philosophy of language. The
closest thing I see to interdisciplinary work are some applications of
Montague grammar (e.g., Hazen
(\citeproc{ref-WOSA1984TJ24700012}{1984})). But the general pattern is
that the philosophy of language articles that were being written did not
engage with debates that would become prominent in later years. As a
consequence, they were not often cited.

There is an interesting contrast to this pattern in work on
philosophical methodology. Here, \emph{Philosophical Studies} was
somewhat ahead of the curve. You can see this in
Figure~\ref{fig-intuitions} (`intuitions') from
Section~\ref{sec-word-guide}. (Lots of philosophers talk about
`intuition', but multiple uses of the plural `intuitions' is a
reasonably good guide that the paper is about methodology.) The papers
that use `intuitions' a lot were often cited a lot, e.g., important
papers by Christopher Hill (\citeproc{ref-WOSA1997XH01200003}{1997}) and
George Bealer (\citeproc{ref-WOSA1996UE45200001}{1996}). Especially
after the publication of Frank Jackson's Locke lectures (Jackson
(\citeproc{ref-Jackson1998}{1998})), there was a lot more discussion of
methodology, and of intuitions, both in \emph{Philosophical Studies} and
elsewhere. And so naturally these good early papers got a lot of
attention.

That case was an exception in the 1990s though. As we'll see in the next
two sections, it would become more common after the turn of the century.

\section{2000s}\label{sec-2000s-articles}

Philosophers have long been fond of named ideologies, and labels for
proponents of these ideologies. The earliest years of philosophy
journals are full of disputes between idealists, realists, pragmatists,
and positivists. These labels can obscure as much as they reveal.
Indeed, another theme of those early years is long disputes about just
what idealism, realism, pragmaticism, and positivism really are.

This trend intensified in the 2000s, with a twist. Now the `isms' most
used tended to be words not in wide circulation just a few years
earlier. In some cases that's because an old view got a new name. In
some cases, it's because a new view appeared on center stage.
Figure~\ref{fig-contextualism}, Figure~\ref{fig-fictionalism}, and
Figure~\ref{fig-physicalism} show the usage of three such words:
``contextualism'', ``fictionalism'', and ``physicalism''.\footnote{A
  similar graph for the 2010s would highlight ``expressivism'',
  ``monism'', and ``presentism''. I've left off the graphs of the `ist'
  equivalents, e.g., `contextualist', but they mostly have the same
  shape.}

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-12-1.pdf}}

}

\subcaption{\label{fig-contextualism-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-12-2.pdf}}

}

\subcaption{\label{fig-contextualism-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-12-3.pdf}}

}

\subcaption{\label{fig-contextualism-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-contextualism}``contextualism''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-12-4.pdf}}

}

\subcaption{\label{fig-fictionalism-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-12-5.pdf}}

}

\subcaption{\label{fig-fictionalism-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-12-6.pdf}}

}

\subcaption{\label{fig-fictionalism-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-fictionalism}``fictionalism''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-12-7.pdf}}

}

\subcaption{\label{fig-physicalism-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-12-8.pdf}}

}

\subcaption{\label{fig-physicalism-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-12-9.pdf}}

}

\subcaption{\label{fig-physicalism-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-physicalism}``physicalism''}

\end{figure*}%

The discussions of fictionalism and fictionalists are much more
concentrated: all these usages are in just 14 articles. But there are 70
articles that talk about contextualism, and 72 articles that talk about
physicalism. In both of the last two cases, that means the term is used
in about 8\% of all articles that decade. In both cases, that's a
dramatic increase on previous usage. The term `contextualism' appears
more often in ``Contextualism, Externalism and Epistemic Standards''
(\citeproc{ref-WOS000168853300001}{Williams 2001}) than it had appeared
in the history of the journal to that point.

As well as the novelty, there are two things worth noting about this
rise. One is that these were, like with mental causation in the 1990s,
debates where \emph{Philosophical Studies} was publishing pieces that
became central to the literature. This was especially true for debates
about contextualism, where papers like ``Contextualism and Warranted
Assertibility Manoeuvres'' (\citeproc{ref-WOS000241143100001}{Brown
2006}), ``From Contextualism To Contrastivism''
(\citeproc{ref-WOS000222384400005}{Schaffer 2004}) and ``Knowledge
Claims and Context: Loose Use'' (\citeproc{ref-WOS000245280900001}{Davis
2007}) quickly became widely cited.

This leads to the big story of the 2000s, the rise of epistemology.
According to the topic model, epistemology went from being 15\% of the
journal over the previous two decades, to being 20\% in the 2000s, and
then rising again in the 2010s. In the 2000s, this was mostly because of
discussions about knowledge. (In the 2010s, the focus would shift more
to justification.) Central to this trend were debates about
contextualism. ``Elusive Knowledge''
(\citeproc{ref-WOSA1996VY21200001}{Lewis 1996}) was cited in 3.3\% of
all articles that decade, and ``Solving the Sceptical Problem''
(\citeproc{ref-WOSA1995RC31600001}{DeRose 1995}) in 2.9\% of all
articles. That's a higher rate than any other article was cited over a
decade. The next highest rate is that ``The Skeptic and the Dogmatist''
(\citeproc{ref-WOS000165361800002}{Pryor 2000}) is cited in 2.8\% of
articles in the 2010s, as the focus moved over to justification.

Figure~\ref{fig-knows} shows the increase in word usage for the word you
might think most clearly indicates epistemology: ``knows''. Unlike with
some of the earlier examples, this is not just driven by a handful of
articles, but by a broader turn towards epistemology.

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-13-1.pdf}}

}

\subcaption{\label{fig-knows-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-13-2.pdf}}

}

\subcaption{\label{fig-knows-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-13-3.pdf}}

}

\subcaption{\label{fig-knows-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-knows}``knows''}

\end{figure*}%

\emph{Philosophical Studies} isn't the only journal that sees a shift to
epistemology at this time. Petrovich
(\citeproc{ref-Petrovich2024}{2024}) looked at citation data from
\emph{Mind}, \emph{Noûs}, \emph{Philosophical Review}, \emph{Journal of
Philosophy} and \emph{Philosophy and Phenomenological Research}, and
concluded that there was a marked uptick in epistemology articles being
written, and cited, in the 2000s. His study wasn't restricted to
citations of journal articles, like this study is. That's relevant not
because there are so many epistemology books that get cited in that
time, but rather because his study lets us see when books like
\emph{Word and Object} and \emph{Naming and Necessity} start getting
cited less, and articles like ``Elusive Knowledge'' start getting cited
more. As with \emph{Philosophical Studies}, that seems to happen in the
2000s.

\section{2010s}\label{sec-2010s-articles}

The change in citation practices in the 2010s means that we can use
citation data alongside word data to see what happened. So many of the
citations in the journal's history through 2019 are in the 2010s that
the inbound citation numbers for the decade look a bit like the overall
citation numbers we discussed earlier, especially in
Table~\ref{tbl-mainly-in-ps} and Table~\ref{tbl-mainly-out-ps}. In
Figure~\ref{fig-2010-citations} I've graphed the number of citations
some prominent articles had in \emph{Philosophical Studies} and
elsewhere, with notable outliers labeled.\footnote{Note I've only
  included articles with 40 or more citations in the 2010s; otherwise
  the graph just gets overloaded at the bottom-left corner.}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/fig-2010-citations-1.pdf}}

}

\caption{\label{fig-2010-citations}Citations in \emph{Philosophical
Studies} and elsewhere. Details of the labeled papers are in the
bibliography.}

\end{figure}%

The simple takeaway from Figure~\ref{fig-2010-citations} is that
\emph{Philosophical Studies} in the 2010s published a lot of
epistemology, especially about contextualism and dogmatism, a lot of
metaphysics, especially about fundamentality, and a lot of papers on
free will. Most of these trends are continuous with earlier decades,
though the centrality of free will is somewhat new.\footnote{Derk
  Pereboom's work was particularly prominent in these discussions, as
  will also be noted in Table~\ref{tbl-names-early-late}.} On the other
hand, there was much less philosophy of science, political philosophy,
and logic. Again, this is mostly continuous with the journal's focus in
earlier decades.

The big change of the 2010s is the rise of social philosophy. This isn't
specific to \emph{Philosophical Studies}. Indeed, none of the stories
I'll tell here are particularly unique to \emph{Philosophical Studies};
everything that happens in the journal reflects wider trends in the
discipline. I'll start with some more superficial results, and end with
social philosophy.

I've already mentioned that articles get longer, and make more
references to ``Oxford'' over this decade.
Figure~\ref{fig-citations-by-year} shows how many more citations there
are to articles in philosophy journals.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/fig-citations-by-year-1.pdf}}

}

\caption{\label{fig-citations-by-year}Citations per article to other
philosophy journals in \emph{Philosophical Studies} 1980-2019.}

\end{figure}%

The graph isn't just going up, it is \emph{accelerating}. The data I
have from the 2020s suggests this trend does not stop.

\emph{Philosophical Studies} was founded to be a journal of analytic
philosophy. By the 2010s, what it meant to be doing analytic philosophy
had changed. It was less about analysis, and more about continuity with
a tradition. That continuity is still there; there are no radical breaks
in the citation patterns. But the word usage does change over time. One
way to see this is with words that were once more central to the
analytic project, like `logic' (Figure~\ref{fig-logic}), or `analysis'
(Figure~\ref{fig-analysis}), are being used less.\footnote{The middle
  graph in Figure~\ref{fig-analysis} is going up. That's in part because
  articles are getting longer, but more because bibliographies are
  getting longer, and `analysis' is a common word in bibliographies.}

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-14-1.pdf}}

}

\subcaption{\label{fig-analysis-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-14-2.pdf}}

}

\subcaption{\label{fig-analysis-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-14-3.pdf}}

}

\subcaption{\label{fig-analysis-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-analysis}``analysis''}

\end{figure*}%

We have to be a little careful here, because there are some purely
verbal trends that could be coming into play. The language of analytic
philosophy changed a fair bit over the 2000s and especially 2010s. There
are fewer `theories' and more `accounts'. There are fewer `criticisms'
and more `challenges'. I think the reduction in how often `logic' and
`analysis' are used reflects a move away from a certain style of doing
philosophy; but it's hard to conclusively rule out that it's not another
verbal trend.

There is more empirical work in \emph{Philosophical Studies} in the
2010s than in previous decades. Words like `experiment', `participants',
and `data' are all used more often than in previous decades. In each
case, though, the increase in usage is less pronounced than in other
philosophy journals.

There is a dramatic change in the 2010s in which philosophers are
frequently named in \emph{Philosophical Studies}. Rather than going
through twenty graphs, I'll just do a table comparing word usage for
prominent names before and after 2010. I'll mostly stick to names which,
in \emph{Philosophical Studies} at least, almost exclusively pick out
one philosopher. That said, I've included ``Schroeder'' because both
Mark and Tim are important to the story of the decade. It would take up
a lot of space to show all these graphs, and also the graphs are
incredibly noisy. In Table~\ref{tbl-names-early-late} and
Table~\ref{tbl-names-early-late-fall}, the rates shown are how often the
word on the left appears per 100,000 words. I've shown this for (a)
\emph{Philosophical Studies} 1980-2009, (b) \emph{Philosophical Studies}
from 2010-2019, (c) the twenty journals I'm comparing
\emph{Philosophical Studies} to in 1980-2009, and (d) those twenty
journals from 2010-2019.

\begin{table}

\caption{\label{tbl-names-early-late}Names that were used more after
2010.}

\centering{

\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrr}
\toprule
 & \multicolumn{2}{c}{Philosophical Studies} & \multicolumn{2}{c}{20 leading journals} \\ 
\cmidrule(lr){2-3} \cmidrule(lr){4-5}
 & 1980-2009 & 2010-2019 & 1980-2009 & 2010-2019 \\ 
\midrule\addlinespace[2.5pt]
Schroeder & 0.8 & 10.3 & 0.3 & 4.0 \\ 
Schaffer & 1.6 & 10.3 & 0.6 & 4.8 \\ 
Sider & 4.4 & 9.1 & 2.5 & 4.9 \\ 
Hawthorne & 2.8 & 8.3 & 1.2 & 5.5 \\ 
Schwitzgebel & 0.0 & 3.5 & 0.1 & 1.1 \\ 
Cappelen & 0.2 & 3.7 & 0.2 & 1.8 \\ 
Siegel & 0.3 & 4.1 & 0.5 & 1.4 \\ 
Enoch & 0.1 & 3.3 & 0.1 & 1.5 \\ 
Huemer & 0.8 & 4.8 & 0.3 & 1.9 \\ 
Pereboom & 1.1 & 5.2 & 0.5 & 2.0 \\ 
\bottomrule
\end{tabular*}

}

\end{table}%

\begin{table}

\caption{\label{tbl-names-early-late-fall}Names that were used less
after 2010.}

\centering{

\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrr}
\toprule
 & \multicolumn{2}{c}{Philosophical Studies} & \multicolumn{2}{c}{20 leading journals} \\ 
\cmidrule(lr){2-3} \cmidrule(lr){4-5}
 & 1980-2009 & 2010-2019 & 1980-2009 & 2010-2019 \\ 
\midrule\addlinespace[2.5pt]
Sellars & 9.1 & 1.1 & 3.2 & 1.4 \\ 
Chisholm & 7.6 & 1.9 & 2.7 & 1.4 \\ 
Putnam & 11.3 & 3.3 & 7.4 & 3.2 \\ 
Quine & 14.5 & 5.8 & 10.3 & 7.5 \\ 
Davidson & 14.0 & 4.9 & 9.1 & 3.8 \\ 
Wittgenstein & 5.2 & 2.1 & 10.6 & 4.3 \\ 
Aristotle & 8.7 & 4.0 & 11.5 & 5.7 \\ 
Plantinga & 5.8 & 2.8 & 2.4 & 1.6 \\ 
Searle & 6.2 & 3.1 & 3.5 & 1.9 \\ 
Fodor & 11.5 & 5.9 & 6.3 & 2.8 \\ 
\bottomrule
\end{tabular*}

}

\end{table}%

This seems like a set of fairly dramatic changes, in both directions.
And it is striking how much larger the change is in \emph{Philosophical
Studies} than in its peer journals.

The biggest story in metaphysics this decade was the end of what Sider
(\citeproc{ref-Sider2020}{2020}) calls the `modal era' in metaphysics.
From the late 1960s to the late 2000s, the most active discussions in
metaphysics were about ontology and modality. The most notable book of
this period, \emph{On the Plurality of Worlds}
(\citeproc{ref-Lewis1986a}{Lewis 1986}) was about both. From 2010
onwards, the focus shifted to discussions of fundamentality, priority,
and, most of all, grounding. As Figure~\ref{fig-grounding} (above)
shows, \emph{Philosophical Studies} was a big part of this shift.

Although there was less discussion of grounding before 2010, there were
several important, and widely cited, papers on grounding published in
\emph{Philosophical Studies} in the first part of the decade
(\citeproc{ref-WOS000341924300014}{Nolan 2014};
\citeproc{ref-WOS000325717500012}{Bliss 2013};
\citeproc{ref-WOS000289572300004}{Bennett 2011}). This discussion was
mainly confined to metaphysics. At the start of the modal era, modal
notions became commonplace across philosophy. That's mostly not happened
with grounding. That said, \emph{Philosophical Studies} has published
papers by Beddor (\citeproc{ref-WOS000356355000009}{2015}) and Wodak
(\citeproc{ref-WOS000468369800007}{2019}) that apply grounding ideas to
debates in epistemology.

Over the 2010s, the space between ethics and epistemology continued to
shrink. This wasn't an entirely new phenomenon; ``Why Be Rational?''
(\citeproc{ref-WOS000231037900002}{Kolodny 2005}) was arguably the most
cited ethics paper of the 2000s. But the focus on questions common to
ethics and epistemology, particularly about the nature of reasons, meant
the two fields were more entwined. Figure~\ref{fig-normative} and
Figure~\ref{fig-reasons} don't have as striking a hockey-stick shape as
Figure~\ref{fig-grounding}, but they are still fairly dramatic rises.

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-15-1.pdf}}

}

\subcaption{\label{fig-normative-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-15-2.pdf}}

}

\subcaption{\label{fig-normative-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-15-3.pdf}}

}

\subcaption{\label{fig-normative-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-normative}``normative''}

\end{figure*}%

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-15-4.pdf}}

}

\subcaption{\label{fig-reasons-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-15-5.pdf}}

}

\subcaption{\label{fig-reasons-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-15-6.pdf}}

}

\subcaption{\label{fig-reasons-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-reasons}``reasons''}

\end{figure*}%

The biggest story of the 2010s though, is the social turn across
philosophy. The decade saw a growing emphasis on social epistemology,
social metaphysics and social philosophy of language.
Figure~\ref{fig-social} displays the simplest way to measure this
growth: how often the word `social' is used.

\begin{figure*}

\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-16-1.pdf}}

}

\subcaption{\label{fig-social-first}Frequency}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-16-2.pdf}}

}

\subcaption{\label{fig-social-second}Appearances}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{phil-studies-november-2025_files/figure-pdf/unnamed-chunk-16-3.pdf}}

}

\subcaption{\label{fig-social-third}10+ Appearances}

\end{minipage}%

\caption{\label{fig-social}``social''}

\end{figure*}%

Figure~\ref{fig-social} might be misleading unless you know how
philosophers use `social'.\footnote{I'm grateful to {[}NAME{]} for this
  observation.} Almost anything involving multiple people will be
classed as social. There isn't a distinction here between interpersonal,
or what Darwall (\citeproc{ref-Darwall2006}{2006}) calls
second-personal, phenomena, and phenomena that only emerge at the level
of large societies. So the increased discussion of reactive attitudes,
especially blame, is part of this social turn. I'm not sure this is
optimal; society-level phenomena are rather different from phenomena
that arise in groups of two or three. But that's how the terminology has
developed, and I'll follow common practice here.

There are a lot of words that I could use to illustrate this, and
graphing all of them would take some space. So as with the names in
Table~\ref{tbl-names-early-late}, I'll present the results in some
tables.\footnote{I've looked at the graphs for all the terms to follow,
  and the three graphs for word count, word appearance, and word
  appearance 10 or more times all have similar shapes for these words.
  This is another reason to save space and use a table.}.
Table~\ref{tbl-social-general}, Table~\ref{tbl-social-ethics}, and
Table~\ref{tbl-social-epistemology} display some notable words whose
usage increased after the social turn in philosophy.

\begin{table}

\caption{\label{tbl-social-general}Uses of terms for groups.}

\centering{

\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrr}
\toprule
 & \multicolumn{2}{c}{Philosophical Studies} & \multicolumn{2}{c}{20 leading journals} \\ 
\cmidrule(lr){2-3} \cmidrule(lr){4-5}
 & 1980-2009 & 2010-2019 & 1980-2009 & 2010-2019 \\ 
\midrule\addlinespace[2.5pt]
group & 12.1 & 20.6 & 19.4 & 23.6 \\ 
groups & 3.8 & 8.5 & 8.8 & 10.1 \\ 
interpersonal & 1.8 & 4.8 & 1.7 & 3.3 \\ 
race & 1.8 & 10.8 & 3.9 & 5.6 \\ 
racial & 1.0 & 5.0 & 1.7 & 3.1 \\ 
gender & 1.1 & 5.2 & 1.9 & 2.6 \\ 
\bottomrule
\end{tabular*}

}

\end{table}%

\begin{table}

\caption{\label{tbl-social-ethics}Uses of terms associated with
interpersonal ethics.}

\centering{

\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrr}
\toprule
 & \multicolumn{2}{c}{Philosophical Studies} & \multicolumn{2}{c}{20 leading journals} \\ 
\cmidrule(lr){2-3} \cmidrule(lr){4-5}
 & 1980-2009 & 2010-2019 & 1980-2009 & 2010-2019 \\ 
\midrule\addlinespace[2.5pt]
praise & 2.7 & 3.5 & 1.5 & 1.8 \\ 
blame & 5.5 & 15.1 & 3.3 & 8.6 \\ 
blameworthy & 2.4 & 8.0 & 1.1 & 3.9 \\ 
friend & 5.2 & 8.0 & 4.7 & 5.5 \\ 
friends & 3.6 & 7.8 & 4.4 & 4.5 \\ 
friendship & 1.0 & 3.7 & 3.7 & 2.7 \\ 
\bottomrule
\end{tabular*}

}

\end{table}%

\begin{table}

\caption{\label{tbl-social-epistemology}Uses of terms from social
epistemology and social philosophy of language}

\centering{

\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrr}
\toprule
 & \multicolumn{2}{c}{Philosophical Studies} & \multicolumn{2}{c}{20 leading journals} \\ 
\cmidrule(lr){2-3} \cmidrule(lr){4-5}
 & 1980-2009 & 2010-2019 & 1980-2009 & 2010-2019 \\ 
\midrule\addlinespace[2.5pt]
communicative & 1.2 & 4.0 & 1.3 & 2.3 \\ 
testimony & 5.0 & 13.6 & 5.2 & 9.3 \\ 
trust & 3.2 & 7.3 & 5.3 & 9.8 \\ 
disagree & 5.6 & 8.8 & 4.0 & 7.3 \\ 
disagreement & 7.8 & 20.6 & 5.0 & 16.6 \\ 
deference & 0.7 & 5.6 & 0.6 & 3.3 \\ 
\bottomrule
\end{tabular*}

}

\end{table}%

There are other terms where the rise is more dramatic. Between 1980 and
2009, the terms `slur', `slurs' and `slurring' appeared a total of 10
times. Between 2010 and 2019 they appeared 266 times.

So we have some evidence for a social turn in \emph{Philosophical
Studies}. That said, the turn was far from complete by 2019. In
Table~\ref{tbl-social-general}, the usage of `group' and `groups' goes
up in \emph{Philosophical Studies}, but by less than it goes up
elsewhere. The same is true of `trust' in
Table~\ref{tbl-social-epistemology}. That result is backed up by the
citation data. The widely cited articles from
Figure~\ref{fig-2010-citations} with `trust' in the title are cited
about half as often in \emph{Philosophical Studies} as you'd expect
given their citations elsewhere.\footnote{There are five such articles:
  Goldman (\citeproc{ref-WOS000170434600004}{2001}), Baier
  (\citeproc{ref-WOSA1986AYY3900001}{1986}), Hardwig
  (\citeproc{ref-WOSA1991GR87800001}{1991}), Holton
  (\citeproc{ref-WOSA1994NA94600005}{1994}), Jones
  (\citeproc{ref-WOSA1996VL52500002}{1996}). They have 12 citations in
  \emph{Philosophical Studies} in the decade, and 271 elsewhere; a ratio
  of about 1:23. The average ratio on the graph is about 1:12.} For
another example, Kristie Dotson's paper on epistemic violence
(\citeproc{ref-WOS000289948200002}{Dotson 2011}) is one of the most
cited papers of the 2010s, but it doesn't get cited in
\emph{Philosophical Studies} until 2019
(\citeproc{ref-WOS000460037300009}{Matthes 2019}). It has been cited
more often in \emph{Philosophical Studies} since 2019, one sign among
many that the social turn is still continuing.

\section{Conclusions and Further
Questions}\label{conclusions-and-further-questions}

One theme of this essay has been the change in the status of
\emph{Philosophical Studies}. In 1980, it primarily published papers
that responded to ideas introduced in books or higher prestige journals
some time earlier, often several years earlier. A few decades later, it
publishes papers that set the research agenda for other journals. There
are two interestingly different stories for how this could have
happened.

Philosophy is notoriously hierarchical. If you're reading this journal
you probably don't need much evidence for this. If you want such
evidence, look back to Table~\ref{tbl-citation-rate}. If
\emph{Philosophical Studies} is playing more of an agenda setting role,
this could be because it has moved up in the hierarchy, or because the
hierarchy is getting flatter. (Or both, these are not exclusive.) When
\emph{Noûs} underwent a similar change a decade or two before
\emph{Philosophical Studies}, this was not a sign of the hierarchy
flattening; \emph{Noûs} just got more prestigious. In this case it's
possible we are seeing a journal ecosystem that is getting more
receptive to ideas from places it had traditionally treated as lower
prestige. But it's also possible that all we're seeing is one journal
move up while others move down. This can't be resolved by just looking
at one journal, and it's an interesting question for future research.

\emph{Philosophical Studies} is often referred to as a generalist
journal. I've presented some reasons here for questioning that label. It
doesn't publish much logic, or history of philosophy, or political
philosophy, or philosophy of various academic subjects, e.g.,
mathematics, biology, economics, history, or music. One question is
whether that should matter. Must one publish articles on philosophy of
history to be a generalist journal? If so, how many such articles must
one publish? If this is a reason for not counting \emph{Philosophical
Studies} as truly generalist, are there \emph{any} generalist journals
in philosophy. If so, what are they, and how would we tell?\footnote{If
  there are any, I suspect much newer journals like \emph{Ergo} and
  \emph{Journal of the American Philosophical Association} are the best
  candidates.}

But the biggest open questions are ones we cannot answer until we see
how philosophy itself develops. The very short version of the story of
\emph{Philosophical Studies} over these four decades is that it moved
from being centered on core analytic questions about language, to first
covering more epistemology, and then doing more empirical and social
philosophy. These moves tracked broader changes in the discipline, and
they don't seem to be slowing over the 2020s.

We can make some of these questions more precise. Will metaphysics
continue to be post-modal, or will we see a revival of modal
metaphysics? Will philosophy of mind continue its trend of becoming more
empirical, or will there be a return to armchair approaches? Will
epistemology and ethics continue to move closer together? Will
philosophy of language keep moving closer to linguistics? And, most of
all, will the social turn across so many different parts of philosophy
continue? If it does, will it turn more towards questions about society
as a whole, or will it continue to be based in interpersonal, or
second-personal, phenomena?

One could use the evidence from these four decades of
\emph{Philosophical Studies} to give two contradictory answers to these
questions. On the one hand, the trends, especially since 2014, seem so
dramatic it's hard to imagine them suddenly reversing. (And the
preliminary data we have from the early 2020s backs up this intuition.)
On the other hand, previous trends have ended rather abruptly, without
much obvious warning, and perhaps these trends will as well.

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-WOSA1985AKA2200025}
Alchourrón, Carlos E., Peter Gärdenfors, and David Makinson. 1985. {``On
the Logic of Theory Change: Partial Meet Contraction and Revision
Functions.''} \emph{Journal of Symbolic Logic} 50 (2): 510--30. doi:
\href{https://doi.org/10.2307/2274239}{10.2307/2274239}.

\bibitem[\citeproctext]{ref-WOS000078432400003}
Anderson, Elizabeth S. 1999. {``What Is the Point of Equality?''}
\emph{Ethics} 109 (2): 287--337. doi:
\href{https://doi.org/10.1086/233897}{10.1086/233897}.

\bibitem[\citeproctext]{ref-WOSA1985ABV7900005}
Asher, Nicholas, and Daniel Bonevac. 1985. {``Situations and Events.''}
\emph{Philosophical Studies} 47 (1): 57--77. doi:
\href{https://doi.org/10.1007/BF00355087}{10.1007/BF00355087}.

\bibitem[\citeproctext]{ref-WOSA1986AYY3900001}
Baier, Annette. 1986. {``Trust and Antitrust.''} \emph{Ethics} 96 (2):
231--60. doi: \href{https://doi.org/10.1086/292745}{10.1086/292745}.

\bibitem[\citeproctext]{ref-WOSA1996UE45200001}
Bealer, George. 1996. {``A-Priori Knowledge and the Scope of
Philosophy.''} \emph{Philosophical Studies} 81 (2-3): 121--42. doi:
\href{https://doi.org/10.1007/BF00372777}{10.1007/BF00372777}.

\bibitem[\citeproctext]{ref-WOS000356355000009}
Beddor, Bob. 2015. {``Evidentialism, Circularity, and Grounding.''}
\emph{Philosophical Studies} 172 (7): 1847--68. doi:
\href{https://doi.org/10.1007/s11098-014-0375-z}{10.1007/s11098-014-0375-z}.

\bibitem[\citeproctext]{ref-WOS000289572300004}
Bennett, Karen. 2011. {``Construction Area (No Hard Hat Required).''}
\emph{Philosophical Studies} 154 (1): 79--104. doi:
\href{https://doi.org/10.1007/s11098-011-9703-8}{10.1007/s11098-011-9703-8}.

\bibitem[\citeproctext]{ref-WOSA1988M482100005}
Blackburn, William K. 1988. {``Wettstein on Definite Descriptions.''}
\emph{Philosophical Studies} 53 (2): 263--78. doi:
\href{https://doi.org/10.1007/BF00354644}{10.1007/BF00354644}.

\bibitem[\citeproctext]{ref-WOS000325717500012}
Bliss, Ricki Leigh. 2013. {``Viciousness and the Structure of
Reality.''} \emph{Philosophical Studies} 166 (2): 399--418. doi:
\href{https://doi.org/10.1007/s11098-012-0043-0}{10.1007/s11098-012-0043-0}.

\bibitem[\citeproctext]{ref-WOS000340619100006}
Bourget, David, and David J. Chalmers. 2014. {``What Do Philosophers
Believe?''} \emph{Philosophical Studies} 170 (3): 465--500. doi:
\href{https://doi.org/10.1007/s11098-013-0259-7}{10.1007/s11098-013-0259-7}.

\bibitem[\citeproctext]{ref-WOSA1991FC38500010}
Boyd, Richard. 1991. {``Realism, Anti-Foundationalism and the Enthusiasm
for Natural Kinds.''} \emph{Philosophical Studies} 61 (1-2): 127--48.
doi: \href{https://doi.org/10.1007/BF00385837}{10.1007/BF00385837}.

\bibitem[\citeproctext]{ref-WOS000084073700005}
Broome, John. 1999. {``Normative Requirements.''} \emph{Ratio} 12 (4):
398--419. doi:
\href{https://doi.org/10.1111/1467-9329.00101}{10.1111/1467-9329.00101}.

\bibitem[\citeproctext]{ref-WOS000241143100001}
Brown, J. 2006. {``Contextualism and Warranted Assertibility
Manoeuvres.''} \emph{Philosophical Studies} 130 (3): 407--35. doi:
\href{https://doi.org/10.1007/s11098-004-5747-3}{10.1007/s11098-004-5747-3}.

\bibitem[\citeproctext]{ref-Brzezinski2015}
Brzezinski, Michal. 2015. {``Power Laws in Citation Distributions:
Evidence from Scopus.''} \emph{Scientometrics} 103 (1): 213--28. doi:
\href{https://doi.org/10.1007/s11192-014-1524-z}{10.1007/s11192-014-1524-z}.

\bibitem[\citeproctext]{ref-WOSA1986AYX3200001}
Burge, Tyler. 1986. {``Individualism and Psychology.''}
\emph{Philosophical Review} 95 (1): 3--45. doi:
\href{https://doi.org/10.2307/2185131}{10.2307/2185131}.

\bibitem[\citeproctext]{ref-WOSA1962CGX0500005}
Cavell, S. 1962. {``The Availability of Wittgenstein's Later
Philosophy.''} \emph{Philosophical Review} 71 (1): 67--93. doi:
\href{https://doi.org/10.2307/2183682}{10.2307/2183682}.

\bibitem[\citeproctext]{ref-WOS000073222300002}
Clark, Andy, and David J. Chalmers. 1998. {``The Extended Mind.''}
\emph{Analysis} 58 (1): 7--19. doi:
\href{https://doi.org/10.1111/1467-8284.00096}{10.1111/1467-8284.00096}.

\bibitem[\citeproctext]{ref-WOSA1989AE70300010}
Cohen, G. A. 1989. {``On the Currency of Egalitarian Justice.''}
\emph{Ethics} 99 (4): 906--44. doi:
\href{https://doi.org/10.1086/293126}{10.1086/293126}.

\bibitem[\citeproctext]{ref-WOS000178597300004}
Cohen, Stewart. 2002. {``Basic Knowledge and the Problem of Easy
Knowledge.''} \emph{Philosophy and Phenomenological Research} 65 (2):
309--29. doi:
\href{https://doi.org/10.1111/j.1933-1592.2002.tb00204.x}{10.1111/j.1933-1592.2002.tb00204.x}.

\bibitem[\citeproctext]{ref-WOSA1986D182100003}
Cross, Charles B. 1986. {``Can and the Logic of Ability.''}
\emph{Philosophical Studies} 50 (1): 53--64. doi:
\href{https://doi.org/10.1007/BF00355160}{10.1007/BF00355160}.

\bibitem[\citeproctext]{ref-WOSA1975BF60100001}
Cummins, Robert. 1975. {``Functional Analysis.''} \emph{Journal of
Philosophy} 72 (20): 741--65. doi:
\href{https://doi.org/10.2307/2024640}{10.2307/2024640}.

\bibitem[\citeproctext]{ref-Darwall2006}
Darwall, Stephen. 2006. \emph{The Second Person Standpoint: Morality,
Respect, and Accountability,}. Cambridge, MA: Harvard University Press.

\bibitem[\citeproctext]{ref-WOS000245280900001}
Davis, Wayne A. 2007. {``Knowledge Claims and Context: Loose Use.''}
\emph{Philosophical Studies} 132 (3): 395--438. doi:
\href{https://doi.org/10.1007/s11098-006-9035-2}{10.1007/s11098-006-9035-2}.

\bibitem[\citeproctext]{ref-WOSA1995RC31600001}
DeRose, Keith. 1995. {``Solving the Skeptical Problem.''}
\emph{Philosophical Review} 104 (1): 1--52. doi:
\href{https://doi.org/10.2307/2186011}{10.2307/2186011}.

\bibitem[\citeproctext]{ref-DeVries2005}
DeVries, Willem A. 2005. \emph{Wilfrid Sellars}. Abingdon: Routledge.

\bibitem[\citeproctext]{ref-WOS000289948200002}
Dotson, Kristie. 2011. {``Tracking Epistemic Violence, Tracking
Practices of Silencing.''} \emph{Hypatia} 26 (2): 236--57. doi:
\href{https://doi.org/10.1111/j.1527-2001.2011.01177.x}{10.1111/j.1527-2001.2011.01177.x}.

\bibitem[\citeproctext]{ref-WOSA1970ZE33800001}
Dretske, Fred. 1970. {``Epistemic Operators.''} \emph{Journal of
Philosophy} 67 (24): 1007--23. doi:
\href{https://doi.org/10.2307/2024710}{10.2307/2024710}.

\bibitem[\citeproctext]{ref-WOSA1995QX94800001}
Edgington, Dorothy. 1995. {``On Conditionals.''} \emph{Mind} 104 (414):
235--329. doi:
\href{https://doi.org/10.1093/mind/104.414.235}{10.1093/mind/104.414.235}.

\bibitem[\citeproctext]{ref-WOS000245280800001}
Egan, Andy. 2007. {``Epistemic Modals, Relativism and Assertion.''}
\emph{Philosophical Studies} 133 (1): 1--22. doi:
\href{https://doi.org/10.1007/s11098-006-9003-x}{10.1007/s11098-006-9003-x}.

\bibitem[\citeproctext]{ref-Egan2011}
---------. 2011. {``Comments on Gendler's, 'the Epistemic Costs of
Implicit Bias'.''} \emph{Philosophical Studies} 156 (1): 65--79. doi:
\href{https://doi.org/10.1007/s11098-011-9803-5}{10.1007/s11098-011-9803-5}.

\bibitem[\citeproctext]{ref-Fodor1998}
Fodor, Jerry A. 1998. \emph{Concepts: Where Cognitive Science Went
Wrong}. Oxford: Oxford University Press.

\bibitem[\citeproctext]{ref-FodorLepore1992}
Fodor, Jerry A., and Ernest Lepore. 1992. \emph{Holism: A Shopper's
Guide}. Cambridge: Blackwell.

\bibitem[\citeproctext]{ref-WOSA1995QE80400001}
van Fraassen, Bas C. 1995. {``Belief and the Problem of Ulysses and the
Sirens.''} \emph{Philosophical Studies} 77 (1): 7--37. doi:
\href{https://doi.org/10.1007/BF00996309}{10.1007/BF00996309}.

\bibitem[\citeproctext]{ref-WOSA1969Y444700002}
Frankfurt, Harry G. 1969. {``Alternate Possibilities and Moral
Responsibility.''} \emph{Journal of Philosophy} 66 (23): 829--39. doi:
\href{https://doi.org/10.2307/2023833}{10.2307/2023833}.

\bibitem[\citeproctext]{ref-WOS000295087100003}
Gendler, Tamar Szabò. 2011. {``On the Epistemic Costs of Implicit
Bias.''} \emph{Philosophical Studies} 156 (1): 33--63. doi:
\href{https://doi.org/10.1007/s11098-011-9801-7}{10.1007/s11098-011-9801-7}.

\bibitem[\citeproctext]{ref-WOSA1985ANT6600005}
Gensler, Harry J. 1985. {``A Kantian Argument Against Abortion.''}
\emph{Philosophical Studies} 48 (1): 57--72. doi:
\href{https://doi.org/10.1007/BF00372407}{10.1007/BF00372407}.

\bibitem[\citeproctext]{ref-WOSA1986AZA8100007}
---------. 1986. {``A Kantian Argument Against Abortion.''}
\emph{Philosophical Studies} 49 (1): 83--98. doi:
\href{https://doi.org/10.1007/BF00372885}{10.1007/BF00372885}.

\bibitem[\citeproctext]{ref-WOS000170434600004}
Goldman, Alvin I. 2001. {``Experts: Which Ones Should You Trust?''}
\emph{Philosophy and Phenomenological Research} 63 (1): 85--110. doi:
\href{https://doi.org/10.2307/3071090}{10.2307/3071090}.

\bibitem[\citeproctext]{ref-WOSA1991GR87800001}
Hardwig, John. 1991. {``The Role of Trust in Knowledge.''} \emph{Journal
of Philosophy} 88 (12): 693--708. doi:
\href{https://doi.org/10.2307/2027007}{10.2307/2027007}.

\bibitem[\citeproctext]{ref-WOSA1984TJ24700012}
Hazen, Allen. 1984. {``Modality as Many Metalinguistic Predicates.''}
\emph{Philosophical Studies} 46 (2): 271--77. doi:
\href{https://doi.org/10.1007/BF00373111}{10.1007/BF00373111}.

\bibitem[\citeproctext]{ref-WOSA1997XH01200003}
Hill, Christopher S. 1997. {``Imaginability, Conceivability, Possibility
and the Mind-Body Problem.''} \emph{Philosophical Studies} 87 (1):
61--85. doi:
\href{https://doi.org/10.1023/A:1017911200883}{10.1023/A:1017911200883}.

\bibitem[\citeproctext]{ref-WOSA1994NA94600005}
Holton, Richard. 1994. {``Deciding To Trust, Coming To Believe.''}
\emph{Australasian Journal of Philosophy} 72 (1): 63--76. doi:
\href{https://doi.org/10.1080/00048409412345881}{10.1080/00048409412345881}.

\bibitem[\citeproctext]{ref-Jackson1998}
Jackson, Frank. 1998. \emph{From Metaphysics to Ethics: A Defence of
Conceptual Analysis}. Clarendon Press: Oxford.

\bibitem[\citeproctext]{ref-WOSA1992KC39800002}
Johnston, Mark. 1992. {``How To Speak of the Colors.''}
\emph{Philosophical Studies} 68 (3): 221--63. doi:
\href{https://doi.org/10.1007/BF00694847}{10.1007/BF00694847}.

\bibitem[\citeproctext]{ref-WOSA1996VL52500002}
Jones, Karen. 1996. {``Trust as An Affective Attitude.''} \emph{Ethics}
107 (1): 4--25. doi:
\href{https://doi.org/10.1086/233694}{10.1086/233694}.

\bibitem[\citeproctext]{ref-WOSA1989CE37600001}
Kamm, FM. 1989. {``Harming Some To Save Others.''} \emph{Philosophical
Studies} 57 (3): 227--60. doi:
\href{https://doi.org/10.1007/BF00372696}{10.1007/BF00372696}.

\bibitem[\citeproctext]{ref-WOS000178572700004}
Kelly, Thomas. 2002. {``The Rationality of Belief and Some Other
Propositional Attitudes.''} \emph{Philosophical Studies} 110 (2):
163--96. doi:
\href{https://doi.org/10.1023/A:1020212716425}{10.1023/A:1020212716425}.

\bibitem[\citeproctext]{ref-WOSA1988P180000006}
King, Jeffrey C. 1988. {``Are Indefinite Descriptions Ambiguous.''}
\emph{Philosophical Studies} 53 (3): 417--40. doi:
\href{https://doi.org/10.1007/BF00353515}{10.1007/BF00353515}.

\bibitem[\citeproctext]{ref-WOSA1981NA08400001}
Kitcher, Philip. 1981. {``Explanatory Unification.''} \emph{Philosophy
of Science} 48 (4): 507--31. doi:
\href{https://doi.org/10.1086/289019}{10.1086/289019}.

\bibitem[\citeproctext]{ref-WOS000231037900002}
Kolodny, Niko. 2005. {``Why Be Rational?''} \emph{Mind} 114 (455):
509--63. doi:
\href{https://doi.org/10.1093/mind/fzi509}{10.1093/mind/fzi509}.

\bibitem[\citeproctext]{ref-WOSA1975BF60000005}
Kripke, Saul. 1975. {``Outline of a Theory of Truth.''} \emph{Journal of
Philosophy} 72 (19): 690--716. doi:
\href{https://doi.org/10.2307/2024634}{10.2307/2024634}.

\bibitem[\citeproctext]{ref-WOS000086712500005}
Latham, Noa. 2000. {``Chalmers on the Addition of Consciousness To the
Physical World.''} \emph{Philosophical Studies} 98 (1): 71--97.

\bibitem[\citeproctext]{ref-WOSA1981LY92900002}
Laudan, Larry. 1981. {``A Confutation of Convergent Realism.''}
\emph{Philosophy of Science} 48 (1): 19--49. doi:
\href{https://doi.org/10.1086/288975}{10.1086/288975}.

\bibitem[\citeproctext]{ref-Lederman2022PR}
Lederman, Harvey. 2022. {``The Introspective Model of Genuine Knowledge
in Wang Yangming.''} \emph{Philosophical Review} 131 (2): 169--213. doi:
\href{https://doi.org/10.1215/00318108-9554691}{10.1215/00318108-9554691}.

\bibitem[\citeproctext]{ref-WOSA1979JB14500003}
Lewis, David. 1979. {``Counterfactual Dependence and Time's Arrow.''}
\emph{Noûs} 13 (4): 455--76. doi:
\href{https://doi.org/10.2307/2215339}{10.2307/2215339}.

\bibitem[\citeproctext]{ref-WOSA1983RR51600001}
---------. 1983. {``New Work for a Theory of Universals.''}
\emph{Australasian Journal of Philosophy} 61 (4): 343--77. doi:
\href{https://doi.org/10.1080/00048408312341131}{10.1080/00048408312341131}.

\bibitem[\citeproctext]{ref-WOSA1984TQ70900001}
---------. 1984. {``Putnam's Paradox.''} \emph{Australasian Journal of
Philosophy} 62 (3): 221--36. doi:
\href{https://doi.org/10.1080/00048408412340013}{10.1080/00048408412340013}.

\bibitem[\citeproctext]{ref-Lewis1986a}
---------. 1986. \emph{On the Plurality of Worlds}. Oxford: Blackwell
Publishers.

\bibitem[\citeproctext]{ref-WOSA1996VY21200001}
---------. 1996. {``Elusive Knowledge.''} \emph{Australasian Journal of
Philosophy} 74 (4): 549--67. doi:
\href{https://doi.org/10.1080/00048409612347521}{10.1080/00048409612347521}.

\bibitem[\citeproctext]{ref-WOSA1997WP33800001}
---------. 1997. {``Finkish Dispositions.''} \emph{Philosophical
Quarterly} 47 (187): 143--58. doi:
\href{https://doi.org/10.1111/1467-9213.00052}{10.1111/1467-9213.00052}.

\bibitem[\citeproctext]{ref-Lewy1976}
Lewy, C. 1976. {``Mind Under {G. E. Moore} (1921-1947).''} \emph{Mind}
85 (337): 37--46. doi:
\href{https://doi.org/10.1093/mind/LXXXV.337.37}{10.1093/mind/LXXXV.337.37}.

\bibitem[\citeproctext]{ref-WOS000087305900001}
Machamer, Peter, Lindley Darden, and Carl F. Craver. 2000. {``Thinking
About Mechanisms.''} \emph{Philosophy of Science} 67 (1): 1--25. doi:
\href{https://doi.org/10.1086/392759}{10.1086/392759}.

\bibitem[\citeproctext]{ref-Malaterre2019}
Malaterre, Christophe, Jean-François Chartier, and Davide Pulizzotto.
2019. {``What Is This Thing Called Philosophy of Science? A
Computational Topic-Modeling Perspective, 1934?2015.''} \emph{Hopos: The
Journal of the International Society for the History of Philosophy of
Science} 9 (2): 215--49. doi:
\href{https://doi.org/10.1086/704372}{10.1086/704372}.

\bibitem[\citeproctext]{ref-Malaterre2022}
Malaterre, Christophe, and Francis Lareau. 2022. {``The Early Days of
Contemporary Philosophy of Science: Novel Insights from Machine
Translation and Topic-Modeling of Non-Parallel Multilingual Corpora.''}
\emph{Synthese} 200 (3): 1--33. doi:
\href{https://doi.org/10.1007/s11229-022-03722-x}{10.1007/s11229-022-03722-x}.

\bibitem[\citeproctext]{ref-Malaterre2020}
Malaterre, Christophe, Francis Lareau, Davide Pulizzotto, and Jonathan
St-Onge. 2020. {``Eight Journals over Eight Decades: A Computational
Topic-Modeling Approach to Contemporary Philosophy of Science.''}
\emph{Synthese} 199 (1-2): 2883--923. doi:
\href{https://doi.org/10.1007/s11229-020-02915-6}{10.1007/s11229-020-02915-6}.

\bibitem[\citeproctext]{ref-Malaterre2019b}
Malaterre, Christophe, Davide Pulizzotto, and Francis Lareau. 2019.
{``Revisiting Three Decades of Biology and Philosophy: A Computational
Topic-Modeling Perspective.''} \emph{Biology and Philosophy} 35 (5):
1--25. doi:
\href{https://doi.org/10.1007/s10539-019-9729-4}{10.1007/s10539-019-9729-4}.

\bibitem[\citeproctext]{ref-WOS000460037300009}
Matthes, Erich Hatala. 2019. {``Cultural Appropriation and
Oppression.''} \emph{Philosophical Studies} 176 (4): 1003--13. doi:
\href{https://doi.org/10.1007/s11098-018-1224-2}{10.1007/s11098-018-1224-2}.

\bibitem[\citeproctext]{ref-WOSA1974U469700001}
Nagel, Thomas. 1974. {``What Is It Like To Be a Bat.''}
\emph{Philosophical Review} 83 (4): 435--50. doi:
\href{https://doi.org/10.2307/2183914}{10.2307/2183914}.

\bibitem[\citeproctext]{ref-WOS000341924300014}
Nolan, Daniel. 2014. {``Hyperintensional Metaphysics.''}
\emph{Philosophical Studies} 171 (1): 149--60. doi:
\href{https://doi.org/10.1007/s11098-013-0251-2}{10.1007/s11098-013-0251-2}.

\bibitem[\citeproctext]{ref-WOS000083809100001}
Ostertag, Gary. 1999. {``A Scorekeeping Error.''} \emph{Philosophical
Studies} 96 (2): 123--46. doi:
\href{https://doi.org/10.1023/A:1004293605139}{10.1023/A:1004293605139}.

\bibitem[\citeproctext]{ref-Petrovich2024}
Petrovich, Eugenio. 2024. \emph{A Quantitative Portrait of Analytic
Philosophy: Looking Through the Margins}. Cham: Springer.

\bibitem[\citeproctext]{ref-WOS000165361800002}
Pryor, James. 2000. {``The Skeptic and the Dogmatist.''} \emph{Noûs} 34
(4): 517--49. doi:
\href{https://doi.org/10.1111/0029-4624.00277}{10.1111/0029-4624.00277}.

\bibitem[\citeproctext]{ref-WOSA1980KH88100001}
Rawls, John. 1980. {``Kantian Constructivism in Moral Theory.''}
\emph{Journal of Philosophy} 77 (9): 515--35. doi:
\href{https://doi.org/10.2307/2025790}{10.2307/2025790}.

\bibitem[\citeproctext]{ref-WOS000222384400005}
Schaffer, Jonathan. 2004. {``From Contextualism To Contrastivism.''}
\emph{Philosophical Studies} 119 (1-2): 73--103. doi:
\href{https://doi.org/10.1023/B:PHIL.0000029351.56460.8c}{10.1023/B:PHIL.0000029351.56460.8c}.

\bibitem[\citeproctext]{ref-WOS000272855000002}
---------. 2010. {``Monism: The Priority of the Whole.''}
\emph{Philosophical Review} 119 (1): 31--76. doi:
\href{https://doi.org/10.1215/00318108-2009-025}{10.1215/00318108-2009-025}.

\bibitem[\citeproctext]{ref-Sider2020}
Sider, Theodore. 2020. \emph{The Tools of Metaphysics and the
Metaphysics of Science}. Oxford: Oxford University Press.

\bibitem[\citeproctext]{ref-WOSA1972Z066400001}
Singer, Peter. 1972. {``Famine, Affluence, and Morality.''}
\emph{Philosophy \& Public Affairs} 1 (3): 229--43.

\bibitem[\citeproctext]{ref-WOSA1989CE37600004}
Terzis, George N. 1989. {``An Objection To Kantian Ethical
Rationalism.''} \emph{Philosophical Studies} 57 (3): 299--313. doi:
\href{https://doi.org/10.1007/BF00372699}{10.1007/BF00372699}.

\bibitem[\citeproctext]{ref-Thomson1971}
Thomson, Judith Jarvis. 1971. {``A Defense of Abortion.''}
\emph{Philosophy and Public Affairs} 1 (1): 47--66.

\bibitem[\citeproctext]{ref-WOSA1984SK63200001}
Tichý, Pavel. 1984. {``Subjunctive Conditionals: Two Parameters
Vs.~Three.''} \emph{Philosophical Studies} 45 (2): 147--79. doi:
\href{https://doi.org/10.1007/BF00372476}{10.1007/BF00372476}.

\bibitem[\citeproctext]{ref-Warnock1976}
Warnock, G. J. 1976. {``Gilbert Ryle's Editorship.''} \emph{Mind} 85
(337): 47--56. doi:
\href{https://doi.org/10.1093/mind/LXXXV.337.47}{10.1093/mind/LXXXV.337.47}.

\bibitem[\citeproctext]{ref-WOS000168853300001}
Williams, Michael. 2001. {``Contextualism, Externalism and Epistemic
Standards.''} \emph{Philosophical Studies} 103 (1): 1--23. doi:
\href{https://doi.org/10.1023/A:1010349100272}{10.1023/A:1010349100272}.

\bibitem[\citeproctext]{ref-WOS000468369800007}
Wodak, Daniel. 2019. {``Moral Perception, Inference, and Intuition.''}
\emph{Philosophical Studies} 176 (6): 1495--1512. doi:
\href{https://doi.org/10.1007/s11098-019-01250-y}{10.1007/s11098-019-01250-y}.

\end{CSLReferences}



\noindent Draft for submission


\end{document}
