---
title: "Is Choice Binary?"
abstract: |
  There is a natural view about how preference relates to choice. On this view, an option is choiceworthy iff no alternative is strictly preferred to it. I'm going to argue against this, for two reasons. First, the view makes a false prediction about which options are choiceworthy in games and in choices between options that differ along multiple dimensions. Second, choice is fundamentally about how options are evaluated prior to a decision, while preference is about how they are (or will be) evaluated post decision. Several consequences of rejecting this natural view are explored, including how it simplifies the relationship between game theory and decision theory, and how it complicates several debates about so-called 'incomplete' preferences.
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
date: today
#thanks: "This article grew out of discussions in Jim Joyce's epistemology seminar at the University of Michigan in Winter term 2024. Thanks to Jim and to the other seminar participants, especially Mitch Barrington, Paulina Ezquerra, Ina Jantgen, Gabrielle Kerbel, Calum McNamara, and Brett Thompson. Thanks also to a reviewer for the AJL who suggested several improvements to the paper."
draft: true
citation: false
categories:
  - games and decisions
format:
  html:
    css: ../trad_defn.css
  pdf:
    output-file: "Is Choice Binary?"
    include-in-header: 
      - text: |
         \usepackage{amsfonts}
    include-after-body: 
      text: |
         \noindent Draft of June 2025
---

Decision theory is, as the name suggests, about how decisions should be made. In real life situations, a chooser has many options available. But the usual way decision theory is formulated gives special place to the chooser's thoughts either about individual options, or about pairs of options. Typically, it either says here's a value function, which maps options to values, and chooser should choose the one with highest value, or it says here's a preference relation, and chosoer should choose one to which no other option is preferred. In this paper, I'm going to argue both these approaches are mistaken. Decision theory has to pay attention to the distinctive features of choices involving more than two options. This is both interesting in its own right, and has implications for theories of so-called 'incomplete' preferences.

# Historical Background {#sec-history}

There is a long tradition in both the economic literature (e.g., @Samuelson1938) and the psychological literature (e.g., @Luce1956), of taking choice dispositions to be the central focus of study, as opposed to values or preferences. Some of the reasons for this were based on behaviourist or positivist commitments. The theorists would have endorsed this recent statement of the irrelevance of mental states to economics.

> Standard economics does not address mental processes and, as a result, economic abstractions are typically not appropriate for describing them. [@GulPesendorfer2008 24]

That's not going to be my approach here. I'm going to start not with observable choice dispositions, like Samuelson, or choice frequencies, like Luce, but with chooser's beliefs about which options are choiceworthy. In familiar terminology^[See, for instance, @SEPPreferences, where I learned about the Gul and Pesendorfer quote], I'm taking a mentalist approach not a behaviourist approach. Much of the formal work on choice theory has been done by theorists from the behaviourist side, and I'll be inevitably drawing from them. But the most important source I'll be using is someone much more sympathetic to mentalism: Amartya Sen. In particular, I'll draw heavily on his "Collective Choice and Social Welfare" [@Sen1970sec]. So I need to start with the way he talks about preferences in that book, which is slightly different to the current philosophical orthodoxy.

Sen starts with a binary relation *R*, defined over options, which is glossed as *xRy* means that *x* is at least as good as *y*. This is potentially misleading. It does not mean that *x* is either better than *y*, or exactly as good as *y*. Rather, it means that *x* is no worse than *y*. Sen introduces two more binary relations, *xPy*, meaning *x* is preferred to *y*, and *xIy*, meaning the chooser is between *x* and *y*. These can both be defined in terms of *R*, as in (@RtoP) and (@RtoI). (Throughout, I'm leaving off wide scope universal quantifiers over free variables.)

(@RtoP) *xPy* ↔︎ (*xRy* ∧ ¬*yRx*)
(@RtoI) *xIy* ↔︎ (*xRy* ∧ *yRx*)

A more common way of doing things in contemporary philosophy is to start with *P* and a fourth relation *E*, where *xEy* means that *x* and *y* are equally good. On this picture, both (@RtoP) and (@RtoI), but the explanatory direction in (@RtoP) is right-to-left. So *xRy* just is ¬*xPy*, and then *xIy* is still defined via (@RtoI). On the version Sen uses, it's a little trickier to define *E*, but (@EtoR) looks like a plausible conjecture.

(@EtoR) *xEy* ↔︎ [(*xRz* ↔︎ *yRz*) ∧ (*zRx* ↔︎ *zRy*)]

That is, two options are equally good iff they are substitutable in other preference relations. Given all these results, we can show that the following claims are all tightly connected.

(@Tri) *xPy* ∨ *xEy* ∨ *yPx*
(@PItrans) (*xPy* ∧ *yIz*) → *xPz*
(@IItrans) (*xIy* ∧ *yIz*) → *xIz*

(@Tri) is what @Chang2017 calls the trichotomy thesis. (@PItrans) is what Sen calls PI-transitivity, and (@IItrans) is what he calls II-transitivity. 

Sen makes very few assumptions about *R*, but it will simplify our discussion to start introducing some assumptions here.^[In part this is because he was interested in exploring what assumptions about preference are crucial to the impossibility theorem that @Arrow1951 derives. He initially noticed that without (@IItrans), the theorem didn't go through. This turned out to be less significant than it seemed, because Allan @Gibbard2014 proved that a very similar theorem can be proven even without (@IItrans). See @Sen1969 for the original optimism that this might lead to an interesting way out of the Arrovian results, and @Sen1970sec for a more pessimistic assessment in light of Gibbard's result. Sen reports that Gibbard originally proved his result in a term paper for a seminar at Harvard in 1969 that he co-taught with Arrow and Rawls. Much of what I'm saying in this paper can be connected in various ways to the literature on Arrow's impossibility theorem, but I won't draw out those connections here.] We'll assume that *R* is reflexive, everything is at least as good as itself, and that *P* is transitive. (Sen calls this quasi-transitivity.) @Sen1970sec [64??] proves that if *P* is transitive, then (@PItrans) and (@IItrans) are equivalent. It's also easy to show that given (@EtoR) plus these assumptions, (@Tri) and (@IItrans) are equivalent.^[Proof: Assume (@Tri) is false. So the right hand side of (@EtoR) is false. Without much loss of generality, assume that *xRz* ∧ ¬*yRz*; the other cases all go much the same way. So all the disjuncts are false. From ¬*xPy* and ¬*yPx* we get *yRx* ∧ *xRy*, i.e., *xIy*. And *xRz* implies *zIx*. So we have a counterexample to II-transitivity, since *zIx* and *xIy*, but since ¬*yRz*, *yIz* is false. So if (@Tri) is false, (@IItrans) is false. In the other direction, assume we have a counterexample to (@IItrans), i.e., *xIy* and *yIz* but not *xIz*. From *xIy* we immediately get that the two outer disjuncts of (@Tri) are false. From *yIz* we get *yRz* and *zRy*. So if *xEy*, (@EtoR) implies that *xRz* and *zRx*, i.e., *xIz*. But we assumed that ¬*xIz*. So all three disjuntcs of (@Tri) are false. That is, if (@IItrans) fails, so does (@Tri), completing the proof that they are equivalent.]

What should we call the principle (@Tri)? Most philosophers call it *completeness*, and its denial *incompleteness*. In his economic work, @Sen1970sec uses the term 'completeness' for a different property of preference relations, namely *xRy* ∨ *yRx*. This is a useful notion to have. If Chooser has never thought of *x*, there is a good sense in which *xRy* ∨ *yRx* is false, even though of course \neg*yPx* is true. Still, using the term for (@Tri) is more common in philosophy. When writing primarily for philosophers, @Sen2004 uses 'completeness' for (@Tri), and I'll do the same. I'll call use *definedness* for *xRy* ∨ *yRx*, and unless stated otherwise, will assume it holds.

There isn't as much discussion of (@Tri) as such in the economics literature, but there is a long tradition of discussing (@IItrans), going back to important works by Henri @Poincare1903 and Wallace E. @Armstrong1939. In most of those works it is assumed that *P* is transitive, so (@Tri) and (@IItrans) are equivalent, so this is really discussing the same thing. Still, it makes the terminology confusing.

When it makes it clearer, I'll use the term @Chang2017 suggests for (@Tri). That is, I'll say that preference relations for which this holds are *trichotomous*.

# Properties of Choice Functions {#sec-properties}

In philosophy we're familiar enough with possible properties of preference relations, e.g., that they are transitive, reflexive, acyclic, etc, that these terms don't need to be defined. We're mostly less familiar with properties of choice functions. So in this short section I'll lay out six properties that will be important in what follows. The first four are discussed in some detail by @Sen1970sec, and I'll use his terminology for them. The fifth is due to @Aizerman1981, and is usually named after Aizerman. The sixth is discussed by @Blair1976.

Property α
:    (*x* ∈ *C*(*S*) ∧ *x* ∈ *T* ∧ *T* ⊆ *S*) → *x* ∈ *C*(*T*)

That is, if *x* is choiceworthy in a larger set, then it is choiceworthy in any smaller set it is a member of. This is sometimes called the *Chernoff condition*, after Herman @Chernoff1954, and sometimes called *contraction consistency*.

Property β
:    (*x* ∈ *C*(*T*) ∧ *y* ∈ *C*(*T*) ∧ *T* ⊆ *S*) → (*x* ∈ *C*(*S*) ↔ *y* ∈ *C*(*S*))

That is, if *x* and *y* are both choiceworthy in a smaller set, then in any larger set they are either both choiceworthy or neither is. Intuitively, if *x* is not chosen in the larger set because one of the new members is better than it, then the new member is also better than *y*.

Property γ
:    (*x* ∈ *C*(*S*) ∧ *x* ∈ *C*(*T*)) → (*x* ∈ *C*(*S* ∪ *T*))

That is, if *x* is choiceworthy in two sets, it is choiceworthy in their union. This is sometimes called *expansion*, e.g., in @Moulin1985.

Property δ
:    (*x* ∈ *C*(*T*) ∧ *y* ∈ *C*(*T*) ∧ *T* ⊆ *S*) → ({*y*} ≠ *C*(*S*))

This is a weakening of \beta. It says that if *x* and *y* are both choiceworthy in the smaller set, then after options are added, it can't be that only one of them is the only choiceworthy option remaining. If *x* is not choiceworthy in the larger set, that's because some other option, not *y*, is chosen in place of it.

Property Aiz
:    (*C*(*S*) \subseteq *T* \wedge *T* \subseteq *S*) \rightarrow *C*(*T*) \subseteq *C*(*S*)

That is, if the smaller set contains all of the choiceworthy members of the larger set, then no option is choiceworthy in the smaller set but not the larger set. If *x* is a nonchoiceworthy member of *S*, then the only way to make it choiceworthy is by deleting choiceworthy members of *S*, not nonchoiceworthy ones.

Path Independence
:    *C*(*S* \cup *T*) = *C*(*C*(*S*) \cup *C*(*T*))

The same options are choiceworthy from a union of two sets as are choiceworthy from the union of the choiceworthy members of those sets. This is a sort of independence of irrelevant alternatives principle; the availability or otherwise of nonchoiceworthy members of *S* and *T* doesn't affect what should be chosen from *S* \cup *T*. 

I'll describe the effects of these properties in more detail in subsequent sections.

# Property \alpha {#sec-alpha}

This is the most commonly used constraint on choice functions, and it does seem intuitive. If *x* is choiceworthy from a larger set, deleting unchosen options shouldn't make it choiceworthy. @Sen1970sec [xx] discusses two possible counterexamples.

One is where the presence of options on the menu gives Chooser relevant information. If the only two options are tea with a particular friend or staying home, Chooser will take tea. But if the option of cocaine with that friend is added, Chooser will stay home. The natural thing to say here is that when one gets new information, *C* changes, so there isn't really a single *C* here which violates \alpha.^[For a quick argument for that, if Chooser learns the only options are tea and staying home because the friend has just run out of cocaine, they might still stay home.]

The more interesting case is where the value Chooser puts on options is dependent on what options are available. So imagine Chooser prefers more cake to less, but does not want to take the last slice. If the available options are zero slices or one slice of cake, Chooser will take zero. But if two slices of cake is an option, Chooser will take one, again violating \alpha.

This is a trickier case, and the natural thing to say is that Chooser doesn't really have the same options in the two cases. Taking the last slice of cake isn't the same thing as taking one slice when two are available. But this move has costs. In particular, it makes it hard to say that *C* should be defined for any set of options. It doesn't clearly make sense to ask Chooser to pick between *taking one slice, which is the last*, and *taking three slices when five are available*.

Still, I'm going to set those issues aside and assume, like most theorists do, and mostly assume that \alpha is a constraint on coherent choice functions, and that choice functions are defined over arbitrary sets of options. In @sec-mixed I'll come back to this last assumption, but otherwise I'll assume it is in place.

# Assumptions {#sec-assumptions}

I've said a few times I'm assuming this or that, so it's a good time to put in one place the assumptions I'm making. These aren't intended to stack the deck in my favour; if any of them are false, I think it makes something like my view (a) more plausible, but (b) harder to state. Anyway, here's what has been assumed.

1. *P* is transitive, i.e., *xRy* \wedge *yRz* \rightarrow *xRz*
2. *R* is 'defined', i.e., *xRy* \vee *yRx*.
3. *R* is reflexive, i.e., *xRx*.
4. *C* is non-empty, i.e., *C*(*S*) \neq \null.
5. *C* is defined everywhere, i.e., there is a universe of options *U* all subsets of *U* are in the domain of *C*.
6. *C* satisfies \alpha.
7. The universe *U* of options, that *S* is a subset of, and *x* is drawn from, is finite.

In @sec-alpha we saw one reason to reject 5, namely that we might want to individuate options in terms of what else is available. We'll see another in @sec-mixed when we get to games with no pure strategy equilibrium. But unless stated otherwise, I'll be assuming these six things without comment.

When *R* satisfies 1-3, I'll follow @Luce1956 and call it a *semiorder*. When it also satisfies trichotomy, i.e., (@Tri), I'll follow standard practice and call it a *weak order*.

# Defining Binaryness {#sec-defining}

With these seven assumptions on board, it's easy to state what it is for a choice function to be binary. Without them there would be a lot of choice points in the definition, but now everything is simple.

First, we'll define an inversion function *B* (for binary) that maps preference relations to choice functions, and vice-versa. Both of these are sets of ordered pairs, and we'll define the ordered pairs directly. I'll assume that there is a universe *U* of options, and every option and set of options is drawn from it. 

If the input to *B* is a preference relation *R*:

(@IRtoC) *B*(*R*) = {\langle*S*, *x*\rangle: \forall*y*(*y* \in *S* \rightarrow *xRy*)}

That is, *B*(*R*) is the choice function which for any set *S* selects what Sen calls 'maximal' members, those members to which nothing is strictly preferred.^[@Hansson2009 calls this the 'liberal maximisation' rule. He contrasts it with five other rules, which are distinct in general but equivalent given *R* is a semiorder.]

If the input to *B* is a choice function *C*:

(@ICtoR) *B*(*C*) = {\langle*x*, *y*\rangle: x \in *C*({*x*, *y*})}

That is, *B*(*R*) is the preference relation which says that in any choices from pair sets, an element is chosen only if it is at least as good as the other member. @Sen1970sec [319??] calls this the 'base relation' as opposed to a more complicated 'revealed preference relation', and notes that the two are equivalent given \alpha. Since we're assuming \alpha, we'll use the simpler version.

A choice function *C* is **binary** if (@Bindef) holds:^[Sen calls these functions 'basic binary', but the distinction he's drawing attention to by adding 'basic' doesn't make a difference given *R* is a semi-order and \alpha.]

(@Bindef) *C* = *B*(*B*(*C*))

That is, if you convert *C* into a preference relation, and back into a choice function, you get the same thing back.

The core claim of this paper is that there are coherent choice functions which are not binary. A related claim is that a plausible pair of coherence constraints that you can state using *B* do not in fact hold. The constraints are that if *C* and *R* are an agent's choice function and preference relation, then *C* = *B*(*R*), and *R* = *B*(*C*). 

# Property \beta

If we start with choice functions, the definition of *E* in (@EtoR) is too simple. A better definition is in (@EtoC).

(@EtoC) *xEy* \leftrightarrow \forall*S*({*x*, *y*} \subseteq *S* \rightarrow (*x* \in *C*(*S*) \leftrightarrow *y* \in *C*(*S*)))

That is, *x* and *y* are equal iff one is never chosen when the other is not.^[Without \alpha, this is too weak, since it doesn't entail that *x* and *y* are intersubstitutable in general. But we won't worry about that.] Given this notion of equality, there is an intuitive gloss on \beta: Two options are both choiceworthy iff they are equal.^[This gloss also assumes \alpha]

To see this, think about choice functions that are defined by starting with numerical value functions, e.g., expected utility, and saying that the choiceworthy options are those with maximal value. If *x* and *y* are both choiceworthy in any set, they must have the same value. That means in any set where either is choiceworthy, i.e., either has maximal value, they both have maximal value, so both are choiceworthy.

More generally, given the assumptions we're making, *C* satisfies \beta iff *B*(*C*) is trichotomous, which is equivalent to *B*(*C*) satisfying II-transitivity. Unsurprisingly, the two historically significant cases of intuitive counterexamples to II-transitivity also generate intuitive counterexamples to \beta.
 
The first example involves distinct but indistinguishable options.^[The idea that humans can't distinguish similar options is important in @Fechner1860. The earlier connection I've found to indifferent being intransitive is in @Armstrong1939. Armstrong's example is rather confusing; the one I'll use here is based on @Luce1956.] Assume that Chooser prefers more sugar in their coffee to less, but can only tell two options apart if they differ by 10 grains of sugar or more. Now consider these three options:

> *x* = Coffee with 100 grains of sugar.    
> *y* = Coffee with 106 grains of sugar.    
> *z* = Coffee with 112 grains of sugar.

This is said to be a counterexample to II-transitivity because Chooser is indifferent between *x* and *y*, and between *y* and *z*, but strictly prefers *z* to *x*. It's also a counterexample to \beta. Chooser would choose either from *x* and *y*, but when *z* is added, *y* is still choiceworthy but *z* is not.

This example was historically important, but it's not discussed that much in the contemporary philosophical literature. It could be because philosophers were convinced by the argument in @Fara2001 that phenomenal indistinguishability is in fact transitive. But it did get widely discussed in economics, especially once it started being discussed by R. Duncan Luce [-@Luce1956; -@Luce1959], who used these examples to argue that preferences form a semi-order.

The cases that were more important in the philosophical literature are what @Chang1997 call 'small improvement' cases. The earliest case I know of fitting this form is from @LuceRaiffa1957.^[I haven't found a case like this in Luce's sole-authored works, and indeed @Debreu1960 notes that a related case raises problems for one of the central assumptions of @Luce1959.] (In this, *P*(*x*,*y*) is the probability that Chooser will select *x* when *x* and *y* are both available.)

> Suppose that *a* and *b* are two alternatives of roughly comparable value to some person, e.g., trips from New York City to Paris and to Rome. Let *c* be alternative a plus $20 and *d* be alternative *b* plus $20. Clearly, in general *P*(*a*, *c*) = 0 and *P*(*b*, *d*) = 0. It also seems perfectly plausible that for some people *P*(*b*, *c*) > 0 and *P*(*a*, *d*) > 0, in which event *a* and *b* are not comparable, and so axiom 2 [i.e., (@Tri)] is violated. [@LuceRaiffa1957 375]

An example with the same structure, involving a boy, a bicycle, and a bell, is discussed in @LehrerWagner1985, and mistakenly attributed to @Armstrong1939.^[Many authors subsequently made the same attribution; if you want to see some examples, search for the word 'pony' among the citations of Armstrong's paper on Google Scholar.] 

The usual way these cases are discussed, starting with Luce and Raiffa, is that they violate a certain kind of comparability. I want to resist this reading. The core intuition here, I think, is that \beta fails. Chooser would choose either option from {*a*, *b*}, but if *c* is added as an option, *a* becomes unchoiceworthy. If we add the assumption that *R* = *B*(*C*), then the usual analysis returns, and both trichotomy and II-intransitivity fail. Without the assumption that *R* = *B*(*C*), it's not so clear this is a counterexample to those principles, even if it is a counterexample to \beta. We'll return to this in @sec-dorr.

# Properties \gamma and \delta {#sec-gamma}

Assume *R* does not satisfy trichotomy, but is a semiorder, and *C* = *B*(*R*). Then \beta will fail, but \gamma and \delta will hold. Conversely, for any *C* where \gamma and \delta hold, there is a semiorder *R* such that *C* = *B*(*R*). We're not going to be very interested in \delta, but we will be very interested in \gamma. 

The reason \gamma holds when *R* is a semiorder and *C* = *B*(*R*) is instructive. If *x* is choiceworthy among *S*, then nothing in *S* is better than *x*. Similarly, if *x* is choiceworthy among *T*, then nothing in *T* is better than *x*. So nothing in *S* \cup *T* is better than *x*. So *x* is choiceworthy among *S* \cup *T*.^[This argument doesn't appeal to *R* being a semiorder, but if it is not, most theorists would not define *B* this way.]

Conversely, if there are cases where *C* should not satisfy \gamma, then we'll have an argument that *C* should not be based in some semiorder *R*. Showing that there are such cases will be one of the main tasks of the rest of this paper.

We had two kinds of counterexamples to \beta, but only one of them will be relevant here. I don't think there are any intuitive counterexamples to \gamma that start with Poincaré-style reflections on the intransitivity of indifference. But there are going to be variations on the bicycle and pony example that generate intuitive counterexamples to \gamma. We'll come back to these in @sec-badcomp.

It is common to say that when *C* = *B*(*R*) for some semiorder *R*, that *C* is **rationalizable**, and when *R* is a partial order, that *C* is **rationalizable by a partial order**. I find this terminology tendentious - why should semiorders be the only things that can make *C* rational? And as we'll see in @sec-games, it conflicts with what is called *rationalizable* in game theory. But it's a common enough terminology that I wanted to mention it here.

# Aizerman's Property {#sec-aiz}

The property Aiz is not particularly intuitive. Fortunately, it turns out to be equivalent, given our assumptions to one that is: Path-Independence.^[Unless stated otherwise, the results in this section, along with proofs, can be found in the helpful survey by Hervé @Moulin1985.] That principle says that to find what's choiceworthy from a union of sets, you only have to consider which options are choiceworthy in the smaller sets.

Note that this isn't just saying that the options choiceworthy from the union are choiceworthy from one of the members. That is implied by \alpha. What it is saying is that whether the unchosen options from S and T are or aren't on the menu doesn't make a difference to which options are choiceworthy from the union.

There is a very natural kind of model where \alpha and Path-Independence holds, but \beta and \gamma do not. Let *O* be a set of total orderings of *U*. (A total ordering is a relation *R* such that *xRy* \vee *yRx* \vee x=y.) Then *C*(*S*) is the set of Pareto-optimal members of *S* relative to those orderings. That is, it is the members of *S* such that no other member of *S* is better according to every member of the set of orderings.

In fact, it turns out the converse of this is also true. If *C* satisfies \alpha and Aiz, then there is some set of total orderings such that *C*(*S*) is the set of Pareto optimal members of *S* according to that set.

It might seem strange after all the talk of weak orderings and semiorders that we're now using total orders. Given that *U* is finite, this turns out to be unsurprising. Any semiorder, and hence any weak order, is such that there is some set of total orders such that *x* is strictly preferred to *y* in the semiorder iff it is preferred in all the total orders. (In fact we can put a sharp cap on how many such orders there must be.) So being Pareto optimal relative to some set of semiorders (or weak orders) is equivalent to being Pareto optimal relative to a larger set of total orders.

If *C* is determined by a set of orders in this way, it is said to be **pseudorationalizable**. These choice functions are not always binary. Consider one simple example, where *U* is {*x*, *y*, *z*}, *C*(*U*) = {*x*, *z*}, and for any other *S*, *C*(*S*) = *S*. That is the choice function determined by the pair of orderings *x* > *y* > *z* and 
*z* > *y* > *x*. This satisfies \alpha, \delta and Aiz, but not \beta or \gamma. And it isn't binary. *B*(*C*) is the universal relation *R*, since whenever *S* is a pair set, *C*(*S*) = *S*.

I'm going to argue over subsequent sections that this is a coherent choice function, and hence not all coherent choice functions are binary.

# Preference and Trade {#sec-trade}

Let's go back to why we might have wanted to focus on binary preference relations. One natural reason is that our primary aim in looking at preferene is to explain trade, and it is natural to give preferences a central role in explaining trade. If Chooser trades a cow for some magic beans, it's natural to explain that by saying Chooser preferred the magic beans.

When we are looking to explain trade in a non-monetary economy, that seems like a good reason to give preferences a central role in the story. But very little trade these days involves barter like this. Most trade involves money. Money is primarily valuable instrumentally. If Chooser buys some shoes for $100, we could say that Chooser prefers the shoes to the money. But that doesn't seem like the end of the story, since there is a reason why Chooser values the money as they do. The deeper point is that the money Chooser has gives them a budget constraint, and Chooser really thinks that the shoes are a better use of the $100 than anything else available. That is, it seems more informative to describe Chooser as choosing the shoes from the menu of things that cost $100 than to describe them as preferring the shoes to the money, since it's the fact about choice that explains why they have that preference.

Not everyone will think these kinds of pragmatic considerations about what we're aiming to explain should be relevant to what kinds of attitudes we take to be primary. If so, you should think this point about monetary economies is irrelevant to whether we should start with preferences or choices. But if you do think the pragmatic considerations are relevant, then you should think that choice functions are a better starting point than preference relations for explaining economic behaviour in monetary economies.

To be sure, if the original motivations for starting with preferences are bad, the original motivations for moving to choice functions might be worse. The focus on choice functions originally came from economists who thought that preferences were unobservable, and hence that we should focus on something observable like choice. If that's the best argument against taking preference to be the basic notion, and hence accepting *C* = *B*(*R*), I'd stick with preferences. But as we'll see, there are better reasons to be sceptical of this preference-first approach.

#  Degenerate Games {#sec-games}

Say a two-player game is **degenerate** iff the payoffs to one of the players are constant in all outcomes of the game. For convenience, say Column is the player with a constant outcome. So @tbl-upmid, @tbl-middown and @tbl-allthree are degenerate games.

|          |   Left   |  Right   |
|---------:|:--------:|:--------:|
|  Up      |   10,0   |   0,0    |
|  Middle  |   1,0    |   1,0    |

: A degenerate two-option game {@tbl-upmid}

|          |   Left   |  Right   |
|---------:|:--------:|:--------:|
|  Middle  |   1,0    |   1,0    |
|  Down    |   0,0    |   10,0   |

: Another degenerate two-option game {@tbl-middown}

|          |   Left   |  Right   |
|---------:|:--------:|:--------:|
|  Up      |   10,0   |   0,0    |
|  Middle  |   1,0    |   1,0    |
|  Down    |   0,0    |   10,0   |

: A degenerate three-option game {@tbl-allthree}

Start with the following two assumptions, which seem fairly weak relative to most practice in game theory.

- If a move is part of a Nash equilibrium, it is choiceworthy.
- A move is choiceworthy only if there is some probability distribution over the other player's moves such that the move maximises expected utility given that distribution.

In degenerate games, these necessary and sufficient conditions for choiceworthiness coincide, but in general they are rather different.

In @tbl-upmid and @tbl-middown, both options are choiceworthy by this standard. Middle-Right is a Nash equilibrium in @tbl-upmid, and Middle-Left is a Nash equilibrium in @tbl-middown. But in @tbl-allthree, the only choiceworthy options are Up and Down. Whatever probability Row assigns to Left/Right, Middle will not maximise expected utility. So this is a counterexample to \gamma. Middle is choiceworthy from {Up, Middle} and from {Middle, Down}, but not from their union.

It follows immediately from Lemma 3 in @Pearce1984 that in degenerate games, a choice satisfies those conditions for being choiceworthy iff it is not strictly dominated, where this includes being dominated by mixed strategies. So in @tbl-allthree, Middle is strictly dominated by the 50/50 mixture of Up and Down. This means that the choices will satisfy Path-Independence. An option is not dominated by the options in *S* \cup *T* iff it is not dominated by the undominated options in *S* \cup *T*, i.e., by the options in *C*(*S*) \cup *C*(*T*). So removing options that are not choiceworthy in *S* and *T* from the union doesn't change what is undominated, i.e., choiceworthy.

This last paragraph is the start of a pattern in the examples that follow. Although I'll be arguing against \gamma, I won't be arguing against Aiz/Path-Independence. I'm not going to offer anything like a conclusive argument for Aiz, but the pattern suggests that it is the right constraint to add to \alpha.

# Choice Under Uncertainty {#sec-uncertainty}



# Multiple Equilibria {#sec-multieq}

- Start with game version
- Then the version with a predictor, Skyrms's 'nice demon'
- Then go on to Spencer/Gallow dispute
- Note that Spencer's argument just needs that if one is completely certain that X is best, then it's irrational to do otherwise
- Go to a four way version that includes (a) a 7,1 option that dominates, and (b) a 1,2 option that is dominated by mixtures.
- This violates \beta and \gamma

# Mixed Strategies {#sec-mixed}

How can mixing be uniquely rational?
Answer, it's the only ratifiable choice.
Also, once one chooses it, all options are equally preferable
Choice is fundamentally an ex ante notion, while preference is an ex post notion
That's why any equation, like *C* = *B*(*R*) must be wrong - they concern different times

# Multiple Attributes and Decisiveness {#sec-sartre}

@Sartre1948 has a famous example of a young man, we'll call him Pierre, caught between two imperatives. The actual example is complicated in interesting ways, but we'll work with a very simple version of this. Pierre lives in occupied France during WWII, and feels torn between his duty to care for his ailing mother, and his duty to fight for his occupied country. What should he do?

The case is horribly underdescribed, but the following verdicts have seemed plausible to many people. First, Pierre can rationally, and morally, choose what to do here. This are both noble impulses, and it's fine to follow other. Second, and this follows from the first and the fact the case is underdescribed, the options are not equally good. After all, a small improvement to either would not break a tie between them. Third, there is something wrong about Pierre going back and forth between the two choices; he should make a choice and stick to it. The intuition I'm interested in here is that there is something intrinsically good about settling on a choice and sticking to it. What makes this intuition less than fully clear is that in any practical version of the case, it will be very bad for Pierre to oscillate between the two views. He could spend the whole war travelling between England and France as he changes his mind on where he should be, and that would be bad. The intuition I want to press is that there is something good about taking a stance and committing to it, even outside of the practical costs of changing one's mind.^[As @Moss2015 points out, it is less clear this is intrinsically bad if there is more time between the reconsiderations; it makes more sense to change one's mind than to rapidly flip-flop. That is perhaps one way to support the intuition in the text. If Pierre resembles the young Thomas Schelling (as discussed by @Holton1999), firmly committing to one plan and then another over the course of successive nights, there's something wrong about that even if it isn't practically bad.]

A very simple model, which captures these intuitions, is that Pierre's situation is surprisingly like the person playing @tbl-nice-demon. There are two options here, and either is acceptable, but once one is chosen, it becomes the preferred one. There are two good values here, caring for family and caring for country, and Pierre's fundamental choice is to adopt one of these as his value. As @Chang2024 puts it, he chooses to put 'his whole self' behind one of those values. Once that choice is made, his preferences and his actions follow naturally.

I do not want to say this is the only way to understand this example. Perhaps Pierre could, as Chang puts it, _drift_ into one choice. Perhaps he could adopt one path and sometime later rationally regret his choice, because the other value strikes his later self as more important. All I mean to say is that it seems possible that Pierre could be someone for whom both choices are rational, but once he has committed to one of them, it would be irrational to turn around and do the other. If that's right, toy models like @tbl-nice-demon are surprisingly good models of real examples like this.

# \beta and Incompleteness {#sec-dorr}

The Pierre case in @sec-sartre is, if the intuitions I was prodding are correct, a straightforward counterexample to \beta. Just to spell it out,

> *x* = Help mother
> *y* = Fight Nazis
> *z* = Help mother plus one extra ration book

If the choices are *x* and *y*, either is acceptable. If the choices are *x*, *y* and *z*, *x* alone is unchoiceworthy. So \beta fails.

This is the Small Improvement argument, and it is often thought to be an argument against completeness, i.e., (@Tri). The point of this section is to say why that argument might fail, even if the argument against \beta works.

Imagine someone was convinced by the arguments in @DorrEtAl2023 that (@Tri) must be true. Their arguments turn on semantic properties of comparatives; since *R* is a comparative, they say it must be complete since all comparatives are complete.^[For what it's worth, I think this argument fails because of the case of 'stronger' in logic. They address this case, but I don't think their response works. But it would be a huge digression to follow that thread through.] Now it would be very strange if the semantics of comparatives in natural language entailed that these intuitions about \beta had to be false. And in fact these claims about semantics do not entail that.^[I'm focussing here on the argument in @DorrEtAl2023, but a similar response works if someone is convinced of (@Tri) by the argument in @Broome1991.]

The following view seems to me to be coherent, and if so it shows why this view of comparatives does not raise a problem for \beta.

- \beta fails in cases like Pierre's.
- An option is choiceworthy for Pierre iff no option is *determinately* preferred to it.
- To make a choice, Pierre must determine which value is really his.
- Once he does that, his preferences will satisfy (@Tri).
- Before he does that there are two possibilities. One is that his preferences aren't even defined over these options, so asking which is preferred is like asking whether the number 7 is taller, shorter, or the same height as justice. Another is that it is vague what Pierre's preferences are, but any resolution of the vagueness makes (@Tri) true. This latter option fits nicely with the idea that *C* should satisfy Aiz, since it should be determined by a set of orderings, each of them the possible precisifications, or determinations, of his current state.^[This view of preference mirrors the view of credence defended by @Carr2020.]

One objection to this view is that it seems to imply that Pierre could rationally choose one option while he prefers, but does not determinately prefer, another. But this isn't what the view implies. Once Pierre makes the choice, he must, if he is rational, determine that his preferences match it. Preference, on this view, is fundamentally an ex post notion. Just like the player in @tbl-multiple-eqm must, if they are rational, form beliefs that make their choice optimal, what's true of Pierre is that he can make a choice while some other option being preferred is consistent with his *prior* preferences. But preference, on this view, is fundamentally an ex post notion. If Pierre is rational, he will choose what he prefers. It's just not true that he'll always choose what he preferred prior to the choice. Choice, on this picture, is prior to preference, both analytically and perhaps, in cases like this, causally.

When I say this is coherent, I don't mean to half-heartedly say that it is correct. My preferred view is that Pierre could rationally drift (in Chang's sense) into either option, and if he does, (@Tri) would fail even ex post. All I mean to argue here is that the case against \beta doesn't turn on this view, and is compatible with preferences being complete.

# Bad Compromises {#sec-badcomp}

My version of the Pierre example was very 

The resistance example
Go through some options
Intuitively, gamma could fail here, just like it fails in the games
Doesn't seem that this should violate Path Independence though

# Levi and Sen {#sec-levisen}

Levi's secretaries examples
Levi uses this to argue for constraint that must be best on some precisification
That is, for pseudo-rationalizability
Sen's objection
The model he's using violates Lederman's unidimensional expectations
Still, Levi's result isn't guaranteed by unidimensional expectations
But it is coherent given it, and we should take that seriously

# Negative Dominance {#sec-negdom}

Lederman's argument using the Sartre/Levi examples
Intuition - choice isn't binary, so it isn't explained by betterness
Translate neg dom into choice theory and it *holds*
What really motivates Lederman's examples is not negdom, but \gamma.
And we've seen lots of reasons to be sceptical of \gamma.

# Conclusion

Say something clever
