Are Choices Binary?

Decision theory is, as the name suggests, about how decisions should be made. In real life situations, a chooser has many options available. But the usual way decision theory is formulated gives special place to the chooser's thoughts either about individual options, or about pairs of options. Typically, it either says here's a value function, which maps options to values, and chooser should choose the one with highest value, or it says here's a preference relation, and chosoer should choose one to which no other option is preferred. In this paper, I'm going to argue both these approaches are mistaken. Decision theory has to pay attention to the distinctive features of choices involving more than two options. This is both interesting in its own right, and has implications for theories of so-called 'incomplete' preferences.

# Historical Background {#sec-history}

There is a long tradition in both the economic literature (e.g., @Samuelson1938) and the psychological literature (e.g., @Luce1956), of taking choice dispositions to be the central focus of study, as opposed to values or preferences. Some of the reasons for this were based on behaviourist or positivist commitments. The theorists would have endorsed this recent statement of the irrelevance of mental states to economics.

> Standard economics does not address mental processes and, as a result, economic abstractions are typically not appropriate for describing them. [@GulPesendorfer2008 24]

That's not going to be my approach here. I'm going to start not with observable choice dispositions, like Samuelson, or choice frequencies, like Luce, but with chooser's beliefs about which options are choiceworthy. In familiar terminology^[See, for instance, @SEPPreferences, where I learned about the Gul and Pesendorfer quote], I'm taking a mentalist approach not a behaviourist approach. Much of the formal work on choice theory has been done by theorists from the behaviourist side, and I'll be inevitably drawing from them. But the most important source I'll be using is someone much more sympathetic to mentalism: Amartya Sen. In particular, I'll draw heavily on his "Collective Choice and Social Welfare" [@Sen1970sec]. So I need to start with the way he talks about preferences in that book, which is slightly different to the current philosophical orthodoxy.

Sen starts with a binary relation *R*, defined over options, which is glossed as *xRy* means that *x* is at least as good as *y*. This is potentially misleading. It does not mean that *x* is either better than *y*, or exactly as good as *y*. Rather, it means that *x* is no worse than *y*. Sen introduces two more binary relations, *xPy*, meaning *x* is preferred to *y*, and *xIy*, meaning the chooser is between *x* and *y*. These can both be defined in terms of *R*, as in (@RtoP) and (@RtoI). (Throughout, I'm leaving off wide scope universal quantifiers over free variables.)

(@RtoP) *xPy* ↔︎ (*xRy* ∧ ¬*yRx*)
(@RtoI) *xIy* ↔︎ (*xRy* ∧ *yRx*)

A more common way of doing things in contemporary philosophy is to start with *P* and a fourth relation *E*, where *xEy* means that *x* and *y* are equally good. On this picture, both (@RtoP) and (@RtoI), but the explanatory direction in (@RtoP) is right-to-left. So *xRy* just is ¬*xPy*, and then *xIy* is still defined via (@RtoI). On the version Sen uses, it's a little trickier to define *E*, but (@EtoR) looks like a plausible conjecture.

(@EtoR) *xEy* ↔︎ [(*xRz* ↔︎ *yRz*) ∧ (*zRx* ↔︎ *zRy*)]

That is, two options are equally good iff they are substitutable in other preference relations. Given all these results, we can show that the following claims are all tightly connected.

(@Tri) *xPy* ∨ *xEy* ∨ *yPx*
(@PItrans) (*xPy* ∧ *yIz*) → *xPz*
(@IItrans) (*xIy* ∧ *yIz*) → *xIz*

(@Tri) is what @Chang2017 calls the trichotomy thesis. (@PItrans) is what Sen calls PI-transitivity, and (@IItrans) is what he calls II-transitivity. 

Sen makes very few assumptions about *R*, but it will simplify our discussion to start introducing some assumptions here.^[In part this is because he was interested in exploring what assumptions about preference are crucial to the impossibility theorem that @Arrow1951 derives. He initially noticed that without (@IItrans), the theorem didn't go through. This turned out to be less significant than it seemed, because Allan @Gibbard2014 proved that a very similar theorem can be proven even without (@IItrans). See @Sen1969 for the original optimism that this might lead to an interesting way out of the Arrovian results, and @Sen1970sec for a more pessimistic assessment in light of Gibbard's result. Sen reports that Gibbard originally proved his result in a term paper for a seminar at Harvard in 1969 that he co-taught with Arrow and Rawls. Much of what I'm saying in this paper can be connected in various ways to the literature on Arrow's impossibility theorem, but I won't draw out those connections here.] We'll assume that *R* is reflexive, everything is at least as good as itself, and that *P* is transitive. (Sen calls this quasi-transitivity.) @Sen1970sec [64??] proves that if *P* is transitive, then (@PItrans) and (@IItrans) are equivalent. It's also easy to show that given (@EtoR) plus these assumptions, (@Tri) and (@IItrans) are equivalent.^[Proof: Assume (@Tri) is false. So the right hand side of (@EtoR) is false. Without much loss of generality, assume that *xRz* ∧ ¬*yRz*; the other cases all go much the same way. So all the disjuncts are false. From ¬*xPy* and ¬*yPx* we get *yRx* ∧ *xRy*, i.e., *xIy*. And *xRz* implies *zIx*. So we have a counterexample to II-transitivity, since *zIx* and *xIy*, but since ¬*yRz*, *yIz* is false. So if (@Tri) is false, (@IItrans) is false. In the other direction, assume we have a counterexample to (@IItrans), i.e., *xIy* and *yIz* but not *xIz*. From *xIy* we immediately get that the two outer disjuncts of (@Tri) are false. From *yIz* we get *yRz* and *zRy*. So if *xEy*, (@EtoR) implies that *xRz* and *zRx*, i.e., *xIz*. But we assumed that ¬*xIz*. So all three disjuntcs of (@Tri) are false. That is, if (@IItrans) fails, so does (@Tri), completing the proof that they are equivalent.]

What should we call the principle (@Tri)? Most philosophers call it *completeness*, and its denial *incompleteness*. In his economic work, @Sen1970sec uses the term 'completeness' for a different property of preference relations, namely *xRy* ∨ *yRx*. This is a useful notion to have. If Chooser has never thought of *x*, there is a good sense in which *xRy* ∨ *yRx* is false, even though of course \neg*yPx* is true. Still, using the term for (@Tri) is more common in philosophy. When writing primarily for philosophers, @Sen2004 uses 'completeness' for (@Tri), and I'll do the same. I'll call use *definedness* for *xRy* ∨ *yRx*, and unless stated otherwise, will assume it holds.

There isn't as much discussion of (@Tri) as such in the economics literature, but there is a long tradition of discussing (@IItrans), going back to important works by Henri @Poincare1903 and Wallace E. @Armstrong1939. In most of those works it is assumed that *P* is transitive, so (@Tri) and (@IItrans) are equivalent, so this is really discussing the same thing. Still, it makes the terminology confusing.

When it makes it clearer, I'll use the term @Chang2017 suggests for (@Tri). That is, I'll say that preference relations for which this holds are *trichotomous*.

# Properties of Choice Functions {#sec-properties}

In philosophy we're familiar enough with possible properties of preference relations, e.g., that they are transitive, reflexive, acyclic, etc, that these terms don't need to be defined. We're mostly less familiar with properties of choice functions. So in this short section I'll lay out six properties that will be important in what follows. The first four are discussed in some detail by @Sen1970sec, and I'll use his terminology for them. The fifth is due to @Aizermann1981, and is usually named after Aizerman. The sixth is discussed by @Platt1976.

Property α
:    (*x* ∈ *C*(*S*) ∧ *x* ∈ *T* ∧ *T* ⊆ *S*) → *x* ∈ *C*(*T*)

That is, if *x* is choiceworthy in a larger set, then it is choiceworthy in any smaller set it is a member of. This is sometimes called the *Chernoff condition*, after Herman @Chernoff1954, and sometimes called *contraction consistency*.

Property β
:    (*x* ∈ *C*(*T*) ∧ *y* ∈ *C*(*T*) ∧ *T* ⊆ *S*) → (*x* ∈ *C*(*S*) ↔ *y* ∈ *C*(*S*))

That is, if *x* and *y* are both choiceworthy in a smaller set, then in any larger set they are either both choiceworthy or neither is. Intuitively, if *x* is not chosen in the larger set because one of the new members is better than it, then the new member is also better than *y*.

Property γ
:    (*x* ∈ *C*(*S*) ∧ *x* ∈ *C*(*T*)) → (*x* ∈ *C*(*S* ∪ *T*))

That is, if *x* is choiceworthy in two sets, it is choiceworthy in their union. This is sometimes called *expansion*, e.g., in @Moulin1985.

Property δ
:    (*x* ∈ *C*(*T*) ∧ *y* ∈ *C*(*T*) ∧ *T* ⊆ *S*) → ({*y*} ≠ *C*(*S*))

This is a weakening of \beta. It says that if *x* and *y* are both choiceworthy in the smaller set, then after options are added, it can't be that only one of them is the only choiceworthy option remaining. If *x* is not choiceworthy in the larger set, that's because some other option, not *y*, is chosen in place of it.

Property Aiz
:    (*C*(*S*) \subseteq *T* \wedge *T* \subseteq *S*) \rightarrow *C*(*T*) \subseteq *C*(*S*)

That is, if the smaller set contains all of the choiceworthy members of the larger set, then no option is choiceworthy in the smaller set but not the larger set. If *x* is a nonchoiceworthy member of *S*, then the only way to make it choiceworthy is by deleting choiceworthy members of *S*, not nonchoiceworthy ones.

Path Independence
:    *C*(*S* \cup *T*) = *C*(*C*(*S*) \cup *C*(*T*))

The same options are choiceworthy from a union of two sets as are choiceworthy from the union of the choiceworthy members of those sets. This is a sort of independence of irrelevant alternatives principle; the availability or otherwise of nonchoiceworthy members of *S* and *T* doesn't affect what should be chosen from *S* \cup *T*. 

I'll describe the effects of these properties in more detail in subsequent sections.

# Property \alpha {#sec-alpha}

This is the most commonly used constraint on choice functions, and it does seem intuitive. If *x* is choiceworthy from a larger set, deleting unchosen options shouldn't make it choiceworthy. @Sen1970sec [xx] discusses two possible counterexamples.

One is where the presence of options on the menu gives Chooser relevant information. If the only two options are tea with a particular friend or staying home, Chooser will take tea. But if the option of cocaine with that friend is added, Chooser will stay home. The natural thing to say here is that when one gets new information, *C* changes, so there isn't really a single *C* here which violates \alpha.^[For a quick argument for that, if Chooser learns the only options are tea and staying home because the friend has just run out of cocaine, they might still stay home.]

The more interesting case is where the value Chooser puts on options is dependent on what options are available. So imagine Chooser prefers more cake to less, but does not want to take the last slice. If the available options are zero slices or one slice of cake, Chooser will take zero. But if two slices of cake is an option, Chooser will take one, again violating \alpha.

This is a trickier case, and the natural thing to say is that Chooser doesn't really have the same options in the two cases. Taking the last slice of cake isn't the same thing as taking one slice when two are available. But this move has costs. In particular, it makes it hard to say that *C* should be defined for any set of options. It doesn't clearly make sense to ask Chooser to pick between *taking one slice, which is the last*, and *taking three slices when five are available*.

Still, I'm going to set those issues aside and assume, like most theorists do, and mostly assume that \alpha is a constraint on coherent choice functions, and that choice functions are defined over arbitrary sets of options. In @sec-mixed I'll come back to this last assumption, but otherwise I'll assume it is in place.

# Assumptions {#sec-assumptions}

I've said a few times I'm assuming this or that, so it's a good time to put in one place the assumptions I'm making. These aren't intended to stack the deck in my favour; if any of them are false, I think it makes something like my view (a) more plausible, but (b) harder to state. Anyway, here's what has been assumed.

1. *P* is transitive, i.e., *xRy* \wedge *yRz* \rightarrow *xRz*
2. *R* is 'defined', i.e., *xRy* \vee *yRx*.
3. *R* is reflexive, i.e., *xRx*.
4. *C* is non-empty, i.e., *C*(*S*) \neq \null.
5. *C* is defined everywhere, i.e., there is a universe of options *U* all subsets of *U* are in the domain of *C*.
6. *C* satisfies \alpha.
7. The universe *U* of options, that *S* is a subset of, and *x* is drawn from, is finite.

In @sec-alpha we saw one reason to reject 5, namely that we might want to individuate options in terms of what else is available. We'll see another in @sec-mixed when we get to games with no pure strategy equilibrium. But unless stated otherwise, I'll be assuming these six things without comment.

When *R* satisfies 1-3, I'll follow @Luce1956 and call it a *semiorder*. When it also satisfies trichotomy, i.e., (@Tri), I'll follow standard practice and call it a *weak order*.

# Defining Binaryness {#sec-defining}

With these six assumptions on board, it's easy to state what it is for a choice function to be binary. Without them there would be a lot of choice points in the definition, but now everything is simple.

First, we'll define an inversion function *B* (for binary) that maps preference relations to choice functions, and vice-versa. Both of these are sets of ordered pairs, and we'll define the ordered pairs directly. I'll assume that there is a universe *U* of options, and every option and set of options is drawn from it. 

If the input to *B* is a preference relation *R*:

(@IRtoC) *B*(*R*) = {\langle*S*, *x*\rangle: \forall*y*(*y* \in *S* \rightarrow *xRy*)}

That is, *B*(*R*) is the choice function which for any set *S* selects what Sen calls 'maximal' members, those members to which nothing is strictly preferred.^[@Hansson2009 calls this the 'liberal maximisation' rule. He contrasts it with five other rules, which are distinct in general but equivalent given *R* is a semiorder.]

If the input to *B* is a choice function *C*:

(@ICtoR) *B*(*C*) = {\langle*x*, *y*\rangle: x \in *C*({*x*, *y*})}

That is, *B*(*R*) is the preference relation which says that in any choices from pair sets, an element is chosen only if it is at least as good as the other member. @Sen1970sec [319??] calls this the 'base relation' as opposed to a more complicated 'revealed preference relation', and notes that the two are equivalent given \alpha. Since we're assuming \alpha, we'll use the simpler version.

A choice function *C* is **binary** if (@Bindef) holds^[Sen calls these functions 'basic binary', but the distinction he's drawing doesn't make a difference given *R* is a semi-order and \alpha.]

(@Bindef) *C* = *B*(*B*(*C*))

That is, if you convert *C* into a preference relation, and back into a choice function, you get the same thing back.

The core claim of this paper is that there are coherent choice functions which are not binary. A related claim is that a plausible pair of coherence constraints that you can state using *B* do not in fact hold. The constraints are that if *C* and *R* are an agent's choice function and preference relation, then *C* = *B*(*R*), and *R* = *B*(*C*). We'll start by looking at a debate which has presupposed these coherence constraints should be applied.

# Property \beta

If we start with choice functions, the definition of *E* in (@EtoR) is too simple. A better definition is in (@EtoC).

(@EtoC) *xEy* \leftrightarrow \forall*S*({*x*, *y*} \subseteq *S* \rightarrow (*x* \in *C*(*S*) \leftrightarrow *y* \in *C*(*S*))

That is, *x* and *y* are equal iff one is never chosen when the other is not.^[Without \alpha, this is too weak, since it doesn't entail that *x* and *y* are intersubstitutable in general. But we won't worry about that.] Given this notion of equality, there is an intuitive gloss on \beta: Two options are both choiceworthy iff they are equal.^[This gloss also assumes \alpha]

To see this, think about choice functions that are defined by starting with numerical value functions, e.g., expected utility, and saying that the choiceworthy options are those with maximal value. If *x* and *y* are both choiceworthy in any set, they must have the same value. That means in any set where either is choiceworthy, i.e., either has maximal value, they both have maximal value, so both are choiceworthy.

More generally, given the assumptions we're making, *C* satisfies \beta iff *B*(*C*) is trichotomous, which is equivalent to *B*(*C*) satisfying II-transitivity. Unsurprisingly, the two historically significant cases of intuitive counterexamples to II-transitivity also generate intuitive counterexamples to \beta.
 
The first example, tracing back at least to @Poincare1903, involves distinct but indistinguishable options. Assume that Chooser prefers more sugar in their coffee to less, but can only tell two options apart if they differ by 10 grains of sugar or more. Now consider these three options:

> *x* = Coffee with 100 grains of sugar.    
> *y* = Coffee with 106 grains of sugar.    
> *z* = Coffee with 112 grains of sugar.

This is said to be a counterexample to II-transitivity because Chooser is indifferent between *x* and *y*, and between *y* and *z*, but strictly prefers *z* to *x*. It's also a counterexample to \beta. Chooser would choose either from *x* and *y*, but when *z* is added, *y* is still choiceworthy but *z* is not.

This example was historically important, but it's not discussed that much in the contemporary philosophical literature. It could be because philosophers were convinced by the argument in @Graff2001 [check this] that phenomenal indistinguishability is in fact transitive. But it did get widely discussed in economics. Poincaré's thought gets picked up in a series of papers by Wallace Armstrong [-@Armstrong1939; -@Armstrong19xx; -@Armstrong19xx], who used it as the basis of an argument against the orthodox choice theory of the day. Armstrong in turn influenced R. Duncan Luce [-@Luce1956; -@Luce1959], who used these examples to argue that preferences form a semi-order. In a review of Luce's book, Gerard @Debreu1960 argued that the model Luce developed for these cases wouldn't work for cases where the options differed along different dimensions.

The class of cases Debreu discussed became central to the philosophical literature, though by this time to connection to choice functions had been dropped. Such cases are central to what Ruth @Chang1997 called the 'small improvement' argument against trichotomous preferences.^[See @Chang2017 [xxx] for a history of this.] Here's one example of the small improvement argument.^[This example is in @LehrerWagner1985, where it is mistakenly attributed to @Armstrong1939. (Many authors subsequently made the same attribution; if you want to see some examples, search for the word 'pony' among the citations of Armstrong's paper on Google Scholar.) Debreu has an example where two alternatives are basically equal, not marginally different. To the best of my knowledge, the earliest example with the small improvement structure  is (maybe Tversky, maybe Luce and Suppes - gotta finish this).] A boy is indifferent between receiving a bicycle and a pony for Christmas. He would prefer a bicycle with a bell to one without a bell, but he would be indifferent between either kind of bicycle and the pony. The usual way this case is analysed is as follows. 

> *x* = Bicycle without bell   
> *y* = Pony    
> *z* = Bicycle with bell

The boy is indifferent between *x* and *y*, and between *y* and *z*, but strictly prefers *z* to *x*. I want to resist this reading. The core intuition here, I think, is that \beta fails. The boy would choose either option from {*x*, *y*}, but if *z* is added as an option, *x* becomes unchoiceworthy. If we add the assumption that *R* = *B*(*C*), then the usual analysis returns, and both trichotomy and II-intransitivity fail. Without the assumption that *R* = *B*(*C*), it's not so clear this is a counterexample to those principles, even if it is a counterexample to \beta. We'll return to this in @sec-dorr.

# Properties \gamma and \delta {#sec-gamma}

Assume *R* does not satisfy trichotomy, but is a semiorder, and *C* = *B*(*R*). Then \beta will fail, but \gamma and \delta will hold. Conversely, for any *C* where \gamma and \delta hold, there is a semiorder *R* such that *C* = *B*(*R*). We're not going to be very interested in \delta, but we will be very interested in \gamma. 

The reason \gamma holds when *R* is a semiorder and *C* = *B*(*R*) is instructive. If *x* is choiceworthy among *S*, then nothing in *S* is better than *x*. Similarly, if *x* is choiceworthy among *T*, then nothing in *T* is better than *x*. So nothing in *S* \cup *T* is better than *x*. So *x* is choiceworthy among *S* \cup *T*.^[This argument doesn't appeal to *R* being a semiorder, but if it is not, most theorists would not define *B* this way.]

Conversely, if there are cases where *C* should not satisfy \gamma, then we'll have an argument that *C* should not be based in some semiorder *R*. Showing that there are such cases will be one of the main tasks of the rest of this paper.

We had two kinds of counterexamples to \beta, but only one of them will be relevant here. I don't think there are any intuitive counterexamples to \gamma that start with Poincaré-style reflections on the intransitivity of indifference. But there are going to be variations on the bicycle and pony example that generate intuitive counterexamples to \gamma. We'll come back to these in @sec-sartre.

It is common to say that when *C* = *B*(*R*) for some semiorder *R*, that *C* is **rationalizable**, and when *R* is a partial order, that *C* is **rationalizable by a partial order**. I find this terminology tendentious - why should semiorders be the only things that can make *C* rational? And as we'll see in @sec-game, it conflicts with what is called *rationalizable* in game theory. But it's a common enough terminology that I wanted to mention it here.

# Aizerman's Property {#sec-aiz}

- Assume there is some set of orderings, each satisfying the assumptions.
- Say *x* \in *C*(*S*) iff *x* is maximal according to one of these orderings.
- Then *C* satisfies Aiz.
- Conversely, if *C* satisfies Aiz, we can generate such a set.
- This matters because it shows we can still put some substantive constraints on *C*.

# Preference and Trade {#sec-trade}

One reason for starting with preference is that we are interested in explaining trade, and the fundamental explanation of trade is that each prefers what the other has got. But this only really holds in a non-monetary economy. In a monetary economy, most trades are for money - Chooser will pay $100 for those shoes. At one level that means Chooser prefers the shoes to the $100. But $100 has exchange value, not use value. It's not of any value in itself, but only what it can buy. So really what explains the trade is that Chooser takes the shoes to be one of the choiceworthy things out of the things that cost $100. In a monetary economy, it's really choice, not preference, that explains most of the trading that we see.

# Constraints on Preference {#sec-constraints}

Another reason for taking preference to be primary is that it lets us state clearly some intuitive rational constraints, such as transitivity, and independence. 

But we can do that for *C* as well.

Boring way, just do it for choices from pair-sets.

Better way, state the more general result.

(I have this in one of the files.)

#  Degenerate Games {#sec-games}

- Mention Pearce's result here
- Also mention that deletion of dominated strategies looks like path independence

# Choice Under Uncertainty {#sec-uncertainty}

# Multiple Equilibria {#sec-multieq}

- Start with game version
- Then the version with a predictor, Skyrms's 'nice demon'
- Then go on to Spencer/Gallow dispute
- Note that Spencer's argument just needs that if one is completely certain that X is best, then it's irrational to do otherwise
- Go to a four way version that includes (a) a 7,1 option that dominates, and (b) a 1,2 option that is dominated by mixtures.
- This violates \beta and \gamma

# Mixed Strategies {#sec-mixed}

How can mixing be uniquely rational?
Answer, it's the only ratifiable choice.
Also, once one chooses it, all options are equally preferable
Choice is fundamentally an ex ante notion, while preference is an ex post notion
That's why any equation, like *C* = *B*(*R*) must be wrong - they concern different times

# Multiple Attributes and Decisiveness {#sec-sartre}

Simplified version of Sartre's example
Intuition, can choose either, but should stick to it
Not just for practical reasons (maybe cite Moss here?)
Model, (10,0) or (0,10); optimal choice includes choosing which you care about
Is that right everywhere? Maybe not, but it's something we can model.

# \beta and Incompleteness {#sec-dorr}

Sartre's example can be used for small improvement argument
But what that really shows is that \beta fails
If preference is about ex post, it doesn't show that completeness fails
Could be that once one has chosen, one should have complete preferences
If you think that completeness has to be true because of the nature of vagueness (a la Broome) or because of the nature of comparatives (a la Dorr), it doesn't follow that you can't have multi-attribute choice, or \beta failures. You just have to think that when preferences are defined ex post, they have to be complete.
To be sure, I don't think Broome's or Dorr et al's arguments do work.
I just want to note that it would be odd to, e.g., insist on \beta because of arguments about the semantics of comparatives.
Taking choice to be ex ante and preference to be ex post means you don't have to.

# Bad Compromises {#sec-badcomp}

The resistance example
Go through some options
Intuitively, gamma could fail here, just like it fails in the games
Doesn't seem that this should violate Path Independence though

# Levi and Sen {#sec-levisen}

Levi's secretaries examples
Levi uses this to argue for constraint that must be best on some precisification
That is, for pseudo-rationalizability
Sen's objection
The model he's using violates Lederman's unidimensional expectations
Still, Levi's result isn't guaranteed by unidimensional expectations
But it is coherent given it, and we should take that seriously

# Negative Dominance {#sec-negdom}

Lederman's argument using the Sartre/Levi examples
Intuition - choice isn't binary, so it isn't explained by betterness
Translate neg dom into choice theory and it *holds*
What really motivates Lederman's examples is not negdom, but \gamma.
And we've seen lots of reasons to be sceptical of \gamma.

# Conclusion

Say something clever


