---
title: "Review of “Sameness and Substance Renewed”"
description: |
  Review of David Wiggins, “Sameness and Substance Renewed”. Cambridge: Cambridge University Press, 2001. 
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
date: 09-06-2002
citation_url: https://ndpr.nd.edu/news/sameness-and-substance-renewed/
self-contained: false
preview: wiggins.jpg
citation: false
categories:
  - book review
  - on books
  - metaphysics
output:
  distill::distill_article:
    toc: false
    toc_depth: 2
    number_sections: TRUE
---

*Sameness and Substance Renewed* (hereafter, 2001) is, in effect, a second edition of Wiggins's 1980 book *Sameness and Substance* (hereafter, 1980), which in turn expanded and corrected some ideas in his 1967 *Identity and Spatio-Temporal Continuity* (hereafter, 1967). All three books have similar aims. The first is to argue, primarily against Geach, that identity is absolute not relative. The second is to argue that, despite this, whenever an identity claim *a* = *b* is true, there is a sortal *f* such that *a* is the same *f* as *b*. The biggest difference between 1967 and the two later books is that the later books contain much more detail on what a sortal must be if this claim, called **D**, is to be both correct and philosophically interesting. The third aim is to apply the first two conclusions to the topic of personal identity.

<aside>This review first published in [Notre Dame Philosophical Reviews](https://ndpr.nd.edu/news/sameness-and-substance-renewed/).</aside>

For the bulk of 2001, most of the changes to 1980 are confined to footnotes, the bulk of these consisting of a citation of, and occasionally a brief comment upon, a post 1980 publication that bears on Wiggins's approach to the topic. This changes in the last two chapters. The penultimate chapter is a mostly new discussion of the determinacy of identity. In the final chapter, on personal identity, Wiggins retracts many of the claims made in the matching chapter of 1980, and raises some interesting objections to Parfit's account of personal identity. Apart from those, the major changes to 1980 are stylistic. No longer is the material considered more peripheral printed in smaller type, though to make up for this there are frequent exhortations to skip these sections. And the longer notes of the 1980 edition are now mostly incorporated into the text, several prefixed with advice that they not be read.

In the preface Wiggins says that it is a matter of no concern whether 1980 and 2001 are the same book. But it is of concern to me, twice over. First, it makes a large difference to what kind of review should be written whether this is an old book reissued or a new book. Secondly, the difficulty in answering this question draws out some problems Wiggins's theory faces when we try to apply it outside the realms of physics and biology. On the first problem, the reader who hopes here to find a comprehensive discussion of the literature on identity post-1980 as it strikes David Wiggins will be disappointed. Three examples should help to illustrate this.

In 1967 Wiggins held, quite sensibly, that a statue is not identical to the bronze that it is made of, but rather is *constituted* by that bronze. This was an important move in his response to Geach. If identity is absolute, and the statue is identical with the bronze, then we can't say that when the statue is remoulded into a vase, we have the same lump of bronze but a different artwork. In 2001 he says much the same thing. This still seems like good common sense, but the problem is that in the intervening 34 years there has been a mass of work on constitution, most of it concluding that the constitution relation is much more problematic than we had originally thought. In a genuinely new work, or even perhaps in a revised old work, this material should have been addressed.

In 1980 Wiggins makes it quite clear he dislikes perdurantist theories of persistence that hold that an object persists from *t*­~1~ to *t*~2~ by having instantaneous temporal parts at every time in [*t*~1~, *t*~2~]. Just why he dislikes perdurantism is unclear, since all his arguments are directed against the conjunction of this view with the striking, and not especially popular, view that our ordinary names refer to these instantaneous objects. In 2001 it is still clear he dislikes perdurantism. But we find little on the barrage of arguments perdurantists have offered in the last 21 years in support of their position. All we find is a footnote expressing agreement with Mark Johnston's response to Lewis's 'problem of temporary intrinsics' argument, and a citation of a paper expanding upon said agreement. Given that this book largely reprints previously available material, including more detail here would not have been absurd, and saying something about other arguments quite appropriate.

The third example is a little more serious. In the book's new chapter, he outlines approvingly Evans's proof that identity is always determinate identity, and cites (without outlining) a proof by Williamson that distinctness is always determinate. From these proofs he quite naturally concludes that the prospects for indeterminate identities are pretty grim. But he doesn't engage with those who maintain that, despite all this, there really are indeterminate identities. It would have been worthwhile, for instance, to see a more direct engagement between his views and those of, say, Terrence Parsons, who over the last 15 years has developed a rather detailed theory on which indeterminate identity is possible. It will probably turn out that Wiggins's position is entirely correct, and Parsons's position basically mistaken, but that's no reason to not take Parsons more seriously.

Apart from this oversight, there is one rather odd feature in the discussion of determinacy. Wiggins says that "it can be *perfectly determinate* which mountain *x* is without *x*'s extent being determinate." (166) The idea is that it can be determinate that *x* is, say, this mountain, while it is indeterminate whether, say, that foothill is part of *x*. Such a position always feels strained to me, but it is certainly not unfamiliar. But it is very hard to see how it is meant to fit in with Wiggins's picture of the role of sortal concepts, such as *mountain*. On page 70 he says a sortal concept is such that grasp of it determines "what changes *x* tolerates without there ceasing to exist such a thing as *x*." (He actually says 'substance-concept', not 'sortal concept' there, but these phrases seem to be used synonymously.) The trouble should be apparent. For it to be determinate what *x* is, presumably just is for it to be determinate that *x* is this *mountain*. That is, it is determinate that *x* falls under the sortal *mountain*, and that sortal must determine persistence conditions, else it fails to be a sortal. But that means *x*'s persistence conditions are determined. So there is a determinate fact, perhaps unknown and perhaps even unknowable, about how far in the future one can go without leaving *x* behind. (I assume here that if *x*'s temporal extent is *determined* by which sortal it falls under, then *x*'s temporal extent is *determinate*. I imagine some will deny this claim, but it looks like a platitude to me.) On the other hand, it seems that it can be determinate what *x* is even though the conditions of *x*'s spatial persistence, conditions that determine how far westward one can go without leaving *x* behind, are not determinate. Just how this asymmetry is to be tolerated is not explained.

Much of the interest in this edition will focus on the new material on personal identity, and I shall say more about this below. But it is worth going over the central claims of the earlier part of the book. The crucial principle is called **D**(ii). The derivation of it appeals crucially to **D**(i). (Both definitions, and the commentary, from page 64.)

**D**(i) (*x*)(*t*) [(*x* exists at *t*) → (∃*g*) (*g*(*x*) at *t*)].

**D**(ii) (*x*)(∃*g*)(*t*) [(*x* exists at *t*) → (*g*(*x*) at *t*)].

'*x*' ranges over three-dimensional continuants, '*t*' over times and '*g*' over sortals. The argument for **D**(i) is that for any object at any time there is an answer to the Aristotelian question *What is it*? This answer is a sortal so, as just noted, it must determine principles of persistence. It must also determine "a prnciple of *activity*, a principle of *functioning* or a principle of *operation*". (72) If the last claim looks disjunctive, that's because it is. Sortals for living objects determine principles of activity, sortals for artifacts determine principles of functioning. Just what philosophically interesting features these principles share is never satisfactorily explained. So there's a suspicion that there is no decent concept of *sortal* that covers the kinds of things living creatures are and the kinds of things artifacts are. In slogan form *sortal* isn't a sortal. Two other considerations reinforce that suspicion.

First, there are objects that don't naturally fall under any known sortal. Just looking at the computer I'm now using, there is the latch that holds the lid down when it's closed, the button that opens the CD tray, the brightness control, and the stick that plays some (but not all) the functional roles of a mouse. It's far from obvious that any of these falls under a sortal, at least if a sortal must determine persistence conditions and a principle of functioning.

Secondly, there's a tension between the kinds of sortals Wiggins thinks appropriate for artifacts and what he says about persistence. Artifact sortals are, he says, functional kinds. These sortals are meant to determine persistence conditions. Whether an object has persisted is not meant to depend on extrinsic, or external, factors. This is the upshot of his *Only a and b* rule (96), which is important in ruling out 'best deserver' theories of persistence. That rule says that we don't need to consider objects other than *a* or *b* to determine whether *a* is *b*. So whether *a*, the boy genius is *b*, the Nobel Prize winning author, cannot depend on the existence or otherwise of a person more closely continuous with *a* than *b* happens to be. Hence Nozick's theory of personal identity, which rejects this, cannot be true. But to determine whether *a*´, the brightness control on my computer at *t*~1~ is *b*´, the volume control on Jack's computer at *t*~2~, we need to see which sortals *a*´ and *b*´ fall under, to see whether *a*´ has persisted. That will depend, in part, on whether *a*´ still falls under that sortal, whatever it is. Such a sortal will sort by functional role, and whether that functional role is fulfilled at all times between *t*~1~ and *t*~2~ will be determined by things other than *a*´ and *b*´. The point generalises: in most cases whether an object continues to fill a functional role often turns on the existence, and behaviour, of *other* objects. The natural conclusion to be drawn here is that **D**(i) might be false for artifacts.

Clearly **D**(i) doesn't entail **D**(ii). But, bracketing our concerns about its truth, it might still be usable in an abductive argument for **D**(ii). Wiggins does just this. The argument, and this is I think the *only* argument for **D**(ii), is that it best explains our widespread agreement over whether an object has survived. Wiggins says that, "Our capacity for massive agreement about this is much more remarkable than our occasional disagreement," (66) and given **D**(i), **D**(ii) is the best explanation of this. Two replies. First, the agreement is not all that widespread, even in actual cases. Think, for example, about the range of disagreement over whether a corpse is a thing that once lived, and hence the disagreement over whether Auntie is buried behind the back shed, or Auntie no longer exists. Secondly, there is a better explanation -- the perdurantist explanation given by Lewis. This not only explains why there is agreement just where there is agreement, but why there is disagreement where there is disagreement. The story is familiar. All sorts of continuants (fusions of temporal parts) exist, but we choose which ones to refer to and quantify over because of our particular interests, and those choices are codified in our linguistic practices. When dealing with historically familiar situations, membership of linguistic, and more broadly cultural, communities commits us to common answers. Since most situations are historically familiar, we have agreement in most cases. When we deal with new cases, either generated by new technology or new imaginativeness, and our interests do not pick out a clearly preferable continuant, we do not have agreement. If this is right, we will agree about the familiar and disagree about the unfamiliar. Happily, this is exactly what we find -- we all know what the persistence conditions for cows, pigs and chicken are, we do not know the persistence conditions for corporate entities or pieces of software or even relocated football teams in perfectly everyday cases.

In 1980, the chapter on personal identity had two main aims. The first was to argue that Lockean considerations about continuity of memory could be used in an account of personal identity, even if they would have to be used as reference fixers rather than as constituents of a reductive analysis. The opponents here were those followers of Bishop Butler, most prominently Anthony Flew, who held that any such consideration would be hopelessly circular. The second aim was to argue that it is a conceptual truth that persons are animals. The targets here were (unnamed) philosophers who wanted to provide a complete functional analysis of a person. The objections were mainly political but since it is unclear whether the philosophy of personal identity should be part of metaphysics or ethics, that's perfectly acceptable.

In 2001, the aims have changed. Wiggins retracts everything he said against Butler and Flew, and then spends most of the chapter in a lengthy discussion of Parfit's theory of personal identity. Butler's original complaint against Locke was that the concept of memory needs a pre-existing concept of personal identity to be applied so it cannot be used in a non-circular account of identity. In the bluntest version of this complaint, it is held that 'A remembers X-ing' is properly represented as 'A remembers A X-ing', which requires an identity between the referents of the two occurences of 'A'. Wiggins's complaint, in 1980, was that this position costs us some vital distinctions. We want to distinguish, for example, 'A imagines being an elephant' from 'A imagines A being an elephant'. In the first case only, A imagines something possible. And what holds for imagining, he thought, holds for remembering. Wiggins now rejects the last step here. Remembering, unlike imagining, has a tie to the truth. A can only remember X-ing if A in fact X-ed. This last claim might not be part of the logical form of 'A remembers X-ing', but there is a close relation between the two. Wiggins calls the relationship presupposition, but the name here doesn't matter much. So Butler, and Flew, were right -- appeals to memory in a theory of personal identity are hopelessly circular, because they presuppose that debates about identity through time are resolved.

The rest of the chapter outlines concerns with Parfit's theory of personal identity, based on his concept of quasi-memory, and with the intuitions behind some cases that support Parfit's theory. Quasi-memory, unlike memory, need not be factive, but what is quasi-remembered must have happened somewhere, to someone. Wiggins launches a barrage of attacks on this idea, of which the following three seem most telling. First, quasi-memory could not be defined (and is not defined) as memory minus factiveness, because conceptual subtraction is undefined in the absence of conceptual analysis, and we don't have a conceptual analysis here. Secondly, the concept of quasi-memory may seem to make sense for quite general, *de dicto* memories, but it runs into trouble with *de re*, or even with more specific memories. If I am to quasi-remember climbing Big Ben on my sixteenth birthday, must someone have climbed Big Ben on my sixteenth birthday? Or perhaps on their sixteenth birthday? Thirdly, even if Parfit can define the concept of *accurate quasi-memory*, that won't get us the general concept of quasi-memory, because again conceptual subtraction doesn't make sense.

There are some good points here for followers of Parfit to consider. They are followed by some interesting considerations about why we might rethink our intuitions about personal identity in cases involving brain swaps. Those interested in personal identity debates, and particularly Wiggins's and Parfit's contributions, should pay close attention here. These will not be the only people to whom this new volume has interest. *Sameness and Substance* was an important statement of a rather commonsensical solution to some of the hardest questions in metaphysics, a solution with which everyone working in the field should be well acquainted. And those who have not previously read it closely will find that the stylistic changes (having a uniform font size, incorporating the longer notes into the text) make the renewed version of *Sameness and Substance* much more accessible than the original.
