---
title: "In Defense of a Kripkean Dogma"
description: | 
    A reply to some empirical arguments against Kripkean meta-semantics.
date: July 1 2012
author:
  - name: Jonathan Jenkins Ichikawa
    url: http://jichikawa.net
    affiliation: University of British Columbia
    affiliation_url: https://philosophy.ubc.ca/profile/jonathan-ichikawa/
  - name: Ishani Maitra
    url: https://lsa.umich.edu/philosophy/people/faculty/imaitra.html
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
journal: 
  title: "Philosophy and Phenomenological Research"
  publisher: Wiley
volume: 85
issue: 1
doi: "10.1111/j.1933-1592.2010.00478.x"
slug: maitraweatherson2010aka
citation_url: https://doi.org/10.1111/j.1933-1592.2010.00478.x
citation: false
bibliography: ../../../articles/Rbib.bib
preview: godel.jpg
categories:
  - methodology
  - language
  - notes
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    number_sections: TRUE
---

In "Against Arguments from Reference" [@MMNS2009], Ron Mallon, Edouard
Machery, Shaun Nichols, and Stephen Stich (hereafter, MMNS) argue that
recent experiments concerning reference undermine various philosophical
arguments that presuppose the correctness of the causal-historical
theory of reference. We will argue three things in reply. First, the
experiments in question---concerning Kripke's Gödel/Schmidt
example---don't really speak to the dispute between descriptivism and
the causal-historical theory; though the two theories are empirically
testable, we need to look at quite different data than MMNS do to decide
between them. Second, the Gödel/Schmidt example plays a different, and
much smaller, role in Kripke's argument for the causal-historical theory
than MMNS assume. Finally, and relatedly, even if Kripke *is* wrong
about the Gödel/Schmidt example---indeed, even if the causal-historical
theory is not the correct theory of names for some human
languages---that does not, contrary to MMNS's claim, undermine uses of
the causal-historical theory in philosophical research projects.

<aside>
Published in _Philosophy and Phenomenological Research_ 85: 56-68.
</aside>

### Experiments and Reference

MMNS start with some by now famous experiments concerning reference and
mistaken identity. The one they focus on, and which we'll focus on too,
is a variant of Kripke's Gödel/Schmidt example. Here is the question
they gave to subjects.

> Suppose that John has learned in college that Gödel is the man who
> proved an important mathematical theorem, called the incompleteness of
> arithmetic. John is quite good at mathematics and he can give an
> accurate statement of the incompleteness theorem, which he attributes
> to Gödel as the discoverer. But this is the only thing that he has
> heard about Gödel. Now suppose that Gödel was not the author of this
> theorem. A man called "Schmidt" whose body was found in Vienna under
> mysterious circumstances many years ago, actually did the work in
> question. His friend Gödel somehow got hold of the manuscript and
> claimed credit for the work, which was thereafter attributed to Gödel.
> Thus he has been known as the man who proved the incompleteness of
> arithmetic. Most people who have heard the name 'Gödel' are like John;
> the claim that Gödel discovered the incompleteness theorem is the only
> thing they have ever heard about Gödel. When John uses the name
> 'Gödel,' is he talking about:
>
> 1.  the person who really discovered the incompleteness of arithmetic?
>     or
>
> 2.  the person who got hold of the manuscript and claimed credit for
>     the work? (MMNS 2009: 341)

The striking result is that while a majority of American subjects answer
(B), consistently with Kripke's causal-historical theory of names, the
majority of Chinese subjects answer (A).[^1] To the extent that Kripke's
theory is motivated by the universality of intuitions in favour of his
theory in cases like this one, Kripke's theory is undermined.

There are now a number of challenges to this argument in the literature.
Before developing our own challenge, we'll briefly note five extant
ones, which all strike us as at least approximately correct.

Kripke's theory is a theory of *semantic* reference. When asked who John
is talking about, it is natural that many subjects will take this to be
a question about *speaker* reference. And nothing in Kripke's theory
denies that *John* might refer to the person who proved the
incompleteness of arithmetic, even if his word refers to someone else.
[@Ludwig2007; @Deutsch2009]

Kripke's argument relies on the *fact* that '

Gödel' refers to Gödel, not to the universality or otherwise of
intuitions about what it refers to. That some experimental subjects
don't appreciate this fact doesn't make it any less of a fact.
[@Deutsch2009]

If the subjects genuinely were descriptivists, it isn't clear how they
could make sense of the vignette, since the name 'Gödel' is frequently
used in the vignette itself to refer to the causal origin of that name,
not to the prover of the incompleteness or arithmetic.

[^2]

On a related point, Martí doesn't mention this, but subjects who aren't
descriptivists should also object to the vignette, since in the story
John doesn't learn Gödel proved the incompleteness of arithmetic, at
least not if 'learn' is factive. [@Marti2009]

The experiment asks subjects for their judgments about a metalinguistic,
and hence somewhat theoretical, question about the mechanics of
reference. It's better practice to observe how people actually refer,
rather than asking them what they think about reference.
[@Marti2009; @Devitt2010]

Intuitions about the Gödel/Schmidt case play at best a limited role in
Kripke's broader arguments, so experimental data undermining their
regularity do not cast serious doubt on Kripke's theory of reference.
[@Devitt2010]

We think challenges (1)-(3) work. Something like (4) should work too,
although it requires some qualification. Consider, for instance, what
happens in syntax. It's true, of course, that we don't go around asking
ordinary speakers whether they think *Lectures on Government and
Binding* was an advance over *Aspects*. Or, if we did, we wouldn't think
it had much evidential value. But that's not because ordinary speaker
judgments are irrelevant to syntax. On the contrary, judgments about
whether particular strings constitute well-formed sentences are an
important part of our evidence.[^3] But they are not our only evidence,
or even our primary evidence; we also use corpus data about which words
and phrases are actually used, and many syntacticians take such usage
evidence to trump evidence from metasemantic intuitions.[^4] Even when
we do seek such intuitive answers, perhaps because there isn't enough
corpus data to settle the usage issue, the questions might be about
cases that are quite different to the cases we primarily care about. So
we might ask a lot about speakers' judgments concerning questions even
if we care primarily about the syntax of declarative sentences.

If what @Kripke1980 says in *Naming and Necessity* (hereafter, NN) is
right, then we should expect something similar in the case of reference.
Kripke anticipates that some people will disagree with him about some of
the examples, and offers a few replies. (Our discussion here largely
draws on footnote 36 of NN.) Part of his reply is a version of point 1
above; those disagreements may well be over speaker reference, not
semantic reference. That reply is correct; it's hard for us to hear a
question about who someone is talking about as anything but a question
about speaker reference. He goes on to note that his theory makes
empirical predictions about how names are used.

> If I mistake Jones for Smith, I may *refer* (in an appropriate sense)
> to Jones when I say that Smith is raking the leaves ... Similarly, if
> I erroneously think that Aristotle wrote such-and-such passage, I may
> perhaps sometimes use 'Aristotle' to *refer* to the actual author of
> the passage ... In both cases, I will withdraw my original statement,
> and my original use of the name, if apprised of the facts. (NN 86n)

This seems entirely right. There's some sense in which John, in MMNS's
vignette, is referring to

Gödel and some sense in which he's referring to Schmidt. Just thinking
about the particular utterance he makes using 'Gödel' won't help much in
teasing apart speaker reference and semantic reference. What we should
look to are patterns of---or if they're not available, intuitions
about---withdrawals of statements containing disputed names. To use the
example Kripke gives here, consider a speaker who (a) associates with
the name 'Aristotle' only the description 'the author of *The
Republic*', (b) truly believes that a particular passage in *The
Republic* contains a quantifier scope fallacy, and (c) is a
descriptivist. She might say "Aristotle commits a quantifier scope
fallacy in this passage." When she's informed that the passage was
written by Plato, she'll no longer utter those very words, but she'll
still insist that the sentence she uttered was literally true. That's
because she'll claim that in that sentence 'Aristotle' just referred to
the author of the passage, and that person did commit a quantifier scope
fallacy. A non-descriptivist will take back the claim expressed, though
she might insist that what she *intended* to say was true.

So to show that subjects in different parts of the world really have
descriptivist intuitions about the Gödel/Schmidt case, we might ask
about whether they think John should withdraw, or clarify, his earlier
statements if apprised of the facts. Or we might ask whether they would
withdraw, or clarify, similar statements they had made if apprised of
the facts. Or, even better, we might test whether in practice people in
different parts of the world really do withdraw their prior claims at
different rates when apprised of the facts about a Gödel/Schmidt case.
Kripke is right that given descriptivism, a speaker shouldn't feel
obliged to withdraw the original statement when apprised of the facts,
but given the causal-historical theory, they should. So there are
experiments that we could run which would discriminate between
descriptivist and causal-historical approaches, but we don't think the
actual experiment MMNS run does so.

In its broad terms, we agree with Devitt's challenge (5), although we
understand the role of the Gödel/Schmidt case rather differently than he
does. We turn now to this question.

### Gödel's Role in Naming and Necessity

In the first section we argued that the experimental data MMNS offer do
not show that the correct account of the Gödel/Schmidt example is
different in different dialects. In this section we want to argue that
there's very little one *could* show about the Gödel/Schmidt example
that would bear on the broader question of what the correct theory of
reference is. To see this, let's review where the Gödel/Schmidt example
comes up in *Naming and Necessity*.

In the first lecture, Kripke argues, via the modal argument, that names
can't be synonymous with descriptions. The reason is that in modal
contexts, substituting a name for an individuating description alters
truth values. So a pure descriptivism that treats names and descriptions
as synonymous is off the table. What's left, thinks Kripke, is what
Soames calls "weak descriptivism" [@Soames2003 Volume II, 356]. This is
the view that although names are not synonymous with descriptions, and
do not abbreviate descriptions, they do have their reference fixed by
descriptions.

Here is the way Kripke introduces the picture that he is attacking.

> The picture is this. I want to name an object. I think of some way of
> describing it uniquely and then I go through, so to speak, a sort of
> mental ceremony: By 'Cicero' I shall mean the man who denounced
> Cataline ... [M]y intentions are given by first, giving some
> condition which uniquely determines an object, then using a certain
> word as a name for the object determined by this condition. (NN 79)

The Gödel/Schmidt example, or at least the version of it that MMNS
discuss, comes up in Kripke's attack on one of the consequences of this
picture of naming. (A variant on the example, where no one proves the
incompleteness of arithmetic, is used to attack another consequence of
the theory.) So the role of the Gödel/Schmidt example is to undermine
this picture of names and naming.

But note that it is far from the only attack on this picture. Indeed, it
is not even the first attack. Kripke's first argument is that for most
names, most users of the name cannot give an individuating description
of the bearer of the name. In fact, those users cannot even give a
description of the bearer that is individuating *by their own lights*.
The best they can do for 'Cicero' is 'a Roman orator' and the best they
can do for 'Feynman' is 'a famous physicist'. (NN 81) But it isn't that
these users think that there was only one Roman orator, or that there is
only one famous physicist. It's just that they don't know any more about
the bearers of these names they possess. The important point here is
that Kripke starts with some examples where the best description a
speaker can associate with a name is a description that isn't
individuating *even by the speakers' own lights*. And he thinks that
descriptivists can't explain how names work in these cases.

Now perhaps we'll get new experimental evidence that even in these
cases, some experimental subjects have descriptivist intuitions. Some
people might intuit that if a speaker does not know of any property that
distinguishes Feynman from Gell-Mann, their name 'Feynman' is
indeterminate in reference between Feynman from Gell-Mann. We're not
sure what such an experiment would tell us about the metaphysics of
reference, but maybe someone could try undermining Kripke's argument
this way. But that's not what MMNS found; their experiments don't bear
on what Kripke says about 'Feynman', and hence don't bear on his primary
argument against weak descriptivism.

Some philosophers will hold that although the picture Kripke describes
here, i.e., weak descriptivism, can't be right in general for
Feynman/Gell-Mann reasons, it could be true in some special cases. We
agree. So does Kripke. The very next sentence after the passage quoted
above says, "Now there may be some cases in which we actually do this."
(NN 79) And he proceeds to describe three real life cases (concerning
'Hesperus', 'Jack the Ripper' and 'Neptune') where the picture is
plausibly correct. But he thinks these cases are rare. In particular, we
shouldn't think that the existence of an individuating description is
sufficient reason to believe that we are in such a case. That, at last,
is the point of the Gödel/Schmidt example. His conclusion from that
example is that weak descriptivism isn't correct even in those special
cases of names where the speaker possesses a description that she
*takes* to be individuating.[^5]

Michael @Devitt2010 also argues that MMNS exaggerate the importance of
the Gödel/Schmidt case. He identifies a number of Kripke's other
arguments (including the Feynman one we mention) that he takes to be
more central, and, like us, he argues that MMNS's results do not cast
doubt on these arguments. We agree, noting only two points of
difference. First, as suggested above, although the Gödel/Schmidt case
is not the only or the most central motivation for Kripke's theory of
reference, we do think that it plays a distinctive role, compared with
that of, for instance, the Feynman case. It refutes even the weak
version of weak descriptivism according to which, in the special case in
which subjects do possess individuating descriptions, those descriptions
determine reference. We think the Gödel/Schmidt case (together with the
Peano/Dedekind case) form the basis of the only argument in *Naming and
Necessity* against this weak weak descriptivism. (On a closely related
point, we, unlike Devitt, take the Gödel/Schmidt case to be addressing a
quantitative question about how common descriptive names are, not the
qualitative question about whether the causal-historical theory is true
at all; we'll expand on this point below.) Second, Devitt expresses some
scepticism about the Gödel/Schmidt judgment on the grounds that the
relevant case is somewhat 'fanciful'---actual cases, Devitt suggests,
are better to be trusted. While there is surely some truth in the
suggestion that intuitions about esoteric and complicated cases can be
less trustworthy than those about everyday ones, we see little reason
for concern in this instance; the Gödel case does not describe a
scenario we should expect to find trouble thinking about.

Our reconstruction of the structure of Kripke's argument should make it
clear how *unimportant* the Gödel/Schmidt example is to the broader
theoretical questions. If Kripke were wrong about the Gödel/Schmidt
case, that would at most show that there are a few more descriptive
names than we thought there were. But since the existence of some
descriptive names is consistent with the causal-historical theory of
reference, the existence of a few more is too. All the Gödel/Schmidt
example is used for in *Naming and Necessity* is to show that the number
of descriptive names in English is not just small, it is *very* small.
But the truth of the causal-historical theory of reference doesn't turn
on whether there are few descriptive names, or very few descriptive
names.

Once we see that the Gödel/Schmidt example concerns a quantitative
question (are descriptive names rare or very rare?) rather than a
qualitative question (is the causal-historical theory correct?), we can
see some limitations of the experiment MMNS rely on. The case that MMNS
describes to their subjects has several distinctive features, and it
isn't clear that we'd be justified in drawing conclusions from it about
cases that lack those features. Here is one such feature. The subject of
the vignette (John) acquires the name 'Gödel' at the same time as he
acquires an individuating description of Gödel. Suppose it turned out
that, in some dialects at least, that would be sufficient for the name
to be a descriptive name; i.e., for it to be a name whose reference is
fixed by a description somehow attached to that name. If this conjecture
is true, then descriptive names are a little more common than Kripke
thinks they are, but not a lot more common. Now we don't actually think
this conjecture is true. And for the reasons given in section 1 we don't
think this experiment is evidence for it. What we do think is that (a)
it's hard to see how studying reactions to cases like the Gödel/Schmidt
example could show more than that some such claim about the prevalence
of descriptive names is true, and (b) such claims are not inconsistent
with the causal-historical theory.

We've argued that even if Kripke is wrong about the Gödel/Schmidt
example, that doesn't undermine the arguments for the main conclusions
of *Naming and Necessity*. A natural inference from this is that
experiments about the Gödel/Schmidt example can't undermine those
conclusions. We think the natural inference is correct. A referee has
suggested that this is too quick. After all, if we have experimental
evidence that Kripke is wrong about the Gödel/Schmidt case, we might
have some grounds for suspicion about the other cases that Kripke uses
in the arguments for more central conclusions. That is, if MMNS are
right about the Gödel/Schmidt case, that doesn't give us a *deductive*
argument against the other anti-descriptivist moves, but it might give
us an *inductive* argument against them. This is an important worry, but
we think it can be adequately responded to.

The first thing to note is that it would be foolish to fall back to a
general scepticism about human judgment just because people disagree in
their intuitive reactions to some tricky cases. This point is well
argued by Timothy Williamson in his [-@Williamson2007-WILTPO-17 Ch. 6].
If there's a worry here, it must be because the evidence about the
Gödel/Schmidt example supports a more modest generalisation about
judgments about cases, but that generalisation is nevertheless strong
enough to undermine Kripke's other arguments. We doubt such a
generalisation exists.

It can't be that the experiments about the Gödel/Schmidt example show
that intuitive judgments about reference are systematically mistaken.
Most of our intuitions in this field are surely correct. For instance,
our intuitions that 'Kripke' refers to Kripke and not Obama, and that
'Obama' refers to Obama and not Kripke, are correct. (And experiments
like the ones MMNS ran don't give us any reason at all to doubt that.)
And we could produce many more examples like that. At most, the
experiments can show us that there are spots of inaccuracy in a larger
pool of correct judgments.

It might be argued that we should be sceptical of intuitions about
reference in counterfactual cases. The correct judgments cited in the
previous paragraph are all about real cases, but the Gödel/Schmidt
example is not a real case. Now we don't think that the experiments do
undermine all intuitions about reference in counterfactual cases, but
even if they did, that wouldn't affect the Kripkean argument. That's
because the central argument against descriptivism at the start of
Lecture II involves real cases. The heavy lifting is done by cases where
speakers don't think they have an individuating description to go along
with names they use (e.g., 'Feynman' and 'Gell-Mann'), or they believe
they have an individuating description, but that description involves
some kind of circularity (e.g., 'Einstein', 'Cicero'). It seems to us
that these cases are much more like the cases where we know people have
accurate intuitions about reference (e.g., 'Obama' refers to Obama),
than they are like cases where there is some dispute about their
accuracy (e.g., 'Gödel' would refer to Gödel even if Schmidt had proved
the incompleteness of arithmetic). So there's no reason to doubt the
intuitions that underlie these central Kripkean arguments. And so
there's no reason from these experiments to doubt the anti-descriptivist
conclusions Kripke draws from them.

### Reference in Philosophy

If the data about the Gödel/Schmidt example don't undermine the
causal-historical theory of reference, then presumably they don't
undermine philosophical uses of that theory. But we think MMNS overstate
the role that theories of reference play in philosophical theorising,
and we'll end by saying something about this.

One simple reaction to MMNS's argument is to say that at most they show
that the causal-historical theory of reference is not true of some
dialects. But, a philosopher might say, they are not writing in such a
dialect, and the causal-historical theory is true of their dialect. And
that's all they needed for their argument. MMNS anticipate this
objection, and reply to it in section 3.3 of their paper. The reply is,
in essence, that such a picture would make a mess of communication. If
we posit dialectical variation to explain different reactions to the
Gödel/Schmidt example, and to other examples, then we cannot know what
dialect someone is speaking without knowing how they respond to these
examples. And plainly we don't need to quiz people in detail about
philosophical examples in order to communicate with them.

We offer three replies.

First, at least one of us is on record raising in principle suspicions
about this kind of argument @Maitra2007. The take-home message from that
paper is that communication is a lot easier than many theorists have
supposed, and requires much less pre-communicative agreement. It seems
to us that the reply MMNS offer here is susceptible to the arguments in
that paper, but for reasons of space we won't rehearse those arguments
in detail.

Second, it's one thing to think that variation in *reference* between
dialects leads to communication breakdown, it's another thing altogether
to think that variation in *meta-semantics* leads to such breakdown. A
little fable helps make this clear. In some parts of Melbourne, 'Gödel'
refers to Gödel because of the causal chains between the users of the
name and the great mathematician. In other parts, 'Gödel' refers to
Gödel because the speakers use it as a descriptive name, associated with
the description 'the man who proved the incompleteness of arithmetic'.
Kevin doesn't know which area he is in when he sees a plaque over a door
saying "Gödel lived here". It seems to us that Kevin can understand the
sign completely without knowing how 'Gödel' got its reference. Indeed,
he even knows what proposition the sign expresses. So meta-semantic
variation between dialects need not lead to communicative failure, even
when hearers don't know which dialect is being used.

Third, if MMNS's argument succeeds, it seems to us that it shows
descriptivist theories, including the weak weak descriptivism that
Kripke is arguing against with the Gödel/Schmidt example, are doomed.
(The arguments in this paragraph are not original. Similar arguments are
used frequently in, e.g., @FodorLepore1992.) It's a platitude that
different people know different things. Barring a miracle, that means
different people will associate different descriptions with different
names. If there is widespread use of descriptive names, that means there
will be widespread differences in which descriptions are associated with
which names. And that will produce at least as much communicative
difficulty as having some people be causal-historical theorists and some
people be descriptivists. In short, if MMNS's argument against
'referential pluralism' is sound, there is an equally sound argument
against descriptivism. And note that this argument doesn't rely on any
thought experiments about particular cases. It doesn't even rely on
thought experiments about names like 'Einstein', where there isn't any
evidence that Kripke is wrong about how those names work.

Dialectically, the situation is this. MMNS have offered an argument from
the possibility of communicating under conditions of ignorance about
one's interlocutor's knowledge. Similar arguments have been offered
against descriptivism. If such arguments are successful, then
descriptivism is false, and there's no problem with philosophers making
arguments from the falsity of descriptivism. If such arguments are
unsuccessful, then MMNS haven't shown that it is wrong for philosophers
to assume that the causal-historical theory is the right theory for
*their* dialect, even if some other people are descriptivists. And, as
MMNS concede, as long as the philosophers themselves speak a
causal-historical theory dialect, the uses of the causal-historical
theory in philosophy seem appropriate. The only way this argument could
fail is if MMNS's argument from the possibility of communicating under
conditions of ignorance about one's interlocutor's knowledge is stronger
than the analogous arguments against descriptivism. But we see no reason
to believe that is so. If anything, it seems like a weaker argument,
because of the considerations arising from our fable about Kevin and the
'Gödel lived here' sign.

So we don't think MMNS have a good reply to the philosopher who insists
that they only need the causal-historical theory to be true of *their*
dialect. But in fact we think that philosophers rarely even assume that
much.

Let's consider one of the examples that they cite: Richard Boyd's use of
the causal-historical theory of reference in developing and defending
his version of "Cornell Realism" in his [-@Boyd1988]. Here's one way one
could try and argue for moral realism from the causal-historical theory.

1.  The causal-historical theory of reference is the correct theory of
    reference for all words in all dialects (or at least our dialect).

2.  So, it is the correct theory for 'good'.

But that's not Boyd's actual argument. And that's a good thing, because
the first premise is implausible. Someone defending it has to explain
descriptive names like 'Neptune', logical terms like 'and', empty
predicates like 'witch', and so on. And Boyd's not in that business. His
argument is subtler. Boyd uses the causal-historical theory for two
purposes. First, he uses the development of a naturalistically
acceptable theory of reference as part of a long list of developments in
post-positivist philosophy that collectively constitute a "distinctively
realist conception of the central issues in the philosophy of science"
[@Boyd1988 188]. Second, he uses the causal-historical theory of
reference, as it applies to natural kind terms, as part of a story about
how we can know a lot about kinds that are not always easily observable
[@Boyd1988 195-196]. By analogy, he suggests that we should be
optimistic that a naturalistically acceptable moral theory exists, and
that it is consistent with us having a lot of moral knowledge.

Once we look at the details of Boyd's argument, we see that it is an
argument that duelling intuitions about the Gödel/Schmidt example simply
can't touch. In part that's because Boyd cares primarily about natural
kind terms, not names. But more importantly it is because, as we noted
in section 2, the only point that's at issue by the time Kripke raises
the Gödel/Schmidt example is the *number* of descriptive names. Just
looking at the arguments Kripke raises before that example gives us more
than enough evidence to use in the kind of argument Boyd is making.

It would take us far beyond the length of a short reply to go through
every philosophical use of the causal-historical theory that MMNS
purport to refute in this much detail. But we think that the kind of
response we've used here will frequently work. That is, we think few, if
any, of the arguments they attack use the parts of the causal-historical
theory that Kripke is defending with the Gödel/Schmidt example, and so
even if that example fails, it wouldn't undermine those theories.

[^1]: Note that a causal descriptivist about names will also say that
    the correct answer to this question is (B). So the experiment isn't
    really testing descriptivism as such versus Kripke's
    causal-historical theory, but some particular versions of
    descriptivism against Kripke's theory. These versions of
    descriptivism say that names refer to the satisfiers of (generally
    non-linguistic) descriptions that the name's user associates with
    the name. One such version is 'famous deeds' descriptivism, and the
    descriptions MMNS use are typically famous deeds; nevertheless, that
    seems inessential to their experiments. When we use 'descriptivism'
    in this paper, we'll mean any such version of descriptivism. Thanks
    here to an anonymous referee.

[^2]: This objection relies on an empirical assumption that may be
    questionable. It assumes that the subject of the experiment
    associates the same description with 'Gödel' as John does. A subject
    who (a) is a descriptivist and (b) associates with the name 'Gödel'
    the description 'the man who proved the compatibility of time travel
    and general relativity', can also make sense of the vignette,
    *contra* Martí. So perhaps the objection could be resisted. But we
    think this empirical assumption is actually fairly plausible. Unless
    the experimental subjects were being picked from a very biased
    sample, the number of subjects who are familiar with Gödel's work on
    closed time-like curves is presumably vanishingly small! We're
    grateful here to an anonymous referee.

[^3]: This point suggests Martí's criticism of MMNS as stated
    overshoots. She wants to dismiss arguments from metalinguistic
    intuitions altogether. But intuitions about well-formedness *are*
    metalinguistic intuitions, and they are a key part of the
    syntactician's toolkit. Martí concedes something like this point,
    but claims that the cases are not on a par, because syntax concerns
    a normative issue and reference does not. We're quite suspicious
    that there's such a striking distinction between the kind of
    subject-matter studied by syntacticians and semanticists. Devitt's
    version of this point is more modest and does not obviously commit
    to this exaggeration.

[^4]: Here's one example where testing intuitions and examining the
    corpus may lead to different answers. Many people think, perhaps
    because they've picked up something from a bad style guide, that the
    sentence 'Whenever someone came into Bill's shop, he greeted them
    with a smile', contains one or two syntactic errors. (It uses a
    possessive as the antecedent of a pronoun, and it uses 'them' as a
    bound singular variable.) Even if most subjects in a survey said
    such a sentence was not a well-formed sentence of English, corpus
    data could be used to show that it is. Certainly the existence of a
    survey showing that users in, say, Scotland and New Jersey give
    different answers when asked about whether the sentence is
    grammatical would not show that there's a syntactic difference
    between the dialects spoken in Scotland and New Jersey. You'd also
    want to see how the sentences are *used*.

[^5]: The Gödel/Schmidt example is also distinctive in another way, in
    that the description in question actually applies to the referent of
    the name, and indeed speakers actually know this. But the flow of
    the text around the example (especially on page 84) suggests Kripke
    intends the example to make the same point as is made by other
    examples, such as the Peano/Dedekind case (in which the possessed
    description doesn't actually apply to the referent of the name). So
    this is probably not crucial to the point the example makes. We'll
    return below to the issue of just what this example shows. The key
    point is that the more distinctive the example is, the *less* that
    would follow if Kripke were wrong about the example; he might only
    be wrong about examples with just those distinctive features.



