---
title: "Review of “The Realm of Reason”"
description: |
  Review of Christopher Peacocke, “The Realm of Reason”. Oxford: Clarendon Press, 2004
author:
  - name: Brian Weatherson 
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://umich.edu
    orcid_id: 0000-0002-0830-141X
doi: "10.1111/j.1933-1592.2003.tb00305.x"
date: 10-15-2004
toc: false
citation:
  type: review-book
  container-title: "Times Literary Supplement"
categories:
  - book review
  - on books
  - epistemology
  - metaphysics
format:
  html: default
  pdf: 
    output-file: "Review of The Realm of Reason"
    include-after-body: 
        text: |
           Published in the \emph{Times Literary Supplement}, 2004 \\
---

Some of what we know we know by experience and some by reason. It's experience not reason that teaches that Arsenal ended last season with 90 points and Chelsea with 79, it's reason not experience that teaches 90 is greater than 79, and, arguably, it's the two together that teach that Arsenal ended with more points than Chelsea. One useful classification of philosophers is by the relative importance they assign to experience and reason in grounding what we know. Empiricists (on one reading of that term) play down reason, sometimes going so far as to declare that anything known by a means other than experience must be a mere matter of definition. Rationalists play reason up.

<aside>Published in the Times Literary Supplement</aside>

Christopher Peacocke is firmly in the rationalist camp, and *The Realm of Reason* is an attempt to lay out what he takes rationalism to be. It gives his preferred version of rationalism and some arguments in its favour. It's much too much to attempt in a short book and it isn't entirely persuasive on any of the applications, but it is a grand vision for what a global rationalism might look like, one that might prove attractive even if the details need work. Given the length of the book a surprising amount of time is spent on relatively abstruse details. Peacocke provides a particularly careful account of what distinguishes rationalists from empiricists and does a lot of work classifying and adjudicating between rationalisms of various strengths. These are the best parts of the book, but also the least accessible.

Peacocke's preferred version of rationalism has two distinctive components. First, he focuses not on beliefs, as is usual, but on the "transitions" between representational states that occur in thought, as when we move to a new belief on the basis of one we already have. Mental representational states are often beliefs, but they also include things, like perceptions, that have representational content without necessarily being believed. Peacocke's rationalist claim is that for any justified transition, there's an a priori explanation of why it is justified. Second, he insists that this explanation rely crucially on the contents of the states involved in the transition.

So we get a quite strong "foundationalist" epistemology. Experience provides the foundations for empirical knowledge, but how we get from there to what we know is entirely in the domain of reason. It is famously difficult to justify many steps by reason alone, and the most pressing is the very first: How do we justify the transition from appearances to reality, such as the transition from *That looks crooked* to *That is crooked*? Some philosophers have thought that we need to link appearance and reality so closely that the link is infallible. Peacocke doesn't take that line, so he has to justify the transition some other way.

Descartes faced a similar problem when trying to get over his radical doubt about the existence of the material world, and solved it by appeal to God. We can tell a priori, he thought, that a benevolent God exists, and a benevolent God will not let us be deceived about this matter, at least when we are careful enough to rely on clear and distinct perceptions. Now Descartes had to be careful here to only appeal to a priori reasons for belief in God. He couldn't, for instance, argue from the apparent design of the universe to the existence of a designer, because we can't tell at this stage whether the apparent design is merely an artifact of our defective perceptual faculties. Indeed, we can't rely on any apparent fact about the external world until we've determined that appearances are a good guide to reality. So we need to argue for the existence of God without appeal to perception, and then use God's existence to justify future reliance on perception.

In keeping with the spirit of the age, Peacocke updates Descartes's strategy by replacing God with Darwin. Very roughly, Peacocke argues that the best explanation of our having representative capacities at all is that we are the products of a long process of natural selection. And if we are the products of a long process of selection, then we probably have accurate representations. If those two claims can be justified a priori we have an a priori argument to the (prima facie, probable) accuracy of our representations.

Less roughly, Peacocke argues for a "Complexity Reduction Principle". We are entitled, on a priori grounds, to believe that complex phenomena have explanations, and we are entitled to regard simpler explanations as more probably true than more complex ones. That we have representations at all is a complex matter. How might it be explained? One explanation is via Divine creation. Another is that we are "brains-in-vats" living in a virtual reality world dreamt up by some quirky scientist (cf *The Matrix*). But neither of these explanations really reduces the complexity, since in each case we need to appeal to a thing (God, the scientist) that already has representational capacities. A simpler explanation, allegedly, is that we are the product of natural selection and having accurate representations is selected for. This is certainly a novel argument for Darwinism. It isn't why they teach natural selection to biology students. And of course it has flaws. Peacocke does little to show that there are no better explanations of our having representations. Nor does he address the question of how complicated hereditary mechanisms must be if they are to support natural selection. Arguably they are much more complicated than is needed for representation, so Darwin doesn't help reduce complexity here.

So it's not clear Peacocke's rationalism can get past step one; but let's see what would happen next. To go beyond particular perceptions, in acquiring knowledge, we need induction. Peacocke takes the basic form of enumerative induction to be the (defeasible) inference from *All the (many and varied) observed Fs have been Gs* to *All Fs are Gs*. The observation of only Gs, and no non-Gs, amongst these many and varied Fs is a complex fact, and its best (ie simplest) explanation is sometimes that all the Fs are Gs. Peacocke argues that in these cases this explanation is the a priori justification of the transition, and in only these cases is the transition justified; he concludes that induction is acceptable by rationalist lights.

The chapter on induction is only fifteen pages long, and it really needs to be much longer. Peacocke sets out the position just outlined, and compares it in some detail to a similar position advocated by Gilbert Harman, and that's it. There is no discussion of what we do when most, rather than all, the observed Fs have been Gs, even though that's surely the more important practical case. There's no discussion of the case that's frequently central to modern discussions on induction---the case in which a certain (stable) ratio of the Fs are Gs. Peacocke only talks about the special case when *all* Fs are Gs, and it isn't obvious that the discussion generalizes. There is no discussion of rationalist alternatives, such as Keynes's justification of enumerative induction in terms of analogical inference, or D. C. Williams's probabilistic defence of induction. And there's no discussion of empiricist attempts to justify induction a posteriori, or to do without it. Even if Peacocke's suggested justification works, and it is at least a serious contender, a persuasive treatment of induction should have dealt with at least some of these points.

The final two chapters discuss moral beliefs. Again, Peacocke thinks that all the inferences we make in order to get from our perceptual beliefs to our moral beliefs can be justified a priori. His view is that we can come to know a priori some moral principles. And we can know contingent moral facts, such as that someone's giving £1000 to Oxfam is morally praiseworthy, by carrying out the following inference. The person, say Joe, helped other people in need. (We learn this by experience.) Helping those in need is morally praiseworthy. (We learn this moral principle by deploying our reason.) Hence what Joe did is morally praiseworthy. But there's a problem here, and Peacocke never fully addresses it. It's only *prima facie* true that helping those in need is morally praiseworthy. There are always exceptions to the principle. If Joe's children starved to death because that donation was the last money Joe had to buy them food, the donation wasn't morally praiseworthy. Moreover, it is just about impossible to state the exceptions without using moral language. So it is far from clear how we are meant to come to know that this case is not one of the exceptions, because knowing this requires both empirical knowledge and moral sensitivity. From a "principleist" position like Peacocke's, knowing this is not one of the exceptions seems just as hard as the original problem of coming to know that the action was praiseworthy. So it seems the rationalist still has work to do here.

One can easily get the feeling from this book that rationalism runs into problems as soon as we try to apply it to real-world cases. But it isn't obvious these are deep problems with rationalism, and in particular it isn't clear that the problems can't be fixed with relatively minor adjustments. Even if there are difficulties in application throughout *The Realm of Reason*, there is a lot of important philosophical work going on beneath the surface. Peacocke's best work is done in classifying the various types of rationalist position that are available, and motivating the kind of view he wants to defend. This material remains valuable, highly valuable to anyone wanting to draw a plausible rationalist picture, even if his real-world applications are not yet perfect.