

```{r}
#| label: tbl-top-ten-1965
#| tbl-cap: "Most cited articles published less than ten years ago as of 1974."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1965) |> select(tbl_cite), col.names = c(as.character(1974)))

```



```{r}
#| label: tbl-top-ten-1966
#| tbl-cap: "Most cited articles published less than ten years ago as of 1975."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1966) |> select(tbl_cite), col.names = c(as.character(1975)))

```



```{r}
#| label: tbl-top-ten-1967
#| tbl-cap: "Most cited articles published less than ten years ago as of 1976."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1967) |> select(tbl_cite), col.names = c(as.character(1976)))

```



```{r}
#| label: tbl-top-ten-1968
#| tbl-cap: "Most cited articles published less than ten years ago as of 1977."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1968) |> select(tbl_cite), col.names = c(as.character(1977)))

```



```{r}
#| label: tbl-top-ten-1969
#| tbl-cap: "Most cited articles published less than ten years ago as of 1978."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1969) |> select(tbl_cite), col.names = c(as.character(1978)))

```



```{r}
#| label: tbl-top-ten-1970
#| tbl-cap: "Most cited articles published less than ten years ago as of 1979."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1970) |> select(tbl_cite), col.names = c(as.character(1979)))

```



```{r}
#| label: tbl-top-ten-1971
#| tbl-cap: "Most cited articles published less than ten years ago as of 1980."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1971) |> select(tbl_cite), col.names = c(as.character(1980)))

```



```{r}
#| label: tbl-top-ten-1972
#| tbl-cap: "Most cited articles published less than ten years ago as of 1981."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1972) |> select(tbl_cite), col.names = c(as.character(1981)))

```



```{r}
#| label: tbl-top-ten-1973
#| tbl-cap: "Most cited articles published less than ten years ago as of 1982."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1973) |> select(tbl_cite), col.names = c(as.character(1982)))

```



```{r}
#| label: tbl-top-ten-1974
#| tbl-cap: "Most cited articles published less than ten years ago as of 1983."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1974) |> select(tbl_cite), col.names = c(as.character(1983)))

```



```{r}
#| label: tbl-top-ten-1975
#| tbl-cap: "Most cited articles published less than ten years ago as of 1984."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1975) |> select(tbl_cite), col.names = c(as.character(1984)))

```



```{r}
#| label: tbl-top-ten-1976
#| tbl-cap: "Most cited articles published less than ten years ago as of 1985."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1976) |> select(tbl_cite), col.names = c(as.character(1985)))

```



```{r}
#| label: tbl-top-ten-1977
#| tbl-cap: "Most cited articles published less than ten years ago as of 1986."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1977) |> select(tbl_cite), col.names = c(as.character(1986)))

```



```{r}
#| label: tbl-top-ten-1978
#| tbl-cap: "Most cited articles published less than ten years ago as of 1987."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1978) |> select(tbl_cite), col.names = c(as.character(1987)))

```



```{r}
#| label: tbl-top-ten-1979
#| tbl-cap: "Most cited articles published less than ten years ago as of 1988."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1979) |> select(tbl_cite), col.names = c(as.character(1988)))

```



```{r}
#| label: tbl-top-ten-1980
#| tbl-cap: "Most cited articles published less than ten years ago as of 1989."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1980) |> select(tbl_cite), col.names = c(as.character(1989)))

```



```{r}
#| label: tbl-top-ten-1981
#| tbl-cap: "Most cited articles published less than ten years ago as of 1990."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1981) |> select(tbl_cite), col.names = c(as.character(1990)))

```



```{r}
#| label: tbl-top-ten-1982
#| tbl-cap: "Most cited articles published less than ten years ago as of 1991."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1982) |> select(tbl_cite), col.names = c(as.character(1991)))

```



```{r}
#| label: tbl-top-ten-1983
#| tbl-cap: "Most cited articles published less than ten years ago as of 1992."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1983) |> select(tbl_cite), col.names = c(as.character(1992)))

```



```{r}
#| label: tbl-top-ten-1984
#| tbl-cap: "Most cited articles published less than ten years ago as of 1993."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1984) |> select(tbl_cite), col.names = c(as.character(1993)))

```



```{r}
#| label: tbl-top-ten-1985
#| tbl-cap: "Most cited articles published less than ten years ago as of 1994."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1985) |> select(tbl_cite), col.names = c(as.character(1994)))

```



```{r}
#| label: tbl-top-ten-1986
#| tbl-cap: "Most cited articles published less than ten years ago as of 1995."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1986) |> select(tbl_cite), col.names = c(as.character(1995)))

```



```{r}
#| label: tbl-top-ten-1987
#| tbl-cap: "Most cited articles published less than ten years ago as of 1996."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1987) |> select(tbl_cite), col.names = c(as.character(1996)))

```



```{r}
#| label: tbl-top-ten-1988
#| tbl-cap: "Most cited articles published less than ten years ago as of 1997."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1988) |> select(tbl_cite), col.names = c(as.character(1997)))

```



```{r}
#| label: tbl-top-ten-1989
#| tbl-cap: "Most cited articles published less than ten years ago as of 1998."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1989) |> select(tbl_cite), col.names = c(as.character(1998)))

```



```{r}
#| label: tbl-top-ten-1990
#| tbl-cap: "Most cited articles published less than ten years ago as of 1999."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1990) |> select(tbl_cite), col.names = c(as.character(1999)))

```



```{r}
#| label: tbl-top-ten-1991
#| tbl-cap: "Most cited articles published less than ten years ago as of 2000."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1991) |> select(tbl_cite), col.names = c(as.character(2000)))

```



```{r}
#| label: tbl-top-ten-1992
#| tbl-cap: "Most cited articles published less than ten years ago as of 2001."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1992) |> select(tbl_cite), col.names = c(as.character(2001)))

```



```{r}
#| label: tbl-top-ten-1993
#| tbl-cap: "Most cited articles published less than ten years ago as of 2002."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1993) |> select(tbl_cite), col.names = c(as.character(2002)))

```



```{r}
#| label: tbl-top-ten-1994
#| tbl-cap: "Most cited articles published less than ten years ago as of 2003."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1994) |> select(tbl_cite), col.names = c(as.character(2003)))

```



```{r}
#| label: tbl-top-ten-1995
#| tbl-cap: "Most cited articles published less than ten years ago as of 2004."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1995) |> select(tbl_cite), col.names = c(as.character(2004)))

```



```{r}
#| label: tbl-top-ten-1996
#| tbl-cap: "Most cited articles published less than ten years ago as of 2005."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1996) |> select(tbl_cite), col.names = c(as.character(2005)))

```



```{r}
#| label: tbl-top-ten-1997
#| tbl-cap: "Most cited articles published less than ten years ago as of 2006."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1997) |> select(tbl_cite), col.names = c(as.character(2006)))

```



```{r}
#| label: tbl-top-ten-1998
#| tbl-cap: "Most cited articles published less than ten years ago as of 2007."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1998) |> select(tbl_cite), col.names = c(as.character(2007)))

```



```{r}
#| label: tbl-top-ten-1999
#| tbl-cap: "Most cited articles published less than ten years ago as of 2008."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 1999) |> select(tbl_cite), col.names = c(as.character(2008)))

```



```{r}
#| label: tbl-top-ten-2000
#| tbl-cap: "Most cited articles published less than ten years ago as of 2009."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2000) |> select(tbl_cite), col.names = c(as.character(2009)))

```



```{r}
#| label: tbl-top-ten-2001
#| tbl-cap: "Most cited articles published less than ten years ago as of 2010."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2001) |> select(tbl_cite), col.names = c(as.character(2010)))

```



```{r}
#| label: tbl-top-ten-2002
#| tbl-cap: "Most cited articles published less than ten years ago as of 2011."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2002) |> select(tbl_cite), col.names = c(as.character(2011)))

```



```{r}
#| label: tbl-top-ten-2003
#| tbl-cap: "Most cited articles published less than ten years ago as of 2012."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2003) |> select(tbl_cite), col.names = c(as.character(2012)))

```



```{r}
#| label: tbl-top-ten-2004
#| tbl-cap: "Most cited articles published less than ten years ago as of 2013."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2004) |> select(tbl_cite), col.names = c(as.character(2013)))

```



```{r}
#| label: tbl-top-ten-2005
#| tbl-cap: "Most cited articles published less than ten years ago as of 2014."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2005) |> select(tbl_cite), col.names = c(as.character(2014)))

```



```{r}
#| label: tbl-top-ten-2006
#| tbl-cap: "Most cited articles published less than ten years ago as of 2015."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2006) |> select(tbl_cite), col.names = c(as.character(2015)))

```



```{r}
#| label: tbl-top-ten-2007
#| tbl-cap: "Most cited articles published less than ten years ago as of 2016."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2007) |> select(tbl_cite), col.names = c(as.character(2016)))

```



```{r}
#| label: tbl-top-ten-2008
#| tbl-cap: "Most cited articles published less than ten years ago as of 2017."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2008) |> select(tbl_cite), col.names = c(as.character(2017)))

```



```{r}
#| label: tbl-top-ten-2009
#| tbl-cap: "Most cited articles published less than ten years ago as of 2018."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2009) |> select(tbl_cite), col.names = c(as.character(2018)))

```



```{r}
#| label: tbl-top-ten-2010
#| tbl-cap: "Most cited articles published less than ten years ago as of 2019."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2010) |> select(tbl_cite), col.names = c(as.character(2019)))

```



```{r}
#| label: tbl-top-ten-2011
#| tbl-cap: "Most cited articles published less than ten years ago as of 2020."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2011) |> select(tbl_cite), col.names = c(as.character(2020)))

```



```{r}
#| label: tbl-top-ten-2012
#| tbl-cap: "Most cited articles published less than ten years ago as of 2021."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2012) |> select(tbl_cite), col.names = c(as.character(2021)))

```



```{r}
#| label: tbl-top-ten-2013
#| tbl-cap: "Most cited articles published less than ten years ago as of 2022."

kable(the_4900_ordered |> filter(rank <= 10, range_year == 2013) |> select(tbl_cite), col.names = c(as.character(2022)))

```

