---
title: "Your Paper Title Here"
author: "Your Name"
draft: true
date: today
format:
  pdf:
    documentclass: article
    fontsize: 12pt
    linestretch: 2
    geometry:
      - margin=1in
    mainfont: "Times New Roman"
    include-in-header:
      text: |
        \usepackage{setspace}
        \doublespacing
    keep-tex: true
  docx:
    toc: false
    number-sections: true
    # Uncomment the line below after creating your reference document
    reference-doc: reference-doc.docx
  html:
    toc: true
    toc-depth: 2
bibliography: references.bib
csl: chicago-author-date.csl
link-citations: true
---

# Introduction

Your paper content begins here. This template is configured for submission to *Logos & Episteme: An International Journal of Epistemology*.

## Key Formatting Notes

- The document is set to double-spacing as required
- Font is 12pt Times New Roman
- Chicago author-date citation style is used
- Maximum word count: 12,000 words (including footnotes and references)

## Citations

Use the Chicago author-date system. For example, you might cite @smith2020 or multiple sources [@jones2019; @brown2021].

For a direct quote:

> "Large quotations should be set off clearly, by indenting the left margin" [@logosguidelines2025, 15].

## Footnotes

You can add footnotes like this.^[This is a footnote. Footnotes should be numbered consecutively and appear at the bottom of each page.]

# Conclusion

Your conclusion here.

# References

::: {#refs}
:::
